Migrate from woocommerce.com to woo.com
woocommerce/woocommerce-android pull request #10177
Opened 2023-11-15 11:43 UTC by kidinov

Closes: #10175

### Description

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-11-15 12:43 UTC, kidinov commented
@0nko could you please take a look if it's safe/needed to change the URL [here ] (https://github.com/woocommerce/woocommerce-android/blob/6dbc7fa4d975a5b2b67ba3bcd716176fbc22476f/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/plans/PlansViewModel.kt#L66)
and [here](https://github.com/woocommerce/woocommerce-android/blob/6dbc7fa4d975a5b2b67ba3bcd716176fbc22476f/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/DomainPurchaseViewModel.kt#L33)?

There is a redirect so I even not sure that this works right now

@hafizrahman the same question for [this part](https://github.com/woocommerce/woocommerce-android/blob/6dbc7fa4d975a5b2b67ba3bcd716176fbc22476f/WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/WCSSRModelExt.kt#L250). That looks like just a text so should be fine, but just in case

2023-11-16 03:10 UTC, hafizrahman commented
@kidinov I saw that in Core they replaced that string with "Connected to Woo.com" ([reference](https://github.com/woocommerce/woocommerce/blob/0a98a249b027b16cbf10490202db6798e9b1179a/plugins/woocommerce/includes/admin/views/html-admin-page-status-report.php#L740-L742))

So it would be good if you can add the change to the string you linked to as well. Thanks for noticing!

2023-11-16 05:28 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
> +        "https://woo.com/woocommerce-features/"
The page there does not seem to explain what a WordPress.com account is.

Did you want to use this instead?

https://woo.com/document/what-is-a-wordpress-com-account/

2023-11-16 05:30 UTC, hafizrahman requested changes, later dismissed
I left a couple of comments re: updating SSR and about the link explaining WordPress.com account.

The rest of the link changes look good to me, I checked them manually and they do open to the right thing.

2023-11-16 09:48 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppUrls.kt
> +        "https://woo.com/woocommerce-features/"
Thanks! Good catch. Fixed here - 4ec1db284309254440f2c05d014596b679d42dbe

2023-11-16 09:50 UTC, kidinov commented
@hafizrahman 

>@kidinov I saw that in Core they replaced that string with "Connected to Woo.com" ([reference](https://github.com/woocommerce/woocommerce/blob/0a98a249b027b16cbf10490202db6798e9b1179a/plugins/woocommerce/includes/admin/views/html-admin-page-status-report.php#L740-L742))

> So it would be good if you can add the change to the string you linked to as well. Thanks for noticing!

Thanks for confirming that. Fixed here
a4dd6aab0ebafb704eb1851622e5a4b01e2eeebc

2023-11-16 10:18 UTC, hafizrahman commented
Looks good on my side. For the question for Ondrej, he's AFK today so pinging @JorgeMucientes to check if the "woocommerce.com" as exit check logic is safe to be changed:

> please take a look if it's safe/needed to change the URL
[here](https://github.com/woocommerce/woocommerce-android/blob/6dbc7fa4d975a5b2b67ba3bcd716176fbc22476f/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/plans/PlansViewModel.kt#L66)
and
[here](https://github.com/woocommerce/woocommerce-android/blob/6dbc7fa4d975a5b2b67ba3bcd716176fbc22476f/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/domain/DomainPurchaseViewModel.kt#L33)?

2023-11-17 08:54 UTC, 0nko commented
> There is a redirect, so I am even not sure that this works right now

These are not links, but triggers in the WebView that notify the ViewModel. I've tested the plan and domain purchase and it seems like both domains work, which is weird 🤔. Can you double check you see the same behaviour with "woo.com"?

2023-11-17 09:42 UTC, kidinov commented
@0nko As I have 0 knowledge about the flows, and even not sure where this code runs, would you mind changing the URL to `https://woo.com/` and see if it's ok?

2023-11-17 10:17 UTC, 0nko commented
These are the Woo express plan purchase and domain purchase flows. I've checked them both and exiting the purchase WebView works. 👍

2023-11-17 10:21 UTC, kidinov commented
Thank you @0nko 🙏

I've changed the trigger URL then - df765f30f201d2e7d500f4bb62b3b5e057be315e

2023-11-21 17:33 UTC, JorgeMucientes approved these changes

2023-11-21 17:37 UTC, JorgeMucientes commented
Good work @kidinov ! Thanks for handling this migration. I've tested the WooCommerce domain deeplinks as well as smoked tested many of the url updated in the PR. Everything works as expected. Ready for merging 👍🏼

2023-11-22 08:06 UTC, merged