[Custom Amounts M4.1] Add the ability to charge tax
woocommerce/woocommerce-android pull request #10222
Opened 2023-11-22 05:46 UTC by AnirudhBhat

Closes: #10214 

### Description

This pull request introduces the capability to apply tax charges when creating custom amounts, thereby aligning the custom amounts feature with the Simple Payment functionality.

### Testing instructions

1. Navigate to Order creation screen
2. Tap on "Add custom amount" row
3. **Ensure you see "Charge Taxes" toggle in the custom amount dialog**
4. Enable the toggle and create custom amount
5. **Ensure the taxes are applied appropriately**
6. Repeat the steps 2 and 3. This time, disable the toggle
7. **Ensure the tax is not applied.**
8. **Ensure while editing custom amounts, the tax toggle state is saved appropriately.**

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-11-22 23:27 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/customamounts/views/TaxToggle.kt
> +        Switch(
🔍 The colour of the switch looks a bit off. It's redish. Is that the colour we are going with?
If not, there's an option to set the Switch colours:

```
Switch(
            checked = taxStatus.isTaxable,
            onCheckedChange = onCheckedChange,
             colors = SwitchDefaults.colors(
                 checkedThumbColor = MaterialTheme.colors.primary,
                 checkedTrackColor = MaterialTheme.colors.onBackground,
                 uncheckedThumbColor = MaterialTheme.colors.secondary,
                 uncheckedTrackColor = MaterialTheme.colors.background
             )
            )```

ps: The color options I added there are totally random, not even using our Woo theme but jut to give an idea.

2023-11-22 23:40 UTC, rossanafmenezes requested changes
LGTM. Left a comment about the colour of the switch.

2023-11-23 03:02 UTC, AnirudhBhat commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/customamounts/views/TaxToggle.kt
> +        Switch(
Good point! I'm making use of `WCSwitch` now instead of `Switch` https://github.com/woocommerce/woocommerce-android/pull/10222/commits/3c2d9af1d79d7bb64624caf9159b83259dc0aa97

2023-11-23 10:56 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/customamounts/views/TaxToggle.kt
> +        Switch(
Awesome! Thanks

2023-11-23 11:06 UTC, rossanafmenezes approved these changes
Thanks!! LGTM

2023-11-23 11:07 UTC, merged