[Custom Amounts M4.2] Track when custom amount is added based on percentage
woocommerce/woocommerce-android pull request #10302
Opened 2023-12-01 05:53 UTC by AnirudhBhat

Closes: #10301 

### Description

This PR adds tracking when custom amount is added based on percentage

Event name: `add_custom_amount_percentage_added`

### Testing instructions

1. Navigate to the order creation screen
2. Click on the "Enter custom amount" button
3. Add a percentage based custom amount
4. Ensure you see `add_custom_amount_percentage_added` event being tracked in the logs

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-12-06 18:30 UTC, rossanafmenezes requested changes
Overall looks good but there's one small issue with one of the trackers. I left a comment about this.

2023-12-06 18:30 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
> +                tracker.track(ADD_CUSTOM_AMOUNT_PERCENTAGE_ADDED)
I was not able to see this one, even tho it is being triggered. Based on the debugger, the CustomAmoutType is being set to Fixed Custom amount even when you add a percentage amount:

![Screenshot 2023-12-06 at 12 47 47 PM](https://github.com/woocommerce/woocommerce-android/assets/30724184/57617d2a-797d-4048-b333-1f3ed512e1d9)

I believe it's because we are setting it in the `CustomAmountUIState` data class in the `CustomAmountDialogViewModel`:

```
    @Parcelize
    data class CustomAmountUIState(
        val id: Long = 0,
        val currentPrice: BigDecimal = BigDecimal.ZERO,
        val name: String = "",
        val taxStatus: TaxStatus = TaxStatus(),
        val type: CustomAmountType = CustomAmountType.FIXED_CUSTOM_AMOUNT,
    ) : Parcelable
```
I mean, the logic for the tracker works and if you change the type there it does show, but tracks everything as Percentage.

2023-12-07 04:10 UTC, AnirudhBhat commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
> +                tracker.track(ADD_CUSTOM_AMOUNT_PERCENTAGE_ADDED)
Good catch! I've fixed it in this commit https://github.com/woocommerce/woocommerce-android/pull/10302/commits/d574f67d58758b2227f7425d82b26d9be4257fc7

2023-12-07 11:19 UTC, rossanafmenezes approved these changes
LGTM

2023-12-07 12:09 UTC, merged