CI: Add pipelines for releases in CI
woocommerce/woocommerce-android pull request #10406
Opened 2023-12-15 09:12 UTC by spencertransier

This PR adds pipelines for running release scenario commands in CI using the new MC release tool from @hannahtinkler. This is part of the project to migrate releases over to that new tool (paaHJt-5MF-p2). 

Each of the pipelines in the `release-pipelines` folder corresponds to a Fastlane command that will be run as part of the release scenario steps. 

These changes don't affect running the commands in CI and don't change how we're currently creating releases locally.

2023-12-15 12:49 UTC, AliSoftware requested changes

2023-12-15 12:49 UTC, AliSoftware commented on .buildkite/commands/configure-git-for-release-management.sh
> +curl -L https://api.github.com/meta | jq -r '.ssh_keys | .[]' | sed -e 's/^/github.com /' >> ~/.ssh/known_hosts
Alternatively, we also have [this utility as part of `a8c-ci-toolkit`](https://github.com/Automattic/a8c-ci-toolkit-buildkite-plugin/blob/trunk/bin/add_host_to_ssh_known_hosts) that you could use instead?

2023-12-15 12:49 UTC, AliSoftware commented on .buildkite/commands/configure-git-for-release-management.sh
> +git remote set-url origin git@github.com:wordpress-mobile/WordPress-Android.git
1. This is surprising, especially given iinm [we have a checkov policy/rule to ensure all our repos use a `git@…` SSH URL](https://github.com/Automattic/buildkite-ci/blob/trunk/src/buildkite/policies/pipeline_repo_ssh_url.yml)
2. Also the Terraform configuration for `woocommerce-android.tf` [seems to already use the `git@` URL](https://github.com/Automattic/buildkite-ci/blob/trunk/src/buildkite/pipelines/woocommerce-android.tf#L10)
3. 🚨  Finally, your line here sets the remote URL **to `WordPress-Android` repo** (which, btw, also already uses `git@` URL in its `wordpress-android.tf` config anyway), not to the `woocommerce-android` one!

2023-12-15 17:10 UTC, spencertransier commented on .buildkite/commands/configure-git-for-release-management.sh
> +git remote set-url origin git@github.com:wordpress-mobile/WordPress-Android.git
TBH, I brought this directly over from WordPress-Android, which led to my oversight about #3 🤦‍♂️ (fixed in https://github.com/woocommerce/woocommerce-android/commit/bb1e1ec8e76b7ee0374af4ba151ec2dde2ae036e) 

I know that this configuration is being used WPAndroid, but I don't know if there are reasons why it's still needed or if we can update it like you suggested. @oguzkocer could you provide some insight here? 

cc @mokagio since it looks like https://github.com/wordpress-mobile/WordPress-iOS/pull/22192 will need to be updated depending on what we decide.

2023-12-15 17:13 UTC, AliSoftware commented on .buildkite/commands/configure-git-for-release-management.sh
> +git remote set-url origin git@github.com:wordpress-mobile/WordPress-Android.git
Oh if that was copied from WPAndroid verbatim, maybe that's because back when Oguz configured all of that for WPAndroid, it was before https://github.com/Automattic/buildkite-ci/pull/214 and we didn't enforce nor have all the repos use SSH just yet back then? But now it shouldn't be necessary anymore?

2023-12-15 17:16 UTC, AliSoftware commented on .buildkite/commands/configure-git-for-release-management.sh
> +git remote set-url origin git@github.com:wordpress-mobile/WordPress-Android.git
Especially since, reading from the **PR description** of https://github.com/Automattic/buildkite-ci/pull/214, I can see this change in the `.tf` configs was created **especially** because we noticed back then that `WPAndroid` was using `https://` and wanted to fix it properly to use ssh:

> While debugging issues with @iangmaia about Danger not being able to detect the repo slug from the `BUILDKITE_REPO` URL, we noticed […] that the issue was WPAndroid was using a `BUILDKITE_REPO` url that not only was `https://`, […]

2023-12-16 09:13 UTC, spencertransier commented on .buildkite/commands/configure-git-for-release-management.sh
> +curl -L https://api.github.com/meta | jq -r '.ssh_keys | .[]' | sed -e 's/^/github.com /' >> ~/.ssh/known_hosts
Updated in https://github.com/woocommerce/woocommerce-android/commit/4344af6e5763e62863c689e5e90ab4e19c9c3f6a. I tested the change in WCiOS during the "Complete Code Freeze" step for the 16.7 release: https://buildkite.com/automattic/woocommerce-ios/builds/18166#018c7051-3ccd-4745-9f19-cb61c73198b6

2023-12-16 09:15 UTC, spencertransier commented on .buildkite/commands/configure-git-for-release-management.sh
> +git remote set-url origin git@github.com:wordpress-mobile/WordPress-Android.git
I tested removing this during the ["Complete Code Freeze" step of the 16.7 release](https://buildkite.com/automattic/woocommerce-ios/builds/18166#018c7051-3ccd-4745-9f19-cb61c73198b6) and it worked great. Removed it here in https://github.com/woocommerce/woocommerce-android/pull/10406/commits/6fae924cb8498c3704120f71b42f82ab16e2bbb5.

2023-12-16 15:05 UTC, AliSoftware approved these changes

2023-12-16 17:24 UTC, merged