Blaze: show an error if one of the requirements of the creation is missing
woocommerce/woocommerce-android pull request #10835
Opened 2024-02-15 17:04 UTC by hichamboushaba

Closes: #10834 

### Description
Blaze campaigns require an image and some content, currently we don't handle validating the presence of both of them, this PR adds this, and guides the user to add the missing parts.

The Ad's tagline and description are fetched from the API, but if the call fails, they'll stay empty, so we still need to handle this.

### Testing instructions
##### Image
1. Create a product that doesn't have an image.
2. Open blaze campaign creation for this product.
3. Click on Confirm Details.
4. Notice the dialog.
5. Click on Add image.
6. Confirm this opens the Ad details screen.

##### Tagline and/or description
1. Disable internet connection.
2. Open blaze campaign creation form.
3. Click on Confirm Details.
4. Notice the dialog.
5. Click on "Add"
6. Confirm this opens the Ad details screen.

### Images/gif
| Image missing | tagline or description missing |
| --- | --- |
| ![Screenshot_20240215_180012](https://github.com/woocommerce/woocommerce-android/assets/1657201/80a47ad8-0f04-44b6-bfad-9a6843880788) | ![Screenshot_20240215_175937](https://github.com/woocommerce/woocommerce-android/assets/1657201/af2eca79-0430-4fe6-a015-3474a5b1b7c9) |

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

2024-02-15 17:05 UTC, dangermattic commented
<!--
  1 Error: Please add tests for class <co...
  1 Warning: <code>strings.xml</code> files...
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>DialogState</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>strings.xml</code> files should only be updated on release branches, when the translations are downloaded by our automation.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-02-15 17:08 UTC, hichamboushaba commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="blaze_campaign_preview_missing_content_dialog_positive_button">Add</string>
I used just "Add" to keep it short, but please let me know if you have a better suggestion.

2024-02-16 16:26 UTC, 0nko requested changes
~~While testing the empty tagline scenario I encountered a crash when I started typing in one of the fields:~~

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.set(ArrayList.java:453)
at com.woocommerce.android.ui.blaze.creation.ad.BlazeCampaignCreationEditAdViewModel.updateSuggestion(BlazeCampaignCreationEditAdViewModel.kt:139)
at com.woocommerce.android.ui.blaze.creation.ad.BlazeCampaignCreationEditAdViewModel.onTagLineChanged(BlazeCampaignCreationEditAdViewModel.kt:113)
```

~~It happens because the suggestions don't get loaded so we must check if there are any in `updateSuggestion()`.~~

I thought it wasn't possible to get there without the dialogs but actually this is not caused by this PR. I'll fix it separately.

2024-02-16 16:31 UTC, 0nko approved these changes
The tests work as expected 👍

2024-02-16 16:36 UTC, hichamboushaba commented
> I thought it wasn't possible to get there without the dialogs but actually this is not caused by this PR. I'll fix it separately.

Thanks @0nko

2024-02-16 16:38 UTC, merged