[Tablet Support M2] Bug/10861 Navigation during dynamic screen size changes
woocommerce/woocommerce-android pull request #10872
Opened 2024-02-21 09:02 UTC by samiuelson

Closes: #10861 

### Description

This PR fixes back navigation 

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

2024-02-21 09:03 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-02-21 10:58 UTC, malinajirka requested changes
Thanks for working on this @samiuelson ! I've encountered a crash which seems to be related to this PR, wdyt?

1. Open the app in the two pane layout
2. Open Order list + order detail
3. Move it to a single pane layout
4. Tap on the up button
5. Select another order
6. Tap on the up button
7. 💥 

`
FATAL EXCEPTION: main
                                                                                                    Process: com.woocommerce.android.prealpha, PID: 11234
                                                                                                    java.lang.IllegalArgumentException: No destination with ID 2131363693 is on the NavController's back stack. The current destination is null
                                                                                                    	at androidx.navigation.NavController.getBackStackEntry(NavController.kt:2450)
                                                                                                    	at com.woocommerce.android.extensions.FragmentExtKt.handleResult(FragmentExt.kt:87)
                                                                                                    	at com.woocommerce.android.extensions.FragmentExtKt.handleDialogResult(FragmentExt.kt:117)
                                                                                                    	at com.woocommerce.android.ui.orders.details.OrderDetailFragment.setupResultHandlers(OrderDetailFragment.kt:477)
                                                                                                    	at com.woocommerce.android.ui.orders.details.OrderDetailFragment.onViewCreated(OrderDetailFragment.kt:206)
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2945)
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3148)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2945)
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3148)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1934)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
                                                                                                    	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
`

2024-02-21 10:58 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
>          _binding?.orderRefreshLayout?.visibility = View.GONE
🔍 Nitpick not related to this PR: It took me a bit to understand this, before I noticed there is an item called `orderRefreshLayout` in both `fragment_order_list.xml` and `fragment_order_detail.xml`. I understand now, that in this class we are working with the list xml, so we are correctly hiding it when we want to display the detail view only, but perhaps there is a space for improvement and we could rename the id in one of these layouts to avoid future confusion. Definitely not a priority.

2024-02-21 10:58 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
> +                if (!findNavController().popBackStack()) requireActivity().onBackPressedDispatcher.onBackPressed()
🔍 Nitpick: This might deserve a comment - it's not clear when can this happen and why we are manually handling it instead of relying on the system. Wdyt?

2024-02-21 15:38 UTC, dangermattic commented
<!--
  4 Errors: Please add tests for class <co...
  1 Warning: This PR is larger than 300 lin...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          4 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>CampaignCreationError</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>Editing</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>DialogState</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>IsTablet</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-02-21 16:28 UTC, samiuelson commented
> Thanks for working on this @samiuelson! I've encountered a crash which seems to be related to this PR, wdyt?
> 
> 1. Open the app in the two pane layout
> 2. Open Order list + order detail
> 3. Move it to a single pane layout
> 4. Tap on the up button
> 5. Select another order
> 6. Tap on the up button
> 7. 💥

Thanks for the review, @malinajirka 🙌🏼 
The issue seems fixed now with https://github.com/woocommerce/woocommerce-android/pull/10872/commits/0812c3f9297344c6a5f62c6db791cb1772a712a1:

https://github.com/woocommerce/woocommerce-android/assets/4527432/002c0b4f-effc-4847-b558-0be0ad3ea7c7

2024-02-22 14:20 UTC, malinajirka approved these changes
Thanks @samiuelson ! Works as expected :shipit:

2024-02-22 14:20 UTC, merged