Bug/10862 crash when no orders
woocommerce/woocommerce-android pull request #10877
Opened 2024-02-21 11:05 UTC by samiuelson

Closes: #10862 

### Description

This PR fixes the crash happening on tablets when entering the Orders screen signed into a newly created store without orders.

### Testing instructions

1. Create a new store (e.g. inside the app)
2. Go to Orders – app should no longer crash; empty state view should be displayed
3. Create a new order – verify it is visible on the order list

### Images/gif

|tablet|phone|
|---|---|
|<img src=https://github.com/woocommerce/woocommerce-android/assets/4527432/44e382ce-f39d-469c-966f-9f036bcdc9a0/>|<img src=/>|

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

2024-02-21 11:08 UTC, dangermattic commented
<!--
  2 Errors: Please ensure the PR has the <...
  1 Warning: This PR is larger than 300 lin...
  2 Messages: <p>This PR contains changes to...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please ensure the PR has the <code>category: tracks</code> label.</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>SelectedOrderTrackerViewModel</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          2 Messages
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-02-21 11:18 UTC, dangermattic commented
<!--
  0 Errors
  2 Warnings: <code>strings.xml</code> files...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>strings.xml</code> files should only be updated on release branches, when the translations are downloaded by our automation.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-02-21 13:20 UTC, malinajirka requested changes
Thanks @samiuelson!

Ideally, we'd keep showing two pane layout but display some meaningful message in the right pane. Having said that, I understand that hiding the right pane is a good enough solution which helps us move forward. However, I noticed an issue, which is visible even on the video you attached - notice, that after the order is created, the view remains as single pane => this doesn't look great, but more importnatly, there is no way how to open the detail of the order => clicking on it doesn't do anything.

2024-02-21 15:20 UTC, samiuelson commented
Thanks for review @malinajirka!

Good catch. I fixed the scenario you pointed out. The solution is not yet ideal because the shimmer/skeleton view is being displayed on the details pane all the time in case there are no orders. Let me know what you think.

<video width=600 src=https://github.com/woocommerce/woocommerce-android/assets/4527432/4c395f2f-555b-45e9-8803-9b8d867c5f38/>

2024-02-21 19:16 UTC, malinajirka approved these changes
Thanks @samiuelson!

The infinite loading feels okay to me - not optimal, but okay.

On my side, after I create the first order, the list refresh and I can see it there, but a second later it refreshes again and the order disappears. I have been able to reproduce it 5 out of 5 times 🤔. It works on your video though, so I'm not sure. Also, we plan to make some changes to the list updates, so perhaps, we don't need to worry about that in this PR. I'm not sure, wdyt?

[Screen_recording_20240221_201217.webm](https://github.com/woocommerce/woocommerce-android/assets/2261188/f46f70c1-368b-486e-b082-4011f1cb9831)

2024-02-22 10:50 UTC, samiuelson commented
> On my side, after I create the first order, the list refresh and I can see it there, but a second later it refreshes again and the order disappears. I have been able to reproduce it 5 out of 5 times 🤔. It works on your video though, so I'm not sure. Also, we plan to make some changes to the list updates, so perhaps, we don't need to worry about that in this PR. I'm not sure, wdyt?

I'm not sure why the order disappears. I'll merge the PR into the base branch and we will test if https://github.com/woocommerce/woocommerce-android/pull/10888 solves the list refresh issue.

2024-02-22 10:53 UTC, merged