Issue/11559 product sales last 30 days
woocommerce/woocommerce-android pull request #11631
Opened 2024-05-30 16:21 UTC by JorgeMucientes

⚠️ Requires the following FluxC changes to be merged first

Second part: #11559 

### Description

Adds all the logic needed to fetch and display sales stats for product stock card in the dashboard

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

2024-05-31 06:53 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/stock/ProductStockRepository.kt
> +    private suspend fun getProductSalesReports(stockReport: ProductStockItems):
Contex on why and how this works. 
- When fetching `wc-analytics/reports/stock` if a product has a `parentId` != 0 then the product is a variation. 
- For a variation, to get the number of items sold, we should request wc-analytics/reports/variations
- For non variable products we fetch the sales stats from `/wc-analytics/reports/products` 

In the current implementation we check what type of products the `stock` report has and fire the needed requests in parallel. 

Known [API bug](https://github.com/woocommerce/woocommerce/issues/47843): If a product has more than 3 variation attributes, then the variation products name returned from the API will be incomplete and won't have appended the variation attributes. We've reported a but here. Hope it gets fixed soon.

2024-06-04 11:14 UTC, hichamboushaba requested changes
Nice work @JorgeMucientes, the logic looks good, but there is a blocking [point](https://github.com/woocommerce/woocommerce-android/pull/11631#discussion_r1625791577) that needs to be addressed before I can properly test the changes, and I left some other remarks for you to check (but there are not blockers for this PR).

2024-06-04 11:14 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockCard.kt
> +    onRetryClicked: () -> Unit,
np, I think we should move these above the `modifier` argument, as `modifier` is optional, and these are not supposed to be trailing lambdas IMO.

2024-06-04 11:14 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockCard.kt
> +        Column(modifier = Modifier.padding(start = 8.dp, top = 8.dp)) {
a very minor np: having non-symmetric paddings makes the logic harder, IMO. To remove the use of non-symmetric paddings, I would use a `Spacer` with a size of `8.dp` instead of the start padding.

2024-06-04 11:14 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/stock/ProductStockRepository.kt
> +                        .map { it.productId!! },
np, I think using `mapNotNull { it.productId }` would be safer.

2024-06-04 11:14 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/stock/ProductStockRepository.kt
> +                        .map { it.productId!! },
Same as above.

2024-06-04 11:14 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/stock/ProductStockRepository.kt
> +                )
This logic means we'll perform fetching for variation reports even when we don't have any variations, I think we should first check if the filtered list is not empty before making the API call, WDYT?

We can also apply the same logic for the products reports as well 🤔

2024-06-04 11:14 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/stock/ProductStockRepository.kt
> +                val (productSalesResult, variationSalesResult) = getProductSalesReports(stockReportResult.model!!)
I think there is a point missing in the logic: which is checking for the local cache before fetching the sales reports, this was suggested and discussed here p1715852940439619/1715228241.268569-slack-C03L1NF1EA3

The idea is simple: just keep a local copy of the responses (stock and sales reports), this could be a simple `Map<ProductStockStatus, List<ProductStockItem>>`, then after fetching the stock report, just compare the products and their stock quantities with the cache, and if they didn't change, proceed with returning the cached value, otherwise invalidate cache and fetch new reports.

This can be implemented on a separate PR if you prefer.

2024-06-04 11:14 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/stock/ProductStockRepository.kt
> +                )
So after testing the feature, it's not just about the optimization of not doing an unneeded API call, the API call fails when we don't have any variations, the API returns the following error: `Invalid parameter(s): per_page`

2024-06-04 11:14 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockCard.kt
>                  WidgetError(
Just a reminder, we'll need to handle the case of when WCAnalytics are missing, I kept a task for this in the ticket https://github.com/woocommerce/woocommerce-android/issues/11544

2024-06-04 11:46 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockCard.kt
>                  WidgetError(
I can take care of this if you are OK with this 🙂

2024-06-04 11:52 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockCard.kt
>                  WidgetError(
I also have some free time, so I can take care of implementing this change if needed.

2024-06-04 14:25 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/stock/ProductStockRepository.kt
> +                )
Great catch, I actually noticed that while adding unit tests to the repository and already fixed it here: https://github.com/woocommerce/woocommerce-android/pull/11656

> We can also apply the same logic for the products reports as well
The products report fetching already ensures not making any request if there aren't any products. The check is done inside the function `getProductSales()`. I was planning on adding the same check for `getVariationsSales()`, but I missed it.

2024-06-04 14:39 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/stock/ProductStockRepository.kt
> +                val (productSalesResult, variationSalesResult) = getProductSalesReports(stockReportResult.model!!)
Good point! Missed that part. I'll address that in a different PR. Thanks

2024-06-04 14:43 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stock/DashboardProductStockCard.kt
>                  WidgetError(
No worries I can handle it in the same PR where I handle the in-memory cache to avoid unneded requests.

2024-06-04 14:46 UTC, JorgeMucientes commented
Hey @hichamboushaba, thanks for the review and the excellent feedback, as always. I've addressed all the suggestions. About the blocking issue as mentioned above I fixed it in the PR were I added the tests, so no need to add here. 

The rest of the bigger changes (memory cache and handling `WCAnalytics are missing` case) I'll tackle that in a different PR.

2024-06-04 15:18 UTC, hichamboushaba approved these changes
Nice work @JorgeMucientes, let's merge this, and handle the missing parts on other PRs.

One missing part is an empty state, the card looks like this when we don't have any products matching the selected filter:
<img width="331" alt="Screenshot 2024-06-04 at 16 07 02" src="https://github.com/woocommerce/woocommerce-android/assets/1657201/26926207-f304-4eda-9949-7ebadc5af490">

> Disabling Stock card if the store doesn't have any products or orders yet. Currently, if the store doesn't have any product or orders in place and the stock card is added to the dashboard the error state is displayed. So this is a good scenario for testing the error state of the card.

Disabling the card when the site doesn't have products is a good idea, but why would we need to disable the card when the store doesn't have orders? In my experience, this didn't cause any errors, the card worked fine.

2024-06-04 15:42 UTC, JorgeMucientes commented
@hichamboushaba 

> One missing part is an empty state; the card looks like this when we don't have any products matching the selected filter:

Good catch! I'll make sure to add one

> Disabling the card when the site doesn't have products is a good idea, but why would we need to disable the card when the store doesn't have orders? In my experience, this didn't cause any errors, the card worked fine. 

I don't have a strong opinion about this, but I felt that if the user doesn't have any orders, a card that displays stock and sales isn't very useful to them. But I can disable it only if there are not products 👍🏼

2024-06-04 17:40 UTC, merged