Fix stats getting refreshed twice when app opened the second time
woocommerce/woocommerce-android pull request #1181
Opened 2019-06-26 07:31 UTC by anitaa1990

Fixes #1178 . The `My Store` tab was getting refreshed twice when the app is closed and open again. This was because when the app is opened again, the fragment was getting re-created and at the same time, the `OnHiddenChanged` method was getting called right away. Since the fragment was not hidden, the stats was getting refreshed again.

### The tracking events:
`dashboard_main_stats_loaded`
`dashboard_top_performers_loaded`
`dashboard_unfulfilled_orders_loaded`

### Changes:
- Added a new variable called `isStatsRefreshed` which is checked in `OnHiddenChanged` method. Only if the value is set to `false`, the request to refresh the stats will be initiated.

### Testing:
- Click on the `Orders` and `Notifications` tab. Click on the `My Store` tab and verify that fragment is refreshed. i.e. the dashboard tracking events are called once.
- Click on the `Orders` tab and click on any order. Click on the `My Store` tab and verify that fragment is refreshed. i.e. the dashboard tracking events are called once.
- Click on the `Orders` tab and click on any order. Click on `Fulfill` button or `Details` button. Click on the `My Store` tab and verify that fragment is refreshed. i.e. the dashboard tracking events are called once.
- Open the app. Click on the back button. Now open the app again and verify that the dashboard tracking events are called only once.

### Behaviour before the fix:
![ezgif com-crop (1)](https://user-images.githubusercontent.com/22608780/60081119-d3e8bf80-974e-11e9-924e-5d7579c9378a.gif)

### Behaviour after the fix:
![ezgif com-crop](https://user-images.githubusercontent.com/22608780/60160184-6f8f3400-9812-11e9-8a5b-2f2fba125887.gif)

2019-07-01 05:11 UTC, AmandaRiu requested changes
@anitaa1990 ~Stepping through the code I can't find any difference between `develop` and this branch as far as double stats being fired.~

~Also after a bunch of testing I believe the change implemented in this PR doesn't have any effect because it sets `isStatsRefreshed` to `false` whenever the user navigates away from the fragment (hidden = true), and then the next time `onHiddenChanged` is called it's when the user navigates back to the dashboard so `!isHidden && !isStatsRefreshed` will always be `true`, and doesn't have a different effect than the original check to only refresh the dashboard if `!hidden`.~

~I placed a breakpoint [here](https://github.com/woocommerce/woocommerce-android/blob/570940639cd45caf09f148911ad2b4a1437eb176/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardPresenter.kt#L87) since that's the method that eventually leads to the `onWCStatsChanged` event getting fired. The issue is we will refresh the stats page every time the user navigates back to it (when it's no longer hidden) via the `onHiddenChanged` method and we will see double track events being fired (for example `DASHBOARD_MAIN_STATS_LOADED`) when an order is changed due to the `onOrderChanged` event in `DashboardPresenter` [here](https://github.com/woocommerce/woocommerce-android/blob/570940639cd45caf09f148911ad2b4a1437eb176/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardPresenter.kt#L230) which also calls the methods to refresh the dashboard stats.~

~Since we already do a silent refresh of the dashboard every time the user navigates back to the dashboard, I think the fix would probably be to remove the logic to refresh the dashboard stats in that else statement of `onOrderChanged`. WDYT?~

@anitaa1990 Actually, my apologies, after reviewing further, I did find a place where your change is working, and that's in the last scenario where hitting back to close the app and then reopening the app. I was confused by the test steps and was still seeing double stats during certain scenarios, but as mentioned above that was due to `onOrderChanged`. So keeping your changes plus maybe removing the refresh during onOrderChanged should cover all the bases 👍

2019-07-01 05:16 UTC, AmandaRiu commented
@anitaa1990 Actually, my apologies, after reviewing further, I did find a place where your change seems to help, and that's in the last scenario where hitting back to close the app and then reopening the app. So keeping your changes plus maybe removing the refresh during `onOrderChanged` should cover all the bases 👍

2019-07-01 09:27 UTC, anitaa1990 commented
Thanks for the quick review @AmandaRiu ! 

> Since we already do a silent refresh of the dashboard every time the user navigates back to the dashboard, I think the fix would probably be to remove the logic to refresh the dashboard stats in that else statement of onOrderChanged. WDYT?

Nice catch on this! I think it makes perfect sense! I removed the logic to refresh dashboard stats in `OnOrderChanged` in d2b7bb1. Checked scenarios where we update the order status and verified that the dashboard stats unfulfilled count is getting refreshed. PR is ready for another round 👍

2019-07-02 01:06 UTC, AmandaRiu approved these changes
LGTM! :shipit:

2019-07-02 01:06 UTC, merged