[Woo POS] Correctly show error state at the right time
woocommerce/woocommerce-android pull request #12050
Opened 2024-07-17 21:02 UTC by backwardstruck

Closes #12015

### Description

This PR introduces error handling for order creation failures. When an order creation fails, the user is presented with a detailed error message and a retry option. 

### Steps to Reproduce
1. Add items to the cart.
2. Proceed to checkout and initiate the order creation process.
3. Simulate an error condition (e.g., disconnect network, simulate server error).
4. Observe the error handling and user feedback, including the retry option.

### Testing Information

#### Devices used:
- Android Emulator

#### Scenarios covered:
1. **Network Failure**: Simulate network disconnections during order creation and ensure the error state is shown with a retry option.
2. **Server Errors**: Simulate server-side error responses (e.g., 500 Internal Server Error) and verify error handling.
3. **Validation Errors**: Trigger validation errors (e.g., invalid product ID) and confirm graceful error handling.

#### Critical Flows:
- Order creation process
- Error state visualization

### Images/GIFs

TBD

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

2024-07-17 21:05 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-07-17 22:43 UTC, backwardstruck commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepositoryTest.kt
> -    fun `given empty product id list, when createOrderWithProducts, then throw IllegalStateException`() = runTest {
This test I added was actually a duplicate.

2024-07-18 08:29 UTC, malinajirka requested changes
Thanks for working on this @backwardstruck!

The error is correctly presented, however, the app crashes when I tap on retry:
`FATAL EXCEPTION: main
                                                                                                    Process: com.woocommerce.android.prealpha, PID: 20356
                                                                                                    kotlin.NotImplementedError: An operation is not implemented.
                                                                                                    	at com.woocommerce.android.ui.woopos.home.totals.WooPosTotalsViewModel.onUIEvent(WooPosTotalsViewModel.kt:87)
                                                                                                    	at com.woocommerce.android.ui.woopos.home.totals.WooPosTotalsScreenKt$WooPosTotalsScreen$1.invoke(WooPosTotalsScreen.kt:47)
                                                                                                    	at com.woocommerce.android.ui.woopos.home.totals.WooPosTotalsScreenKt$WooPosTotalsScreen$1.invoke(WooPosTotalsScreen.kt:47)
                                                                                                    	at com.woocommerce.android.ui.woopos.home.totals.WooPosTotalsScreenKt$WooPosTotalsErrorScreen$1$1.invoke(WooPosTotalsScreen.kt:271)
                                                                                                    	at com.woocommerce.android.ui.woopos.home.totals.WooPosTotalsScreenKt$WooPosTotalsErrorScreen$1$1.invoke(WooPosTotalsScreen.kt:271)
                                                                                                    	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke-k-4lQ0M(Clickable.kt:987)
                                                                                                    	at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke(Clickable.kt:981)
                                                                                                    	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:175)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:164)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:466)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:500)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:489)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:364)`

do we plan to work on it in a separate issue or is that a bug?

I also left some in-code comments, let me know what you think. Thanks!

2024-07-18 08:29 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
> +private fun HandleErrorState(
❓ 💡  I'm not fluent with Compose, however, from all my observations composable functions are usually named after the component which they represent. However, the name of this method doesn't sound like a component but more like a business logic which will determine which component to display. 

Is that the plan or am I misinterpreting it? If it's not the plan, could you please elaborate on the reasoning behind creating this method? If it's the plan, have you considered keeping such logic in the VM layer, perhaps by using `sealed class` for WooPosTotalsState.Error?

2024-07-18 08:29 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
> +                        _state.value = WooPosTotalsState.Error(error.message ?: "Unknown error")
⚠️ It seems this string might be presented to users, but is not localized. I believe we should always use localized strings even if the plan is to release within the US at the beginning. We could use either the generic `error_generic` or perhaps create a new one which says a bit more, something like `An error occurred while creating the order, please retry!`. Wdyt?

2024-07-18 08:29 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepositoryTest.kt
> -    fun `given empty product id list, when createOrderWithProducts, then throw IllegalStateException`() = runTest {
👍 I also noticed it was missing the `@Test` annotation, so it wasn't active anyway.

2024-07-18 08:29 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
> +            override fun apply(
1. TIL about this approach to mocking static methods, thanks!

2. Is it a delibrate decision that we are not using WooLog class that is already mocked or you weren't familiar with this class? If it is a delibrate decision, could you please elaborate on the reasoning behind it? 

3. Have you considered implementing this rule somewhere more generic, so it could be re-used in other test suites? It might be perhaps worth implementing it in a separate PR to keep both PRs single focused and retain cleaner history. Wdyt?

2024-07-18 18:39 UTC, backwardstruck commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
> +                        _state.value = WooPosTotalsState.Error(error.message ?: "Unknown error")
Yes, I am going to replace all the strings with localized ones in the resource file. I made a separate GH issue for that for this feature:
https://github.com/woocommerce/woocommerce-android/issues/12016

2024-07-18 18:43 UTC, backwardstruck commented
> Thanks for working on this @backwardstruck!
> 
> The error is correctly presented, however, the app crashes when I tap on retry: `FATAL EXCEPTION: main Process: com.woocommerce.android.prealpha, PID: 20356 kotlin.NotImplementedError: An operation is not implemented. at com.woocommerce.android.ui.woopos.home.totals.WooPosTotalsViewModel.onUIEvent(WooPosTotalsViewModel.kt:87) at com.woocommerce.android.ui.woopos.home.totals.WooPosTotalsScreenKt$WooPosTotalsScreen$1.invoke(WooPosTotalsScreen.kt:47) at com.woocommerce.android.ui.woopos.home.totals.WooPosTotalsScreenKt$WooPosTotalsScreen$1.invoke(WooPosTotalsScreen.kt:47) at com.woocommerce.android.ui.woopos.home.totals.WooPosTotalsScreenKt$WooPosTotalsErrorScreen$1$1.invoke(WooPosTotalsScreen.kt:271) at com.woocommerce.android.ui.woopos.home.totals.WooPosTotalsScreenKt$WooPosTotalsErrorScreen$1$1.invoke(WooPosTotalsScreen.kt:271) at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke-k-4lQ0M(Clickable.kt:987) at androidx.compose.foundation.ClickablePointerInputNode$pointerInput$3.invoke(Clickable.kt:981) at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:175) at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:164) at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:466) at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:500) at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:489) at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:364)`
> 
> do we plan to work on it in a separate issue or is that a bug?
> 
> I also left some in-code comments, let me know what you think. Thanks!

Yes, I should have made it clear that this is just part of the feature. I have [GH issues](https://github.com/woocommerce/woocommerce-android/issues/11708) for the remaining work, including the [retry button functionality](https://github.com/woocommerce/woocommerce-android/issues/12017). The reason for that is to keep my PRs smaller. I'll note this in the description as well.

2024-07-18 18:49 UTC, backwardstruck commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
> +private fun HandleErrorState(
That's true. I'm also new to Compose. Reverted that.

2024-07-18 20:52 UTC, backwardstruck commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
> +            override fun apply(
I should have used `WooLog` instead. Changing that now.

2024-07-18 21:06 UTC, backwardstruck commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
> +                        WooLog.e(T.ORDERS, "Order creation failed - $error")
Use `WooLog` instead of `Log` per [this](https://github.com/woocommerce/woocommerce-android/pull/12050/files#r1682416492) comment.

2024-07-18 21:11 UTC, backwardstruck commented
Thanks for the suggestions @malinajirka This is now updated.

2024-07-19 05:49 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
> +                        _state.value = WooPosTotalsState.Error(error.message ?: "Unknown error")
👍 Thanks! 

In general, I'd personally consider implementing these types of tasks within one PR. On one hand, I like that it keeps the PR smaller and even more focused but on the other hand the cost of re-testing all the flows after strings are updated is quite high IMO.

2024-07-19 05:52 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
> +                        WooLog.e(T.ORDERS, "Order creation failed - $error")
Awesome thanks! One last nitpick - we might want to consider introducing a new `Woo.T` for POS to make the logs a bit easier to parse. Either case, this definitely isn't a blocker for this PR.

2024-07-19 06:03 UTC, malinajirka approved these changes
Thanks for the updates @backwardstruck ! I believe it's good to go :shipit: , I'm leaving the merge for you in case you'd decide to make the suggested change in WooLog within this PR.

2024-07-19 06:03 UTC, merged

2024-07-19 14:57 UTC, backwardstruck commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
> +                        WooLog.e(T.ORDERS, "Order creation failed - $error")
Great idea. I had auto-merge turned on so I'll add an issue for this:
https://github.com/woocommerce/woocommerce-android/issues/12083

2024-07-19 14:58 UTC, backwardstruck commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
> +                        _state.value = WooPosTotalsState.Error(error.message ?: "Unknown error")
Yep. I understand the tension between making the feature in a PR more complete and having the PR remain small. I can do the strings in the PR going forward if that's helpful.

2024-07-22 10:21 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
> +                        _state.value = WooPosTotalsState.Error(error.message ?: "Unknown error")
Yeah, it's tricky to find the balance. What I personally try to ask myself is if making the change in one PR will make the PR more tricky to review => with strings I believe it won't. Similarly with tests, those are actually making the PR significantly **easier** to review IMO. If we start fixing unrelated bugs in a PR, that's what usually makes it more difficult to review. So all in all, it's not about the number of lines per se, more about the number of things it solves and how are those un/related. Wdyt?

2024-07-22 19:45 UTC, backwardstruck commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
> +                        _state.value = WooPosTotalsState.Error(error.message ?: "Unknown error")
> Yeah, it's tricky to find the balance. What I personally try to ask myself is if making the change in one PR will make the PR more tricky to review => with strings I believe it won't. Similarly with tests, those are actually making the PR significantly **easier** to review IMO. If we start fixing unrelated bugs in a PR, that's what usually makes it more difficult to review. So all in all, it's not about the number of lines per se, more about the number of things it solves and how are those un/related. Wdyt?

Yes, that's a good way to analyze it. I've added this to my PR review notes. Makes sense to keep the code changes related to each other so everything that's relevant can be viewed at once.

2024-07-23 10:03 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
> +                        _state.value = WooPosTotalsState.Error(error.message ?: "Unknown error")
Keep in mind that this is just my POV, not necessarily a guideline everyone in Woo follows. When a PR starts becoming big, what I find helpful is split it into N consecutive PRs depending on each other and ask the reviewer to test just the last one in the chain => this allows them to test the changes just once, keeps each of the PRs easy to reason about, and often gives us the best of the both worlds (unless the number of changes and back-forth merges between the branches start causing too much overhead).

2024-07-23 14:06 UTC, backwardstruck commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
> +                        _state.value = WooPosTotalsState.Error(error.message ?: "Unknown error")
That's an idea. I am often chaining my PRs anyway. I could just wait until I have the full chain ready before assigning the reviewer.