[Google for Woo] Refactor Webview usage to only use WPComWebview
woocommerce/woocommerce-android pull request #12097
Opened 2024-07-22 05:11 UTC by hafizrahman

Closes: #

### Description

### Steps to reproduce

### Testing information

### Images/gif

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

2024-07-22 05:13 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-07-22 06:29 UTC, dangermattic commented
<!--
  1 Error: Please add tests for class <co...
  1 Warning: This PR is larger than 300 lin...
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>WebViewEvent</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-07-22 11:18 UTC, hichamboushaba requested changes
Thanks @hafizrahman for working on this.

As shared in the comments, there is a major issue with the approach used in the PR, and I'm afraid there is not an easy solution to achieve what you are trying while reusing the `WPComWebViewFragment`, I think the easiest solution for you is to have a specific fragment used only for the Google Ads campaign creation, the `WPComWebViewFragment` is intended for more simple usages.

As an example for how to approach this, you can check how we handled the Blaze campaign creation in the WebView, it's very similar to what you are trying to achieve here, and should provide a clear idea of how to it while reusing many parts of the `WebView` architecture in the app.
The code is available here: https://github.com/woocommerce/woocommerce-android/tree/e49ff61cbdd887b6726c9c8f07c8e7b28ab8017c/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze, the classes suffixed with `BlazeCampaignCreation`

2024-07-22 11:18 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/wpcomwebview/SharedWebViewFlow.kt
> +class SharedWebViewFlow @Inject constructor() {
Good idea for this @hafizrahman, but sadly and given Android's quirks, this won't work as expected in some cases, I'll explain more below.

Given how this is being used, we assume that the previous fragment will stay active in the backstack while the user creates the campaign, but this is not true, if the Activity was re-created for some reason (the device was low on resources, and the app was on the background for example), only the top fragment (the last one on the backstack) will be re-created, the others won't be re-created until we pop the backstack, and this means that all events emitted during this time will be lost.

You can simulate this with the following (in the branch of the tracking):
1. Go to the developer options, and enable the option: `Don't keep activities`
2. Open the app, then start the campaign creation flow.
3. Switch to a different app, then switch back to the Woo app.
4. Perform any actions on the campaign creation, and notice that the events are not tracked.

You might say that this doesn't happen often, but in my experience it does happen quite often given the limited resources of Android devices.

2024-07-22 11:18 UTC, hichamboushaba commented on WooCommerce/src/main/res/navigation/nav_graph_main.xml
> +            app:argType="boolean" />
Just a discussion regarding this flag, why do we need it? couldn't we just just check the `SelectedSite` insite the `WPComWebViewAuthenticator` and decide when to authenticate and when not?

2024-07-22 11:44 UTC, hafizrahman commented
@hichamboushaba Thanks for the comment, that's an angle that I hadn't considered and I'm glad I got you to review it. I'll refactor using the example in `BlazeCampaignCreation-`.

2024-07-23 12:20 UTC, hafizrahman commented
@hichamboushaba I added the refactor by creating a separate `GoogleAdsWebView` as you suggested. The code more or less looks the same as the previous iteration, without the flow. For tracking, the plan is just to do it directly inside `GoogleAdsWebViewViewModel`'s various functions.

> Just a discussion regarding this flag, why do we need it? couldn't we just just check the SelectedSite insite the WPComWebViewAuthenticator and decide when to authenticate and when not?

As for this, I'm creating a specific usecase `CanUseAutoLoginWebview` just to make it super clear what the criteria is, and make things easier to test also. With this current refactor, it is only injected into `GoogleAdsWebViewViewModel`.

 Let me know what you think!

2024-07-24 09:18 UTC, hichamboushaba approved these changes
Nice work @hafizrahman, the code looks great, I left just one small remark regarding the usage of the layout file `R.layout.fragment_googleads_webview`, it's not blocking, but it would be great to remove it before merging the PR.

2024-07-24 09:18 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/google/webview/GoogleAdsWebViewFragment.kt
> +class GoogleAdsWebViewFragment : BaseFragment(R.layout.fragment_googleads_webview) {
I don't think we need a layout file for this Fragment, it's using `Compose`.

I think this was a copy paste from the `WPComWebViewFragment`, and I mistakenly didn't remove this part when I converted it to Compose 🤦, so for your case now, you can remove this part and remove the file `R.layout.fragment_googleads_webview`

2024-07-24 12:29 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/google/webview/GoogleAdsWebViewFragment.kt
> +class GoogleAdsWebViewFragment : BaseFragment(R.layout.fragment_googleads_webview) {
Thanks for catching that. Done https://github.com/woocommerce/woocommerce-android/pull/12097/commits/7b8c8b9727d65f01a5bd1eeebbe37d0b50e83c64

2024-07-24 12:30 UTC, merged