[Woo POS] Do not send price when create an order, only product ids
woocommerce/woocommerce-android pull request #12158
Opened 2024-07-26 19:56 UTC by backwardstruck

Closes: #12144

### Description

We don’t need to send a price when creating an order, only `products_ids`. 

### Steps to reproduce

1. Go to POS
2. Add a few products
3. Checkout

Confirm price, tax and totals are correct for different carts.

### Testing information

### Images/gif

![Screenshot_20240726_155330](https://github.com/user-attachments/assets/6671908b-8683-45c7-bbaa-25eab4ff58e6)
![Screenshot_20240726_155310](https://github.com/user-attachments/assets/458dfa1f-fd6e-49c3-86ec-81244411ab6d)

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

2024-07-26 19:58 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-07-26 20:19 UTC, backwardstruck commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepository.kt
> -                                sku = product?.sku.orEmpty(),
As far as I can tell, we don't need to pass the SKU either.

2024-07-30 09:56 UTC, malinajirka requested changes
Thanks @backwardstruck!

I wanted to test the behavior before and after and I noticed it works as expected even on `trunk`.

This is an example request from `trunk`:
<img width="392" alt="Screenshot 2024-07-30 at 11 54 42" src="https://github.com/user-attachments/assets/01c243ca-8c73-4485-93a9-d65837cdcbe6">

Looking at the code, the logic seems to be implemented [here](https://github.com/woocommerce/woocommerce-android/blob/1a1500f9a6a4038fbeca5dec804fc4e749ccbdd1/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/ListItemMapper.kt#L24).

What do you think? Is there any additional value in merging this PR as well?

2024-07-30 13:21 UTC, backwardstruck commented
Thanks for pointing that out @malinajirka I was under the impression from [this comment](https://wp.me/pfoUAQ-RI#comment-736) that we needed to change what we sent. 

I agree that this change is optional at this point, as the current implementation already handles the necessary functionality. However, merging this change will offer some benefits in terms of code readability and maintainability.

It's interesting that we can set those fields but they are never actually sent 😸

2024-07-30 14:10 UTC, malinajirka approved these changes
> However, merging this change will offer some benefits in terms of code readability and maintainability.

Yep good point that the current state in which we are setting the data but ignoring them isn't optimal. I've reviewed the PR and left some comments - mostly clarifying questions, but I think this is good to be merged.

> I was under the impression from pfoUAQ-RI-p2#comment-736 that we needed to change what we sent.

I think Andrei didn't realize the implementation differs between iOS vs Android.

2024-07-30 14:10 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepositoryTest.kt
> -    fun setUp() {
❓ Could you please elaborate on the reasoning behind this change? Do you see any benefits in explicitly initializing the SUT in each test?

2024-07-30 14:10 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepository.kt
> +                                price = EMPTY_TOTALS_SUBTOTAL_VALUE,
❓Have you considered not specifying the price at all instead of setting it to `EMPTY_TOTALS_SUBTOTAL_VALUE`?  It seems we use this constant for `total` and `subtotal` because it's later on used to determine if the app should include or exclude the fields in the request [here](https://github.com/woocommerce/woocommerce-android/blob/1a1500f9a6a4038fbeca5dec804fc4e749ccbdd1/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/ListItemMapper.kt#L31). However, since the price is never included in the request, it seems a bit confusing. Wdyt? 

(P.S. It's not ideal, the existing code is not using the same constant but defines the same constant twice, but that's out of scope of this PR. We also likely shouldn't use `0` as an indicator of the value being empty, but that's also out of scope.)

2024-07-30 14:10 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepository.kt
> -                                sku = product?.sku.orEmpty(),
> It's interesting that we can set those fields but they are never actually sent 😸

I can't see a reason why we'd want to include it either - however, it seems suspicious that `price` and `sku` has been explicitly set on this empty order item. 

Looking back in history, we were not setting them when [this code was implemented](https://github.com/woocommerce/woocommerce-android/pull/11705/files) but decided to add them explicitly later on [here](https://github.com/woocommerce/woocommerce-android/pull/11717). Perhaps @samiuelson might have more context why they were added and how the code evolved?

2024-07-30 14:10 UTC, merged

2024-07-30 14:18 UTC, backwardstruck commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepositoryTest.kt
> -    fun setUp() {
My understanding is that we don't want to have the setup method in our tests. Like how I created `ChangeDueCalculatorViewModelTest`. Is that not the case?

2024-07-30 14:20 UTC, backwardstruck commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepository.kt
> +                                price = EMPTY_TOTALS_SUBTOTAL_VALUE,
That's a good point. Since it's not being sent I guess we don't need to set it at all. I'm learning a lot more about how this code works!

2024-07-30 14:24 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsRepositoryTest.kt
> -    fun setUp() {
It's likely I might be missing some context/discussion - if that's something you discussed and decided against, it is completely fine with me. In general, in the codebase (not POS related) we have been using @Before quite a lot.