[Custom Fields] Metadata refactor - part 2
woocommerce/woocommerce-android pull request #12252
Opened 2024-08-07 17:55 UTC by hichamboushaba

Closes: #12212

### Description
This PR updates the app to align with the FluxC change introduced in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3073 and https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3074.

For the app part, the needed changes were:
- Update the Product model to expose the bundle min/max sizes and update the logic of calculating the quantity rules to use them.
- Update the function `ProductDetailRepository#getProductMetadata` to use the new FluxC function.

### Testing information
##### Product Addons
1. Install the [WooCommerce Product Addons](https://woocommerce.com/products/product-add-ons/) extension on your store.
2. Add some addons to one of the products.
3. Create an order using this product while using some addons.
4. Open the app and enable the"View Add-ons" feature in the "Beta features" in the app's settings.
5. Open the product details of the product from step 2.
6. Confirm the "Product Add-ons" row is present, and when tapped it shows the list of product addons added above.
7. Open the order details for the order from step 3
8. Confirm a button "View add-ons" is shown, and when tapped it shows the list of selected addons.

##### Subscriptions
1. Install the [Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/) extension on your store.
2. Open the app.
3. Test creating and editing subscription products, and confirm there are no issues.

##### Regression
Smoke test products features (display, creation and edition) 
 
- [x] I have considered adding unit tests for this change. If I decided not to add them, I have provided a brief explanation below (optional):
- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

2024-08-07 17:59 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-08-13 18:06 UTC, irfano requested changes

2024-08-13 18:06 UTC, irfano commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/addons/AddonTestFixtures.kt
> +            ?.map { RemoteAddonMapper.toDomain(it) }
Before, we were setting the `metadata` of `WCProductModel` and the model was parsing it so we could `get` addons. Now, `addons` are separated from `WCProductModel`. I believe that adding logic to parse product_addon_metadata.json to set defaultProductAddonList is no longer necessary. I suggest that we set `defaultProductAddonList` in the code, similar to how we did it for `defaultAddonsList` below, and then remove `product_addon_metadata.json`. WDYT?

2024-08-13 18:10 UTC, hichamboushaba commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/addons/AddonTestFixtures.kt
> +            ?.map { RemoteAddonMapper.toDomain(it) }
I agree with you @irfano, but since this is just for tests, I decided to not spend time on writing the mocks by hand and instead keep using `mocks/product_addon_metadata.json`, if you think this is a major issue, I can work on fixing it.

2024-08-13 18:55 UTC, irfano approved these changes
LGTM! 👍🏻 I'm not merging, and assigning the PR to you for merging.

2024-08-15 16:07 UTC, merged