[Tooling] Release-on-CI automation improvements
woocommerce/woocommerce-android pull request #12265
Opened 2024-08-08 19:09 UTC by iangmaia

This PR implements a few additions for our release automation on CI:
- Automatically move PRs from the current release milestone to the next one
- Uses the shared `create_release_backmerge_pull_request` Action from [release-toolkit](https://github.com/wordpress-mobile/release-toolkit).
- Make sure release tasks won't fail due to milestones already being closed
- Close hotfix milestone

2024-08-08 19:11 UTC, dangermattic commented on fastlane/Fastfile
> +    create_release_backmerge_pull_request(
<table data-meta="generated_by_pr-check">
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/woocommerce/woocommerce-android/blob/f0bd62ea3404de42aa0a9ef809079221f600677a/fastlane/Fastfile#L1302"></span>Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.</td>
    </tr>
  </tbody>
</table>

2024-08-08 19:11 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-08-19 17:17 UTC, AliSoftware requested changes

2024-08-19 17:17 UTC, AliSoftware commented on fastlane/Fastfile
> +    ensure_branch_does_not_exist(new_release_branch)
To follow Ruby conventions and indicate that the lane will be interrupted and existed early if this assetion fails
```suggestion
    ensure_branch_does_not_exist!(new_release_branch)
```

2024-08-19 17:17 UTC, AliSoftware commented on fastlane/Fastfile
> +      )
⚠️  We need to call `update_assigned_milestone` **before** calling `set_milestone_frozen_marker`, due to a bug/latency in GitHub API.

Indeed I've observed in the past (in Tumblr) that if you call `set_milestone_frozen_marker` first, GitHub will take a couple of seconds to update the milestone title—and I'm guessing all its references in the PRs or issues which are referencing it, and probably triggering a quick reindexing of its database as well…—which means that when `update_assigned_milestone` tries to do a `get_milestones` + do a search using the query API to find all PRs with `milestone:"#{milestone_title}"`, this will return no result and fail, probably as GitHub would still be indexing/propagating the change of the milestone's name from `set_milestone_frozen_marker` called only seconds beforehand.

Swapping the order of the call for those 2 actions in the `Fastfile` solves the issue.

2024-08-19 17:17 UTC, AliSoftware commented on fastlane/Fastfile
> +      Please close any previous backmerge PR for `#{version}`, also deleting the merge branch, and then run again the release task.
Except that the Release Manager might not be able to run the release task again, especially if that backmerge PR failure happened during `complete_code_freeze` while you added `retry: { manual: { allowed: false }}` to those in this PR.

So we might want to adjust the wording of the recovery suggestion there.

2024-08-19 17:17 UTC, AliSoftware commented on fastlane/Fastfile
> +  buildkite_annotate(style: 'error', context: 'error-creating-backmerge', message: error_message) if is_ci
`buildkite_annotate` will never be run because `UI.user_error!` will exit the lane early and make the lane crash (as it's `!` suffix implies as per Ruby conventions)

You need to swap the calls of these two if you want `buildkite_annotate` to ever been called.

2024-08-19 17:17 UTC, AliSoftware commented on fastlane/Fastfile
> +def ensure_branch_does_not_exist(branch_name)
Suggestion to rename this helper with a `!` suffix to abide to Ruby's naming convention wrt to methods that `raise` and exit early.

2024-08-19 17:17 UTC, AliSoftware commented on fastlane/Fastfile
> +  buildkite_annotate(style: 'error', context: 'error-checking-branch', message: error_message) if is_ci
Ditto, need to swap those two in order for the `buildkite_annotate` to actually be called before we make the lane crash/exit early.

2024-08-21 19:46 UTC, iangmaia commented on fastlane/Fastfile
> +    ensure_branch_does_not_exist(new_release_branch)
Updated on be3d32506a9c15dcf4ce1d89112723a0e79a15ba together with some other fixes and improvements mentioned in this set of Woo / Day One ReleasesV2 PRs.

2024-08-21 19:47 UTC, iangmaia commented on fastlane/Fastfile
> +      Please close any previous backmerge PR for `#{version}`, also deleting the merge branch, and then run again the release task.
My goal of `retry: { manual: { allowed: false }}` is to enforce a setup where we don't retry using Buildkite and always do it via Releases v2 (to prevent e.g. running the same build agains the same commit and situations like that we've seen before).

I changed the wording to `run again the release task` at the end, but the "retry lane" in the beginning is still the same. I've changed it a bit on be3d32506a9c15dcf4ce1d89112723a0e79a15ba.

2024-08-21 19:48 UTC, iangmaia commented on fastlane/Fastfile
> +  buildkite_annotate(style: 'error', context: 'error-creating-backmerge', message: error_message) if is_ci
Nice catch. I think I repeated this error in the PRs when I first implemented this solution with just `UI.error(error_message)`, which I later swapped to `UI.user_error!(error_message)`. I've updated it on be3d32506a9c15dcf4ce1d89112723a0e79a15ba.

2024-08-21 21:56 UTC, AliSoftware approved these changes
Left two nitpicks about wording and error reporting but otherwise LGTM so approving to unblock

2024-08-21 21:56 UTC, AliSoftware commented on fastlane/Fastfile
> +      report_milestone_error(error_title: "Error closing milestone `#{hotfix_version}`: #{e.message}")
Note that in our official process we don't suggest (nor automate) the creation of a GitHub milestone for hotfixes.

The only reason why we might end up having such a milestone existing in GitHub anyway is because of developers manually creating it from the GitHub UI… which is actually pretty common in this context in my experience, I think because Danger is complaining on the PR they created to include the fixes for that hotfix, and so to make Danger happy they end up typing the name of the hotfix version in the "Milestone" dropdown on their PR… and when GitHub doesn't find a matching existing milestone for that string typed in the milestone search field, the default action when you hit enter and validate that field is for GitHub to create the milestone for you. So that's why such a milestone might still end up existing once the hotfix is about to be finalized.

Given all this, I still think it's a good idea for us to add this `close_milestone` action to cover that case of manually-created-milestone… but then maybe we shouldn't `report_milestone_error` for that particular case, because it would also be totally valid for a hotfix milestone not to exist in the first place (eg if the Developers used `milestone-exemption` label to appease Dangermattic, or if they selected the then-already-closed milestone of the stable `x.y` version the hotfix was patching, as opposed to creating a hotfix milestone manually for the occasion)

2024-08-21 21:56 UTC, AliSoftware commented on fastlane/Fastfile
> +      - If you are running the release task again, the backmerge PR for the version `#{version}` might have already been previously created.
I find this new wording confusing in a different way now 😅 as I initially read it as "If you were to run the release task again, here's what would happen"

Maybe something like this instead?

```suggestion
      - If this is not the first time you are running the release task, the backmerge PR for the version `#{version}` might have already been previously created.
```

2024-08-22 12:11 UTC, iangmaia commented on fastlane/Fastfile
> +      report_milestone_error(error_title: "Error closing milestone `#{hotfix_version}`: #{e.message}")
> Note that in our official process we don't suggest (nor automate) the creation of a GitHub milestone for hotfixes.

Doesn't ReleasesV2 also create milestones for hotfixes? 🤔  I think that's what I observed (or maybe I just saw a few hotfix milestones created manually and got confused). I'll test in a bit to be sure.

2024-08-22 14:12 UTC, iangmaia commented on fastlane/Fastfile
> +      report_milestone_error(error_title: "Error closing milestone `#{hotfix_version}`: #{e.message}")
Milestones for hotfixes are created by ReleasesV2 when creating a hotfix release! Just tested now:
<img width="596" alt="Screenshot 2024-08-22 at 16 06 19" src="https://github.com/user-attachments/assets/317c92df-54ad-4e0d-83b0-d6279ff7779a">

I think it makes sense, given the entire process is automated and transparent for developers / release managers, so they'd just assign a milestone to PRs / issues as needed exactly like they do for regular releases.

2024-08-22 16:10 UTC, AliSoftware commented on fastlane/Fastfile
> +      report_milestone_error(error_title: "Error closing milestone `#{hotfix_version}`: #{e.message}")
Ohh good point. I think I based my comment from my experience with Tumblr (which is not in ReleasesV2 yet). 🤦 

> I think it makes sense, given the entire process is automated and transparent for developers / release managers, so they'd just assign a milestone to PRs / issues as needed exactly like they do for regular releases.

Yep, I agree, ReleasesV2 always creating milestones even for hotfixes makes sense to me. No changes needed there after all then 👍

2024-08-23 11:17 UTC, merged

2024-08-27 11:08 UTC, mokagio commented on fastlane/Fastfile
> +    buildkite_annotate(style: moved_prs.empty? ? 'success' : 'warning', context: 'start-code-freeze-wcios', message: moved_prs_info) if is_ci
@iangmaia @AliSoftware I was looking at this and https://github.com/woocommerce/woocommerce-ios/pull/13535 in preparation to doing the same work for the Simplenote apps.

I noticed the context here has `-wcios` where it should be `-wcandroid`.

But really, I would suggest dropping the app prefix from the context altogether. This pipeline has only this one app, so I'd say `start-code-freeze` is enough to identify the context? (_It also makes the code easier to copy-paste_)

2024-08-27 11:12 UTC, AliSoftware commented on fastlane/Fastfile
> +    buildkite_annotate(style: moved_prs.empty? ? 'success' : 'warning', context: 'start-code-freeze-wcios', message: moved_prs_info) if is_ci
Agreed

2024-08-27 18:30 UTC, iangmaia commented on fastlane/Fastfile
> +    buildkite_annotate(style: moved_prs.empty? ? 'success' : 'warning', context: 'start-code-freeze-wcios', message: moved_prs_info) if is_ci
Yep, I myself concluded the same and deleted any app-specific reference in the context in other instances 👍 
I'll update Woo, thanks for bringing it up!

2024-08-27 21:22 UTC, mokagio commented on fastlane/Fastfile
> +    buildkite_annotate(style: moved_prs.empty? ? 'success' : 'warning', context: 'start-code-freeze-wcios', message: moved_prs_info) if is_ci
I'm happy to do this little nit-change as part of my work, as I have a little tweak on the wording to propose.

It didn't occur to me to check the other apps, but I should have! Code gets better after a few iterations.