Remove QR code scanning CTA from login flow
woocommerce/woocommerce-android pull request #12303
Opened 2024-08-12 11:57 UTC by JorgeMucientes

https://github.com/user-attachments/assets/f8275a30-7961-4ee5-bfa4-3fe3c4d16f80
 | https://github.com/user-attachments/assets/f8275a30-7961-4ee5-bfa4-3fe3c4d16f80

Closes: #12301 

### Description
Currently, the QR code generation is broken. It has been reported multiple times. The backend fix is not going to happen in the short term, so for now we'll update the login email to remove the QR code entirely and disable any mentions to QR code login from the Woo app.

<img width="1418" alt="Screenshot 2024-08-12 at 09 44 54" src="https://github.com/user-attachments/assets/8ed74d80-d743-43de-8b7e-4eff47ed09f3">

### Steps to reproduce

### Testing information
1.  Start login flow
2. Enter a WP.con / Jetpack connected site url
3. Enter WP.com email
4. Click on `Log in with magic link`
5. Check the button `Scan QR code to login` button is gone

| Before  | After |
| ------------- | ------------- |
| <img width="300"  src="https://github.com/user-attachments/assets/75bc5bf7-ceb9-4b85-8f4b-49d146982af4">  | <img width="300"  src="https://github.com/user-attachments/assets/fdbba6fe-a53f-453c-a10f-29d1574c74b4">  | Cell  | Cell  |  

## Images/gif

- [ ] I have considered adding unit tests for this change. If I decided not to add them, I have provided a brief explanation below (optional):
- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

0

2024-08-12 11:59 UTC, dangermattic commented
<!--
  1 Error: Please ensure the PR has the <...
  0 Warnings
  2 Messages: <p>This PR contains changes to...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please ensure the PR has the <code>category: tracks</code> label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          2 Messages
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-08-12 17:15 UTC, irfano commented
@JorgeMucientes, I think we can target beta 19.9 for this fix. WDYT?

2024-08-13 19:24 UTC, irfano requested changes
The QR button is no longer visible. 🟢
I added two more comments for possible additional removals.

2024-08-13 19:24 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
> -                KEY_FLOW to VALUE_LOGIN_WITH_WORDPRESS_COM,
We can also remove `AnalyticsTracker.VALUE_LOGIN_WITH_WORDPRESS_COM` since it's unused now.

2024-08-13 19:24 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
> -                if (ValidateScannedValue.validate(rawValue.rawValue)) {
We can remove the `ValidateScannedValue` class, as it is no longer in use.

2024-08-14 06:35 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
> -                if (ValidateScannedValue.validate(rawValue.rawValue)) {
Good catch, removed!

2024-08-14 06:49 UTC, JorgeMucientes commented
Thanks for the review and feedback @irfano. Applied your suggestions

> @JorgeMucientes, I think we can target beta 19.9 for this fix. WDYT?

About that. I'm not sure tbh. I think the most critical part to fix is the broken [QR in the login email itself](https://github.com/woocommerce/team-ghidorah/issues/343). Removing this CTA from the app feels less importan to me. The fact that the button is visible now is not blocking the user on any relevant action or flow from the app, since there's no QR code to be scanned. 
Imho it feels fine to merge this a regular task rather than a beta fix in `19.9`. 

Wdyt?

2024-08-14 08:31 UTC, irfano approved these changes
Okay, I agree with your comment. We can target `trunk`.
LGTM! 👍🏻 I'm merging now.

2024-08-14 08:31 UTC, merged