[Product AI v2] Remove feature flag and code cleanup
woocommerce/woocommerce-android pull request #12366
Opened 2024-08-19 12:42 UTC by hichamboushaba

Closes: #

### Description

### Steps to reproduce

### Testing information

### Images/gif

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

2024-08-19 12:45 UTC, dangermattic commented
<!--
  1 Error: Please ensure the PR has the <...
  1 Warning: This PR is larger than 300 lin...
  2 Messages: <p>This PR contains changes to...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please ensure the PR has the <code>category: tracks</code> label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          2 Messages
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-08-21 16:27 UTC, irfano requested changes
Thanks for cleaning up the repo. I found more code that can be tidied up. We could use AS's command to find unused string resources, but I believe I've already listed all the new unused strings that this PR introduced.

2024-08-21 16:27 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AIProductNameBottomSheet.kt
> -                            text = stringResource(id = string.ai_product_name_sheet_title),
We can also remove
- `ai_product_name_sheet_title`
- `ai_product_name_sheet_subtitle`
- `ai_product_name_sheet_input_description`
- `ai_product_name_sheet_generate_button`
- `ai_product_name_sheet_regenerate_button`
- `ai_product_name_sheet_error_message`

from `strings.xml`.

2024-08-21 16:27 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AIProductNameBottomSheetFragment.kt
> -            context?.copyToClipboard(getString(R.string.ai_product_name_copy_label), name)
We can remove
- `ai_product_name_copy_label`
- `ai_product_name_copy_success`
- `ai_product_name_copy_error`

from `strings.xml`.

2024-08-21 16:27 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AIProductNameViewModel.kt
> -        val result = aiRepository.generateProductName(
Now, there are unused functions in `AiRepository`. Can you also remove them?

2024-08-21 16:27 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AboutProductSubScreen.kt
> -                    text = stringResource(id = R.string.product_creation_ai_about_product_title),
We can also remove
- `product_creation_ai_about_product_title`
- `product_creation_ai_about_product_subtitle`
- `ai_product_creation_add_name_keywords_placeholder`
- `product_creation_ai_about_product_edit_text_caption`
- `product_creation_ai_about_product_set_tone`
- `product_creation_ai_about_product_continue_button`
- `product_creation_ai_tone_title`
- `product_creation_ai_tone_description`
- `product_creation_ai_tone_selected_content_desc`

from `strings.xml`.

2024-08-21 16:27 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/PackagePhotoBottomSheet.kt
> -                            message = stringResource(id = string.product_creation_package_photo_error),
We can also remove
- `product_creation_package_photo_error`
- `product_creation_ai_preview_description_section`
 
from `strings.xml`.

2024-08-21 16:27 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/PackagePhotoViewModel.kt
> -                            AnalyticsTracker.KEY_SCANNED_TEXT_COUNT to keywords.size
We can remove these keys:
<img width="428" alt="image" src="https://github.com/user-attachments/assets/cd14aec4-7977-418d-bf02-52b4f20e5146">
<img width="498" alt="image" src="https://github.com/user-attachments/assets/5040dabf-4c47-479f-afd6-4b6fbdced08b">

2024-08-21 16:27 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductNameSubScreen.kt
> -                text = stringResource(id = R.string.ai_product_creation_add_name_title),
We can also remove
- `ai_product_creation_add_name_title`
- `ai_product_creation_add_name_subtitle`
- `ai_product_creation_add_name_keywords_label`
- `ai_product_creation_add_name_keywords_placeholder`
- `ai_product_creation_add_name_suggest_name_button`

from `strings.xml`.

2024-08-21 16:27 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductPreviewSubScreen.kt
> -            text = stringResource(id = R.string.product_creation_ai_preview_subtitle_legacy),
We can also remove 
- `product_creation_ai_preview_subtitle_legacy`

from `strings.xml`.

2024-08-22 10:06 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AIProductNameBottomSheet.kt
> -                            text = stringResource(id = string.ai_product_name_sheet_title),
Done in 4df2243e4920b2eae24c9ca96fd159c41ecbe531

2024-08-22 10:06 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AIProductNameBottomSheetFragment.kt
> -            context?.copyToClipboard(getString(R.string.ai_product_name_copy_label), name)
Done in 4df2243e4920b2eae24c9ca96fd159c41ecbe531

2024-08-22 10:06 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AboutProductSubScreen.kt
> -                    text = stringResource(id = R.string.product_creation_ai_about_product_title),
Done in 4df2243e4920b2eae24c9ca96fd159c41ecbe531

2024-08-22 10:07 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/PackagePhotoBottomSheet.kt
> -                            message = stringResource(id = string.product_creation_package_photo_error),
Done in 4df2243e4920b2eae24c9ca96fd159c41ecbe531

2024-08-22 10:07 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductNameSubScreen.kt
> -                text = stringResource(id = R.string.ai_product_creation_add_name_title),
Done in 4df2243e4920b2eae24c9ca96fd159c41ecbe531

2024-08-22 10:07 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductPreviewSubScreen.kt
> -            text = stringResource(id = R.string.product_creation_ai_preview_subtitle_legacy),
Done in 4df2243e4920b2eae24c9ca96fd159c41ecbe531

2024-08-22 10:13 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/PackagePhotoViewModel.kt
> -                            AnalyticsTracker.KEY_SCANNED_TEXT_COUNT to keywords.size
Done in 980e6436553ce115b29af1998012360a317488b1

`VALUE_PRODUCT_CREATION` is still used, so it's kept.

2024-08-22 10:13 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AIProductNameViewModel.kt
> -        val result = aiRepository.generateProductName(
Done in 4f3460fb0c0112c2101dd0286506f59b071905f6

2024-08-22 10:41 UTC, hichamboushaba commented
Thanks @irfano for the great feedback, this is ready for another round.

2024-08-22 10:46 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AIProductNameViewModel.kt
> -        val result = aiRepository.generateProductName(
You didn't remove the `AiRepository.generateProductLegacy()` function. Is there a reason to keep it?

2024-08-22 10:58 UTC, irfano requested changes
There is one more function in `AiRepository` that I think was overlooked. We’re good to merge once it is removed. Thank you for addressing all my comments. 👍🏻

2024-08-22 12:22 UTC, hichamboushaba commented
Sorry for missing this function, it is removed now

2024-08-22 12:26 UTC, irfano approved these changes
LGTM! 👍🏻

2024-08-22 12:54 UTC, merged