Issue/12365 custom fields list
woocommerce/woocommerce-android pull request #12406
Opened 2024-08-23 11:57 UTC by hichamboushaba

Closes: #

### Description

### Steps to reproduce

### Testing information

### The tests that have been performed

### Images/gif

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

2024-08-23 11:59 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: This PR is larger than 300 lin...
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-08-23 16:09 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldModels.kt
> +        get() = HtmlUtils.fastStripHtml(value)
`WCMetaData` already contains a property `valueStrippedHtml`, it was based on the solution implemented in the previous screen (a simple regex `replace`), but from my testing on this PR, I found out that it's not working well, so I'm using here `HtmlUtils.fastStripHtml`.

I'll update the property on the WCMetaData model later when I work on any FluxC changes.

2024-08-23 16:11 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldModels.kt
> +typealias CustomField = WCMetaData
I introduced this typealias just to simulate a new "domain" model that we use in the repository and the ViewModel, this allows us to stay relatively decoupled from the lower layers without introducing a new model with the mappers.

2024-08-26 12:25 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldModels.kt
> +typealias CustomField = WCMetaData
While working on the editor screen, I found out that a new model here would be easier: it would be a `Parcelable` object to make saving it to the saved state easier, and also to return the result after saving changes, so please treat this as temporary subject, as it'll be updated later.

2024-08-26 16:24 UTC, irfano requested changes
The PR was large but organized commits helped me to review it. Great job on this task, especially for previous PRs that update metadata usage. 

I don't request major changes. Just small ones that I want you to consider.

2024-08-26 16:24 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldsRepository.kt
> +    ) = metaDataStore.hasDisplayableMetaData(selectedSite.get(), parentItemId)
This function is unused now. Do you plan to use it in the future? If not, I'd prefer not to introduce unused functions. WDYT?

2024-08-26 16:24 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldsScreen.kt
> +                        onValueClicked(customField)
This approach supports only one clickable type. For example, If I type two email addresses, it doesn't detect they're clickable. But these custom fields are key-value data. I think it's not necessary to support multiple clickables in a single field.

<img src="https://github.com/user-attachments/assets/8872198b-ca3e-49d9-8313-a23ebd5d720c" width=300>

2024-08-26 16:24 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsScreen.kt
> +        )
I would like to remove this icon. Because the chevron is iOS style, and also we don't navigate when these items are tapped. The chevron icon makes users think it'll navigate. WDYT?

2024-08-26 16:24 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldModels.kt
> +        }
I couldn't quite understand why the tests fail with Patterns.PHONE but not with PatternsCompat.EMAIL_ADDRESS. Anyway, may I suggest a different approach? Instead of using this copied code, we could continue using Patterns.PHONE but mock it during testing. Have you considered this? The mock can return `true` when we give a phone number, cause we don't test `android.util.Patterns`.

2024-08-26 18:11 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldsRepository.kt
> +    ) = metaDataStore.hasDisplayableMetaData(selectedSite.get(), parentItemId)
Yes, it will be used to decide whether the custom fields button should be displayed by default or under the "Add more details" button in the product details screen.

2024-08-26 18:12 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldsScreen.kt
> +                        onValueClicked(customField)
Yes, that's a good point, but this part is an existing feature on the previous screen that we are not planning to improve further, so this was just a port of the feature as it's from `CustomOrderFieldsFragment`, I should've mentioned this before, sorry for not doing it.

2024-08-26 18:18 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsScreen.kt
> +        )
> we don't navigate when these items are tapped

I should've mentioned that later the items will be tappable and will open an editor screen where the users can edit the fields, that's actually the reason we decided to show the chevrons on them.

I know the chevrons are more of an iOS pattern, but we also regularly use them on our app (for example, the product details and Blaze campaign form), so let's keep them here too to indicate the clickability and the navigation.

2024-08-26 18:21 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldModels.kt
> +        }
> I couldn't quite understand why the tests fail with Patterns.PHONE but not with PatternsCompat.EMAIL_ADDRESS

`Patterns.PHONE` comes from the Android SDK, so they are not part of the JVM code we run in the tests, while `PatternsCompat.EMAIL_ADDRESS` comes from an external library, so the code is available during the test.

> Anyway, may I suggest a different approach? Instead of using this copied code, we could continue using Patterns.PHONE but mock it during testing. Have you considered this? The mock can return true when we give a phone number, cause we don't test android.util.Patterns.

Can you clarify how the mock will work? `Patterns.PHONE` is a static field, and I'm not sure `Mockito` allows mocking it.

2024-08-27 13:26 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldModels.kt
> +        }
I was thinking using a provider class like this:
```
class PhoneValidatorProvider {
    fun isValidPhoneNumber(value: String) = value.startsWith("tel://") || Patterns.PHONE.matcher(value).matches()
}
```
In `given custom field contains phone, when custom field value is clicked, then phone is opened` test fucntion, we could do this:
```
...
setup {
   ...
   whenever(phoneValidatorProvider.isValidPhoneNumber("tel://123456789"))
   .thenReturn(flowOf(listOf(customField)))
}
```

This will require extra work, mostly related injecting PhoneValidatorProvider in model classes, but it would save us from using a hardcoded pattern. On the other hand the hardcoded code is not something that likely change. I wonder what you think about the benefit of this effort for my suggested change?

2024-08-27 13:31 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldModels.kt
> +        }
Thanks for the suggestion, but I think this will just overengineer the logic, we are always using a hardcoded pattern, whether it's defined in the Android SDK or the app's code is the same, so IMO this doesn't bring any real benefits while complicating the logic.

Unless you think this is a major point, I'd vote to keep it as it's 🙂.

2024-08-28 11:26 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/CustomFieldModels.kt
> +        }
Thanks for explaining it. Let's keep it as it is.

2024-08-28 11:26 UTC, irfano approved these changes
Thank you for commenting on all my comments. LGTM! 👍🏻 We can merge after resolving the conflict.

2024-08-28 12:07 UTC, merged