Update campaign list to support Evergreen campaigns and display CTR
woocommerce/woocommerce-android pull request #12433
Opened 2024-08-28 14:48 UTC by JorgeMucientes

Closes: #12389

### Description

This PR adds the following design to Blaze campaign items: 

<img width="300"  src=""> 

The logic of how campaign stats are displayed follows these rules: 

- Active () campaigns with end date will show “Remaining” budget
- Active Evergreen/Endless campaigns will show  weekly budget
- Finished campaigns will display “Total” spent budget

### Testing information
1. Log into a site with Blaze enabled
2. Create a

### The tests that have been performed

### Images/gif

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

12389

2024-08-28 14:50 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-08-28 17:48 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/notification/BlazeCampaignsObserver.kt
> +    private fun scheduleNotification(campaigns: List<BlazeCampaignModel>) {
Unrelated to the PR changes. It is a small side effect of updating `BlazeCampaignsStore.observeBlazeCampaigns` to return the domain model instead of the DB entity which shouldn't be propagated outside the storage layer.

2024-08-28 17:48 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetViewModel.kt
> -        const val WEEKLY_DURATION = 7 // Used to calculate weekly budget in endless campaigns
Moved this to the `BlazeRepository` where all the constants belong

2024-08-29 16:51 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeUiMapper.kt
> +                value = "$impressions ➔ $clicks"
I think we should move ➔ to the `strings.xml` file for localization. Otherwise, → should wrong direction in RTL languages.

2024-08-29 17:23 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignItem.kt
> +                        }
I duplicated `campaign.stats` and made it four items. The UI doesn't look good. I think we should display only the first two items of `campaign.stats` in the UI. Otherwise, there’s a possibility that the backend might break the app's UI.

<img src="https://github.com/user-attachments/assets/8f2b0c41-18c4-4242-aa5e-6cb697cc34f6" width=300>

2024-08-29 18:10 UTC, irfano requested changes
Good job! I added two minor comments.

2024-08-29 19:43 UTC, irfano approved these changes
@JorgeMucientes, my requested changes are not blockers. I'm approving the PR now in case you want to address them in a separate PR and merge this feature for 20.2 before the codefreeze.

2024-08-29 20:03 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignItem.kt
> +                            Spacer(modifier = Modifier.weight(1f))
I think setting spaces' weight to 1 does not work good here. You can see it in the horizontal mode. What about using fixed width for the space?

<img src="https://github.com/user-attachments/assets/54f21c8f-ad82-4499-88e2-681e0bed577a" width=600>

2024-08-29 21:11 UTC, JorgeMucientes commented
Thanks for the review and feedback @irfano, I will proceed to address it now 👍🏼

2024-08-29 21:48 UTC, JorgeMucientes commented
I fixed the main issues about the arrow symbol not being localised 👍🏼 . Moving that string to `string.xml` res required a bit of refactoring. While I was at it I fixed the other 2 UI glitches. However, one of them wasn't real issue, I'll provide context about it in the specific comment.

2024-08-29 21:52 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignItem.kt
> +                        }
I'm not really concerned about this one (even though it's "fixed now). The number of stats we display is up to us. It doesn't depend on any number of stats returned by the backend. The Campaign stat concept is something specific to the Woo app code. The reason we were using `campaign.stats` array is because with the prior UI we depending on where `BlazeCampaignItem` was displayed (Dashboard card or campaign list) the number of stats would be 2 or 3. But now we display the same 2 stats everywhere, so I simplified de code. 

Hope this helps clarify a bit the prior implementation 🙂

2024-08-29 21:55 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeUiMapper.kt
> +                value = "$impressions ➔ $clicks"
Good catch!! Extracted the arrow to strings.xml 👍🏼

2024-08-29 22:10 UTC, merged