Issue/12445 budget screen redesign
woocommerce/woocommerce-android pull request #12451
Opened 2024-08-29 22:21 UTC by JorgeMucientes

Closes: #12445

### Description

### Steps to reproduce

### Testing information

### The tests that have been performed

### Images/gif

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

2024-08-29 22:24 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-09-01 20:31 UTC, irfano requested changes
**Suggestion:** I noticed an issue with the date picker that's beyond the scope of this PR. When the date picker is opened, it always defaults to today's date instead of the currently selected Starts date. I believe it should display the selected Starts date. Would you like to fix this in this PR, or want me to open an issue for it?

**Bug:** Another issue is that if I change the state of the bottom sheet and then dismiss it, the state is retained when it shouldn’t be.
<details>
  <summary>bug video for bottom sheet state</summary>
 
[bug.webm](https://github.com/user-attachments/assets/7b6cdcf6-10e4-4225-a85a-9bd7b6d72b71)
</details>

**Suggestion:** The design uses the thousand separators but we don't use it in the app. I suggest adding it.

<img width="250" alt="image" src="https://github.com/user-attachments/assets/44f63556-e106-491f-aedd-11752e123c8e">

2024-09-01 20:31 UTC, irfano commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="blaze_campaign_budget_scheduled_section_title">Scheduled</string>
The design uses "Schedule." Did you use "Scheduled" intentionally?

2024-09-02 10:17 UTC, JorgeMucientes commented
Excellent feedback and attention to details @irfano. Thanks. I've addressed all of it. Ready for another round.

2024-09-03 12:11 UTC, irfano requested changes
Thanks for addressing my comments. 

- When I change the duration switch and dismiss the bottom sheet, the animation stucks halfway.  Could you please take a look at this issue?
<details>
  <summary>Bottom sheet animation issue</summary>
 
[Screen_recording_20240903_150317.webm](https://github.com/user-attachments/assets/07da8c46-9c30-497e-9725-8a65fb63e363)
</details>

- The bottom sheet still retains the slider’s value.
<details>
  <summary>Bottom sheet slider value issue</summary>
 
[bug2.webm](https://github.com/user-attachments/assets/bba9cd9a-103a-4118-abd3-0bfca1c2839b)
</details>

2024-09-03 14:51 UTC, JorgeMucientes commented
Thanks for the feedback @irfano 

> When I change the duration switch and dismiss the bottom sheet, the animation stucks halfway. Could you please take a look at this issue?

Yeah, I was aware of this issue when submitting the PR. While I spent some time trying to mitigate it, I failed and though speding to much time on it, wasn't worth it. After your feedback I gave it some more thinking. I added a workaround to ensure animations run one after the other, and the weird effect is gone. I still feel it is a bit weird that the user will see how all the values they changed are reverted to the original ones before the bottom sheet is hidden. But I think that is an acceptable behavior. 

Let me know your thoughts. 

> The bottom sheet still retains the slider’s value.

Arg completely missed that one, sorry. Fixed it.

2024-09-03 15:42 UTC, irfano approved these changes
It's better now. 👍🏻 If you told me it wasn’t a bug but a feature, I would believe it. 😆 Users can now see that their choices are not saved.

[bug.webm](https://github.com/user-attachments/assets/e2289969-9ee5-4029-a530-a1569c708c32)

LGTM!

2024-09-03 15:43 UTC, merged