[Custom Fields] Handle saving changes
woocommerce/woocommerce-android pull request #12484
Opened 2024-09-02 16:50 UTC by hichamboushaba

Closes: #

### Description

### Steps to reproduce

### Testing information

### The tests that have been performed

### Images/gif

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

2024-09-02 16:51 UTC, dangermattic commented
<!--
  1 Error: Please add tests for class <co...
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>DiscardChangesDialogState</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-09-04 10:21 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorViewModel.kt
> +        initialValue = navArgs.customField ?: CustomFieldUiModel("", ""),
Instead of passing just the `id`, we'll need to pass the whole custom field, this is because the value could be modified and not saved yet, so if we pass just the `id`, the editor will show the DB value which is different from what the user was seeing in the list.

2024-09-04 10:24 UTC, hichamboushaba commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/customfields/editor/CustomFieldsEditorViewModelTest.kt
> +    }
I don't like this mocking here, but we need it right now because the Wordpress utils library uses the `TextUtils.isEmpty` internally.

If I can find time, I might update the library to remove this usage, then remove this mock here later.

2024-09-09 12:23 UTC, irfano commented
I haven't reviewed the code yet, but I tested it and found an issue. When I edit the field a second time, the changes are ignored. Let me know if you’re unable to reproduce the issue. I can continue reviewing the code once this is fixed.

[bug.webm](https://github.com/user-attachments/assets/6b2ce010-a58e-4809-a28e-792530ead7b9)

2024-09-09 13:26 UTC, hichamboushaba commented
> I haven't reviewed the code yet, but I tested it and found an issue. When I edit the field a second time, the changes are ignored. Let me know if you’re unable to reproduce the issue. I can continue reviewing the code once this is fixed.

Thanks @irfano, nice catch, actually I thought I already fixed this issue, but I think I didn't commit the changes while refactoring some parts 🤦.
Anyway, since I already knew the cause, the fix was straightforward, I also added a unit test for this case, all done in the commit 63e98715edeca725af7385bf3759ec051f847e5c

Ready for code review now

2024-09-10 15:07 UTC, irfano commented
One more small issue: The behavior of the back button and system back navigation should be the same on the field editing screen. System back navigation doesn't display a dialog.

[Screen_recording_20240910_180523.webm](https://github.com/user-attachments/assets/bb39bed6-486b-4003-b119-ff9ae80ace01)

2024-09-10 15:15 UTC, irfano commented
**Suggestion:** When I tap just on the value ("irfan" in the screenshot), the detail screen doesn't open. I guess the reason is that values can be clickable as a view. If the value is not clickable, we could set the view "clickable=false" for the view. I believe this should resolve it.

![image](https://github.com/user-attachments/assets/6ee51cd9-79e8-4ea8-ae5d-e2651b545a4a)

2024-09-10 15:52 UTC, irfano requested changes
My review is complete. Everything works as expected, except for the points I mentioned in my comments. I can review it again once those are fixed.

2024-09-10 15:52 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsFragment.kt
> +            }
minor suggestion: We can pass the `result` directly to the view model, allowing the view model to decide whether to insert or update. It's a small logic, but it might fit better in the view model.

2024-09-10 15:58 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsFragment.kt
> +            }
Actually I decided to do it this way because the List ViewModel doesn't have to care about how the result is passed, the editor could choose to use different keys for passing insertions and additions.

But anyway, I see this goes this way or the other, so let's keep it this way :).

2024-09-10 16:06 UTC, hichamboushaba commented
> One more small issue: The behavior of the back button and system back navigation should be the same on the field editing screen. System back navigation doesn't display a dialog.

Good catch, this should be fixed by 4e700bb

> Suggestion: When I tap just on the value ("irfan" in the screenshot), the detail screen doesn't open. I guess the reason is that values can be clickable as a view. If the value is not clickable, we could set the view "clickable=false" for the view. I believe this should resolve it.

Yes, this is a known issue, I'm planing to address it on a separate PR to keep the PRs more focused.

2024-09-10 16:12 UTC, irfano approved these changes
Thanks for the fix. LGTM! 👍🏻

2024-09-10 16:33 UTC, merged