Ensures budget label doesn't get cut off in smaller screens
woocommerce/woocommerce-android pull request #12524
Opened 2024-09-04 15:11 UTC by JorgeMucientes

Closes: #12520

### Description

Fix UI glitch when displaying Blaze budget in small screens. It also improves how the Blaze stats are displayed in larger screens or tablets. 

### Steps to reproduce

### Testing information

1. Use a device with a small screen, an emulator should work. For example: `720x1280 - 4.6 inch` screen. 
2. Log into the app to a site with Blaze campaigns
3. Check the Blaze campaign stats are displayed without any cuts of like this: 

<img src="https://github.com/user-attachments/assets/3b89cd79-5b23-4830-a4a7-9b9692ccf1d9" width=300>

### The tests that have been performed

Tested different label and values length as well as tested portrait and landscape orientations in different screen sizes: 

### Images/gif

https://github.com/user-attachments/assets/14603348-b419-4410-9f26-dab579ad792d

https://github.com/user-attachments/assets/66d8d278-1e9b-4122-86ec-c4d83a65eb08

- [X] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

2024-09-04 15:13 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: This PR is assigned to the mil...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/234">20.3</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-09-05 13:02 UTC, irfano requested changes

2024-09-05 13:02 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NumberExt.kt
> +fun Long.shortenToNearestThousand(): String = when {
We will have a localization issue with this function. Andoir already has a built-in feature, [CompactDecimalFormat](https://developer.android.com/reference/android/icu/text/CompactDecimalFormat). I think we can use it.

2024-09-05 13:02 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignItem.kt
> +                    }
Have you considered using `land/dimens.xml`? I don’t think it would provide much benefit in this case, but I just wanted to remind you.

2024-09-05 13:02 UTC, irfano commented on WooCommerce/src/main/res/values/strings.xml
>      <string name="blaze_campaign_status_ctr_valur">%1$d ➔ %2$d</string>
`blaze_campaign_status_ctr_valur` is unused now, we can remove it.

2024-09-05 15:28 UTC, JorgeMucientes commented on WooCommerce/src/main/res/values/strings.xml
>      <string name="blaze_campaign_status_ctr_valur">%1$d ➔ %2$d</string>
Yeah, good catch. I actually left it to avoid extra conflicts once merging with [this](https://github.com/woocommerce/woocommerce-android/pull/12471#discussion_r1740727579).

Anyway I'll help deal with conflicts when `release-20.2` is merged back into `trunk`

2024-09-05 15:29 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignItem.kt
> +                    }
Yeah, thanks for the reminder. I'm not using the actual `dimen.xml` values for compose for neither of the orientations, for reasons we already talked about. So, for this case is the same 🙂

2024-09-05 15:32 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NumberExt.kt
> +fun Long.shortenToNearestThousand(): String = when {
Very good point @irfano . I actually based this logic in the existing logic we have in [CurrencyFormatter](https://github.com/woocommerce/woocommerce-android/blob/66d162b2cfb007c7a75234eb8454a177f0c817ec/WooCommerce/src/main/kotlin/com/woocommerce/android/util/CurrencyFormatter.kt#L47) class, that we use everywhere 😅. 
Perhaps we should refactor that. 

I've applied a solution based on your suggestion. After reading the docs for , [CompactDecimalFormat](https://developer.android.com/reference/android/icu/text/CompactDecimalFormat) it seems is discouraged for newer versions. So I've added a compatibility function to shorten the numbers. Worked well in my tests. Let me know what you think: https://github.com/woocommerce/woocommerce-android/pull/12524/commits/0e50fed33b2f227969777caf7bcf4f4f03255656

2024-09-05 19:13 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NumberExt.kt
> +fun Long.shortenToNearestThousand(): String = when {
I tested and verified it's localized now. Good job!

> Perhaps we should refactor that.

I opened an [issue](https://github.com/woocommerce/woocommerce-android/issues/12541) for it.

2024-09-05 19:14 UTC, irfano approved these changes
LGTM! 👍🏻 I'm approving and it's good to merge after fixing failing unit tests.

2024-09-06 09:40 UTC, merged