Fix bug where the App Bar and Bottom Nav don't get updated when navigation is interrupted
woocommerce/woocommerce-android pull request #12523
Opened 2024-09-04 14:59 UTC by hichamboushaba

Closes: #

### Description

### Steps to reproduce

### Testing information

### The tests that have been performed

### Images/gif

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

2024-09-04 15:02 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-09-05 11:03 UTC, irfano requested changes
Great analysis of the issue, @hichamboushaba! I was wondering if using `onFragmentStarted` instead of `onFragmentViewCreated` could help. It resolved the issue, and I didn't encounter any side effects. Could you test this patch and share your feedback?


[Fix_issue_with_updating_the_app_bar_when_switching_tabs.patch](https://github.com/user-attachments/files/16888342/Fix_issue_with_updating_the_app_bar_when_switching_tabs.patch)

2024-09-05 11:19 UTC, hichamboushaba commented
> Great analysis of the issue, @hichamboushaba! I was wondering if using onFragmentStarted instead of onFragmentViewCreated could help. It resolved the issue, and I didn't encounter any side effects. Could you test this patch and share your feedback?

@irfano yes, using `onFragmentStarted` always will resolve the issue, but it comes with two downsides:
1. It happens later in the lifecycle, so the UI changes to the app bar and bottom nav comes later to the Fragment's view creation, it's not very noticeable, but if you record the screen and play it in slow motion, you'll notice that for example when we hide the bottom nav view, it happens later when the destination is almost visible.
2. It's called more often, for example when the app goes to background then opened later, so it means we'll execute the logic more than needed.

This is why personally I think that keeping `onFragmentViewCreated` is better, and using `onFragmentStarted` just when needed is enough, WDYT?

2024-09-05 11:31 UTC, irfano approved these changes
Good catch! You’ve already noticed a side effect of it, so I’m withdrawing my suggestion. LGTM! 👍🏻

2024-09-05 11:59 UTC, merged