[Hack Week] Api Faker: introduce new module and logic
woocommerce/woocommerce-android pull request #13052
Opened 2024-12-03 11:35 UTC by hichamboushaba

Closes: #

### Description

### Steps to reproduce

### Testing information

### The tests that have been performed

### Images/gif

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

2024-12-03 11:36 UTC, dangermattic commented
<!--
  0 Errors
  11 Warnings: This PR is larger than 300 lin...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          11 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>ApiFakerConfig</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>ApiFakerInterceptor</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>ApiFakerUiHelper</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>ApiFakerDatabase</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>EndpointTypeConverter</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>QueryParameterConverter</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>Screen</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>EndpointDetailsViewModel</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>HomeViewModel</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/245">21.3</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-12-05 09:21 UTC, hichamboushaba commented on libs/apifaker/src/main/java/com/woocommerce/android/apifaker/EndpointProcessor.kt
> +        // TODO match against method and query parameters too
This TODO here is not accurate, as part of this PR we are already matching against the HTTP method, the comment is fixed in next PRs, to avoid issues with merge conflicts, let's ignore it here.

2024-12-05 09:28 UTC, hichamboushaba commented on libs/apifaker/src/main/java/com/woocommerce/android/apifaker/EndpointProcessor.kt
> +                    url.queryParameter("_method") ?: "GET",
For Jetpack Tunneled GET requests, the HTTP method is sent as a query parameter `_method`, see https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/64479b5648444c945dccae776f596daf192f4b87/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/jetpacktunnel/JetpackTunnelGsonRequest.kt#L249

This will generally be always `GET`, but to avoid hardcoding it, I'm reading it from the parameter when it exists.

2024-12-05 09:29 UTC, hichamboushaba commented on libs/apifaker/src/main/java/com/woocommerce/android/apifaker/EndpointProcessor.kt
> +                val method = pathParts.firstOrNull { it.startsWith("_method") }?.split("=")?.getOrNull(1) ?: "POST"
For Jetpack Tunneled POST requests, the actual endpoint HTTP method will be past with the json property `path`, see: https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/64479b5648444c945dccae776f596daf192f4b87/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/jetpacktunnel/JetpackTunnelGsonRequest.kt#L265

2024-12-05 09:30 UTC, hichamboushaba commented on libs/apifaker/src/main/java/com/woocommerce/android/apifaker/EndpointProcessor.kt
> +            "{\"data\": $this}"
Jetpack Tunnel sends responses [wrapped](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/64479b5648444c945dccae776f596daf192f4b87/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/jetpacktunnel/JetpackTunnelResponse.kt#L4) in a `data` property, this logic makes it easier for faking those without the wrap, which should work for both site credentials login and Jetpack login.

2024-12-05 09:32 UTC, hichamboushaba commented on .buildkite/commands/run-unit-tests.sh
> +./gradlew testJalapenoDebugUnitTest testDebugUnitTest
This allows running unit tests for all modules instead of having to list all of them

2024-12-05 10:17 UTC, Zulu-1540 requested changes
Fake account

2024-12-05 10:17 UTC, Zulu-1540 submitted a review, later dismissed
Hacker

2024-12-09 16:20 UTC, JorgeMucientes approved these changes
Great job @hichamboushaba, looking forward to see this in action in subsequent PRs. Code looks clean and well organised. I just left a couple minor questions, but nothing blocking.

2024-12-09 16:20 UTC, JorgeMucientes commented on libs/apifaker/build.gradle
> +            includeGroup "com.automattic.tracks"
Do you need all these? I see you only add FluxC as dependency (which also makes sense since it's where all the requests happen). But why include `tracks`, `mediapicker`, `wellsql`, `wordpress` ?

2024-12-09 16:20 UTC, JorgeMucientes commented on libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ApiFakerInterceptor.kt
> +                // TODO check if it's safe to always use JSON as the content type
Since the body of the faked request is anything the user inputs from the app, wouldn't it make more sense to leave `MediaType` null? For example sometimes we get and html body for API errors. Haven't tested yet, but what happens if we keep this `application/json` content type and enter non json body?

2024-12-09 16:20 UTC, JorgeMucientes commented on libs/apifaker/src/main/java/com/woocommerce/android/apifaker/EndpointProcessor.kt
> +            "{\"data\": $this}"
This brings up the same question from above. What if we don't want to have JSON formatted body with `data { }` as the root of if?  Like the example mentioned above when simulating an error that returns html?

2024-12-10 07:18 UTC, hichamboushaba commented on libs/apifaker/build.gradle
> +            includeGroup "com.automattic.tracks"
I don't like this either, but I tried to just keep the same setup as what we have in the other modules, personally I think this code should be in the root build.gradle file, or better in a [convention plugin](https://docs.gradle.org/current/samples/sample_convention_plugins.html), but since this is not the setup we have yet, I prefer to keep the same setup as the other modules here, as the `includeGroup` statements won't have any impact here, they are just used for defining the repo itself.

2024-12-10 07:24 UTC, hichamboushaba commented on libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ApiFakerInterceptor.kt
> +                // TODO check if it's safe to always use JSON as the content type
This is a good point; but for now I'll keep it like this, my rationale for hardcording `application/json` here is that all of the API requests we have in the app use JSON responses, the HTML errors are an exception that can be caused by a specific site setup that returns an error before the site handles the error.

> what happens if we keep this application/json content type and enter non json body?

It should work as you expect from the app, the upper layer will try to deserialize the content, and would fail, then return a JSON error, this is what happens when we receive HTML instead of JSON (for example this case: p1723565504566789/1720009283.216679-slack-C6H8C3G23 `API org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject`)

2024-12-10 07:25 UTC, hichamboushaba commented on libs/apifaker/src/main/java/com/woocommerce/android/apifaker/EndpointProcessor.kt
> +            "{\"data\": $this}"
As said in the other thread, I would love to keep this as is right now, changing it would require more testing.

Depending on the developer's needs, we can revisit this in the future.

2024-12-19 08:50 UTC, merged