[API Faker] Main UI and logic
woocommerce/woocommerce-android pull request #13064
Opened 2024-12-04 14:02 UTC by hichamboushaba

Closes: #

### Description

### Steps to reproduce

### Testing information

### The tests that have been performed

### Images/gif

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

2024-12-04 14:03 UTC, dangermattic commented
<!--
  5 Errors: Please add tests for class <co...
  1 Warning: This PR is larger than 300 lin...
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          5 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>ApiFakerConfig</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>ApiFakerUiHelper</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>Screen</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>EndpointDetailsViewModel</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>HomeViewModel</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-12-05 10:55 UTC, Zulu-1540 requested changes
Ok

2024-12-09 17:22 UTC, JorgeMucientes approved these changes
Nice job @hichamboushaba. Everything works as expected. Just left a minor point for discussion but nothing blocking :)

2024-12-09 17:22 UTC, JorgeMucientes commented on libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/home/HomeViewModel.kt
> +        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())
Minor np about using the magic number 5000 for this. I understand the reason of it and [where is it coming from](https://medium.com/androiddevelopers/things-to-know-about-flows-sharein-and-statein-operators-20e6ccb2bc74#:~:text=Tip%20for%20Android,used%20in%20ViewModels.): 

> Tip for Android apps! You can use WhileSubscribed(5000) most of the time to keep the upstream flow active for 5 seconds more after the disappearance of the last collector. That avoids restarting the upstream flow in certain situations such as configuration changes. This tip is especially helpful when upstream flows are expensive to create and when these operators are used in ViewModels.

However, when the state flow we are exposing from the viewmodel is a flow we want to keep running until the screen is closed (the host fragment is removed from the stack) why not use `SharingStarted.Lazily` and avoid magic numbers here? Wdyt?

2024-12-10 07:31 UTC, hichamboushaba commented on libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/home/HomeViewModel.kt
> +        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())
If we use `SharingStarted.Lazily` then if the app is background (the user switched to using a different app), then the upstream flow (the DB connection) will stay open and we keep listening to its changes, which is a waste of the device resources.

(But my above statement is true when we use [`collectAsStateWithLifecycle`](https://developer.android.com/reference/kotlin/androidx/lifecycle/compose/package-summary#extension-functions), which I'm not using here now, and which makes `SharingStarted.Lazily` and `SharingStarted.WhileSubscribed(5000)` exactly equivalent 😅. I think the API wasn't stable when I worked on this last year, I'll update it to use it now)

2024-12-10 07:37 UTC, hichamboushaba commented on libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/home/HomeViewModel.kt
> +        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())
This is done now in 9375f2d, please let me know if you still have any concerns with this.

2024-12-10 08:39 UTC, JorgeMucientes commented on libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/home/HomeViewModel.kt
> +        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())
Thanks for updating this to use `collectAdStateWithLifecycle` I wasn't aware of that API. TIL

> If we use SharingStarted.Lazily then if the app is background (the user switched to using a different app), then the upstream flow (the DB connection) will stay open and we keep listening to its changes, which is a waste of the device resources.

While I don't have a strong opinion, specially because we are discussing in the context of a developer feature, I don't think is a big deal to keep the DB connection open while the app is in background and the system is keeping the app resources alive. It might even be handy, because if the DB content changes while the user is looking at another app, when they come back the UI will be fresh right away. Anyway it's really a minor point, for just dealing with another minor thing: the `5000` magic number. 

Let's keep it as is 👍🏼

2024-12-10 09:42 UTC, hichamboushaba commented on libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/home/HomeViewModel.kt
> +        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())
> It might even be handy, because if the DB content changes while the user is looking at another app, when they come back the UI will be fresh right away

The UI will be fresh also when using `SharingStarted.WhileSubscribed(5000)`.

> I don't think is a big deal to keep the DB connection open while the app is in background and the system is keeping the app resources alive..

Yes, I agree it's a very minor point, but since this comes for free with the `collectAdStateWithLifecycle` API, I don't see why we shouldn't have this free optimization 🙂

2024-12-10 10:32 UTC, JorgeMucientes commented on libs/apifaker/src/main/java/com/woocommerce/android/apifaker/ui/home/HomeViewModel.kt
> +        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())
> but since this comes for free with the collectAdStateWithLifecycle API, I don't see why we shouldn't have this free optimization

Oh sure! My comment about "keeping things as is" was related to keeping `SharingStarted.WhileSubscribed(5000)` vs updating it to use `Lazily`

2024-12-17 10:26 UTC, merged