[POS][Custom payment UI] – Payment processing animation
woocommerce/woocommerce-android pull request #13100
Opened 2024-12-10 15:55 UTC by samiuelson

Closes: #

### Description

### Steps to reproduce

### Testing information

### The tests that have been performed

### Images/gif

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

2024-12-10 15:56 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: This PR is larger than 300 lin...
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-12-11 15:00 UTC, samiuelson commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
> +                    CardReaderPaymentState.ReFetchingOrder -> Unit
💡 `ReFetchingOrder` state is emitted after `PaymentSuccess` state on which we show Payment success screen. `ReFetchingOrder` indicates the order is synced in DB. We want to ignore it.

2024-12-11 15:02 UTC, samiuelson commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsScreen.kt
> +        clipSpec = LottieClipSpec.Markers("reader_awaiting_start", "reader_awaiting_end"),
💡 Marker names refer to makers[] table from `woopos_card_ilustration.json` file and point to animation frames we loop animation between.

2024-12-12 10:28 UTC, malinajirka approved these changes
Thanks @samiuelson ! Looks great overall. I've left two unrelated comments that don't block merge of this PR.

The animations of the illustrations look great. We'll need to work on both the state transition (transition from one illustration to the other) and screen transitions. These both look significantly smoother on iOS. However, I guess these aren't part of this PR.

I'm leaving the merge to you since I'm not sure if this is dependant on another PR or can be merged immediatelly into `[custom-payment-ui-6-use-payment-controller-in-pos](https://github.com/woocommerce/woocommerce-android/tree/custom-payment-ui-6-use-payment-controller-in-pos)`.

2024-12-12 10:28 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
> +                        uiState.value = buildPaymentProcessingState(paymentState)
🔍 I'd personally consider either renaming `processing` to something else or splitting processing and capturing steps.

The current solution is fine, but it can be a bit misleading. We could perhaps call it `buildPaymentInProgressState` and `PaymentInProgress` or something in that sense.

2024-12-12 10:28 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
> +    @Test
💬  This is not an issue with this PR since this PR is consistent with the remaining unit tests. However, I think it's something we should iterate on rather sooner than later. IMO the body of each tests should contain only changes that are affecting the result of the test. 

For example, for test called `given order draft created and reader connected, when payment is captured, should show processing state`, the body of the test would IMO ideally prepare only `order draft, reader connected, payment capture`. Everything else would be setup using a single preparation method or ideally in `@Before` or similar. The current approach increases maintenance cost as well as makes it more time consuming to write additional tests.

If implementing such approach is difficult, it's in my experience usually a flag that the SUT is doing more than it should and should be split into smaller classes.

Wdyt?

2024-12-12 11:17 UTC, malinajirka requested changes
I encountered this crash when adding a variation into the cart. I thought it was not related to this PR, so I reported it on Slack. However, it seems it works as expected on `trunk`. 

1. Open POS
2. Tap on a variable product
3. Tap on a variation
4. Tap on checkout
5. Notice crash

`
FATAL EXCEPTION: main
                                                                                                    Process: com.woocommerce.android.prealpha, PID: 19229
                                                                                                    java.lang.NullPointerException
                                                                                                    	at com.woocommerce.android.ui.woopos.home.totals.WooPosTotalsRepository$createOrderWithProducts$3$2.invokeSuspend(WooPosTotalsRepository.kt:47)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@686a376, Dispatchers.Main.immediate]
`

2024-12-12 15:49 UTC, samiuelson commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt
> +                        uiState.value = buildPaymentProcessingState(paymentState)
Good point. I got inspired by designs in Figma. Renamed in fadb13d9b62e4bc98243638d7820024c11edd62e.

2024-12-12 15:52 UTC, samiuelson commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
> +    @Test
I agree. `WooPosTotalsViewModelTest` got quite messy recently. I'll try to clean it up as much as possible in next PR and report an issue to team backlog if needed.

2024-12-12 15:54 UTC, samiuelson commented
> I encountered this crash when adding a variation into the cart. I thought it was not related to this PR, so I reported it on Slack. However, it seems it works as expected on `trunk`.
> 
> 1. Open POS
> 2. Tap on a variable product
> 3. Tap on a variation
> 4. Tap on checkout
> 5. Notice crash

Thanks for the review, @malinajirka. I've updated the branch with the latest trunk and verified the crash is no longer happening. I also addressed comments. Let me know what you think!

2024-12-12 18:07 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt
> +    @Test
Noice, thanks so much! This should definitely be a team effort considering the tests were written by all of us, so don't hesitate spliting it into tasks.

2024-12-12 18:08 UTC, malinajirka approved these changes
Awesome, thanks for the follow ups! LGTM 🙇

2024-12-12 18:09 UTC, merged