Show currently selected site in site visibility editor screen
woocommerce/woocommerce-android pull request #13160
Opened 2024-12-18 12:14 UTC by JorgeMucientes

Closes: #13107

### Description

### Steps to reproduce

### Testing information

### The tests that have been performed

### Images/gif

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

2024-12-18 12:15 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: This PR is larger than 300 lin...
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-12-21 21:55 UTC, irfano requested changes
The design and code look good. However, I noticed some issues:
- When the list is too long, the footer is not visible. 
<img src="https://github.com/user-attachments/assets/565869c6-7d01-42a4-8e2b-e12a3c265475" width=270>

- Perhaps we should consider making the entire screen scrollable instead of just the “Other Sites” section, as the current experience in landscape orientation is not ideal.

<img src="https://github.com/user-attachments/assets/a1aeb731-7542-4314-92f2-2eb9fbe27ac6" width=600>

2024-12-21 21:55 UTC, irfano commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/sitepicker/sitevisibility/WooSitesVisibilityViewModelTest.kt
> +            assert(updatedState.wooStores?.first()?.isSelected == true)
We can simplify this line as you did in the previous function:

```suggestion
            assert(updatedState.wooStores.first().isSelected)
```

2024-12-23 16:22 UTC, JorgeMucientes commented
Thanks for the review @irfano! Good points!

I fixed both of them. To do that I made the whole screen scrollable and added the footer as subtitle so it is always visible: 

https://github.com/user-attachments/assets/e8571f02-8a22-4ad7-b5a7-cc120c5462ac

The alternative approach was to anchor the footer to the bottom, but since it is a very small text it didn't look well. I did a quick test (without adding the paddings or enything) and wasn't convinced about it. Let me know what you think.

https://github.com/user-attachments/assets/700322c5-3271-4860-b877-4f1cd8f9e200

2024-12-23 16:23 UTC, JorgeMucientes commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/sitepicker/sitevisibility/WooSitesVisibilityViewModelTest.kt
> +            assert(updatedState.wooStores?.first()?.isSelected == true)
I fixed this already in a subsequent [PR](https://github.com/woocommerce/woocommerce-android/pull/13188), so I won't update it here to avoid unnecessary commits! But thank for the suggested change :)

2024-12-24 11:22 UTC, irfano commented
I don’t have a strong opinion, but placing the text at the top looks good. cc @itsmeichigo

2024-12-24 11:22 UTC, irfano approved these changes

2024-12-24 11:32 UTC, merged