Issue/13163 logic to save hidden sites
woocommerce/woocommerce-android pull request #13188
Opened 2024-12-23 11:01 UTC by JorgeMucientes

Closes: #

### Description

### Steps to reproduce

### Testing information

### The tests that have been performed

### Images/gif

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

2024-12-23 11:02 UTC, dangermattic commented
<!--
  0 Errors
  0 Warnings
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-12-24 14:41 UTC, irfano commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="site_picker_select_store_list_header_with_hidden_sites">Select store to connect(%d hidden)</string>
Is it better to add a space before parentheses?

```suggestion
    <string name="site_picker_select_store_list_header_with_hidden_sites">Select store to connect (%d hidden)</string>
```

2024-12-24 14:41 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/datastore/DataStoreModule.kt
> +    )
I think we should clear hidden site data when the user logs out. Currently, it remains. WDYT?

2024-12-24 14:41 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModel.kt
> +                    .filter { wooVisibleSiteIds.contains(it.siteId) }
We're calling `getWooVisibleSites()` above, which already filters `wooSites`. So, we can avoid filtering it twice. To reduce computation, we could add  `val wooVisibleSites = getWooVisibleSites()` at the top and use `wooVisibleSites` here. The impact is not big, but it's still ideal.

2024-12-24 14:41 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/sitevisibility/WooSitesVisibilityScreen.kt
> +            onSiteSelected = viewModel::onSiteTapped,
`onSiteTapped` is a better name. I think we can also update the `onSiteSelected` parameter name in `WooSitesVisibilityScreen()`.

2024-12-27 11:12 UTC, JorgeMucientes commented
Hey @irfano thanks for the great input! I've addressed the suggestions. This is ready for another round!

2024-12-29 20:51 UTC, irfano requested changes

2024-12-29 20:51 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/datastore/DataStoreModule.kt
> +    @DataStoreQualifier(SITE_PICKER_HIDDEN_SITES)
Since you changed the function name, let’s also rename `SITE_PICKER_HIDDEN_SITES` to `SITE_PICKER_WOO_VISIBLE_SITES`.

2024-12-29 20:51 UTC, irfano commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/sitevisibility/VisibleWooSitesDataStore.kt
> +        siteIds.forEach { (siteId, hidden) ->
We should also rename `hidden` to `isVisible` here.

2024-12-30 09:04 UTC, JorgeMucientes commented
Thank you for the careful review @irfano. I've addressed the 2 suggested renamings 👍🏼. Ready for one last round.

2024-12-30 12:35 UTC, irfano approved these changes
LGTM! 👍🏻 Thank you for making all the changes and adding this feature to the app. Great work!

2024-12-30 12:35 UTC, merged