Refund by items: Number picker dialog
woocommerce/woocommerce-android pull request #1621
Opened 2019-12-02 21:09 UTC by 0nko

This is the first sub-PR of Refund by items feature branch. I had to split up the original PR because it became too large to review all at once. I tried to separate it by logical blocks.

Unfortunately, this one's a bit weird because there is no way to actually test the functionality. That will be possible in one of the subsequent PRs, which will have the necessary logic for displaying it.

2019-12-02 23:28 UTC, AmandaRiu requested changes
@0nko I looked over the code and left a nitpick for your review. I know this is just a subset of changes, but it'd be really helpful to have the following added to the PR so I can properly review it:
- A screenshot of how the component should look from the designs
- A snippet of code I can insert somewhere in the app to open the new number picker dialog successfully. I could add it to the "search" button in the order list or something. Just so I can see how it works and make sure it's doing what it's supposed to be doing. The snippet should include a callback so I can test that the selected number is getting properly returned to the caller.

2019-12-02 23:28 UTC, AmandaRiu commented on WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/NumberPickerDialog.kt
> +        // TODO: android.app.Fragment  is deprecated since Android P.
np: Is this TODO valid? You're using the androidx version which should automatically be using the support library code (since it's the recommended way of interacting with the library going forward).

2019-12-03 09:13 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/NumberPickerDialog.kt
> +        // TODO: android.app.Fragment  is deprecated since Android P.
This isn't valid. This got copied from a different code I reused. I eventually removed this comment.

2019-12-03 09:19 UTC, 0nko commented
> A snippet of code I can insert somewhere in the app to open the new number picker dialog successfully. I could add it to the "search" button in the order list or something. Just so I can see how it works and make sure it's doing what it's supposed to be doing. The snippet should include a callback so I can test that the selected number is getting properly returned to the caller.

Thanks for the review! As I mentioned above, this is just an intermediate PR. I guess I should have just kept the dialog things together. I just tried to break up the number of changes to be reviewed. You can inspect it and test the functionality in #1622. The whole thing is being merged into a feature branch, which will contain everything before the final merge to `develop`.

2019-12-04 08:58 UTC, 0nko commented
I've thought about it and it's probably better to have the code in the same PR where it can be tested, so I'm closing this in favor of #1622.

2019-12-04 08:58 UTC, closed without merging