Refund by items: Refund items list - Step 2
woocommerce/woocommerce-android pull request #1622
Opened 2019-12-02 21:46 UTC by 0nko

This PR adds the a new refund-by-items Fragment, layout and the item list implementation with all the necessary infrastructure. It was not possible to break this down further because there are some SavedState merge conflict resolutions that needed to be included.

On the bright side, it's now possible to test the number picker dialog by tapping on the item count view. The refund by items functionality is not working, but you can select the number of items to refund and the refund subtotal and taxes are calculated. The `Select all` button works, as well.

![image](https://user-images.githubusercontent.com/1522856/69997851-53c45280-1555-11ea-824a-45e4a6892c3f.png) 
![image](https://user-images.githubusercontent.com/1522856/69997867-63439b80-1555-11ea-8237-e2fc5332bec9.png)

**Note:** #1621 must be merged before this!

2019-12-06 01:04 UTC, AmandaRiu commented
NOTE: Added the label `Tracks Events` to this PR since it includes new tracks events.

2019-12-06 02:58 UTC, AmandaRiu requested changes
@0nko First round complete 😄 I've left some comments in the code, and below are some additional notes:

> By the way, I’m not sure what’s going on with ciklint failing (ktlint passes on my machine), but the Step 3 PR is passing so just ignore it here and it’ll get fixed when that one gets merged.

Thanks for the heads up. That is weird, but I think I’ve run into that before as well. 👍

### Refund snack messaging

This part is completely unrelated to this PR specifically, but is a code change in your feature branch and would’ve already been reviewed so I thought I should bring it up. First I have a question: what is the `isEndless` property of the `ShowSnackbar` event for and where is it being handled? I looked all through the code and can’t seem to find it on my own but you are setting it to `true` in `IssueRefundViewModel` and I can’t figure out what for or if it’s working. 

The issue I found in testing is if I cancel the refund request, I still see the second snackbar message. It looks like you need to move the event trigger down to be ***inside*** the `if (!wasRefundCanceled)` block:

```
val wasRefundCanceled = waitForCancellation()
triggerEvent(ShowSnackbar(
        R.string.order_refunds_amount_refund_progress_message,
        arrayOf(formatCurrency(refundByAmountState.enteredAmount)),
        isEndless = true)
)

if (!wasRefundCanceled) {
	// Trigger the event here instead
} 
```

This is just my opinion, but first showing a snackbar message with “Your refund for %s is being processed. Please wait…” with the UNDO button, and then having that disappear and be replaced by a new snackbar with exactly the same message sans the UNDO button feels really awkward to me. WDYT about changing that second message to something like “Waiting for refund confirmation”?

## Design Review
### Refund by Items View
It looks like some padding needs to be added below the ::Next:: button on this screen. You don’t really notice it in portrait mode, but in landscape mode it feels very crunched:

<img src="https://user-images.githubusercontent.com/5810477/70291781-75158080-1799-11ea-9e2f-0f6d86dc1e14.png" width="600"/>

The **Product refund** total amount doesn’t align with the right edges of the totals above it, and the button doesn’t align on theleft and  right edges with the rest of the items. The total amount color doesn’t match the design which shows it should be #3C3C3C:

![Screenshot_1575598560](https://user-images.githubusercontent.com/5810477/70291822-91b1b880-1799-11ea-9e1a-b7420173ddca.png)

### Number Picker Dialog

![Screenshot_1575599710](https://user-images.githubusercontent.com/5810477/70291825-97a79980-1799-11ea-8e25-6fc061909afa.png)

* I recommend removing the need for clicking “OK” or cancel since only a single item may be selected and changing the value doesn't require the user confirm the change. [Per the material design guidelines](https://material.io/components/dialogs/#simple-dialog) you would use a single-click Simple dialog in this scenario. The docs also recommend using a popup contextual menu instead of a dialog since it’s less disruptive and isn’t modal. If the user clicks outside of the menu it just dismisses. 

![Screen Shot 2019-12-05 at 7 54 33 PM](https://user-images.githubusercontent.com/5810477/70291831-9e361100-1799-11ea-846d-3e3d4cc482de.png)


* If a title is needed I recommend something more descriptive like “Select  quantity”. WDYT?

2019-12-06 02:58 UTC, AmandaRiu commented on WooCommerce/src/main/res/layout/fragment_refund_by_items.xml
> +                    android:textAppearance="@style/Woo.OrderDetail.TextAppearance"/>
np: `Woo.TextAppearance`, `Woo.TextAppearance.Bold`, etc... styles should be used if not creating a custom versions for this view.

2019-12-09 12:14 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/BaseFragment.kt
> +abstract class BaseFragment : Fragment(), BaseFragmentView, HasSupportFragmentInjector {
> Why remove use of DaggerFragment?

`DaggerFragment` is just a convenience class provided by Dagger that implements the `inject()` so you don't have to do it yourself. However, it injects a `Fragment` in `onAttach()`, which is too early for the way SavedState is used to provide arguments. So here we need to implement the interface ourselves. 

> Would it be a better solution would be to extend BaseFragment to create a BaseDaggerFragment for classes that require this functionality?

We could, but almost every fragment in the app needs to be injected so I'm not sure we need a separate class.

2019-12-09 12:22 UTC, 0nko commented on WooCommerce/src/main/res/layout/fragment_refund_by_amount.xml
> +    <LinearLayout
It has 2 children. There's also the button.

2019-12-09 18:21 UTC, 0nko commented on WooCommerce/src/main/res/layout/fragment_refund_by_items.xml
> +                    tools:listitem="@layout/refunds_product_list_item"
:)

2019-12-09 18:22 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +    final val refundByItemsStateLiveData = LiveDataDelegate(savedState, RefundByItemsViewState(), onChange = {
Thanks!

2019-12-09 18:56 UTC, AmandaRiu commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/BaseFragment.kt
> +abstract class BaseFragment : Fragment(), BaseFragmentView, HasSupportFragmentInjector {
Ok, I understand now. Thanks for the clarification. 👍

2019-12-09 18:57 UTC, AmandaRiu commented on WooCommerce/src/main/res/layout/fragment_refund_by_amount.xml
> +    <LinearLayout
Oy...not sure how I missed that. 🙈

2019-12-09 20:32 UTC, 0nko commented on WooCommerce/src/main/res/layout/fragment_refund_by_items.xml
> +    <LinearLayout
I've flattened it a bit but it can't be all converted into a single `ConstraintLayout` because there's a card style that must be applied partially. Also, some `LinearLayout` are sections that can be show/hidden.

2019-12-09 21:10 UTC, 0nko commented
Thanks for the review @AmandaRiu! I've addressed your comments in code and some answers to your questions here:

> what is the isEndless property of the ShowSnackbar event for and where is it being handled? 

It was supposed to be a flag for showing an indefinite snackbar but it's not really useful so I removed it.

> It looks like some padding needs to be added below the ::Next:: button on this screen. You don’t really notice it in portrait mode, but in landscape mode it feels very crunched

Fixed.

> The Product refund total amount doesn’t align with the right edges of the totals above it, and the button doesn’t align on the left and right edges with the rest of the items. 

Fixed.

> The total amount color doesn’t match the design which shows it should be #3C3C3C:

Please ignore this for now. The amount text view is actually a button from the original design, which we decided to remove. The actual amount dialog is implemented in one of the following PRs and eventually disabled in the last one. So the correct color can be verified then.

> The docs also recommend using a popup contextual menu instead of a dialog since it’s less disruptive and isn’t modal. If the user clicks outside of the menu it just dismisses.

I'm not sure a number picker view inside a context pop up menu would work. It's scrollable and the pop up view would need to be large enough so that it'd be easy to change the value. I guess the whole thing could be converted into a list but if there were a lot of items it could become very long. We can discuss it further if you like but if do decide to change it, let's do it in a separate PR. What do you think?

Ready for another round of review :).

2019-12-11 04:30 UTC, AmandaRiu commented on WooCommerce/src/main/res/layout/fragment_refund_by_items.xml
> +    <LinearLayout
> Also, some LinearLayout are sections that can be show/hidden.

You can actually do this in `ConstraintLayout` using `Group`. Just replace that `LinearLayout` with this:

```
<androidx.constraintlayout.widget.Group
    android:id="@+id/issueRefund_discountSection"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:visibility="gone"
    tools:visibility="visible"
    app:constraint_referenced_ids="issueRefund_lblDiscount,issueRefund_discountItems,issueRefund_discountTotal"/>

<TextView
    android:id="@+id/issueRefund_lblDiscount"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_marginStart="@dimen/card_padding_start"
    android:layout_marginTop="@dimen/card_item_padding_intra_h"
    android:text="@string/discount"
    android:textAppearance="@style/Woo.Refunds.TextAppearance"
    app:layout_constraintEnd_toStartOf="@+id/issueRefund_discountItems"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toBottomOf="@id/issueRefund_lblSubtotal" />

<TextView
    android:id="@+id/issueRefund_discountItems"
    android:layout_width="262dp"
    android:layout_height="wrap_content"
    android:textAlignment="viewStart"
    android:layout_marginStart="@dimen/card_item_padding_intra_h"
    android:layout_marginEnd="@dimen/card_item_padding_intra_h"
    android:textAppearance="@style/Woo.Refunds.TextAppearance"
    app:layout_constraintEnd_toStartOf="@+id/issueRefund_discountTotal"
    app:layout_constraintStart_toEndOf="@+id/issueRefund_lblDiscount"
    app:layout_constraintTop_toTopOf="@+id/issueRefund_lblDiscount"
    tools:text="(sale4theday, firstTime, anyothertime, blah)" />

<TextView
    android:id="@+id/issueRefund_discountTotal"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_marginEnd="@dimen/card_padding_end"
    android:textAppearance="@style/Woo.Refunds.TextAppearance"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintStart_toEndOf="@+id/issueRefund_discountItems"
    app:layout_constraintTop_toTopOf="@+id/issueRefund_lblDiscount"
    tools:text="-$4.00" />
```

> I've flattened it a bit but it can't be all converted into a single ConstraintLayout because there's a card style that must be applied partially. 

This one is a little tricker, but it seems like it is possible by using a `View`, setting the background you want to it, and then arranging all the items over it, but that seems like a lot of work and one extra layer shouldn't be that big of a performance hit.

2019-12-11 04:33 UTC, AmandaRiu commented
@0nko finished another round. Made a comment in the code about `ConstraintLayout`. Also the following:

* When processing a refund that has a discount, the discount section is hidden until the user selects an item for refund. Is this intentional?
* I don’t see the option to refund shipping that were in the designs. Is this intentional?

![refund-shipping](https://user-images.githubusercontent.com/5810477/70591795-90ff9480-1b94-11ea-9473-a9970a36baf4.png)

* The parentheses around the discount items from the design are missing 
* Should the **select all** button convert to a **select none** option once clicked?

2019-12-11 09:52 UTC, 0nko commented on WooCommerce/src/main/res/layout/fragment_refund_by_items.xml
> +    <LinearLayout
Interesting, TIL. Thanks!

2019-12-11 12:25 UTC, 0nko commented
> When processing a refund that has a discount, the discount section is hidden until the user selects an item for refund. Is this intentional?

Sort of, because not all orders contain discounts. But after thinking about it, it doesn't make sense to show discounts in refunds because items already have the discount included in the price -- this is done by the API (for example, if you have an order of 2 items for $10 each and a discount for $2, the actual price for an item in the refunds would show $9). The user might be confused why the discount amount isn't applied in the total summary, so I removed that line altogether.

> I don’t see the option to refund shipping that were in the designs. Is this intentional?

Yeah. We've discovered the API doesn't support shipping refunds. But I already implemented the feature by that time. Because of this, #1623 does show it (a stub) so that it can be reviewed. It's then hidden in the next PR. I kept the code so that it can be used once the API supports it.

> Should the select all button convert to a select none option once clicked?

I've implemented this in #1633 to avoid unnecessary refactoring.

2019-12-11 19:45 UTC, AmandaRiu commented
> The user might be confused why the discount amount isn't applied in the total summary, so I removed that line altogether.

I totally agree. It confused me. I was referring to the discount being hidden even for an order that has a discount applied - it unhides itself _after_ you select an item for a refund.

> Yeah. We've discovered the API doesn't support shipping refunds. But I already implemented the feature by that time. Because of this, #1623 does show it (a stub) so that it can be reviewed. It's then hidden in the next PR. I kept the code so that it can be used once the API supports it.

👍 

> I've implemented this in #1633 to avoid unnecessary refactoring.

👍

2019-12-11 19:47 UTC, AmandaRiu commented
> But after thinking about it, it doesn't make sense to show discounts in refunds because items already have the discount included in the price -- this is done by the API (for example, if you have an order of 2 items for $10 each and a discount for $2, the actual price for an item in the refunds would show $9). The user might be confused why the discount amount isn't applied in the total summary, so I removed that line altogether.

NM - I see you have this removed now.

2019-12-11 20:02 UTC, AmandaRiu approved these changes
LGTM! Nice work @0nko :shipit:

2019-12-11 20:02 UTC, merged