Issue/1955 negative revenue stats
woocommerce/woocommerce-android pull request #1989
Opened 2020-02-24 06:15 UTC by anitaa1990

Fixes #1955. This PR adds the following changes to the new stats UI. 

- Modifies the label count of y-axis to 3 and removes logic to NOT display labels with revenue <= 0.
- Right align the x-axis labels so there's enough space in between the x-axis and y-axis labels.

#### Screenshots
<img width="300" src="https://user-images.githubusercontent.com/22608780/75131807-992e9100-56fa-11ea-819a-44299a875c4b.png">. <img width="300" src="https://user-images.githubusercontent.com/22608780/75131845-b4010580-56fa-11ea-9d43-ea0b749fca9a.png">. <img width="300" src="https://user-images.githubusercontent.com/22608780/75131867-c67b3f00-56fa-11ea-97f3-a4434513a9c4.png">. <img width="300" src="https://user-images.githubusercontent.com/22608780/75131868-c9762f80-56fa-11ea-988d-ea0f705c784a.png"> 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-02-24 06:16 UTC, anitaa1990 commented
@Garance91540, I have updated this logic only for the new stats UI but not the old Stats (without WC-admin). This is because we only display the first and the last x-axis labels in the old Stats screen and right aligning it would mean we would need to change the x-axis labels to display more than 2 values at a time. 

This is how it currently looks with just 2 x-axis labels.
<img width="300" src="https://user-images.githubusercontent.com/22608780/75131965-2bcf3000-56fb-11ea-9852-90dc08582659.png">

2020-02-24 14:17 UTC, Garance91540 commented
Hi @anitaa1990 , great progress!

I've only a few notes:
- Whenever there's negative revenue, can the second x-axis always be zero?So we avoid the case of "floating bars" that are not linked to an axis

<img width="649" alt="Screen Shot 2020-02-24 at 3 13 14 PM" src="https://user-images.githubusercontent.com/28450084/75159321-351ac580-5718-11ea-845b-88f93e8f7dd5.png">

- For the old stats, is it possible to add 4px of vertical padding between the x axis legend and the x axis? (so the -210 and Jan 24 in your screenshot have a little bit more breathing room)

Let me know if you have any questions!

2020-02-24 14:18 UTC, Garance91540 requested changes
Hi @anitaa1990 , great progress!

I've only a few notes:
- Whenever there's negative revenue, can the second x-axis always be zero?So we avoid the case of "floating bars" that are not linked to an axis

<img width="649" alt="Screen Shot 2020-02-24 at 3 13 14 PM" src="https://user-images.githubusercontent.com/28450084/75159321-351ac580-5718-11ea-845b-88f93e8f7dd5.png">

- For the old stats, is it possible to add 4px of vertical padding between the x axis legend and the x axis? (so the -210 and Jan 24 in your screenshot have a little bit more breathing room)

Let me know if you have any questions!

2020-02-27 12:27 UTC, nbradbury commented
@anitaa1990 Just wanted to make sure you saw Garance's comments above.

2020-03-05 06:34 UTC, anitaa1990 commented
Thanks for the review @Garance91540! Sorry for the late reply! It took a while to find a way to display 0 as the second axis. Let me know if this is fine. Thanks!

>  Whenever there's negative revenue, can the second x-axis always be zero?So we avoid the case of "floating bars" that are not linked to an axis

Is this fine?
<img width="300" src="https://user-images.githubusercontent.com/22608780/75954140-fdaad680-5ed8-11ea-831f-52a9a1a87b8f.png">

> For the old stats, is it possible to add 4px of vertical padding between the x axis legend and the x axis? (so the -210 and Jan 24 in your screenshot have a little bit more breathing room)

<img width="300" src="https://user-images.githubusercontent.com/22608780/75954222-30ed6580-5ed9-11ea-9909-877ac5b6dde8.png">. <img width="300" src="https://user-images.githubusercontent.com/22608780/75954228-334fbf80-5ed9-11ea-9eec-fdc10a825c11.png">

2020-03-05 14:12 UTC, Garance91540 commented
Looking great, is it possible to send me screenshots of old the time period (days, weeks, months, year) for the new stats? (I didn't see the apk)

2020-03-05 20:20 UTC, Garance91540 commented
Hi @anitaa1990 , I also just realized that our charts are currently implemented with rectangular straight lines all around, when the top of the tap bar should have rounded corners (2px radius). Here's a screenshot of the designs:

<img width="636" alt="Screen Shot 2020-03-05 at 2 16 25 PM" src="https://user-images.githubusercontent.com/28450084/76022100-1a043e80-5eec-11ea-8643-4f68e6b3f970.png">

I think this would help understand when the data bar starts and end, and decrease the "floating data bar" feels we see when the zero axis bar is in the middle of the chart. Let me know if you have any questions on this or if you;d rather open a different PR since I know it's currently implemented like this in prod.

2020-03-06 08:53 UTC, anitaa1990 commented
> Looking great, is it possible to send me screenshots of old the time period (days, weeks, months, year) for the new stats? (I didn't see the apk)

Sorry, my bad! I missed sending you the apk file yesterday! I shared it to you in Slack now. 

> I also just realized that our charts are currently implemented with rectangular straight lines all around, when the top of the tap bar should have rounded corners (2px radius). 

This is great! I created another issue [here](https://github.com/woocommerce/woocommerce-android/issues/2027) to implement with this separately since it isn't as straight forward as I thought.

2020-03-09 21:46 UTC, jkmassel commented
I'm freezing `3.8`, so this is being bumped to `3.9`. If you need it to be part of the `3.8` release, please re-target `release/3.8` and merge there. Once you have, please ping me that it's been merged and I'll be happy to cut a new release candidate!

2020-03-11 19:45 UTC, nbradbury commented
@anitaa1990 Is this ready for code review? It looks like it, but it still has the "needs design review" label.

2020-03-12 08:21 UTC, Garance91540 commented
I think that's a good V1 (sorry for the delayed answer here)!

I have a few follow-ups we can talk about after hack week as you suggested @anitaa1990

2020-03-12 08:21 UTC, Garance91540 approved these changes

2020-03-12 09:55 UTC, anitaa1990 commented
Thank you @Garance91540 for the design review! I have opened a separate issue to tackle some of the design changes needed for supporting negative revenue [here](https://github.com/woocommerce/woocommerce-android/issues/2040). 

@nbradbury, apologies for the long delay in this PR but I spent an inordinate amount of time trying to get the chart to display only 3 gridlines with 3 y-axis labels (min revenue value, 0 and max revenue value) as per the design and it doesn't look like the gridlines play well with the [zeroline](https://github.com/PhilJay/MPAndroidChart/wiki/YAxis#the-zero-line) and I got caught in a rabbit hole. i have opened a separate issue to tackle those design changes so this PR is ready for review 👍

2020-03-12 11:34 UTC, nbradbury approved these changes
:shipit:

2020-03-12 11:34 UTC, merged