Issue/2051 m2 update product status
woocommerce/woocommerce-android pull request #2240
Opened 2020-04-14 13:40 UTC by nbradbury

Closes #2051 - adds the ability to update a product's status. To test:

* Open product detail
* Choose "Product settings" from the options menu
* Tap to change the status
* Tap "Done" in settings
* Tap "Update" in product detail and verify the status is correctly updated

**Note:** This is a draft because [this FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1545) needs to be merged first.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-04-15 18:59 UTC, AmandaRiu commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt
> +                textStatusBadge.text = status.toLocalizedString(requireActivity())
great catch 👍

2020-04-15 19:03 UTC, AmandaRiu commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/BaseProductSettingsFragment.kt
> +    // descendents should override this with a unique request code
np: typo in word `descendants`

2020-04-15 19:28 UTC, AmandaRiu requested changes
@nbradbury Just a small change request, but other than that this looks great. I do have an open question about the design since in other areas we are doing things differently, but we can always address that later in a different PR if needed.

2020-04-15 19:28 UTC, AmandaRiu commented on WooCommerce/src/main/res/layout/fragment_product_settings.xml
> +    xmlns:app="http://schemas.android.com/apk/res-auto"
np: Why the `NestedScrollView`? None of the children are scrolling children like a `RecyclerView` or `List`. I'd recommend changes to just a simple `ScrollView` since it's not as heavy.

2020-04-15 19:38 UTC, nbradbury commented on WooCommerce/src/main/res/layout/fragment_product_settings.xml
> +    xmlns:app="http://schemas.android.com/apk/res-auto"
Good point. Done in 6a63912.

2020-04-16 09:40 UTC, AmandaRiu approved these changes
Awesome work @nbradbury ! :shipit:

2020-04-16 09:40 UTC, merged