Issue/m2 wp media library
woocommerce/woocommerce-android pull request #2345
Opened 2020-04-29 17:11 UTC by nbradbury

Adds the WP media library as a source for product images.

### Testing

- Open product detail and tap to add an image
- Tap "Add photos"
- Choose "WordPress media library" as the source
- Choose a few images and verify the activity title updates to show the selection count
- Press the back button and verify the discard dialog appears
- Rotate the device and ensure the selection is maintained
- Tap "Done" and verify the selected images appear on the product images screen
- Return to product detail, tap "Done" and verify the selected images are actually attached to the product

### Demos

Light mode and dark mode are very similar.

![light](https://user-images.githubusercontent.com/3903757/80624769-26070b00-8a1a-11ea-8a06-da29cf0e22ea.png)

![ezgif-4-b9dfbe17b75f](https://user-images.githubusercontent.com/3903757/80624784-2acbbf00-8a1a-11ea-950d-7ad1ab4ada12.gif)

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-04-30 02:00 UTC, AmandaRiu requested changes
@nbradbury This is looking really nice. Some issues I found:

- The “No images yet” text was hidden in light mode since the text was white and the background was set to `color_surface` which is white in light mode. 
- Opening an image full screen when other items are selected will lose selected items when returning to the image grid.

I started leaving code comments, but it ended up being easier to just [create a temp branch containing all my recommended changes for you to play with](https://github.com/woocommerce/woocommerce-android/compare/issue/m2-wp-media-library...amanda/m2-wp-media-library). I implemented light/dark theming based on how we are currently handling it in the main app, but @Garance91540 should definitely look it over and approve. 

I tweaked the selector dialog to use the design margins, as well as `Subtitle1` for the title since that's what's used in the rest of the app. 

Here are some screenshots from my changes:

Light | Dark
-- | --
![Screenshot_1588211497](https://user-images.githubusercontent.com/5810477/80664300-47ccb600-8a4b-11ea-963f-cc9f12d8c4d8.png)|![Screenshot_1588211506](https://user-images.githubusercontent.com/5810477/80664302-48654c80-8a4b-11ea-8f6f-716620420d54.png)
![Screenshot_1588211487](https://user-images.githubusercontent.com/5810477/80664307-4b603d00-8a4b-11ea-94e6-3bb32dc0bf7f.png)|![Screenshot_1588211476](https://user-images.githubusercontent.com/5810477/80664310-4c916a00-8a4b-11ea-9228-b27202dbf99c.png)

2020-04-30 07:25 UTC, Garance91540 commented
hi @nbradbury  and @AmandaRiu , looking good on my end! 2 comments:
1. is it possible to only show the "Done" top nav CTA when there's at least one image selected?
2. I noticed that both on Woo web and the WP app there's also a search feature in the top nav. not a priority but are we thinking of including it later?

2020-04-30 12:07 UTC, nbradbury commented
> * is it possible to only show the "Done" top nav CTA when there's at least one image selected?

@Garance91540 We can do that, but it would be inconsistent with all the other settings screens which always show "Done" regardless of changes.



> 2. I noticed that both on Woo web and the WP app there's also a search feature in the top nav. not a priority but are we thinking of including it later?

Honestly, I'd forgotten all about that feature even though I coded it for WPAndroid :) I don't think it's a priority but if as a team we want to add it, we certainly can.

2020-04-30 12:18 UTC, nbradbury commented
> I started leaving code comments, but it ended up being easier to just [create a temp branch containing all my recommended changes for you to play with](https://github.com/woocommerce/woocommerce-android/compare/issue/m2-wp-media-library...amanda/m2-wp-media-library)

@AmandaRiu Thanks for the thorough review and style changes! I pulled your temp branch into this PR, but I kept the always dark background for `WPMediaViewerActivity` so it matches the existing `ProductImageViewerFragment` (as well as WPAndroid).

2020-04-30 16:27 UTC, Garance91540 commented
> @Garance91540 We can do that, but it would be inconsistent with all the other settings screens which always show "Done" regardless of changes.

mmm... I guess I miss this during testint. Ideally the feedback CTA is only displayed when an action is triggered. If we haven't implemented it this way for other screens we can leave it like this for now! (I may create a separate issue later to address this issue on all the screens at once)

> Honestly, I'd forgotten all about that feature even though I coded it for WPAndroid :) I don't think it's a priority but if as a team we want to add it, we certainly can.

Totally agree that's not a priority! But nice to have later probably

2020-04-30 17:02 UTC, nbradbury commented
> I may create a separate issue later to address this issue on all the screens at once

@Garance91540 Handling this in a separate PR would definitely be preferable, as this one is already quite large.

2020-04-30 17:16 UTC, nbradbury commented
@AmandaRiu I fixed the issue with selected images not being retained in 6dd4b01. The problem was that the fragment's `onSaveInstanceState()` wasn't being called, so the selection wasn't being saved. I resolved this by having the `WPMediaGalleryView` retain & restore its own state.

2020-04-30 19:07 UTC, AmandaRiu commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaPickerRepository.kt
> +            loadContinuation?.cancel()
We tested this out further and it's working as expected 👍

2020-04-30 19:10 UTC, AmandaRiu approved these changes
Works beautifully 😍 

<img src="https://user-images.githubusercontent.com/5810477/80749592-8447f280-8adb-11ea-8c91-4fce653a862e.jpeg" width="100"/>

2020-04-30 19:10 UTC, merged

2020-05-01 08:02 UTC, Garance91540 commented
> @Garance91540 Handling this in a separate PR would definitely be preferable, as this one is already quite large.

Oh yes, for sure!