Feature/remove store stats availability banner
woocommerce/woocommerce-android pull request #2580
Opened 2020-06-26 16:40 UTC by ThomazFB

Summary
==========
Implements point 1 and 4 of #2539, this PR removes the Stats V4 availability banner and starts to activate the Stats V4 View if the API is available

Changelog
------------
| Description | Commit |
| ------------- | ------------- |
| Exclude the `MyStoreStatsAvailabilityCard` from the code base and UI since it will be no longer needed, removes from the `AppPrefs` all flags configuration related to the Stats Availability Banner  | 1c6f8b9430bf9934db77d42ab4c377b0d1c3c035 |
| Effectively starts to activate the Stats V4 right away if the V4 API is available. Removes from the `AppPrefs` and `MainActivity` any code related to the user enablement of the V4 feature and every listener method implementation and declaration related to it |  dddd849e26764f72be1c36e4455a74d849dd4e75 |
| Updates the `MyStoreStatsRevertedNoticeCard` message string, changing the Stats V3 due date warning from July 1 to September 1 | b0a673ccaed36c648fb968f551cf47e9ed8df90c |
| Rename the `isUsingV4Api` to `isV4StatsSupported` so the naming keeps the idea of the previous `isV4StatsUISupported` to ensure better code readability | b1dc8521ae79efab00df1a910b3064034b629e43 |

Screenshots when V4 API is only available
------------

| Before we just warned through a banner the Stats V4 availability and the option to try it | Now we change it right away without asking permission for the user |
| ------------- | ------------- |
| ![Screenshot_1592963863](https://user-images.githubusercontent.com/5920403/85635878-5d2e1d00-b655-11ea-9dde-217f1e7fd3da.png) | ![Screenshot_1592963801](https://user-images.githubusercontent.com/5920403/85635897-64edc180-b655-11ea-83d9-7c98c1820994.png) |

| Before | After |
| ------------- | ------------- |
| ![Screenshot_1593188945](https://user-images.githubusercontent.com/5920403/85879945-911e5500-b7b1-11ea-810f-5e760e3e6b4c.png) | ![Screenshot_1593189503](https://user-images.githubusercontent.com/5920403/85880434-684a8f80-b7b2-11ea-9a7b-f4f84060b03d.png) |

Update release notes:

- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-06-29 21:33 UTC, AmandaRiu requested changes
@ThomazFB Code chances look good! Tested through the app and noticed a couple issues:

**Double row of actionbar tabs issue:**
1. Log in with a store running v3 Woo and *does not* have WCAdmin installed.
2. On the My Store page the appropriate "upgrade" card is displayed. 
3. Install the WCAdmin plugin on the store.
4. Perform a pull to refresh. The card disappears and v4 stats are displayed, but there are no two tabbed rows:
<img src="https://user-images.githubusercontent.com/5810477/86057636-c67aab00-ba1c-11ea-8926-2a3a2b8f2bb8.png" width="330"/>

**Actionbar tabs are not removed when downgrading to v3 stats**:
1. Log in with a store that has the WCAdmin plugin installed
2. Notice v4 stats are displayed
3. In wp-admin, disable the WCAdmin plugin. 
4. Notice the v4 toolbar tabs are still visible.
<img src="https://user-images.githubusercontent.com/5810477/86057920-40129900-ba1d-11ea-961e-f4e813720e64.png" width="330"/>

There should be some code in `MyStoreFragment` to add and remove the tabs from the toolbar: `removeTabLayoutFromAppBar(...)` - that may be a good place to start troubleshooting.

2020-07-01 23:33 UTC, ThomazFB commented on RELEASE-NOTES.txt
> +* Remove Stats V4 Availability Banner Suggestion
Hey @AmandaRiu, thanks for that information and suggestion, I'll try to leave the release notes concise as possible! I've committed the changes right here: 28aafbb412f4fd5e465bb7d3328f7d10420014f1

2020-07-01 23:35 UTC, ThomazFB commented
Hey @AmandaRiu, thank you so much for your review, I've just pushed the changes around those two bugs you reported in these two commits:

Multiple tabs bug: 28aafbb412f4fd5e465bb7d3328f7d10420014f1
Tab not removed bug: a7e940d063257b060755bda3b51674fd27c5560d

Let me know what you think!

2020-07-02 20:37 UTC, AmandaRiu commented on WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/SequenceExt.kt
> +        .isNotEmpty()
This is really slick 👍

2020-07-02 20:39 UTC, AmandaRiu requested changes
@ThomazFB Nice work 👍 both bugs are fixed, but now I have a new bug. The "Upgrade" card isn't getting displayed on first login with a store running less than 4.0:

1. Uninstall app and reinstall
2. Login with a store running 3.9.x
3. Note the My Store tab does not display the "Upgrade to keep seeing your stats" card. 

<img src="https://user-images.githubusercontent.com/5810477/86407204-ca533b00-bc71-11ea-8117-4246b81c93f7.png" width="330"/>

2020-07-03 16:23 UTC, ThomazFB commented
Hey @AmandaRiu, thanks for catching this issue! Here's what I decided to solve this.

Since we discussed on slack that the `MyStoreStatsRevertedNoticeCard` should now be displayed every time the Stats V3 is visible, at first I decided to remove everything around the `shouldDisplayV4StatsRevertedBanner` and let the banner always there, but later I started to notice that won't be a good idea because it would remove from the user the `dismiss` option to not see this banner anymore.

With that said, I decided to only change the default value of `shouldDisplayV4StatsRevertedBanner` to `true`, so we will always present the banner and dismiss it only after the user hits the `dismiss` button and never see it again.

Here's the commit: 4fc7992e5ebddd0f91fe6b42190bd461197e5d2b

Let me know what you think.

2020-07-03 16:54 UTC, AmandaRiu approved these changes
@ThomazFB Looks good! Nice work :) :shipit:

2020-07-03 16:54 UTC, merged