Integrate with the Stats V4 Top Performers API
woocommerce/woocommerce-android pull request #2676
Opened 2020-08-05 10:42 UTC by ThomazFB

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-08-10 10:23 UTC, loremattei commented
Hey! I'm moving this to 4.9 since 4.8 has been cut. Since it's still a draft, I think it's fine. Otherwise, feel free to ping me to get this included in 4.8.

2020-08-18 23:21 UTC, AmandaRiu requested changes
@ThomazFB Nice work on this! Tested and results match my store dashboard 👍 Also tested offline mode and that works fine. Even though it is all working I did find a couple things for your review:

The app doesn’t match the web as far as prioritization. Is this something that can be fixed?

![Screen Shot 2020-08-17 at 6 26 03 PM](https://user-images.githubusercontent.com/5810477/90574864-01c96880-e188-11ea-886b-8637acd17421.png)



There is an `IllegalArgumentException` being thrown in logical when I try to fetch the data to populate the Top Performers view. It doesn’t appear to prevent it from populating, but it’s definitely a new error (I checked out `develop` and that error is not thrown). Here is the stack trace:

```
2020-08-17 18:23:27.561 21610-21610/com.woocommerce.android.dev E/WordPress-UTILS: Error finding valid currency symbol for currency code [$] in locale [en_US]
    java.lang.IllegalArgumentException: The input currency code is not 3-letter alphabetic code.
        at android.icu.util.Currency.getInstance(Currency.java:291)
        at java.util.Currency.getInstance(Currency.java:289)
        at org.wordpress.android.fluxc.utils.WCCurrencyUtils.getLocalizedCurrencySymbolForCode(WCCurrencyUtils.kt:45)
        at org.wordpress.android.fluxc.store.WooCommerceStore.formatCurrencyForDisplay(WooCommerceStore.kt:170)
        at com.woocommerce.android.util.CurrencyFormatter.formatCurrencyRounded(CurrencyFormatter.kt:74)
        at com.woocommerce.android.ui.mystore.MyStoreFragment$onActivityCreated$4.invoke(MyStoreFragment.kt:148)
        at com.woocommerce.android.ui.mystore.MyStoreFragment$onActivityCreated$4.invoke(MyStoreFragment.kt:37)
        at com.woocommerce.android.ui.mystore.MyStoreTopPerformersView$TopEarnersAdapter.onBindViewHolder(MyStoreTopPerformersView.kt:150)
        at com.woocommerce.android.ui.mystore.MyStoreTopPerformersView$TopEarnersAdapter.onBindViewHolder(MyStoreTopPerformersView.kt:114)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
        at android.view.View.measure(View.java:24530)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.cardview.widget.CardView.onMeasure(CardView.java:260)
        at com.google.android.material.card.MaterialCardView.onMeasure(MaterialCardView.java:159)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24530)
        at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1599)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:585)
        at android.view.View.measure(View.java:24530)
        at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:641)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
2020-08-17 18:23:27.561 21610-21610/com.woocommerce.android.dev E/WordPress-UTILS:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
        at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:99)
        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1892)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:831)
        at android.view.View.measure(View.java:24530)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1676)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widg [...]

2020-08-18 23:21 UTC, AmandaRiu commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStorePresenter.kt
> +                topPerformersForceRefresh[i] = true
NP: lint warning - statement can be changed to:
```
for (i in topPerformersForceRefresh.indices) {
    topPerformersForceRefresh[i] = true
}
```

2020-08-20 15:27 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStorePresenter.kt
> +                topPerformersForceRefresh[i] = true
Hey Amanda, thanks for warning about that, I've fixed the lint warnings for this and for another additional point of the code right here: https://github.com/woocommerce/woocommerce-android/pull/2676/commits/2799e905750c44cbfabb9b0862ad3e5acd0cb3c6

2020-08-20 15:38 UTC, ThomazFB commented
Hey @AmandaRiu, thanks for the review! I've added some changes and I think the code is ready for a second round 👍 

>The app doesn’t match the web as far as prioritization. Is this something that can be fixed?

Sure! I've added a presentation sorting rule right here: https://github.com/woocommerce/woocommerce-android/pull/2676/commits/2b257803728a2318ea47963706be3ef2506e2b79. The sorting rule I've added is inspired by the Woo site Leaderboards view, as shown below:

<img width="1728" alt="Screen Shot 2020-08-20 at 10 38 50 AM" src="https://user-images.githubusercontent.com/5920403/90792519-ef167700-e2e0-11ea-9ae9-6bcedf577282.png">

So, the main sorting considers as the sorting value the `total orders / items sold` and as a second sorting value the `total spend / net sales` as a diff rule for the first sort value. Here's the output on the app:

<img width="455" alt="Screen Shot 2020-08-20 at 12 35 03 PM" src="https://user-images.githubusercontent.com/5920403/90793042-9dbab780-e2e1-11ea-9bd4-0053a5042b8d.png">

>There is an IllegalArgumentException being thrown in logical when I try to fetch the data to populate the Top Performers view. It doesn’t appear to prevent it from populating, but it’s definitely a new error (I checked out develop and that error is not thrown). Here is the stack trace:

Thanks for detecting this one! As we talked on Slack, after a further investigation about this exception, I've found that the Stats V4 API doesn't return the currency code anymore but only the already formatted symbol in its place. At first, I thought this wasn't an issue since I saw the Woo app converting everything just fine, but after investigating this exception you pointed out, it looks like we can only know for sure that we can display the region currency format if we have the ISO code, I think the API didn't put that in consideration (especially considering that the currency and price are getting return as an HTML, which would already do the formatting job on a Woo site, but not on the app). 

For now, I'm patching this using the currency code provided by the site settings, it should be safe, but isn't totally synced with the Top Performers data. Here's the change: https://github.com/woocommerce/woocommerce-android/pull/2676/commits/8ff6f198c57cdb28d902513b0a235a26f50d1260

It should solve the problem in a reliable way.

2020-08-21 01:52 UTC, AmandaRiu approved these changes
@ThomazFB The sorting is still off (see screenshot below), but that's really low priority so I'm not going to hold up this PR over it. Everything else is working great! :shipit: 

<img width="1097" alt="Screen Shot 2020-08-20 at 9 50 39 PM" src="https://user-images.githubusercontent.com/5810477/90843369-7559aa00-e32f-11ea-94d4-168c746f2169.png">

2020-08-21 01:52 UTC, merged