Issue/2644 add crowdsignal survey
woocommerce/woocommerce-android pull request #2723
Opened 2020-08-13 10:27 UTC by ThomazFB

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-08-19 07:30 UTC, Garance91540 requested changes
Hi Thomaz, looking good! 

I have a few comments/questions:
- Can you please share with me dark mode screenshots and one iPad screenshot too?
- Which survey are you using exactly? I think we should use the same on Android and iOS so we only have on place to go to see all the data. Here's the Crowdsignal survey @shiki worked on https://automattic.survey.fm/woo-app-general-feedback-test-survey, can we use it for Android too?

2020-08-20 03:03 UTC, ThomazFB commented
Hey @Garance91540! Thanks for your outputs!
>Can you please share with me dark mode screenshots and one iPad screenshot too?
Sure! I've added into the PR description the navigation sequence running in Dark Mode and on an Android Tablet 😄 

>Which survey are you using exactly? I think we should use the same on Android and iOS so we only have on place to go to see all the data. Here's the Crowdsignal survey @shiki worked on https://automattic.survey.fm/woo-app-general-feedback-test-survey, can we use it for Android too?

I've intentionally left the PR with the test survey URL just for review purposes, but to make easier the design review I've just added the production URL with the CSS changes made by @shiki. Thanks for pointing that out!

2020-08-20 07:55 UTC, Garance91540 approved these changes, later dismissed
Looking awesome, thank you @ThomazFB !

2020-08-20 12:44 UTC, shiki commented
Regarding the style, looks like the radio buttons are squares instead of circles. 😄 I'll fix those next sprint. (https://github.com/woocommerce/woocommerce-ios/issues/2546)

2020-08-20 14:38 UTC, AmandaRiu requested changes
@ThomazFB Nice work on this 🥳 Here's some feedback from what I found during testing:

- I noticed that if the device is rotated the survey loses it's values. Is there a way we can prevent that from happening?
- The "Feedback sent" screen does not scroll so you can't see the rest of the view in landscape mode or click the "Back to Store" button:

<img src="https://user-images.githubusercontent.com/5810477/90783352-f4b69180-e2cd-11ea-91ef-e456c81cf537.png" width="600"/>

@shiki I noticed the survey errors look like this on Android, is this expected?

<img src="https://user-images.githubusercontent.com/5810477/90786104-2da43580-e2d1-11ea-8664-78ea1a18f642.png" width="330"/>

2020-08-20 14:53 UTC, shiki commented
@AmandaRiu Yes, it's a problem in Crowdsignal's CSS editor. I reported it to them (p91TBi-2RL-p2#comment-1530). Thank you for confirming. 🙂

2020-08-20 21:08 UTC, ThomazFB commented
Hey @AmandaRiu! Thank you so much for your review, I've submitted some change and I think the code is ready for a second round!

>I noticed that if the device is rotated the survey loses it's values. Is there a way we can prevent that from happening?

Thank you for pointing that out! I did some investigations regarding WebView state management and it doesn't look very reliable, nevertheless, I did some additional changes and restored my previous attempts to restore the WebView previous state and it looks to be working now. Let me know how that goes for you. Here's the changes: https://github.com/woocommerce/woocommerce-android/pull/2723/commits/1034133023f225423111c47cd92ea72f01c965a0

>The "Feedback sent" screen does not scroll so you can't see the rest of the view in landscape mode or click the "Back to Store" button

Sorry about that! Here's the change allowing scrolls on the UI: https://github.com/woocommerce/woocommerce-android/pull/2723/commits/7803c858618345e84f8adc5d2276f7189875fcc9

2020-08-21 02:09 UTC, AmandaRiu requested changes
@ThomazFB The scrolling thing is fixed 👍 thanks for taking care of that. I'm still seeing some issues when rotating the survey. The email disappears:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5810477/90844378-c10d5300-e331-11ea-83f5-a80c86d2dc72.gif)

Other than that I left a couple smaller comments in code. It's really close to merging! 👍

2020-08-21 02:09 UTC, AmandaRiu commented on WooCommerce/src/main/res/layout/fragment_feedback_completed.xml
> +        android:padding="32dp">
np: hard code values. Should use one of our established values in `dimens.xml` - same for the rest of this file.

2020-08-21 02:09 UTC, AmandaRiu commented on WooCommerce/src/main/res/layout/fragment_feedback_completed.xml
> +        <TextView
should use a `MaterialTextView`

2020-08-21 02:09 UTC, AmandaRiu commented on WooCommerce/src/main/res/layout/fragment_feedback_completed.xml
> +            android:layout_height="48dp"
Why hard-coded widths and heights?

2020-08-21 14:48 UTC, ThomazFB commented on WooCommerce/src/main/res/layout/fragment_feedback_completed.xml
> +            android:layout_height="48dp"
My mistake here, sorry about that, I've fixed this for all the missing extraction dimensions right here: https://github.com/woocommerce/woocommerce-android/pull/2723/commits/c1ad309bd828fa668d181fb13f41ce708841a6b1

2020-08-21 14:48 UTC, ThomazFB commented on WooCommerce/src/main/res/layout/fragment_feedback_completed.xml
> +        <TextView
Oops, forgot to adjust that one, it's fixed right here: https://github.com/woocommerce/woocommerce-android/pull/2723/commits/c1ad309bd828fa668d181fb13f41ce708841a6b1

2020-08-21 14:48 UTC, ThomazFB commented on WooCommerce/src/main/res/layout/fragment_feedback_completed.xml
> +        android:padding="32dp">
Sure! Thanks for that! It's done right here: https://github.com/woocommerce/woocommerce-android/pull/2723/commits/c1ad309bd828fa668d181fb13f41ce708841a6b1

2020-08-21 14:48 UTC, ThomazFB commented
Hey @AmandaRiu, thank you again for your review. I've pushed all the missing dimension extractions on the `xml` files. But there's one thing I'm worried about the `WebView` state handling. I did a lot of attempts trying to find a reliable way to restore the state on the `email` field, but it looks like this field uses JS to control their state because of pattern matching to verify if it's a valid e-mail address, and since the Android WebView instance state storing bundle doesn't cover JS variable states and logic control, we see this kind of behavior happening.

Because of that same characteristic of the survey webpage, if we access the [Survey link](https://automattic.survey.fm/woo-app-general-feedback-test-survey) from a desktop browser like Chrome, we can see that even in that case the browser has a hard time to keep the email state in scenarios like pressing back and forward buttons on the browser tab.

I think we'll need to assume some unwanted compromises in order to achieve a good state handling, like blocking the Activity from recreating itself when we do a configuration change like rotation, but I think that's a way too harsh measure since it will affect a lot of other Fragments and Views, and overall it's a not good practice to be adopted. Not sure if we have many options to solve this problem. WDYT?

I'm curious if the iOS part managed to solve this problem in some way. CC: @shiki @Ecarrion

2020-08-21 15:03 UTC, Ecarrion commented
@ThomazFB 
> I'm curious if the iOS part managed to solve this problem in some way.

I just tested it and it doesn't seem to be a problem iOS side, I assume it's because iOS doesn't recreate view upon rotation, just re-layout them.

2020-08-21 19:47 UTC, AmandaRiu commented
> I think we'll need to assume some unwanted compromises in order to achieve a good state handling, like blocking the Activity from recreating itself when we do a configuration change like rotation, but I think that's a way too harsh measure since it will affect a lot of other Fragments and Views, and overall it's a not good practice to be adopted. Not sure if we have many options to solve this problem. WDYT?

I agree that preventing a configuration change on rotation would be too harsh for something like this. I think we should leave it for now. The good news is that the survey will not be submitted without the email form filled so the user will be asked to re-enter it if a configuration change happens. And at least the rest of the survey is 👍

2020-08-21 20:36 UTC, AmandaRiu approved these changes
LGTM! :shipit:

2020-08-21 20:45 UTC, merged