Issue/2630 search grouped products
woocommerce/woocommerce-android pull request #2775
Opened 2020-08-25 06:54 UTC by anitaa1990

Fixes part 2/2 of #2630 by adding the search functionality in this PR when adding a grouped product.

#### Changes
- Fixed a bug as mentioned in #2774 by ensuring that an already added product is not added again.
- Added search functionality to the `ProductSelectionListViewModel`.
- Added missing analytic events: `GROUPED_PRODUCT_LINKED_PRODUCTS_ADD_TAPPED` (when the "Add product" button is clicked)  and `GROUPED_PRODUCT_LINKED_PRODUCTS_ADDED ` (when a product is selected from the list).

#### Screenshots
<img src="https://user-images.githubusercontent.com/22608780/91140526-4a73ab00-e6cd-11ea-89f7-2d56159520b8.gif" width="300"/>. <img src="https://user-images.githubusercontent.com/22608780/91140551-4c3d6e80-e6cd-11ea-8315-084e047df5c4.gif" width="300"/>

#### Testing
- Click on a grouped product -> `Grouped products` section -> `Add product`.
  - Click on the search icon and enter a valid product.
    - Verify that the product is displayed. 
    - Click on the product and click on the `Done` menu button and verify the product is added successfully.
  - Click on the search icon and enter an invalid product.
    - Verify that the empty view is displayed correctly.
- Click on a grouped product -> `Grouped products` section -> `Add product`.
  - Click on an already selected product and click on the "Done" menu button.
  - Verify that the already added product is not displayed in the grouped product list and that the "Done" menu button is NOT displayed.
  
**This PR is in draft till this [FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1675) and this [Woo PR](https://github.com/woocommerce/woocommerce-android/pull/2774) can be reviewed and merged.**

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-09-02 20:01 UTC, AmandaRiu requested changes
@anitaa1990 tested through steps but something appears to be wrong. I can't add products to the group. I've enabled product editing so I'm able to get into a grouped product, click "add product", but when I click on a product nothing happens. It doesn't get selected. This happens when clicking on products in the initial list, as well as clicking products in the search results. See gifs below. 

### Click to add a product

![add-product](https://user-images.githubusercontent.com/5810477/92030714-71695700-ed35-11ea-8b59-e159912e8f39.gif)

### Click to add product from search results

![search-add-product](https://user-images.githubusercontent.com/5810477/92030738-79c19200-ed35-11ea-8715-eb4262f761d7.gif)

2020-09-03 11:51 UTC, anitaa1990 commented
>  I can't add products to the group. I've enabled product editing so I'm able to get into a grouped product, click "add product", but when I click on a product nothing happens. It doesn't get selected. 

Hey @AmandaRiu! The products are selected only when long pressed! Sorry for not being clear in this PR. It's actually mentioned in the previous [PR](https://github.com/woocommerce/woocommerce-android/pull/2774) that I had added the `recyclerview-selection` library to handle long press and multi selection to the recyclerview.

2020-09-03 20:15 UTC, AmandaRiu commented
> > I can't add products to the group. I've enabled product editing so I'm able to get into a grouped product, click "add product", but when I click on a product nothing happens. It doesn't get selected.
> 
> Hey @AmandaRiu! The products are selected only when long pressed! Sorry for not being clear in this PR. It's actually mentioned in the previous [PR](https://github.com/woocommerce/woocommerce-android/pull/2774) that I had added the `recyclerview-selection` library to handle long press and multi selection to the recyclerview. I had forgotten to updatee this PR though.

@anitaa1990 Ah ok, long-clicking works, but I don't think we should use a long-click if single-click doesn't do anything. It seems to me that if we're using long-click to turn on multi-select, then a regular click should just add that one product immediately (ie - close the list of products screen). If multi-select is the only option, then we shouldn't use long-click at all - just let the user click to select multiple products. This is how I would expect it to work and I'd hate for users coming away thinking this feature is broken like I did. WDYT?

2020-09-04 06:56 UTC, anitaa1990 commented
> Ah ok, long-clicking works, but I don't think we should use a long-click if single-click doesn't do anything. It seems to me that if we're using long-click to turn on multi-select, then a regular click should just add that one product immediately (ie - close the list of products screen). If multi-select is the only option, then we shouldn't use long-click at all - just let the user click to select multiple products. This is how I would expect it to work and I'd hate for users coming away thinking this feature is broken like I did. WDYT?

You raise a good point that it's not really easy to understand that we need to long press on the product to enable selection, especially since this is the first time we are introducing long press, multi selection in the Woo app.  

> If multi-select is the only option, then we shouldn't use long-click at all - just let the user click to select multiple products. 

I have only ever seen multi select enabled in applications when long pressing on the list (but most of those applications have a single click option that opens a detail screen for the list item. The Gmail app, for instance). Also, we are using the Android's [recyclerview-selection](https://developer.android.com/reference/kotlin/androidx/recyclerview/selection/package-summary) library that is used only for multi selection and is only enabled when long pressing on a list item. There is a not-so-straightforward option mentioned in [this post](https://proandroiddev.com/a-guide-to-recyclerview-selection-3ed9f2381504), to enable single select using the library but it's not really the standard practice when using his library. Do you think it makes sense to include an info of some kind to ensure that users know they can long press to select multiple items? I'm happy to start a discussion on which solution makes more sense and I'll ping @Garance91540 here for her thoughts as well. 

Having said that, since this selection is already reviewed and merge in [another PR](https://github.com/woocommerce/woocommerce-android/pull/2774) and this PR just adds the search functionality to the feature, I can we can merge this PR as is and start any new solutions in another PR. WDYT?

2020-09-04 14:03 UTC, Garance91540 commented
If it's possible to select multiple files on single tap (no long press needed), I think that's the most intuitive and easy (similarly to how iOS implemented it: https://d.pr/v/opgve2 )

2020-09-04 14:04 UTC, AmandaRiu commented
@anitaa1990 @Garance91540 

> Also, we are using the Android's recyclerview-selection library that is used only for multi selection and is only enabled when long pressing on a list item.

That makes sense. We could leave the long-press and just use a single tap to instantly select an item and return to the previous screen. This is typical behavior. If I click "Add product" and tap "Beanie" then it should instantly be added and I get returned to the previous screen. 

>  Do you think it makes sense to include an info of some kind to ensure that users know they can long press to select multiple items? 

Yes, it would be a good idea to have this even if we have a regular click incorporated. 

> Having said that, since this selection is already reviewed and merge in another PR and this PR just adds the search functionality to the feature, I think we can merge this PR as is and start any new solutions in another PR. WDYT?

Sounds good to me. I'll merge this one.

2020-09-04 14:05 UTC, AmandaRiu approved these changes
The long-press discussion will be moved outside this PR since this functionality was added in a previous PR. Everything else looks good 👍  🚢

2020-09-04 14:05 UTC, merged