Issue/2792 virtual flag fix
woocommerce/woocommerce-android pull request #2806
Opened 2020-08-31 07:05 UTC by anitaa1990

This PR fixes #2792, #2785, #2609 and #2608. 

#### Issue 2972:
I see the `Virtual product` setting in the Product settings for any product type in the app. I can toggle that setting for any product, but it doesn't do anything unless I'm editing a simple product.

Fixed in 9385ae4

##### To test
- Go to Settings > Beta features and enable Product Editing.
- Go to the Products tab.
- Select a simple product from the product list.
- Open the product settings and toggle the Virtual Product setting. Notice that in the product details, this changes the product type between Physical and Virtual.
- Go back to the product list and select a variable product.
- Open the product settings and verify that the Virtual setting is no longer visible.

#### Issue 2785:
When I first open the product details for a product, if that product is visible on my store I'll see a "View Product in Store" link in the ellipsis menu.

Fixed in f8f3868

##### To test
- Open the Products tab.
- Select a product.
- Tap the ellipsis menu and confirm you see a "View Product in Store" link.
- Select "Product Settings."
- Tap the X button to close the product settings screen without making any changes.
- Tap the ellipsis menu again and notice you the "View Product in Store" is still visible.

#### Issue 2609:
When I select the password-protected option, edit the field and dismiss my changes, I keep seeing the keyboard overlapping the Settings screen.

Fixed in 9ac2f6e

##### To test
- Select a product
- Open Product Settings
- Select "Visibility"
- Select "Password Protected"
- Edit Password
- Select back button
- Select dismiss changes
- Notice the keyboard is no longer displayed.

#### Issue 2608:
Currently, when selecting "Password-protected", there's a blank text input field. Can we add a text label placeholder to guide users more about what they should be doing?

Fixed in 7e51717

##### To test
- Select a product
- Open product Settings
- Select "Visibility"
- Select "Password protected"
- Notice the hint in the "Password protected" EditText.

cc @Garance91540 and @rachelmcr I have added you as reviewers since you both caught the initial bug. Thanks 🙏 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-09-01 19:52 UTC, AmandaRiu approved these changes
Ran through all of the testing scenarios and reviewed the code. All looks good 👍 I'll wait till @Garance91540  and @rachelmcr get a chance to look this over before I merge it.

2020-09-02 08:06 UTC, Garance91540 requested changes
Hi @anitaa1990, thank you for working on this!

All changes look good except that when selecting "Password-protected", I'm still seeing a blank text input field.

https://d.pr/i/dKmLOM

Another note that I wanted to make that can totally be addressed in a separate PR: The product type row should always be last in the Product Details page. Can we update this? https://d.pr/i/9Y4P8I

Thank you!

2020-09-02 09:18 UTC, anitaa1990 commented
Thanks for the review @Garance91540 🙇‍♀️ 

> All changes look good except that when selecting "Password-protected", I'm still seeing a blank text input field.

I'm not able to reproduce this issue. I still see the hint when selecting "Password-protected", in both dark and light mode. Is there a specific set of steps to reproduce this scenario? Looking at the code, we don't really update the hint for the "Password protected"  text box anywhere so not really sure in which scenario this is happening?

<img src="https://user-images.githubusercontent.com/22608780/91963278-47ab3280-ed2b-11ea-9b39-8b705f0e0fe0.png" width="300"/>. <img src="https://user-images.githubusercontent.com/22608780/91963284-4a0d8c80-ed2b-11ea-8282-767ea4c06e96.png" width="300"/>

> Another note that I wanted to make that can totally be addressed in a separate PR: The product type row should always be last in the Product Details page. Can we update this? https://d.pr/i/9Y4P8I

Ohh, sure! I'll add a separate issue for that and open it in another PR 👍

2020-09-03 13:04 UTC, Garance91540 approved these changes
Everything fixed on my end, thank you @anitaa1990 !!

2020-09-03 15:02 UTC, rachelmcr approved these changes
These changes look good in my testing, too. Thanks for the fixes!

2020-09-03 20:05 UTC, AmandaRiu commented
Rachel and Garance have both tested and approved. Merging 👍  :shipit:

2020-09-03 20:05 UTC, merged