issue/2659 track shipments
woocommerce/woocommerce-android pull request #2808
Opened 2020-08-31 10:40 UTC by anitaa1990

Fixes #2654 and part 1/2 of #2659 by providing the option to track shipments when the Shipment Tracking plugin is not available.

#### Issue #2654 
We need to display the header for products not associated with any shipping labels as "Remaining Products" since it can include both virtual and physical products. Fixed in 69a144f.

##### Testing
- Create an order from your test site with atleast 2 products.
- Follow the instructions provided in the Shipping Labels Master Thread - `p91TBi-2om` to create a shipping label for the order, with only 1 product.
- Open the app and click on the order.
- Notice that product header for the shipping label is displayed as `Package 1` and the second product heading is displayed as `Remaining items`.

#### Issue 2659
**Tracking shipment**
- With the Shipment Tracking plugin available: Calling the GET shipment tracking list API endpoint will provide the list of shipment trackings for the order. We can then match the shipping label tracking number with the shipment tracking number to display the corresponding tracking link.
- Without the Shipment Tracking plugin: If the shipment tracking plugin is not available, we won't be able to use the GET shipmen tracking API endpoint. But WCS still displays the tracking link in wp-admin. We need to [store the tracking link for each carrier in the app and we just need append the tracking Id for that shipping label to that link](https://github.com/Automattic/woocommerce-services/blob/develop/client/extensions/woocommerce/woocommerce-services/views/shipping-label/tracking-link.js), if the tracking link icon is clicked from the app.

Fixed in 1bd2f93

##### Testing
- Enable the Shipment Tracking plugin and WooCommerce Services plugin on your test site.
- Create an order from your test site with atleast 2 products.
- Follow the instructions provided in the Shipping Labels Master Thread - `p91TBi-2om` to create a shipping label for the order, with only 1 product.
- Click on the order from the app that has the shipping label.
- Notice the tracking number displayed for the shipping label and the tracking icon displayed. Clicking on the tracking link should open the tracking link for the carrier.
- Disable the Shipment Tracking plugin for the test site.
- Open the same order from the app.
- Notice the tracking number displayed for the shipping label and the tracking icon is also displayed. Clicking on the tracking link should open the tracking link for the carrier.

<img src="https://user-images.githubusercontent.com/22608780/91711901-5ca98980-eba4-11ea-9aac-2a68e5e3c2a2.png" width="300"/>. <img src="https://user-images.githubusercontent.com/22608780/91711904-5e734d00-eba4-11ea-9497-5f0ff89f5069.png" width="300"/

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-09-01 20:12 UTC, AmandaRiu requested changes
@anitaa1990 I tested through the scenarios and reviewed the code. The first scenario worked like a charm, but I ran into issues with the second scenario. When I have the Shipment Trackings plugin enabled, there is no link button available for me to click (also note that even though both packages were created under the same shipping label session, only 1 of the packages has a tracking number):

<img src="https://user-images.githubusercontent.com/5810477/91901129-c8a3f480-ec6d-11ea-9cb6-8f9e2fdb3db1.png" width="300"/>


If I deactivate the Shipment Tracking plugin, then suddenly the link buttons appear to view the tracking information on the web:

<img src="https://user-images.githubusercontent.com/5810477/91901113-bfb32300-ec6d-11ea-8919-cc95f4d93425.png" width="300"/>

2020-09-02 10:58 UTC, anitaa1990 commented
Thanks for the review @AmandaRiu!!

>  I ran into issues with the second scenario. When I have the Shipment Trackings plugin enabled, there is no link button available for me to click (also note that even though both packages were created under the same shipping label session, only 1 of the packages has a tracking number).
If I deactivate the Shipment Tracking plugin, then suddenly the link buttons appear to view the tracking information on the web:

It looks like the shipping labels API returns a different tracking number and the shipment tracking API returns a different tracking number, which was why the link did not appear in the app. I took at look at how Core was handling it and it looks like the tracking number from the Shipment Tracking API is used (if it's available) so I updated the logic in the app to follow a similar approach in 4cf1761. 

Ready for another round 👍

2020-09-03 11:53 UTC, anitaa1990 commented
Hey @AmandaRiu, this one is ready for another round of review 👍

2020-09-03 20:03 UTC, AmandaRiu approved these changes
@anitaa1990 That fix worked! Really nice job on this! :shipit:

2020-09-03 20:03 UTC, merged