Add WireMock network mocking for screenshot test
woocommerce/woocommerce-android pull request #2933
Opened 2020-09-29 11:42 UTC by rachelmcr

Adds infrastructure for network mocking in connected tests with WireMock.
Also adds an initial set of mocks for the screenshot test.

### Changes

* This uses [WireMock](http://wiremock.org/) to power mocking the network requests.
* WireMock runs a small HTTP server on `localhost:8080` which mimics the WordPress.com API. Request/response configuration is done with the JSON files (loaded as assets).
* The implementation is based on the WordPress Android network mocking setup. (In future we may want to share this implementation more directly.)

### Pending issues

* To support WireMock running on an HTTP server I had to change the network security config, to allow cleartext traffic for `localhost`. However, this change results in `SSLHandshakeException` errors when running the app normally (not running tests) and I can't work out why that's happening or what the best solution is.
* The mocks asset loading is written in Java (in `AssetFileSource.java`). I tried converting this to Kotlin but couldn't get it to successfully load the assets and didn't want to spend too much time on that piece since the Java implementation is working.

### To test

1. Ensure your `gradle.properties` includes `wc.screenshots.url`, `wc.screenshots.username`, and `wc.screenshots.password`. (These can be set to the same example values as in `gradle-properties.example`.)
2. Run the connected test in `ScreenshotTest`.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-09-29 20:55 UTC, AmandaRiu commented
@rachelmcr 

> To support WireMock running on an HTTP server I had to change the network security config, to allow cleartext traffic for localhost. However, this change results in CertificateException and SSLHandshakeException errors when running the app normally (not running tests), specifically when the app makes requests for media files.

I've been debugging this and it looks to be due to this specific part of an error I'm seeing:

```
SSLHandshakeException: Domain specific configurations require that hostname aware checkServerTrusted(X509Certificate[], String, String) is used
```

All the networking for the WCAndroid app is written in FluxC which is shared between WPAndroid and WCAndroid. Since the original network config didn't specify any domain-specific handling that code is using the default `TrustManager` when working with SSL communication. When an exception is added that means a different method needs to be worked in to ensure a different `TrustManager` is issued when talking to a specific domain. Since your new code adds a domain-specific exception the FluxC networking code will need to be modified to include this domain when checking if a server is trusted so the appropriate `TrustManager` is issued and used for checking if a server is trusted during communication. This is at least my understanding after digging through the FluxC code. I'm not sure how much rework this will require to get it working or even if I'm 100% correct on any of this. It looks like @planarvoid  and @maxme both worked in a lot of the FluxC networking code - so pinging them to see if they have any recommendations or know more.

2020-09-29 20:57 UTC, AmandaRiu commented
Also, I noticed that WPAndroid is using this in their config which is less secure but would get around this whole domain-specific thing:

```
<base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system"/>
        </trust-anchors>
    </base-config>
```

2020-10-01 07:39 UTC, planarvoid commented
hey 👋 

> ... 100% correct on any of this. It looks like @planarvoid and @maxme both worked in a lot of the FluxC networking code - so pinging them to see if they have any recommendations or know more.

I've only done some small changes to the code. I don't really know how this all is set up. 

> Add WireMock network mocking for screenshot test

I was wondering if it might be cleaner, faster, and less flakey to do screenshot tests by mocking the `ViewModels` instead. What I mean is that we could have a mock implementation of a view model for the test which would give us the state of the screen we need. Woo would be a great place to use this approach since it's all Kotlin & ViewModels. What do you think @AmandaRiu ? I think it would require only small change (either having the view model behind an interface or figure out mocking the models).This approach gives you total control of the data you're showing for the screenshot.

2020-10-01 13:59 UTC, maxme commented
> All the networking for the WCAndroid app is written in FluxC which is shared between WPAndroid and WCAndroid. Since the original network config didn't specify any domain-specific handling that code is using the default TrustManager when working with SSL communication. When an exception is added that means a different method needs to be worked in to ensure a different TrustManager is issued when talking to a specific domain. Since your new code adds a domain-specific exception the FluxC networking code will need to be modified to include this domain when checking if a server is trusted so the appropriate TrustManager is issued and used for checking if a server is trusted during communication. This is at least my understanding after digging through the FluxC code.

This is correct, the `MemorizingTrustManager` implemented in FluxC allows us to add exceptions for SSL certificates (at the device level). I think the only solution here is to inject a TrustManager that accepts all certificates (trusted or not).

2020-11-11 14:57 UTC, rachelmcr commented
Thanks everyone for your help with the network security config. I haven't had the bandwidth to figure out the changes needed for a new TrustManager, so for now I went with [this suggestion](https://github.com/woocommerce/woocommerce-android/pull/2933#issuecomment-700982222) to allow clear text traffic — if we're ok with it being less secure, it'll let us move forward with these mocked tests for now and we can always revisit that if needed.

The plan for now is to stick with WireMock for a consistent testing infrastructure across apps. Once it's in place we'll start writing more tests to cover broader user journeys (like login), in addition to the screenshot test.

2020-11-17 18:06 UTC, AliSoftware approved these changes
Aside from the main issue of the use of `{{now}}` instead of `{{fnow}}` (*), the rest looks good to me at first glance to the code and when tested in Android Studio 👍 

 * I mainly looked at some JSON mocks (not all in details, but glanced at the most important ones) and at if the test code made sense
 * I'm no Android expert tho, so would easily fail to see if anything is amiss in the implementation or dependencies. It would be nice to have and Android Wrangler double-checking those
 * I ran the `ScreenshotTest` on a Pixel 2 API 30 emulator and it passed 🎉 

---

_(*) see internal post I linked in the review; but wondering: did you pick that usage of `{{now}}` from WireMock's documentation, or from seeing that in WordPress-Android's own JSON mocks?_

_If the latter, that means that `{{now}}` might have been reintroduced even after the fix I did during my trial for screenshots with arabic locale… and we might need to consider adding a linter rule to prevent people to reintroduce `{{now}}` in WordPress-Android (and Woo)?_

2020-11-17 18:06 UTC, AliSoftware commented on WooCommerce/src/androidTest/assets/mocks/mappings/devices/devices_new_post.json
> +}
super nit: add a newline at end of file (POSIX standard; prevents some old UNIX tools from getting confused)

2020-11-17 18:06 UTC, AliSoftware commented on WooCommerce/src/androidTest/assets/mocks/mappings/me/rest_v11_me_sites.json
> +        "urlPattern": "/rest/v1.1/me/sites(\\?|/|$).*",
Is this valid in regex to have `$` (aka "this is anchored at the end of the string we match") but followed by something (in that case `.*`), which seems conflicting to me?

Wondering if something like `"/rest/v1.1/me/sites(\\?.*|/.*|$)"` wouldn't be more accurate? Tho if we go there, maybe `"/rest/v1.1/me/sites.*"` is good enough 🤔

2020-11-17 18:06 UTC, AliSoftware commented on WooCommerce/src/androidTest/assets/mocks/mappings/stats/stats_orders-day.json
> +                ["{{now format='yyyy-MM-dd'}}", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "USD", 710, 0, 0, 0]
⚠️ You might want to use `{{fnow …}}` instead of `{{now …}}` in all your mocks, because unfortunately Wiremock's `{{now …}}` implementation uses the current user's locale to do the formatting, while for an API response we should not depend on the user's locale and use ISO / POSIX generic locale instead.

See this internal post for more details: pbMoDN-13F-p2 (you'll need to copy/duplicate the implementation of the `fnow` tag I did from WPAndroid in Woo for your mocks to be able to use that locale-agnostic tag)

2020-11-17 18:06 UTC, AliSoftware commented on WooCommerce/src/androidTest/assets/mocks/mappings/stats/stats_orders-week.json
> +            "date": "{{now format='yyyy-MM-dd'}}",
ditto. I'll let you do a search & replace `now` -> `fnow` on all `json` files 😉

2020-11-17 18:06 UTC, AliSoftware commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/helpers/MockingInterceptor.kt
> +        }
Should we also intercept API requests that are to domains other than the ones from public-api we mock, and catch/throw them, just to be sure that our tests don't depend on other servers and we don't accidentally send a real request to the real world to a third party every time we run the tests (and that our tests would end up failing if said 3rd party goes down at the moment we run the tests, making us depend on them for continuous testing)? 🤔 

Or is that fallback of "any request that isn't mocked will log/warn/fail during test to ensure we don't forget any mock" handled somewhere else (by WireMock itself as a high level failsafe config option, or from a second `Interceptor` I missed?)

2020-11-17 18:08 UTC, AliSoftware requested changes
Woops I submitted as "Approve" but just realised I should have submitted as "Request changes" instead, until the `{{now}}` issue is fixed 😅

2020-11-25 16:48 UTC, rachelmcr commented on WooCommerce/src/androidTest/assets/mocks/mappings/me/rest_v11_me_sites.json
> +        "urlPattern": "/rest/v1.1/me/sites(\\?|/|$).*",
Ah, I think I originally copied that mock from the [WordPress Android mock](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/me/rest_v11_me_sites.json#L3), and didn't look too closely at the regex there. I believe that was added when we were still sharing mocks between Android and iOS, and we can almost assuredly simplify it one way or another. I'll double check the actual response and update that.

2020-11-25 16:55 UTC, AliSoftware commented on WooCommerce/src/androidTest/assets/mocks/mappings/me/rest_v11_me_sites.json
> +        "urlPattern": "/rest/v1.1/me/sites(\\?|/|$).*",
🤔 💭  Another alternative regex that could work to match what we want: `"/rest/v1.1/me/sites([?/].*)?$"`

2020-11-26 12:37 UTC, rachelmcr commented on WooCommerce/src/androidTest/assets/mocks/mappings/me/rest_v11_me_sites.json
> +        "urlPattern": "/rest/v1.1/me/sites(\\?|/|$).*",
I checked and we don't even need the regex here anymore — we can switch to using `urlPath` with `"/rest/v1.1/me/sites/"` instead of `urlPattern`, to simplify things. I'll make that change now.

2020-11-26 12:54 UTC, rachelmcr commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/helpers/MockingInterceptor.kt
> +        }
I agree that we _should_ do this but our infrastructure up to now hasn't been set up for it. At the moment we're only mocking WordPress.com API requests for tests across our apps, so other requests do hit live servers. This includes e.g. images that are loaded from live sites (not via API requests), so it does have an impact on things like our screenshot generation and mocking these requests would be a smart improvement. (This also came up while making changes for the WordPress tests, tracked in https://github.com/wordpress-mobile/WordPress-iOS/issues/13234, but we haven't had a chance to come back to it.) 

I considered improving that here but in the interest of time decided for now to stick with the same mocking setup we're using elsewhere. My suggestion is that we add this as a small followup task/project for improving the mocking infrastructure in all our apps.

2020-11-26 13:14 UTC, rachelmcr commented
I seem to be running into conflicting checkstyle and lint errors in [this line in UnlocalizedDateHelper](https://github.com/woocommerce/woocommerce-android/pull/2933/files?file-filters%5B%5D=.kt#diff-716beb1d0d8d07d0dc03674b318a4d25849490b7ed7bcee19f5703208a53cf61R52):

```
@Throws (IOException::class) override fun apply(context: Any?, options: Options): Any {
```

That line results in a lint error `Unexpected spacing before "("` because of the space after `@Throws`, but without that space I get the checkstyle error `In-line annotations must be followed by one whitespace [RegexpSingleline]` (which is why I added the space).

Is that a problem with our checkstyle config or is there a better way for me to do this?

2020-11-26 13:44 UTC, AliSoftware commented
> Is that a problem with our checkstyle config or is there a better way for me to do this?

I think you are expected to add the annotation on its own line. You can look at examples of how that's formatted in other files like `WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt` or `WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/StringDateFormatExt.kt`. I've left an inline suggestion on the line in your PR to suggest such a solution (not tested, tho)

2020-11-26 13:44 UTC, AliSoftware commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/helpers/TestBase.kt
> +    @Throws (IOException::class) override fun apply(context: Any?, options: Options): Any {
```suggestion
    @Throws(IOException::class)
    override fun apply(context: Any?, options: Options): Any {
```

2020-11-26 13:45 UTC, rachelmcr commented
Yeah, I realized that was the obvious solution after making that comment and confirmed it works fine. 🤦  Thanks!

2020-11-26 19:29 UTC, AmandaRiu approved these changes
Changes look good to me! :shipit:

2020-11-26 19:49 UTC, AliSoftware approved these changes

2020-11-26 19:49 UTC, AliSoftware commented on WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/reviews/products_reviews-all.json
> +                "date_created": "{{#assign 'customformat'}}yyyy-MM-dd'T'HH:mm:ss{{/assign}}{{fnow format=customformat}}",
I'm curious why the use of `{{#assign}}` then `format=customformat`, instead of using the custom format literal directly in `{{fnow … format=…}}`?

Took me a couple of minutes to understand what this `customformat` was supposed to be, at first I thought it was some magic keyword like `unix` and `epoch` from your implementation of `LocaleAwareRenderableDate` — especially since I remember seeing a custom format function (actually it's named `fun formatCustom` but confused the two). 

Looking more closely I'm guessing/realizing you did that in those cases likely because you use the same custom format multiple times in the same mock tho, right?

_(Maybe a different name for that local variable could help, as well as moving the `{{#assign}}` on top of the file… but not sure I have a better name to suggest after all tho, and not sure it would make a difference; maybe it's just me being tired and reviewing the code from smaller mobile screen 😅)

2020-11-27 13:42 UTC, rachelmcr commented on WooCommerce/src/androidTest/assets/mocks/mappings/jetpack-blogs/wc/reviews/products_reviews-all.json
> +                "date_created": "{{#assign 'customformat'}}yyyy-MM-dd'T'HH:mm:ss{{/assign}}{{fnow format=customformat}}",
> Looking more closely I'm guessing/realizing you did that in those cases likely because you use the same custom format multiple times in the same mock tho, right?

Yep, exactly. I forgot this was in the mocks (these are the same ones I used for Woo iOS) and so I didn't think to change how I was doing it when I added the helpers for the `{{fnow}}` implementation. I can see how it's not as clear as it could be, but I'm also unsure of a better local variable name, so I think I'll leave it as is for now. We can always change it later if we run into trouble or have a spark of inspiration. :D

2020-11-27 13:43 UTC, merged