Shipping Labels: Creation workflow
woocommerce/woocommerce-android pull request #3224
Opened 2020-11-27 19:40 UTC by 0nko

Adds the shipping label state machine-driven creation workflow.

2020-12-06 23:54 UTC, AmandaRiu requested changes
@0nko Brilliant work so far on this. Really cool code. I left some code notes - I think most of them minor, and found the following while testing: 

I noticed that the button to create a shipping label will be hidden if one is already created for that particular order, but if you go into another child screen - such as issuing a refund and then go back to order details, the button to create a shipping label will appear: 

<img src="https://user-images.githubusercontent.com/5810477/101296902-10e62c00-37f4-11eb-8390-035254f62176.gif" width="320"/>

Once I do a pull-to-refresh the label disappears:

<img src="https://user-images.githubusercontent.com/5810477/101296918-2a877380-37f4-11eb-9ed7-2d0bb4d53e7a.gif" width="320"/>

Also, I’ve noticed that while loading an order that already has shipping labels created that the view will jump by first showing the button to create the shipping labels and then hide the button:

<img src="https://user-images.githubusercontent.com/5810477/101296941-5276d700-37f4-11eb-959c-966ea219c61f.gif" width="320"/>

2020-12-06 23:54 UTC, AmandaRiu commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelFragment.kt
> +    }
Slick 👍

2020-12-06 23:54 UTC, AmandaRiu commented on WooCommerce/src/main/res/layout/fragment_create_shipping_label.xml
> +            android:orientation="vertical">
np: Recommend using the  custom layout`WCElevatedLinearLayout` to remove the extra layers since this view doesn't really require a material card. This will optimize the view.

2020-12-06 23:54 UTC, AmandaRiu commented on WooCommerce/src/main/res/layout/shipping_label_creation_step.xml
> +
if the `editButton` gets hidden, then the end margin for `captionTextView` being 0 kicks in and the text goes all the way to the border of the card. 

![Screen Shot 2020-12-06 at 6 20 48 PM](https://user-images.githubusercontent.com/5810477/101296513-0dea3c00-37f2-11eb-8bf1-2499ae0da9dc.png)

2020-12-06 23:54 UTC, AmandaRiu commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="shipping_label_create_packaging_details_description">Select the type of packaging you’d like to ship your items in</string>
Recommend escaping `'`

2020-12-06 23:54 UTC, AmandaRiu commented on WooCommerce/src/main/res/layout/fragment_create_shipping_label.xml
> +<androidx.core.widget.NestedScrollView xmlns:android="http://schemas.android.com/apk/res/android"
np: It think just a `ScrollView` should work here.

2020-12-07 19:25 UTC, 0nko commented on WooCommerce/src/main/res/layout/fragment_create_shipping_label.xml
> +            android:orientation="vertical">
TIL. Thanks for the tip!

2020-12-08 09:46 UTC, 0nko commented
@AmandaRiu Thanks so much! I've addressed all issues. Ready for another round.

2020-12-08 16:24 UTC, AmandaRiu approved these changes
LGTM! Awesome work @0nko! :shipit:

2020-12-08 16:24 UTC, merged