Convert "shipment tracking providers" screen to MVVM
woocommerce/woocommerce-android pull request #3315
Opened 2020-12-11 09:46 UTC by hichamboushaba

The third and last part of #2892, it converts the screen `AddOrderTrackingProviderListFragment` to MVVM, changes made:

1. Converts AddOrderTrackingProviderListFragment to a regular fragment.
2. Update navigation to use navigation component.
3. Add an OrderShipmentProvidersRepository.
3. Converts the architecture to MVVM. 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-12-11 15:12 UTC, 0nko requested changes
The changes look good 👍, but the search doesn't work (more details in the code).

2020-12-11 15:12 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderTrackingProviderListViewModel.kt
> +    val TrackingProviderListViewStateData = LiveDataDelegate(
Nit-pick: Normally we use lower-case letters for properties. I checked that the upper-case is used if it's a reference to an `object`.

2020-12-11 15:12 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderTrackingProviderListFragment.kt
> +            new.providersList.takeIfNotEqualTo(old?.providersList) {
The `query` observer is missing, so the search doesn't work.

2020-12-11 21:24 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderTrackingProviderListFragment.kt
> +            new.providersList.takeIfNotEqualTo(old?.providersList) {
I can't reproduce the issue of search, it's working for me, but I'll try to check it more, now that I think about it, having the same menu inflated here and in OrdersListFragment may cause an issue, as `onCreateOptionsMenu` will be called for both fragments (the same thing that caused the crash we just fixed)

But I don't think that the `query` has to be observed here, its value is just to restore the query text, which is done in `onCreateOptionsMenu`, and the filtering and propagating the filtered list is done here: https://github.com/woocommerce/woocommerce-android/blob/3ca9e474b7fe330981595059d1dcc2c330213fe0/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderTrackingProviderListViewModel.kt#L78-L90

2020-12-11 21:29 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderTrackingProviderListViewModel.kt
> +    val TrackingProviderListViewStateData = LiveDataDelegate(
Good catch, autocomplete is useful, but sometimes it does thing like this 😄, I'll fix it 👍

2020-12-14 09:24 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/tracking/AddOrderTrackingProviderListFragment.kt
> +            new.providersList.takeIfNotEqualTo(old?.providersList) {
@0nko I was able to confirm the issue I described above after screen rotation, I added the commit 157c6b848e06c58cb4237f549ac8b4fba4d30f4d to use a separate menu with a separate id for the search view to fix it.

2020-12-14 16:01 UTC, 0nko commented
@hichamboushaba The search works now 👍. Just `TrackingProviderListViewStateData` needs to be changed and we can merge it.

2020-12-14 16:04 UTC, hichamboushaba commented
> @hichamboushaba The search works now 👍. Just `TrackingProviderListViewStateData` needs to be changed and we can merge it.

@0nko done eea1556, I forgot about it 🤦

2020-12-14 16:24 UTC, 0nko approved these changes
Nice work! :shipit:

2020-12-14 16:24 UTC, merged