Product Attributes: Use the correct hex for interpunct
woocommerce/woocommerce-android pull request #3329
Opened 2020-12-14 20:35 UTC by AmandaRiu

Updates the hex code for the interpunct used to separate the order product attributes from quanity. 

Before | After
-- | --
![Screenshot_1607977973](https://user-images.githubusercontent.com/5810477/102132638-d860d680-3e21-11eb-92bb-772028769a01.png)|![Screenshot_1607977922](https://user-images.githubusercontent.com/5810477/102132640-da2a9a00-3e21-11eb-8bd6-899f45fd7bca.png)

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-12-15 16:54 UTC, Garance91540 requested changes
Hi Amanda, sorry to be a pain, but now it's a bit too small 😭 https://d.pr/i/cOt3a5

The font size should be roboto 14 regular, does that help?

2020-12-15 21:06 UTC, AmandaRiu commented
@Garance91540 

> Hi Amanda, sorry to be a pain, but now it's a bit too small 😭 https://d.pr/i/cOt3a5
> 
> The font size should be roboto 14 regular, does that help?

No pain at all...I was afraid of that. I have the font correct, there are just a lot of options to choose from when using a unicode character. [If you scroll to the bottom of this wiki article you can see a table of them.](https://en.wikipedia.org/wiki/Interpunct)  This latest change was using the interpunct unicode (U+00B7). Since that one's too small, I tried out a couple other options. Let me know if any of these work:

Bullet (U+2022) | Z note (U+2981)
-- | --
![2022](https://user-images.githubusercontent.com/5810477/102272850-6c4ca400-3eef-11eb-8a0f-d809f32f7373.jpg)|![2981](https://user-images.githubusercontent.com/5810477/102272855-6e166780-3eef-11eb-80bc-231fb146f5bd.jpg)

2020-12-16 13:47 UTC, Garance91540 submitted a review, later dismissed
Z note (U+2981) seems to work great!

2020-12-16 16:52 UTC, AmandaRiu commented
Updated to Z note then. Final screenshot: 

<img src="https://user-images.githubusercontent.com/5810477/102272855-6e166780-3eef-11eb-80bc-231fb146f5bd.jpg" width="320"/>

2020-12-17 10:24 UTC, Garance91540 approved these changes
👏

2020-12-17 19:39 UTC, 0nko approved these changes
:shipit:

2020-12-17 19:39 UTC, merged