Product Review Detail: Add ability to wrap moderation buttons if necessary
woocommerce/woocommerce-android pull request #3382
Opened 2020-12-30 22:19 UTC by AmandaRiu

Fixes #2128 by using the new Flow widget for `ConstraintLayout`. Since the buttons are already right-aligned, when they wrap they will stay right aligned. 

Before | After 
-- | --
![before](https://user-images.githubusercontent.com/5810477/103384033-eae63b80-4ac2-11eb-8e00-1118614c6a8f.png)|![after](https://user-images.githubusercontent.com/5810477/103384036-ed489580-4ac2-11eb-922d-76ad95627af5.png)
![before_boundaries](https://user-images.githubusercontent.com/5810477/103384041-f5a0d080-4ac2-11eb-9db9-a5b27b8fa2a2.png)|![after_bounds](https://user-images.githubusercontent.com/5810477/103384045-f76a9400-4ac2-11eb-8a79-fc44419a0131.png)

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-12-31 10:42 UTC, hichamboushaba requested changes
Nice fix @AmandaRiu, but I think the order of the buttons should be reviewed.

Another np comment: you can remove the constraints from the individual buttons to make clearer that the Flow widget will align them, and not the declared constraints.

2020-12-31 10:42 UTC, hichamboushaba commented on WooCommerce/src/main/res/layout/fragment_review_detail.xml
> +                app:constraint_referenced_ids="review_approve,review_spam,review_trash"/>
I think the order here is different from before, as the approve button was the last one, not first:

<img src="https://user-images.githubusercontent.com/1657201/103406966-ef5f3280-4b5c-11eb-89fa-523622c5d3fe.png" width=360/>

2020-12-31 16:02 UTC, AmandaRiu commented on WooCommerce/src/main/res/layout/fragment_review_detail.xml
> +                app:constraint_referenced_ids="review_approve,review_spam,review_trash"/>
@hichamboushaba  Ah good catch! Fixed the order as well as removed the unused constraints in ebf9e1e87d2fa7f5988ef151ac278a2e8d8094dd. Ready for another review 👍 

<img src="https://user-images.githubusercontent.com/5810477/103417185-a8bb0980-4b57-11eb-8d75-f3b903f9600e.jpg" width="320"/>

2020-12-31 16:33 UTC, hichamboushaba commented on WooCommerce/src/main/res/layout/fragment_review_detail.xml
> +                app:constraint_referenced_ids="review_approve,review_spam,review_trash"/>
Thanks @AmandaRiu, please just fix the lint issues, and I'll merge it

2020-12-31 22:37 UTC, hichamboushaba requested changes
There is a lint issue @AmandaRiu, if you missed it 🙂

2021-01-05 00:26 UTC, AmandaRiu commented
@hichamboushaba Fixed the lint warnings. Ready for another round 👍

2021-01-05 10:53 UTC, hichamboushaba approved these changes
:shipit:

2021-01-05 10:53 UTC, merged