Added fees section to refund by items screen
woocommerce/woocommerce-android pull request #3394
Opened 2021-01-06 03:45 UTC by anitaa1990

Fixes #3392 by adding the option to display fees section in the Issue refund screen. This section will only be displayed if fees is applicable for an order.

#### Screenshot
<img src="https://user-images.githubusercontent.com/22608780/103726701-97fb0f80-4fff-11eb-8f44-204d0f4c95ea.png" width="300"/>

#### Testing
- Create an order.
- Add some fees in `wp-admin`.
- Open the order in the app and confirm the fees are displayed in the payment section.
- Issue a refund for the order and notice the fees are displayed on the refund screen.

@rachelmcr, I have added you as a reviewer since you caught the bug in the first place. I also targeted `develop` instead of the release branch because we are already in `5.7-rc-5` and I didn't think this warranted another beta release. But let me know if you feel otherwise :D  

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-01-06 09:23 UTC, 0nko submitted a review, later dismissed
Looks good :+1:. I'll wait for @rachelmcr's review before merging.

2021-01-06 12:49 UTC, rachelmcr requested changes
> I also targeted develop instead of the release branch because we are already in 5.7-rc-5 and I didn't think this warranted another beta release. But let me know if you feel otherwise :D

I agree! Targeting develop makes sense for this change.

The fees section looks good, but when the fees section is there can we also update the informational text below it to mention how to refund fees as well? Like this:

> You can refund fees, shipping, and tax amounts in your store admin

2021-01-07 04:44 UTC, anitaa1990 commented
> The fees section looks good, but when the fees section is there can we also update the informational text below it to mention how to refund fees as well? 

@rachelmcr Good point! Fixed in 2c3b465 👍 

<img src="https://user-images.githubusercontent.com/22608780/103851905-d0b6e980-50d0-11eb-8b55-1d976b58aa20.png" width="300"/>

2021-01-07 12:27 UTC, rachelmcr approved these changes
Looks great! I tested orders with and without fees, and the refund screen includes all the details I expect in both cases.

2021-01-07 12:47 UTC, anitaa1990 commented
Thank you @rachelmcr 🙇‍♀️

2021-01-07 12:47 UTC, merged