Issue/3603 order creation fab
woocommerce/woocommerce-android pull request #3613
Opened 2021-02-21 13:34 UTC by kidinov

Issue: woocommerce#3603

It contains the changes from https://github.com/woocommerce/woocommerce-android/pull/3612. I'm not sure if it's possible to create a PR to the branch which is in the fork. Please let me know if this possible. If not, we'd better merge the first PR and then review this one.

* Description: FAB which is an entry to the order creation flow. Similar to the products, it disappears during orders loading.
* Testing instructions: It should be only visible in debug builds
* Images and Gif:
https://user-images.githubusercontent.com/4923871/108626472-6def9680-7461-11eb-9933-ff41e79a9040.mp4
https://user-images.githubusercontent.com/4923871/108626339-bd819280-7460-11eb-92f0-389a1e14034f.mp4

2021-02-22 14:52 UTC, 0nko commented
I've updated the target branch from `develop` to `kidinov/order-creation`. You can use this branch to create future PRs.

2021-02-22 15:19 UTC, 0nko requested changes
The FAB changes look good, but there's a change in behavior in order list, as I've mentioned in the code comment.

2021-02-22 15:19 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
> -        showAddProductButton(false)
Removing this line will cause the FAB to stay visible even after leaving the list (either orders or products). For example, tapping on an order list item, or when adding a new product.

2021-02-23 13:16 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
> -        showAddProductButton(false)
Good catch, thanks! Somehow I was under impression that we always start a new activity in the flows you mentioned above which obviously is not correct.

But just hiding the FAB in `onDestroyView` in both fragments won't work, because it's called after the destination fragment's "onViewCretead". So we effectively hide the FAB from the original fragment after it's shown by the destination fragment.

I've come up with the following solution: we hide the FAB in `onDestroyView` in every child of `TopLevelFragment` unless the destination fragment declares that it has the FAB. Please take a look at my [latest commit](https://github.com/woocommerce/woocommerce-android/pull/3613/commits/8f620e2467d330b8c276ed5234e55af6c1e21362) and let me know if there is a simpler solution we can use.

2021-02-23 21:23 UTC, 0nko reviewed
Thanks for the changes, please see my code comments.

2021-02-23 21:23 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
> -        showAddProductButton(false)
The solution works, but the way it's implemented now the visibility of the FAB can't be unit-tested for the order list.

2021-02-23 21:23 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
> +        if (navPos != ORDERS && navPos != PRODUCTS) {
Is this still necessary?

2021-02-24 07:27 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
> -        showAddProductButton(false)
I've moved order related FAB logic to the view model and added some tests

2021-02-24 07:28 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
> +        if (navPos != ORDERS && navPos != PRODUCTS) {
Nope. Redundant. I've removed it

2021-02-24 11:25 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
> +class FeatureFlagResolver @Inject constructor() {
I don't think this is really necessary. You can still call `ORDER_CREATION.isEnabled()` without `Context` in the ViewModel.

2021-02-24 11:41 UTC, 0nko reviewed
Looks good now! 👍 

Just a minor nit-pick: I noticed the behavior is different for orders and products. In products, the button isn't hidden during loading and I think that's a good thing -- when orders are initially loaded, the button is first shown, then immediately hidden for loading and the shown again, which looks flaky.

2021-02-26 08:48 UTC, kidinov commented
@0nko I've spent quite some time trying out a different approach to avoid FAB flickering and at the same time to hide when data is loading and my conclusion is that the best way will be hiding the FAB when a user explicitly does pull-to-refresh and we don't change the visibility of the FAB when a user comes to the orders screen. Please take a look at my last commit and please let me know wdyt about that

2021-02-26 20:23 UTC, 0nko reviewed
Thanks for the changes! I've left a couple of comments in the code.

2021-02-26 20:23 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
> +                            viewModel.onRefreshOrders()
Nice!

2021-02-26 20:23 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
> +    private var isRefreshing: Boolean = false
What's the purpose of this variable? I don't see it being used anywhere.

2021-02-26 20:23 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
> +    private val _isAddOrderButtonVisible = SingleLiveEvent<Boolean>()
`SingleLiveEvents` are intended to be used for one-off events, which should only be triggered once (for example showing a dialog). I know in this VM it hasn't been completely followed  but simple state properties should all go to the `ViewState` class. It makes testing easier and reduce the amount of boiler plate.

2021-02-26 20:23 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
> +    fun onFetchingFirstPage(isFetchingFirstPage: Boolean) {
Do we really need to make this public for testing? I see you're using it in unit tests for testing but wouldn't mocking the `PageListWrapper`, like you do in other tests?

2021-02-26 20:23 UTC, 0nko commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
> +            viewModel.onFetchingFirstPage(true)
When you change this to `false`, the test result does not change.

2021-02-27 07:13 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
> +    private val _isAddOrderButtonVisible = SingleLiveEvent<Boolean>()
It was a conscious decision here to use `SingleLiveEvent`. Using `MutableLiveData` causes the last emitted event to be emitted again when the fragment starts observing, which does not really match the logic here. We don't want to have the previous visibility state of the FAB interfere with the visibility of the FAB when a user coming back to the Orders screen. The idea is to keep FAB at the same visibility state as its current one in order to avoid FAB flickering. I hope it makes sense =)

2021-02-27 08:16 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
> +    private var isRefreshing: Boolean = false
The original idea was to have this flag as an indicator that the FAB visibility can be changed when the first page is loading, but then I've switched to another approach - hiding the FAB only when "on refresh" happens, and forgot to remove the flag =(. [Removed now](https://github.com/woocommerce/woocommerce-android/pull/3613/commits/9a5e1617297007c290108f1da095c91665fc62cc)

2021-02-27 08:18 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
> +    fun onFetchingFirstPage(isFetchingFirstPage: Boolean) {
TBH I was just following the same approach as it's done with `createAndPostEmptyViewType` method. I've changed it to a more blackboxish approach now.

2021-02-27 08:20 UTC, kidinov commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt
> +            viewModel.onFetchingFirstPage(true)
That's correct. I'm testing that if the feature is disabled, then even when fetching is not in progress anymore we don't show the FAB.

2021-02-27 12:01 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt
> +    fun onFetchingFirstPage(isFetchingFirstPage: Boolean) {
Oh ok, I didn't realize it was already used somewhere else. Anyway, thanks for changing it, I think that's a cleaner approach 👍.

2021-02-27 12:24 UTC, 0nko approved these changes
The changes are looking good! 👍

2021-02-27 12:25 UTC, merged