Issue/3604 Order creation. Order creation screen infrastructure.
woocommerce/woocommerce-android pull request #3621
Opened 2021-02-23 19:26 UTC by kidinov

Issue: #3604

Description: Infrastructure to move forward with order creation feature. [Customer](https://woocommerce.github.io/woocommerce-rest-api-docs/#customers) model.
Images and Gif:

https://user-images.githubusercontent.com/4923871/108896534-1b130c00-7626-11eb-9917-47b39beea9f2.mp4

2021-02-23 19:27 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
> +        ORDERS_LIST_ADD_ORDER_TAPPED,
Don't know the details of the tracking you use here, so please let me know if this makes sense

2021-02-26 20:50 UTC, 0nko reviewed
Looks good 👍. See my code comments.

2021-02-26 20:50 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/model/customer/CustomerBilling.kt
> +data class CustomerBilling(
We already have an `Address` data class used for orders and it can be reused for customers, as well.

2021-02-26 20:50 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/model/customer/CustomerShipping.kt
> +data class CustomerShipping(
Same as above, see `Address`.

2021-02-27 08:51 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/model/customer/CustomerShipping.kt
> +data class CustomerShipping(
[Fixed](https://github.com/woocommerce/woocommerce-android/pull/3621/commits/67f51dcf56376cc3d592ddd9aa1e19362c97c9dd)

2021-02-27 08:51 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/model/customer/CustomerBilling.kt
> +data class CustomerBilling(
[Fixed](https://github.com/woocommerce/woocommerce-android/pull/3621/commits/67f51dcf56376cc3d592ddd9aa1e19362c97c9dd)

2021-02-27 13:25 UTC, 0nko requested changes
Please see the code comments.

2021-02-27 13:25 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
> +                fabManager.showFabAnimated(R.string.orderlist_add_order_button) { openOrderCreation() }
The way you had it before was better. Opening the creation screen directly in the fragment and bypassing the ViewModel means we won't be able to unit-test it.

2021-02-27 14:58 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
> +                fabManager.showFabAnimated(R.string.orderlist_add_order_button) { openOrderCreation() }
Yeah, I was thinking about that, and seems that:
* We can't unit test analytics tracking properly, it's static and tracking is done in the fragment anyway, so moving it in the VM breaks consistency with the current codebase
```
AnalyticsTracker.track(Stat.ORDERS_LIST_ADD_ORDER_TAPPED)
```

* Things that were there related to the search also not really JVM unit-testable because coupled to the platform. It's possible to decouple it, but I'm hesitant to change a lot here due to the restriction of my trial
```
        if (isSearching) {
            val savedSearch = searchQuery
            clearSearchResults()
            updateActivityTitle()
            searchQuery = savedSearch
            isSearching = true
        }
```

* Navigation to the screen itself also not unit-testable
```
(activity as? MainNavigationRouter)?.showOrderCreationScreen()
```

So it looks like that having a method in the view model that just throws back a single event doesn't bring any testability, but at the same time brings extra code and complexity. What do you think?

2021-03-02 09:02 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
> +                fabManager.showFabAnimated(R.string.orderlist_add_order_button) { openOrderCreation() }
> We can't unit test analytics tracking properly, it's static and tracking is done in the fragment anyway, so moving it in the VM breaks consistency with the current codebase

Yeah, the static method is unfortunate. I've been trying to move the tracking calls to the VM (for example, `VariationDetailViewModel`). This is a good candidate for a future refactoring.

> Things that were there related to the search also not really JVM unit-testable because coupled to the platform. It's possible to decouple it, but I'm hesitant to change a lot here due to the matter of the task I'm working on

I agree that `OrderListViewModel` is not great.. Don't worry about changing the existing code, though. We'll have to address these issues separately.

> So it looks like that having a method in the view model that just throws back a single event doesn't bring any testability, but at the same time brings extra code and complexity. What do you think?

I'd argue that just because there is code that's not testable doesn't mean we should add more of it. Not being able to test the search functionality doesn't prevent us from testing order creation, at least partially. Bad code can always be fixed and tests can be added. I think the separation of concerns principle (views are dumb; all logic lives inside VMs or some layer above) should still stand. Bypassing this would go against the current practice and would break the consistency with most of the other ViewModels in the project.

2021-03-02 09:46 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
> +                fabManager.showFabAnimated(R.string.orderlist_add_order_button) { openOrderCreation() }
It makes sense 👍 I'm passing the event via ViewModel now. (Commit)[https://github.com/woocommerce/woocommerce-android/pull/3621/commits/198cd5c441f0dda84b74f0cc067eda7fdb0eeec0]

2021-03-02 11:23 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt
> +                fabManager.showFabAnimated(R.string.orderlist_add_order_button) { openOrderCreation() }
Thanks for the update!

2021-03-02 11:35 UTC, 0nko approved these changes
:shipit:

2021-03-03 06:26 UTC, kidinov commented
@0nko shell be merged? (I can not do this, you know =) )

2021-03-03 16:31 UTC, 0nko commented
Oops, yeah :)

2021-03-03 16:31 UTC, merged