Use Gradle Configuration
woocommerce/woocommerce-android pull request #3661
Opened 2021-03-04 23:47 UTC by jkmassel

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-03-05 09:55 UTC, AliSoftware reviewed
Did not actually test this yet (did not checkout and run the task, only reviewed the diff on github), but posting my initial feedback anyway

2021-03-05 09:55 UTC, AliSoftware commented on .configure
> +  "project_name": "wc-android",
I have to admit I don't know what this key is used for in the `configure` tooling… but why this change?

2021-03-05 09:55 UTC, AliSoftware commented on .configure
> +      "destination": "WooCommerce/google-services.json"
I'm guessing `encrypt: true` is the default? (why would we use `configure` and mobile secrets if it was not encrypted anyway…)

2021-03-05 09:55 UTC, AliSoftware commented on .gitignore
> +!.configure-files/*.enc
nit: would be nice to rebase this PR on top of `develop` now that https://github.com/woocommerce/woocommerce-android/pull/3659 is merged, as this PR would be a perfect candidate to double-check that the enc files changes are also properly shown as binary in this PR. 😛

2021-03-05 09:55 UTC, AliSoftware commented on secrets.properties-example
> +wc.in_app_update_type = 0
nit: LF at EOF

2021-03-05 09:55 UTC, AliSoftware commented on WooCommerce/build.gradle
> +        }
Can't we DRY this?

I'm seeing a very similar logic for the `google-services.json[-example]` file and for the `secrets.properties[-example]` file, seems to me we could maybe instead have an array of "files to be processed" and loop over them to apply the same logic to all of them? 🤔  (maybe not though, as the code run when the file exists differs… but still worth pondering.)

2021-03-05 09:55 UTC, AliSoftware commented on WooCommerce/build.gradle
> +                        "${property.value}"
Would it make sense to have the `wc.` prefix extracted in a local variable (or automatically derived from some other property)? My thought is those lines are likely to be copy/pasted into our other apps and repos (especially WPAndroid will use a very similar task when it adopts the new configure too like here) and if we want to keep our repos as in sync as possible and copy/paste changes to keep applying future fixes to all repos, it's easy to forget to update the `wc` prefix to `wp` if that gets copy/pasted too.

2021-03-05 20:06 UTC, jkmassel commented on .configure
> +  "project_name": "wc-android",
This key defines which encryption key from `keys.json` to use – it needs to be changed here in order to avoid breaking mobile secrets while I do this work. 

At some point after this PR lands (once any branches using the old `project_name` land, we can roll it back to the proper name if we like

2021-03-05 20:06 UTC, jkmassel commented on .configure
> +      "destination": "WooCommerce/google-services.json"
Yeah, exactly. The newer tool just encrypts everything whether it _needs_ to be or not.

2021-03-05 20:10 UTC, jkmassel commented on .gitignore
> +!.configure-files/*.enc
Good call – this is done and it looks good! 🎉

2021-03-05 20:37 UTC, jkmassel commented on WooCommerce/build.gradle
> +                        "${property.value}"
This is a pre-existing things. I've rolled back this change, so it's no longer applicable.

2021-03-08 11:17 UTC, AliSoftware requested changes
Tried this today and on the first try I was able to make rust be "panicked"…

```
10:56:58 [DEBUG] (1) configure::fs: Reading keys from "/Users/olivier/.mobile-secrets/keys.json"
thread 'main' panicked at 'Unable to decrypt and copy files: MissingProjectKey', src/configure.rs:193:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I quickly figured that this was due to my `mobile-secrets` not being up-to-date and not having pulled the latest keys (though a more explicit error message could have been nice), so doing a `git pull` in `~/.mobile-secrets` then re-trying finally made the task pass… 

But then when I looked at `.configure-files`, **only one file (`upload.jks`) were un-encrypted**, all the other files were `.enc` files (despite the logs saying that it stored other decrypted files during the process). So seems like it didn't work all the way?

```
$ ls -l .configure-files
total 64
-rw-r--r--  1 olivier  staff  2144 Mar  8 11:47 automattic_upload.jks.enc
-rw-r--r--  1 olivier  staff  1264 Mar  8 11:47 debug.keystore.enc
-rw-r--r--  1 olivier  staff  3903 Mar  8 11:48 google-services.json.enc
-rw-r--r--  1 olivier  staff  2402 Mar  8 11:48 google-upload-credentials.json.enc
-rw-r--r--  1 olivier  staff  2123 Mar  8 11:48 gradle.properties.enc
-rw-r--r--  1 olivier  staff   170 Mar  8 11:48 sentry.properties.enc
-rw-r--r--  1 olivier  staff  2142 Mar  8 12:02 upload.jks
-rw-r--r--  1 olivier  staff  2182 Mar  8 11:48 upload.jks.enc
```

I also think it could be nice to improve a couple of things here:

1. Probably reduce the verbosity of the output, as it's printing a lot of `[DEBUG] (1) configure:…` lines when running that could make it a bit scary for end-users. Maybe only print those debug lines if `DEBUG=1` env var is set or something like that?
2. Would be very nice to have a better error message when the decryption key is not found, to suggest users to update their `mobile-secrets` repo and retry.

### Log Details

<details><summary>Step 1: Fresh clone the repo.</summary>

```
$ git clone git@github.com:woocommerce/woocommerce-android.git woocommerce-android-clean
…
$ cd woocommerce-android-clean 
$ git checkout use/binary-configure 
```
</details>

<details><summary>Step 2: <tt>./gradlew applyConfiguration</tt> fail as expected.</summary>

```
$ ./gradlew applyConfiguration
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
Copying git-hooks scripts from tools/team-props/git-hooks to .git/hooks
Checking whether `configure` binary is present
Downloading `configure` binary
Detected current OS: macos
Detected plugin version: 0.5.0
200
OK

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/olivier/Documents/Dev/woocommerce-android-clean/WooCommerce/build.gradle' line: 347

* What went wrong:
A problem occurred evaluating project ':WooCommerce'.
> Build configuration file gradle.properties doesn't exist, follow README instructions

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
```
</details>

<details><summary>Step 3: Creating <tt>gradle.properties</tt> then re-running <tt>applyConfiguration</tt>: panic!</summary>

```
$ cp gradle.properties-example gradle.properties         
$ ./gradlew applyConfiguration                  
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :
Copying git-hooks scripts from tools/team-props/git-hooks to .git/hooks

> Configure project :WooCommerce
WARNING: You're using the example google-services.json file. Google login will fail.
WARNING: You're using the example google-services.json file. Google login will fail.
Could not find google-services.json while looking in [src/wasabi/debug, src/debug/wasabi, src/wasabi, src/debug, src/wasabiDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/jalapeno/debug, src/debug/jalapeno, src/jalapeno, src/debug, src/jalapenoDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/vanilla/debug, src/debug/vanilla, src/vanilla, src/debug, src/vanillaDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/wasabi/release, src/release/wasabi, src/wasabi, src/release, src/wasabiRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/jalapeno/release, src/release/jalapeno, src/jalapeno, src/release, src/jalapenoRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/vanilla/release, src/release/vanilla, src/vanilla, src/release, src/vanillaRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
WARNING: API 'variant.getMappingFile()' is obsolete and has been replaced with 'variant.getMappingFileProvider()'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMappingFile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

> Configure project :
Checking whether `configure` binary is present

> Task :applyConfiguration FAILED
10:56:58 [DEBUG] (1) configure: libconfigure initialized
10:56:58 [DEBUG] (1) configure: libConfigure initializing encryption
10:56:58 [DEBUG] (1) configure: libConfigure encryption initialization successful
10:56:58 [DEBUG] (1) configure::fs: Discovered Repository at "/Users/olivier/Documents/Dev/woocommerce-android-clean"
10:56:58 [DEBUG] (1) configure::fs: Configure file found at: "/Users/olivier/Documents/Dev/woocommerce-android-clean/.configure"
10:56:58 [DEBUG] (1) configure::fs: Discovered Repository at "/Users/olivier/Documents/Dev/woocommerce-android-clean"
10:56:58 [DEBUG] (1) configure::fs: Keys file found at: "/Users/olivier/.mobile-secrets/keys.json"
10:56:58 [DEBUG] (1) configure::fs: Reading keys from "/Users/olivier/.mobile-secrets/keys.json"
thread 'main' panicked at 'Unable to decrypt and copy files: MissingProjectKey', src/configure.rs:193:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':applyConfiguration'.
> Process 'command '/Users/olivier/Documents/Dev/woocommerce-android-clean/vendor/configure/configure'' finished with non-zero exit value 101

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
1 actionable task: 1 executed
```
</details>

<details><summary>Step 4: Updating <tt>~/mobile-secrets</tt> and re-running <tt>applyConfiguration</tt>: task succeeds...</summary>

```
$ cd ~/.mobile-secrets
$ git pull
…
$ cd -
$ ./gradlew applyConfiguration

> Configure project :WooCommerce
WARNING: You're using the example google-services.json file. Google login will fail.
WARNING: You're using the example google-services.json file. Google login will fail.
Could not find google-services.json while looking in [src/wasabi/debug, src/debug/wasabi, src/wasabi, src/debug, src/wasabiDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/jalapeno/debug, src/debug/jalapeno, src/jalapeno, src/debug, src/jalapenoDebug]
registerResGeneratingTask is deprecated, u [...]

2021-03-18 12:20 UTC, AliSoftware commented
@jkmassel any luck on making progress on the issues highlighted above? Wondering if I could get this tested during next code freeze on Monday 🤔

2021-04-06 10:24 UTC, AliSoftware commented
@jkmassel: moved the milestone of this PR once again (since I'm doing the code freeze of 6.4 today).

2021-05-17 14:13 UTC, AliSoftware commented
Another sprint, another milestone move 😅  (We'll get there! 🤞 )

2021-09-16 12:12 UTC, astralbodies commented
@jkmassel Should we move this to a draft status?

2024-11-15 12:47 UTC, closed without merging

2024-11-15 12:47 UTC, wzieba commented
I'll allow myself to close this PR - it updates CircleCI config that we don't use anymore. Tasks removed here are also discussed in #12934