Shipping refund: Add shipping lines selection in order refund selection screen.
woocommerce/woocommerce-android pull request #3666
Opened 2021-03-08 08:42 UTC by hafizrahman

This is step 3 out of 4 for this feature development, [as outlined here.](https://github.com/woocommerce/woocommerce-android/issues/3319#issuecomment-783276159)

This PR deals with showing the toggle that allows user to select shipping line(s) to be refunded.

To test this, please prepare three different Orders:
1. An order with no shipping line items.
2. An order with one shipping line item.
3. An order with more than one shipping line items. This can be created in core by editing an Order, then click "Add Item(s)", then add a Shipping line item from there.

_pr in progress, to be continued_

2021-03-19 14:42 UTC, 0nko commented
Is there something specific I need to do to enable this? I've created the orders specified above but I'm not seeing the switch 🤔.

2021-03-20 08:15 UTC, hafizrahman commented
Thanks for taking a look @0nko . Do you mean you can't see the "Refund shipping" switch like on the screenshot below, for an Order with 1 or more shipping lines?

![Screenshot_20210320-151146_WooCommerce (Pre-Alpha).jpg](https://user-images.githubusercontent.com/266376/111863514-a1eda700-898e-11eb-8c67-bea64635a78d.jpg)

I just tried installing the apk from scratch using the automated link above and it does show the switch 🤔

2021-03-22 23:03 UTC, 0nko commented
Sorry, the generated APK worked. I must have tested it with an old build.

> This is the part where I could use some help because I might be missing some edge cases when counting grand total.

Just so that I don't misunderstand you, you mean help with testing or implementing the functionality correctly?

> Toggle selections on Order with multiple shipping line items. Checked and un-checked items should stay checked/un-checked as you make configuration changes, and as you toggle the main refund switch.

When you have multiple shipping lines, toggle the main switch, un-toggle individual lines and rotate the device, the main switch will get un-toggled.

2021-03-24 07:49 UTC, hafizrahman commented
> Just so that I don't misunderstand you, you mean help with testing or implementing the functionality correctly?

More with testing, especially when combining between selecting some products and selecting some refunds. I think I've implemented it as correctly as I could, just wondering if I miss some cases.

> When you have multiple shipping lines, toggle the main switch, un-toggle individual lines and rotate the device, the main switch will get un-toggled.

Did you mean un-toggling all the individual lines? By default when all individual lines are toggled off, the main switch is toggled off automatically, with or without rotating. I wonder if this is what you're seeing.

But if you meant un-toggling some of the individual lines then rotating, in my test it doesn't un-toggle the main switch afterward. Video below:


https://user-images.githubusercontent.com/266376/112273532-06bb4100-8cb0-11eb-8d1f-1685843a9742.mp4

2021-03-25 19:45 UTC, 0nko commented
I meant if you un-toggle all of the individual shipping lines, toggle the main one back, rotate the screen and then it gets hidden. But it's not a big deal.

2021-03-25 19:47 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt
> +            return 0.toBigDecimal()
You can use `BigDecimal.ZERO` here.

2021-03-25 20:50 UTC, 0nko requested changes
Nice work. The functionality is good but I have some suggestions in the code.

2021-03-25 20:50 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt
> +    fun getTotalShippingTaxes(): BigDecimal {
You can replace the whole function with `shippingLines.sumByBigDecimal { it.totalTax }`.

2021-03-25 20:50 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +    val refundShippingLines: LiveData<List<RefundListItem>> = _refundShippingLines
Reusing `RefundListItem` here is not a good idea. Shipping refund items have completely different properties. They don't have quantity or max quantity. It'd be better to create a new data class, such as `ShippingRefundListItem` (and maybe rename the original one to `ProductRefundListItem`).

2021-03-25 20:50 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +            RefundListItem(it.toItem(), 1, 1)
As mentioned above, this is not a good practice. `ShippingLine.toItem()` should not exist. `ShippingRefundListItem` can reference a `ShippingLine` and you won't need to use dummy values for unused properties.

2021-03-25 20:50 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +        if (refundByItemsState.isShippingMainSwitchChecked == true) {
It should be the other way. The `isShippingMainsSwitchChecked` should be determined by the `refundByItemsState.shippingRefund` (whether it's 0 or not). See the `RefundByItemsViewState` suggestion below. 

So you can get rid of this check and just replace this block with `val grandTotal = productRefund + refundByItemsState.shippingRefund`

2021-03-25 20:50 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +        _refundShippingLines.value = items.filter { it.maxQuantity > 0 }
What does this filter do?

2021-03-25 20:50 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +        val grandTotalRefund: BigDecimal = BigDecimal.ZERO /* for now it's productsRefund + shippingRefund */
This value could be calculated automatically like `totalRefund`, couldn't it?

2021-03-25 20:50 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +        val isShippingMainSwitchChecked: Boolean? = null,
You can make this value automatic simply with `shippingRefund > BigDecimal.ZERO`.

2021-03-25 20:50 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +    private fun calculatePartialShippingSubtotal(selectedShippingLinesId: List<Long>): BigDecimal {
You could simplify this function by adding `import org.wordpress.android.fluxc.utils.sumBy as sumByBigDecimal` to the imports and then:

```
return selectedShippingLinesId
    .map { order.shippingLines.first { line -> line.itemId == it } }
    .sumByBigDecimal { it.total }
```

2021-03-25 20:50 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +    private fun calculatePartialShippingTaxes(selectedShippingLinesId: List<Long>): BigDecimal {
Same as above.

2021-03-29 03:13 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt
> +    fun getTotalShippingTaxes(): BigDecimal {
Thank you, that's good to know! I've done this.

2021-03-29 03:41 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +    val refundShippingLines: LiveData<List<RefundListItem>> = _refundShippingLines
Thank you for your feedback! This was the part that I wasn't sure what the ideal solution should be.

What still confuses me right now is that eventually both `ShippingRefundListItem` and `ProductRefundListItem` will have to be converted to `WCRefundItem` in `onRefundConfirmed()`. And `WCRefundItem` does require quantity value. 

So to clarify, it's better to separate product and shipping into two distinct data classes, then turn them both into `WCRefundItem` in `onRefundConfirmed()`?

2021-03-29 05:09 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +    private fun calculatePartialShippingSubtotal(selectedShippingLinesId: List<Long>): BigDecimal {
Thanks! For this and the next suggestion I have used the sumByBigDecimal method as suggested. I also kept the original `filter` because doing so makes the code slightly shorter and for me faster to understand.

2021-03-29 06:37 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +        val isShippingMainSwitchChecked: Boolean? = null,
Good point! Added.

2021-03-29 06:38 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +        if (refundByItemsState.isShippingMainSwitchChecked == true) {
Makes sense! Added.

2021-03-29 07:05 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +        val grandTotalRefund: BigDecimal = BigDecimal.ZERO /* for now it's productsRefund + shippingRefund */
Good point! This simplifies many places in the code, thanks. Have added the change. I've also removed `totalRefund` since `grandTotalRefund` works the same now.

2021-03-29 07:19 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +        _refundShippingLines.value = items.filter { it.maxQuantity > 0 }
Oh, good point. I copied this from `updateRefundItems()` without realizing that it won't be needed. This is now fixed.

2021-03-30 13:24 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +    val refundShippingLines: LiveData<List<RefundListItem>> = _refundShippingLines
> What still confuses me right now is that eventually both ShippingRefundListItem and ProductRefundListItem will have to be converted to WCRefundItem in onRefundConfirmed(). And WCRefundItem does require quantity value.

Are you sure? I couldn't find an example with the shipping refund API call but in core you have to specify the amount, not quantity.

2021-03-31 02:21 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +    val refundShippingLines: LiveData<List<RefundListItem>> = _refundShippingLines
Oh hm, I might have misunderstood things there. [I was referring to this `quantity` property in FluxC](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/a097f94c384cc146c9a187144ea73eb1ab64c893/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/refunds/WCRefundModel.kt#L18):

```
 data class WCRefundItem(
        val itemId: Long,
        @SerializedName("qty")
        val quantity: Int,
```

2021-04-01 11:32 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +    val refundShippingLines: LiveData<List<RefundListItem>> = _refundShippingLines
I see. I'd still add the `ShippingRefundListItem` which obscures this implementation detail from the business logic layer (the ViewModel). It can contain the `fun toDataModel()` which then adds the necessary dummy values and proceeds as before. It's a bit extra code but makes the code much cleaner.

2021-04-06 08:10 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +    val refundShippingLines: LiveData<List<RefundListItem>> = _refundShippingLines
That makes sense, thanks! I've added your suggestion.

2021-04-06 08:13 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +            RefundListItem(it.toItem(), 1, 1)
This function is now deleted.

2021-04-06 08:25 UTC, hafizrahman commented
@0nko Thanks for all your suggestions! This is now ready for another review.

2021-04-06 10:24 UTC, AliSoftware commented
FYI: moved the milestone from 6.4 to 6.5 since I'm doing the code freeze of 6.4 today.

2021-04-06 20:08 UTC, 0nko reviewed
I've marked this as Ready for review, since I'm actually reviewing it :).

Thanks for the fixes, @hafizrahman! After playing with the app, I noticed that after untoggling all the individiual shipping items (when there are more), the shipping refunds are hidden but the main switch is still toggled.

Also, I'm not sure if you were planning to address this in a different PR, but when you toggle a shipping refund, the Next button stays disabled.

2021-04-07 09:23 UTC, hafizrahman commented
>  I noticed that after untoggling all the individual shipping items (when there are more), the shipping refunds are hidden but the main switch is still toggled.

Good find, thanks. Main toggle is now automatically toggled off, if all individual items are toggled off.

> when you toggle a shipping refund, the Next button stays disabled.

Yup! This will be part of the next PR where the actual refund is processed.

@0nko Ready for another review :)

2021-04-07 19:38 UTC, 0nko approved these changes
Nice job! 🎉

2021-04-07 19:39 UTC, merged