Variable refund notice
woocommerce/woocommerce-android pull request #3720
Opened 2021-03-19 21:26 UTC by 0nko

Addresses #2000.

Based on the available refund options (fees, shipping and taxes), the refund notice is changed accordingly.

| Single option | Two options | Three options |
|-|-|-|
| ![image](https://user-images.githubusercontent.com/1522856/111843565-b8015600-8901-11eb-8872-be5735d8331e.png) | ![image](https://user-images.githubusercontent.com/1522856/111843591-c3548180-8901-11eb-8258-184189009c4e.png) | ![image](https://user-images.githubusercontent.com/1522856/111843620-cea7ad00-8901-11eb-9dd1-d1b18a93e2d9.png) |

**To test:**
1. Create orders with different combinations of items (fees, shipping and taxes)
2. Go to Order details and issue a refund
3. Verify the right combination of options is displayed in the notice (or the notice is hidden, if none are available)

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-03-22 13:59 UTC, malinajirka requested changes
Thanks @0nko on working on this! 

I've tested the changes and it works as expected (with English locale). I've left a couple of comments, let me know what you think.

P.S. I realize this class is not unit tested, but we might want to consider creating a first few tests for this logic, wdyt?

2021-03-22 13:59 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +                val fees = resourceProvider.getString(string.orderdetail_payment_fees).toLowerCase(Locale.ROOT)
⚠️ I'm a bit worried "Locale.ROOT" might not work as expected in some languages. Have you considered using device's locale instead? Wdyt?

2021-03-22 13:59 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +            val and = resourceProvider.getString(string.and).toLowerCase(Locale.ROOT)
Nitpick: We could move "val and" into the `if (refundOptions.isNotEmpty())`.

2021-03-22 13:59 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt
> +import com.woocommerce.android.R.string
⚠️ Importing `R.string` sometimes confuses lint when it tries to find usages of strings. We might want to consider removing this import. Wdyt?

2021-03-23 20:21 UTC, 0nko commented
@malinajirka Thanks for the review! I've addressed your comments and the PR is ready for another round.

2021-03-24 12:53 UTC, malinajirka submitted a review, later dismissed
Thanks for the changes @0nko! It all looks good to me now ;). I've left one minor comment, but feel free to merge it no matter if you decide to update the test names or not.

2021-03-24 12:53 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModelTest.kt
> +    fun `test order with no extra shipping options`() = coroutinesTestRule.testDispatcher.runBlockingTest {
Nitpick: I think it's a good practice to explain what the test is testing and what is the expected result in the name of the test. Tests serve as a form of documentation and keeping the names self-explanatory helps all future devs to quickly understand what is the expected behavior.

We might for example name this something like `when order has zero taxes and no shipping and fees, then refund notice is not visible`.

Wdyt?

2021-03-24 13:32 UTC, 0nko commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModelTest.kt
> +    fun `test order with no extra shipping options`() = coroutinesTestRule.testDispatcher.runBlockingTest {
Thanks, good point 👍

2021-03-24 13:37 UTC, 0nko commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModelTest.kt
> +    fun `test order with no extra shipping options`() = coroutinesTestRule.testDispatcher.runBlockingTest {
@malinajirka Fixed!

2021-03-24 18:31 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModelTest.kt
> +    fun `test order with no extra shipping options`() = coroutinesTestRule.testDispatcher.runBlockingTest {
Love it! Thank you 🙇

2021-03-24 18:31 UTC, malinajirka approved these changes

2021-03-24 18:32 UTC, merged