Support products and variations with decimal stock quantities
woocommerce/woocommerce-android pull request #3737
Opened 2021-03-24 10:57 UTC by hafizrahman

**_This is a work in progress_**

This is to fix: #3611 
Depends on: [FluxC #1931](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1931) 

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-03-31 09:19 UTC, anitaa1990 requested changes
Great work @hafizrahman! I tested the scenarios described and faced one issue mentioned in the comment. Other than that, everything works great :shipit:

2021-03-31 09:19 UTC, anitaa1990 commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt
> +    }
np: This method could use a comment on what it does. Also we could remove the return type from the if else statement and modify it to something like this:
```
return if (number.rem(1).equals(0.0)) {
            formatCount(number.toInt())
        } else {
            number.toString()
        }
```

2021-03-31 09:19 UTC, anitaa1990 commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt
> +    }
Actually I don't know that this method would work for stock quantity. We don't want to format stock quantity to `10k` or `10m`. I think we just display the full value as is. But after the changes in this PR, I am seeing the stock quantity as `10m`, when it should be `56,575,639`.
(The commas are displayed based on the Locale of the device I think).

What we can do is to use the previous function as it is, if the stock quantity is an int:
```
        return if (number.rem(1).equals(0.0)) {
            FormatUtils.formatInt(number.toInt())
        } else {
            number.toString()
        }
``` 

WDYT?

2021-03-31 10:30 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt
> +    }
Yup I just saw this bug as well. Thanks for noticing, will fix that.

2021-04-01 03:50 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt
> +    }
I found that using `FormatUtils.formatInt(number.toInt())` introduces thousands separator in the `TextInputEditText`, and does this weird text jumping behavior when entering content. That behavior does not happen if I use `number.toInt().toString()`, and this is the one that mimics how `develop` version as well, so this is what I end up using.

So in the end I chose to use `formatInt` for regular text, but use `number.toInt` for text input.

Check out the input box behavior comparison below for more details: 

Develop | Using `FormatUtils.formatInt` | Using `number.toInt`
--|--|--
<video src="https://user-images.githubusercontent.com/266376/113239446-f240ff00-92d4-11eb-9009-e8ad02bfb3ad.mp4" data-canonical-src="https://user-images.githubusercontent.com/266376/113239446-f240ff00-92d4-11eb-9009-e8ad02bfb3ad.mp4" controls="controls" muted="muted" class="d-block rounded-bottom-2 width-fit" style="max-height:640px;"></video> | <video src="https://user-images.githubusercontent.com/266376/113240801-988e0400-92d7-11eb-860d-6c0faa70a1dd.mp4" data-canonical-src="https://user-images.githubusercontent.com/266376/113240801-988e0400-92d7-11eb-860d-6c0faa70a1dd.mp4" controls="controls" muted="muted" class="d-block rounded-bottom-2 width-fit" style="max-height:640px;"></video> | <video src="https://user-images.githubusercontent.com/266376/113239770-9cb92200-92d5-11eb-94ae-01299b7a388e.mp4" data-canonical-src="https://user-images.githubusercontent.com/266376/113239770-9cb92200-92d5-11eb-94ae-01299b7a388e.mp4" controls="controls" muted="muted" class="d-block rounded-bottom-2 width-fit" style="max-height:640px;"></video>

2021-04-01 04:54 UTC, anitaa1990 approved these changes
This works great @hafizrahman :shipit: I'm good to merge this PR once the fluxC PR has been merged and the hash has been updated in this PR

2021-04-01 09:44 UTC, hafizrahman commented
> I'm good to merge this PR once the fluxC PR has been merged and the hash has been updated in this PR

Thank you! This PR [already has the updated hash](https://github.com/woocommerce/woocommerce-android/pull/3737/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R85).

2021-04-01 12:24 UTC, anitaa1990 commented
> Thank you! This PR already has the updated hash.

Ah, I meant the hash once the fluxC PR has been merged to `develop`. We need to update that hash in this PR before merging this one.

2021-04-01 12:25 UTC, anitaa1990 commented
Also closing this one since this PR also includes the saame details as this PR and both are getting merged into `develop` anyway 😄

2021-04-01 12:25 UTC, closed without merging