ContinuationWrapper
woocommerce/woocommerce-android pull request #3773
Opened 2021-03-31 10:09 UTC by 0nko

A possible remedy for fixing some of the coroutine continuation woes.

2021-04-09 14:11 UTC, nbradbury approved these changes
@0nko This looks good to me, but on Slack I've asked someone with more coroutine experience to also take a look.

2021-04-09 15:18 UTC, malinajirka requested changes
Thanks @0nko! It looks good to me overall - I have left a few questions/suggestions, let me know what you think. 

Also I think it'd be really good to introduce tests for this new class, since it'll be used throughout the codebase. Wdyt?

2021-04-09 15:18 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt
> +            this.timeout = timeout
🔍  Nitpick: We might want to consider removing this method and adding a default `timeout = 0` parameter to `callAndWait`. We wouldn't need to store `timeout` in a field and we wouldn't need to use lock for this scenario. 

Option 2: If you introduced it because of the `AppConstants.REQUEST_TIMEOUT`, I'd consider creating an additional method instead of removing this one.

```
suspend fun callAndWaitUntilTimeout(
        timeout: Long = AppConstants.REQUEST_TIMEOUT,
        asyncAction: () -> Unit
    ): ContinuationResult<T> {
           callAndWait(asyncAction, timeout)
    }
    
suspend fun callAndWait(asyncAction: () -> Unit): ContinuationResult<T> {
                   callAndWait(asyncAction, 0)
}
   
private fun callAndWait(asyncAction: () -> Unit, timeout: Long) { ... }
```

Wdyt?

2021-04-09 15:18 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt
> +            continuation = null
We might want to consider wrapping this line with `finally` block to make sure we clear the field even if the coroutine throws an unhandled exception, wdyt?
`+` we could remove `result` and return the whole `try/catch` after this change.

2021-04-09 15:18 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaPickerRepository.kt
> +            canLoadMoreMedia = event.canLoadMore
⚠️  I'm not sure if it's intended or if it matters, but this code slightly changes the current behavior. Consider the following scenario:
1. We start the job
2. It times out
3. onMediaListFetched gets invoked
4. we update `canLoadMoreMedia` but since "loadContinuation.continueWith(true)" doesn't do anything after timeout, the result is ignored. 

Is it ok, that we update `canLoadMoreMedia` even when the OnMediaListFetched event was ignored?

2021-04-12 11:10 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt
> +            this.timeout = timeout
That's what I had initially but after @nbradbury's suggestion I added the timeout method with a default REQUEST_TIMEOUT interval. Option 2 makes sense 👍.

2021-04-12 11:15 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt
> +            continuation = null
Great point!

2021-04-12 11:33 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaPickerRepository.kt
> +            canLoadMoreMedia = event.canLoadMore
I've added a way to check if a continuation is still active and updated the handler to use it.

2021-04-12 14:50 UTC, malinajirka reviewed
Thanks @0nko! I've left one more question/suggestions - these types of synchronization issues are always tricky. Perhaps, I'm overthinking this. Let me know what you think.

2021-04-12 14:50 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt
> +            continuation?.cancel()
❓ Since this block is not synchronized (wrapped in mutex) anymore, I'm wondering if it'll work as expected. AFAIU `cancel` is not a synchronous operation -> what if we reach `continuation = it` sooner than the previous coroutine gets canceled and when it gets canceled it sets `continuation = null` in the finally block. We'd lose reference to the current `continuation` in such scenario. Do you think it could happen?

1. Coroutine A starts and sets continuation to ACont
2. Coroutine B invokes ACont.cancel and sets continuation to BCont
3. A is canceled sets continuation to null (it override BCont to null 💥) 

----------------------------

I'm wondering if the following code would work, wdyt?
```
        continuation?.cancel()
        mutex.withLock {
            return try { ... } finally { ...} 
         }
```

2021-04-12 15:04 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt
> +            continuation?.cancel()
You're right. I've removed the mutex as per your previous suggestion but it's still required. It's back now and it should address the scenario above.

2021-04-12 15:14 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt
> +            continuation?.cancel()
Ohh, sorry for the confusion. I wasn't suggesting we should remove it here - I was suggesting that we wouldn't need it to protect "this.timeout = timeout".  Thanks for the fix!

2021-04-12 15:16 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt
> +            continuation?.cancel()
@0nko I think we need to move "continuation.cancel()" outside of the lock, wdyt?

2021-04-12 21:52 UTC, malinajirka approved these changes
Thanks for all the improvements ;). LGTM

2021-04-12 21:52 UTC, merged