Empty states design updates
woocommerce/woocommerce-android pull request #3879
Opened 2021-04-21 09:18 UTC by hafizrahman

This is to fix #3678.

Here are the list of items being worked on in this PR. The items in parenthesis are the values used in the code.

### Empty State Screen in Light Mode
- [x] Background: Gray 0 (`@color/woo_gray_0` which translates to `#F6F7F7`)
- [x] Headline: Headline 6 (`@style/TextAppearance.Woo.Headline6`)
- [x] Body: Body 1 (`@style/TextAppearance.Woo.Body1`)
- [x] Button width: 197 x 36px (`@dimen/empty_states_button_width`)
### Not a WordPress site:
- [x] Vertical padding 42px (`@dimen/major_300`) 
- [x] Body: Body 1 (`@style/TextAppearance.Woo.Body1`)
### Site needs Jetpack screen:
- [x] Vertically center the main content.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-04-28 07:05 UTC, adamzelinski commented
Hey, @hafizrahman these are looking great however, some of the body copy looks a little small to me. Do you think you'd be able to double-check these, please? Also the pink used looks a little different (not sure if it's just the screenshots) we use Pink 50 for our primary buttons in light and Pink 30 when in dark mode.

Cheers!

<img width="1878" alt="Screen Shot 2021-04-28 at 5 03 04 pm" src="https://user-images.githubusercontent.com/74938219/116360862-b2bdf200-a843-11eb-99b6-6c1a85235776.png">

2021-04-28 07:11 UTC, anitaa1990 requested changes

2021-04-28 07:11 UTC, anitaa1990 commented on WooCommerce/src/main/res/layout/fragment_login_jetpack_required.xml
> +                android:id="@+id/msg_wrapper"
I don't know if we want to wrap the images and text in a `LinearLayout`. The idea of using a `ConstraintLayout` is to ensure that there is a flat hierarchy. If you're looking to vertically align the image and text in the screen, you can change the value of `layout_constraintVertical_bias=0.7` in the `jetpack_required_msg`. That would achieve the same effect.

#### Before
<img src="https://user-images.githubusercontent.com/22608780/116354120-960ac580-a815-11eb-8109-b5e426a102dc.png" width="300"/>


#### After
<img src="https://user-images.githubusercontent.com/22608780/116354144-9b681000-a815-11eb-877e-332086e30a67.png" width="300"/>

2021-04-28 09:21 UTC, anitaa1990 commented on WooCommerce/src/main/res/layout/wc_empty_view.xml
> +            android:layout_width="@dimen/empty_state_button_width"
I don't think we want to set a fixed width to the button. If we want to increase the size of the button, we could always set the width to `match_parent` and add margins.

I tried playing around with the button width and adding the following changes to the `xml` file, gave me the same results. WDYT?
```
        <com.google.android.material.button.MaterialButton
            android:id="@+id/empty_view_button"
            style="@style/Woo.Button.Colored"
            android:layout_marginStart="@dimen/major_300"
            android:layout_marginEnd="@dimen/major_300"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="0dp"
            android:layout_marginBottom="@dimen/major_200"
            android:text="@string/share_store_button" />
```

2021-04-30 06:45 UTC, hafizrahman commented
Thank you for the reviews!

## Re: Button colors:

**Button color:**  The button currently uses `android:color="@color/color_secondary"` [declared here](https://github.com/woocommerce/woocommerce-android/blob/0821552ebc66e4f352c00e8046382979731e72d2/WooCommerce/src/main/res/color/button_colored_bg_selector.xml#L8), and `color_secondary` itself is defined as:
- **Light mode**: `<color name="color_secondary">@color/woo_pink_50</color>` ([values/colors_base.xml](https://github.com/woocommerce/woocommerce-android/blob/0821552ebc66e4f352c00e8046382979731e72d2/WooCommerce/src/main/res/values/colors_base.xml#L9))
- **Dark mode**: `<color name="color_secondary">@color/woo_pink_30</color>` ([values-night/colors_base.xml](https://github.com/woocommerce/woocommerce-android/blob/0821552ebc66e4f352c00e8046382979731e72d2/WooCommerce/src/main/res/values-night/colors_base.xml#L9))

Or in other words, they're already set as Pink 50 in light mode and Pink 30 in dark mode 🤔 
This issue seems specific to how screenshots are created from my test device (Samsung S21).

I tested this again in an emulator and the color looks correct:

![image](https://user-images.githubusercontent.com/266376/116658306-f5093f80-a9b9-11eb-8f35-749ffd69f2f9.png)

@anitaa1990 I wonder if you can help check the above and see what the color looks like in your device(s)?

2021-05-21 05:12 UTC, anitaa1990 approved these changes
LGTM :shipit:

2021-05-21 05:12 UTC, merged