Replace FAB with empty state button on Empty Product screen.
woocommerce/woocommerce-android pull request #3882
Opened 2021-04-21 10:24 UTC by hafizrahman

To fix #3712

## What this PR does:
Replaces the FAB on empty product screen with the default button that the empty view layout has.

|Before | After |
|-|-|
| ![image](https://user-images.githubusercontent.com/266376/115538734-649a7300-a2c6-11eb-96c1-1095d92345c5.png) | ![image](https://user-images.githubusercontent.com/266376/115538121-c1e1f480-a2c5-11eb-9b0d-74f50ce9e4b0.png) |

## Testing instruction:
1. Use a site with zero products in it.
2. Go to "Products" tab in the app.
3. Make sure that you're seeing layout similar to the "After" screenshot above.
4. Tap the "Add product" button and make sure adding products work normally as before.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-04-26 14:05 UTC, hichamboushaba requested changes
The change works as expected 👍, but having the logic in the View is not recommended, as we can't test it, and it's not its responsibility, I left a comment suggesting how we can improve this 🙂

2021-04-26 14:05 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
> +    }
Instead of exposing a function to hide the add product, and having to control the ViewModel from the View, we should make the ViewModel responsible of the logic, and the view as dumb as possible.
We can do this by setting `isAddProductButtonVisible` to false in the appropriate places where `isEmptyViewVisible` is set to `true` in the viewmodel, and the two places I see are https://github.com/woocommerce/woocommerce-android/blob/71ce26ceb5a40d482d4b638196d4cf7c817afde3/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt#L189-L192 and https://github.com/woocommerce/woocommerce-android/blob/71ce26ceb5a40d482d4b638196d4cf7c817afde3/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt#L266-L277
You should be able to make this by verifying the search state, and wether the products list is empty or not, and the set the correct value to `isAddProductButtonVisible`.

2021-04-27 07:18 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
> +    }
Thanks! That's very clever. I've updated the code to update `isAddProductButtonVisible` in the right places instead.

2021-04-27 08:52 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
> +    }
Thanks for addressing it, but from my testing, it seems the FAB button is being hidden also for the empty search view: 
![Screenshot_1619513320](https://user-images.githubusercontent.com/1657201/116213519-65535f00-a735-11eb-8f9a-dacc16652a1a.png)
I think you should confirm that the user is not searching, nor filtering before hiding it, you can do so by checking the `query` and `productFilterOptions`.

2021-04-27 09:29 UTC, hafizrahman commented
This is now ready to review again 🙌  @hichamboushaba Thanks in advance!

2021-04-27 10:30 UTC, hichamboushaba commented
Thanks @hafizrahman, please check my comment: https://github.com/woocommerce/woocommerce-android/pull/3882#discussion_r621000778

2021-04-29 09:32 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
> +    }
> it seems the FAB button is being hidden also for the empty search view:

Thank you for that, at the beginning I hadn't considered that this is affecting search result screen as well.

As I worked on this, I found that there are several cases involved, so I'm adding a **"Testing instruction part 2:"** section on [the first post](https://github.com/woocommerce/woocommerce-android/pull/3882#issue-620072711) to deal with the searching/filtering situation.

This is now ready for another review, please have a look at the testing instruction above for more details. Thanks!

2021-04-29 10:53 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
> +        viewState = viewState.copy(query = query, isEmptyViewVisible = false, isAddProductButtonVisible = true)
@hafizrahman can you explain why you had to add this? during my testing, this is causing an issue:
<img width=400 src="https://user-images.githubusercontent.com/1657201/116539795-d97a3800-a8d8-11eb-8ab2-42fc871e8261.gif"/>
As you can see, when the search is still loading, changing the query text would cause the add button to be shown on top of the skeleton.

2021-04-29 11:06 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
> +            }
Nice, but IMO we can simplify further like this:
```suggestion
        val shouldShowAddProductButton = _productList.value?.isNotEmpty() == true ||
            viewState.query?.isNotEmpty() == true ||
            productFilterOptions.isNotEmpty()
```
WDYT?

2021-04-29 12:55 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
> +        viewState = viewState.copy(query = query, isEmptyViewVisible = false, isAddProductButtonVisible = true)
Ah, nice catch! I tried mimicking the original behavior prior to this change, but I missed testing the case of changing existing query while it's still loading. I also incorrectly assumed that the code I added would make the button appear after search is done. 

I'll remove it.

2021-04-29 13:08 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
> +            }
Thanks for the feedback. My main concern when writing that is that the conditionals here are not super intuitive ("hide button on empty view, but not if empty view is from search result", etc). I worried that in the future if I come back to this code, they will be hard to understand. So my goal is to make the if/else structure mimic the comment I wrote above it. It's more verbose but hopefully easier to follow.

I like the brevity in your proposed code, but from my beginner perspective, it takes me longer to follow and figure out what's happening. I'd like to keep the original code if possible. What do you think?

2021-04-29 13:19 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
> +            }
Regarding your remark, when it comes to chained conditions, they are not hard to understand if you follow the logic, for example in our case, as it's an `or` relation, you just need to pick each condition, and then go to the next if it's false:
1. If the product list is not empty, show the add, else check 2.
2. if the search query is not null, show the add button, else check 3.
3. if the product filters is not empty, show the add button, otherwise hide it.
That's how I like to think about them 🙂.
But I'm not against keeping your version 🙂 , just if you do please remove the unneeded curly braces, as they are just noise in this case, I mean change it to something like this:
```kotlin
val shouldShowAddProductButton =
            if (_productList.value?.isEmpty() == true) {
                when {
                    viewState.query != null -> true
                    productFilterOptions.isNotEmpty() -> true
                    else -> false
                }
            } else {
                true
            }
```
And sorry for the many comments on the PR, it's helping us all learn from each other 🙂

2021-04-29 13:30 UTC, hichamboushaba approved these changes
Nice work on this @hafizrahman 
Feel free to merge this after checking my last [comment](https://github.com/woocommerce/woocommerce-android/pull/3882/files#r623044425)

2021-04-30 04:28 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt
> +            }
> And sorry for the many comments on the PR, it's helping us all learn from each other 🙂

No, no, don't be sorry at all :) I do appreciate and even need these sort of comments so I can learn further.

I agree with the braces, have removed them.

2021-04-30 05:05 UTC, merged