Updates the release toolkit version
woocommerce/woocommerce-android pull request #3914
Opened 2021-04-27 04:29 UTC by JavonDavis

Updates the release toolkit version to the release branch, once https://github.com/wordpress-mobile/release-toolkit/pull/239 is merged, this will be updated to the `0.17.2` tag. 

To test: The majority of the changes here are already tested and present in develop via the `android/translations` branch but additional testing can be done via the `download_translations` lane. 

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-04-27 17:54 UTC, AliSoftware commented
💡  This PR will likely supersede the https://github.com/woocommerce/woocommerce-android/pull/3821 draft I made to test the action back in the day, so feel free to close 3821 once your PR here is approved and merged.

2021-04-27 17:57 UTC, AliSoftware commented on fastlane/Fastfile
>    desc "Get a list of pull request from `start_tag` to the current state"
The lane description needs to be updated too to match the new options (`milestone` instead of `start_tag`)

2021-04-28 20:17 UTC, AliSoftware requested changes
Additional feedback (previous pending feedback still apply).

You might also need to rebase this PR on top of `develop` now that https://github.com/woocommerce/woocommerce-android/pull/3785 has been merged to get rid of the odd fact that GitHub seems to still include the diff and changes from that other PR (even if those changes have now landed in `develop`) in the diff of this one…

2021-04-28 20:17 UTC, AliSoftware commented on .circleci/config.yml
> +
I'm unsure why this PR contains the commits and changes about the trigger of CI via API calls, while those should already be in `develop` since https://github.com/woocommerce/woocommerce-android/pull/3785 has been merged now 🤔  Somethings feels odd about this (maybe a GitHub glitch?!)

2021-04-28 20:17 UTC, AliSoftware commented on fastlane/Fastfile
> +    end
Fix indentation, remove "Adapt…" comment, add a `desc` to the lane

```suggestion
  #####################################################################################
  # download_translations
  # -----------------------------------------------------------------------------------
  # This lane download the string translations from GlotPress
  # -----------------------------------------------------------------------------------
  # Usage:
  # bundle exec fastlane download_translations
  #####################################################################################
  desc "Download the latest app translations from GlotPress and update the strings.xml files accordingly"
  lane :download_translations do |options|
    android_download_translations(
      res_dir: File.join(ENV['PROJECT_NAME'], 'src', 'main', 'res'),
      glotpress_url: 'https://translate.wordpress.com/projects/woocommerce/woocommerce-android/',
      locales: SUPPORTED_LOCALES,
      lint_task: 'lintVanillaRelease'
    )
  end
```

2021-04-28 20:17 UTC, AliSoftware commented on fastlane/Fastfile
>  ENV["validate_translations"]="lintVanillaRelease"
```suggestion
```

2021-04-28 20:17 UTC, AliSoftware commented on fastlane/Fastfile
>      ) unless hotfix
You can just call the other lane from line 187 here: `download_translations(options) unless hotfix`

2021-04-28 20:17 UTC, AliSoftware commented on fastlane/Pluginfile
> +gem 'fastlane-plugin-wpmreleasetoolkit', git: 'https://github.com/wordpress-mobile/release-toolkit', branch: 'release/0.17.2'
We're ready now! 🎉 
```suggestion
gem 'fastlane-plugin-wpmreleasetoolkit', git: 'https://github.com/wordpress-mobile/release-toolkit', tag: '0.18.0'
```

2021-04-30 04:15 UTC, JavonDavis commented on fastlane/Fastfile
>      ) unless hotfix
👍

2021-04-30 04:15 UTC, JavonDavis commented on fastlane/Pluginfile
> +gem 'fastlane-plugin-wpmreleasetoolkit', git: 'https://github.com/wordpress-mobile/release-toolkit', branch: 'release/0.17.2'
🎉

2021-04-30 04:18 UTC, JavonDavis commented on .circleci/config.yml
> +
Github has been being weird for me lately!

2021-04-30 04:37 UTC, JavonDavis commented on .circleci/config.yml
> +
Cleaned this up with `git checkout develop -- .circleci/config.yml`

2021-04-30 13:24 UTC, AliSoftware requested changes
You apparently forgot to delete the `tools/exported-language-tools.csv` and `tools/update-translations.sh` files to clean things up 😉 

While you're at it, even if that's unrelated to this PR, I'm pretty sure you can also remove `tools/release-notes-language-codes.csv` and `get-translated-release-notes.sh` too.

(Also, merging `develop` back to this branch before merging might help GitHub getting less confused 🙃 )

2021-04-30 13:24 UTC, AliSoftware commented on fastlane/Fastfile
> +   lane :trigger_release_build do | options |
GitHub showing an unrelated change in the diff again… 😒 
Maybe you cut the branch for this PR _before_ this change landed in `develop`… and that's what confusing GitHub? (even though I would have expected it to be more clever and figure that out in the diff)

Maybe merging `develop` back into this PR to resync stuff could help GitHub be less confused on that diff?

2021-04-30 13:24 UTC, AliSoftware commented on fastlane/Fastfile
>  SUPPORTED_LOCALES = [
I double-checked by comparing that list with `tools/exported-language-codes.csv` and they seem to match, so all good there 👍

2021-04-30 13:28 UTC, AliSoftware commented
Mmmmh tested by switching to this branch and running `bundle exec fastlane download_translations` and got `[!] Syntax error in your Fastfile on line 530: Fastfile:530: syntax error, unexpected end, expecting end-of-input`. There's probably a `end` missing somewhere in the middle of the Fastfile (in some random line before 530) that we forgot to close 🤔

2021-04-30 13:34 UTC, AliSoftware commented on fastlane/Fastfile
> +  desc "Get a list of pull request from the `milestone`
Ah! After more scrutiny I found the syntax error that leads to that `[!] Syntax error in your Fastfile on line 530: Fastfile:530: syntax error, unexpected end, expecting end-of-input`: a missing closing quote! Sneaky!

```suggestion
  desc "Get a list of pull request from the `milestone`"
```

2021-04-30 16:40 UTC, AliSoftware approved these changes
LGTM! :shipit:

2021-04-30 16:40 UTC, AliSoftware commented on fastlane/Fastfile
> +  desc "Get a list of pull request from the `milestone`"
```suggestion
  desc "Get a list of pull requests from the `milestone`"
```

2021-04-30 16:40 UTC, AliSoftware commented on fastlane/Fastfile
> +  # This lane download the string translations from GlotPress
```suggestion
  # This lane downloads the string translations from GlotPress
```

2021-04-30 16:50 UTC, merged