Allow Re-creating Shipping Label
woocommerce/woocommerce-android pull request #3961
Opened 2021-05-04 08:36 UTC by hafizrahman

To fix #3856

## What this PR does
Allow user to re-purchase Shipping Label on the same Order, and modify the Order Details screen's design to accommodate it.

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-05-05 07:32 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
> +            isProductListMenuVisible = shippingLabels.isVisible
Previously I used `areShippingLabelsVisible` as checker for displaying/hiding the Products list menu button. However, I found that it made it not super obvious for unit testing it. So while this is a bit redundant (i.e.: `isProductListMenuVisible` will always have the same value as `areShippingLabelsVisible`), it helps make it be more obvious during example, like so:

```
            assertThat(shippingLabels).isNotEmpty
            assertThat(isCreateShippingLabelButtonVisible).isFalse()
            assertThat(isProductListMenuVisible).isTrue()
```

2021-05-05 13:22 UTC, hichamboushaba requested changes
Really great job @hafizrahman 👏 
I left some comments about the usage of the `Woo.Card.ExpanderButton` style, as it's not matching the mockups, and some other small tips.

2021-05-05 13:22 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
> +        val isProductListMenuVisible: Boolean? = null
It's nice to have a an explicit variable about this as you said in https://github.com/woocommerce/woocommerce-android/pull/3961/files#r626326768, I like it.
But as its value is always same as `areShippingLabelsVisible`, we can simplify the logic a bit, and avoid any unwanted bugs (for example changing `isProductListMenuVisible` in some other areas of the viewmodel) by making it a [property without a backing field](https://kotlinlang.org/docs/properties.html#backing-fields), similar to the below property `isMarkOrderCompleteButtonVisible`, we can do this like this:
```kotlin
val isProductListMenuVisible: Boolean?
      get() = areShippingLabelsVisible
```

2021-05-05 13:22 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/adapter/OrderDetailShippingLabelsAdapter.kt
> +                    WooAnimUtils.fadeOut(viewBinding.shippingLabelListProducts)
Normally we should [avoid](https://softwareengineering.stackexchange.com/a/16530) using single-line statement if blocks without braces, so either move the statement to the same line:
```kotlin
if (isChecked) WooAnimUtils.fadeIn(viewBinding.shippingLabelListProducts)
else WooAnimUtils.fadeOut(viewBinding.shippingLabelListProducts)
```
or add curly braces to those statements.

2021-05-05 13:22 UTC, hichamboushaba commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="orderdetail_products_more_button">Create new shipping label</string>
np, I think in our last session we were planning to rename this string resource to something more meaningful, and that this was temporary 🤔, can you please rename it to something like `orderdetail_products_recreate_label_button`

2021-05-05 13:22 UTC, hichamboushaba commented on WooCommerce/src/main/res/layout/order_detail_shipping_label_list_item.xml
> +            android:paddingBottom="@dimen/major_85" />
I don't think we can use the style `Woo.Card.ExpanderButton` here, as the arrow image there uses a smaller size 12dp, while in the designs we have 24dp, and also the color is different.
I think you can achieve similar effect using the same technique as the button `shippingLabelItem_viewMoreButtonTitle` below, and with more customizability.

2021-05-06 04:16 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
> +        val isProductListMenuVisible: Boolean? = null
Thank you, that's a great tips!

2021-05-06 09:26 UTC, hafizrahman commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="orderdetail_products_more_button">Create new shipping label</string>
Thanks for reminding me! I missed this part.

2021-05-06 09:26 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/adapter/OrderDetailShippingLabelsAdapter.kt
> +                    WooAnimUtils.fadeOut(viewBinding.shippingLabelListProducts)
Awesome, learned something new here. Thanks.

2021-05-06 10:21 UTC, hafizrahman commented on WooCommerce/src/main/res/layout/order_detail_shipping_label_list_item.xml
> +            android:paddingBottom="@dimen/major_85" />
Nice attention to details, I didn't realize the button size and behavior are different. I've refactored this to be something similar to `shippingLabelItem_viewMoreButtonTitle` instead.

2021-05-06 10:22 UTC, hafizrahman commented
Thanks for your feedbacks @hichamboushaba . This is now ready for another review.

2021-05-06 14:32 UTC, hichamboushaba approved these changes
Really good job @hafizrahman, looks good to me :shipit:

2021-05-06 14:32 UTC, merged