Issue/3725 implement connect UI flow
woocommerce/woocommerce-android pull request #3969
Opened 2021-05-05 20:30 UTC by malinajirka

Parent issue #3725 

Merge instructions:
1. Make sure https://github.com/woocommerce/woocommerce-android/pull/3968 is merged
2. Remove "Do not merge" label
3. Merge this PR

This PR implements happy path for "Connect to reader" flow.

Known issue (coming in upcoming PRs):
- Errors are not implemented -> the flow dialog just gets dismissed + an error is logged
- Only the first found reader is presented to the user -> other readers are ignored
- When a reader is found it's name is not shown on the UI yet
- When a connection is successfully established the dialog gets dismissed -> clicking on "Connect" button again results in an error since a reader is already connected

To test - Only simulated reader is supported at the moment
1. Open app settings
2. Tap on "Manage card reader"
3. Tap on "Redirect to CardDetailFragment"
4. Tap on "Connect"
5. Notice "Scanning for readers" dialog is shown
6. Notice "Reader found" dialog is shown
7. Tap on "Cancel" and notice the dialog gets dismissed
8. Tap on "Connect"
5. Notice "Scanning for readers" dialog is shown
6. Notice "Reader found" dialog is shown
7. Tap on "Connect to reader"
8. Notice "Connecting dialog" is shown for a moment and than the flow gets dismissed

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-05-11 15:39 UTC, hichamboushaba requested changes
Nice job 👏, I left some comments in the code.

2021-05-11 15:39 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +        viewModelScope.launch {
You don't need to explicitly state `viewModelScope`, you can simplify it to just `launch`

2021-05-11 15:39 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +        appLogWrapper.e(T.MAIN, "Connection flow interrupted by the user.")
I believe it's best to use `WooLog` here, to append those entries to the app's logs, and help investigate any issues reported by users later, WDYT?

2021-05-11 15:39 UTC, hichamboushaba commented on WooCommerce/src/main/res/layout/fragment_card_reader_connect.xml
> +</LinearLayout>
I believe there is more spacing between the buttons than the mockups:

<img width="331" alt="Screen Shot 2021-05-11 at 15 29 38" src="https://user-images.githubusercontent.com/1657201/117843569-742a2d80-b26e-11eb-913e-4759dd200599.png"> <img width="325" alt="Screen Shot 2021-05-11 at 15 29 14" src="https://user-images.githubusercontent.com/1657201/117843581-768c8780-b26e-11eb-882c-a0c633eacdd5.png">

I also noticed that the header's color is different, I believe you need `color_on_surface_high` and not the one used in the style `color_on_surface_medium`.

2021-05-11 18:34 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +        viewModelScope.launch {
Good catch ! ;) Fixed in 8c7ff8c0a9bc7367bca3d99c60d8fc70e15c24bf

I implemented it before ScopedViewModel got updated to use `viewModelScope` under the hood.

2021-05-11 18:35 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +        appLogWrapper.e(T.MAIN, "Connection flow interrupted by the user.")
Wow great catch - I didn't realize that WooLog is not the same thing as AppLog! Since I'm using AppLog all over the place, I'll update all the usages in a different PR - I added a task to [this ticket](https://github.com/woocommerce/woocommerce-android/issues/3724). Does that sound ok or would you prefer me to fix this usage in this PR?

2021-05-11 18:38 UTC, malinajirka commented on WooCommerce/src/main/res/layout/fragment_card_reader_connect.xml
> +</LinearLayout>
Good eye! ;) Some of the designs aren't up to date (even in Figma) and they are not 100% finalized. I have a "polish UI" task in the backlog and plan to fix all these UI/Style issues later.

2021-05-11 18:38 UTC, malinajirka commented on WooCommerce/src/main/res/layout/fragment_card_reader_connect.xml
> +</LinearLayout>
I'm sorry I didn't mention this in the PR instructions :(.

2021-05-11 18:58 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +        appLogWrapper.e(T.MAIN, "Connection flow interrupted by the user.")
OK for me 🙂

2021-05-11 18:59 UTC, hichamboushaba approved these changes
LGTM :shipit:

2021-05-11 19:00 UTC, merged

2021-05-12 09:58 UTC, wzieba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +        appLogWrapper.e(T.MAIN, "Connection flow interrupted by the user.")
Eventually, it shouldn't be any difference if I'm not mistaken. There's listener in `WooLog` that catches all logs from `AppLog` and saves it into the map. This is why we have all logs from `FluxC` saved in `WooLog#logEntries`.

https://github.com/woocommerce/woocommerce-android/blob/develop/WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt#L50-L52

2021-05-12 10:03 UTC, wzieba commented on WooCommerce/src/main/res/layout/fragment_card_reader_connect.xml
> +</LinearLayout>
offtop: Sorry I can't resist. If you have any problems with "**polish** UI", feel free to ping me 😄

2021-05-12 11:46 UTC, malinajirka commented on WooCommerce/src/main/res/layout/fragment_card_reader_connect.xml
> +</LinearLayout>
It took me 2 seconds to get the joke, but it made me laugh hard 🤣

2021-05-12 12:46 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +        appLogWrapper.e(T.MAIN, "Connection flow interrupted by the user.")
Thanks for all the info and suggestions! 🙇