Enable variable product creation
woocommerce/woocommerce-android pull request #4024
Opened 2021-05-13 08:06 UTC by ThomazFB

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-05-17 00:12 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
> +        }
Since a Variable Product needs to also be existent at the site in order to make available any Attributes or Variations creating/editing, I decided to do what iOS does and submit the new Product to the site immediately after the creation request but flagged with the `Draft` status, this way all Variable Product modifications will be available, and the product will be published only after the merchant think it's done with the editing.

2021-05-17 00:12 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductHelper.kt
> +            status = if (productType == VARIABLE) DRAFT else PUBLISH,
Relates with https://github.com/woocommerce/woocommerce-android/pull/4024/files#r633160009

2021-05-17 09:54 UTC, ThomazFB commented
@AliSoftware I'm not sure if this PR will take too long to be merged since I only could place it for review today, but it would be really important following release 6.6 that this code goes in 6.7. In case it gets merged today, do you think there's still a time frame to do that or it's better to wait and target the branch for the `release/6.7` branch when available?

2021-05-17 09:59 UTC, AliSoftware commented
Thanks for the heads up.

I haven't yet started the code freeze for 6.7 so that gives us a little leeway. If it takes too long to get reviewed and merged, I can always cut the release branch but not yet create the first beta, then just edit this PR's target branch to the release/6.7 branch and wait for the merge before I issue the first beta.

Let's see how it goes. Don't hesitate to ping the team in Slack to get an expedite review of this PR ASAP.

2021-05-17 11:54 UTC, nbradbury commented
The user experience here could be better, and I think we should hold off merging this until our designers provide some input.

If you choose to create a new variable product you immediately see an "Updating product" progress dialog and then a "Product draft saved" snackbar, neither of which occur if you create a different product type, and these don't appear on iOS. It makes sense to us why these appear, but I think they would be confusing to our users. Perhaps not save the draft until the user chooses to create a variation, and do so silently?

Also, if the user backs out of the product detail because they chose to create a variable product by mistake, the product draft is still created and the user needs to delete it. This also doesn't happen on iOS.

And I noticed that if you choose to create a new variable product, then tap on "Add variations" and click "Done," you see a "Creating variation" dialog, and when you save changes and return to the product list, the product shows "1 variation." But if you then return to product detail it shows no variations for that variable product.

@Garance91540 @adamzelinski

2021-05-18 08:37 UTC, Garance91540 commented
Hi there, @ThomazFB , would it be possible to include a screencast of the flow to review in this PR (and in future PR in general)? It really speeds up the review for the designers. I'll try with the apk

2021-05-18 09:08 UTC, Garance91540 commented
Ok I was able to install and the APK and here's my review:

**Creating variation**

This is the designed flow when a user selects "create variable product" from the list:
<img width="728" alt="Screen Shot 2021-05-18 at 10 51 33 AM" src="https://user-images.githubusercontent.com/28450084/118621898-185c2900-b7c7-11eb-86b9-79f48ffc9628.png">

Creating a variable product should follow the same logic as creating any other product. With this in mind:
- Is it possible to remove the "updating product" dialog?
- Is it possible to remove the "Draft" tag and the snackbar "Product Draft Saved"? As Nick suggested, if it's necessary to create a draft product it would be better to do it silently so not to confuse users
- Can we remove the Title "Product"? The title field should display "Enter Product Title" as a default placeholder until the product title is added
- The "Publish" CTA should appear on the top navbar as soon as the product is created (I see when I make changes that the "Update" CTA appears)

For the rest of the flow, I flagged some issues [here](https://apptestingo2.wordpress.com/2021/05/05/to-test-woocommerce-android-6-6/#comment-8146). Is it possible to request a review again when these issues are addressed so I can review them again? Thanks!

2021-05-18 12:50 UTC, ThomazFB commented
Hey @Garance91540, thanks for your contribution and feedback, sure! I'll make sure to request a review from the `mobile-designers` for any of these key changes, and I'll add a detailed capture of the screen from now on.

About your suggestions, I'll come back here and let you and @nbradbury know when it's done. Thanks!

2021-05-27 11:47 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
> +                viewModel.storeSilentlyWhenNewVariableProduct()
Since a Variable Product needs to also be existent at the site in order to make available any Attributes or Variations creating/editing, I decided to submit the new Product to the site immediately after the creation request but flagged with the Draft status, this way all Variable Product modifications will be available, and the product will be published only after the merchant think it's done with the editing.

I'll deliver in an upcoming PR a bigger change that allows us to fully manage Attributes and Variations without having to post the product before hand, so we can at least enable the Variable Product creation right away.

2021-05-27 13:11 UTC, ThomazFB commented
Hey @Garance91540 and @nbradbury, the PR is ready for another round, sorry for the long time to come back here but it took me a lot of thinking about how to approach these changes without affecting the Product Details view too much

I've covered all your suggestions, but it's worth mentioning this explanation that I've added to the PR description:
>Since a Variable Product needs to also be existent at the site in order to make available any Attributes or Variations creating/editing, I decided to submit the new Product to the site immediately after the creation request but flagged with the Draft status, this way all Variable Product modifications will be available, and the product will be published only after the merchant think it's done with the editing. 
I'll deliver in an upcoming PR a bigger change that allows us to fully manage Attributes and Variations without having to post the product beforehand, so we can at least enable the Variable Product creation right away.

And here's the current creation flow capture:



https://user-images.githubusercontent.com/5920403/119831587-ceb0c400-bed3-11eb-8f80-94da9b04151a.mp4

2021-05-27 16:11 UTC, nbradbury commented
@ThomazFB - I'm seeing a Done button in the "Add Attribute" screen. We don't show that when editing an existing variation. Shouldn't that be dropped, since it was decided we wouldn't require the user to keep tapping Done through the variation flow?

2021-05-27 16:16 UTC, nbradbury commented
If I chose to create a variable product and tap Add variations in the detail screen, then chose to back out of adding a variation and back out of product detail, a draft product is still created even though I never chose to publish the product.

Is there some way we can avoid this?

2021-05-27 16:21 UTC, nbradbury commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
> +    fun storeSilentlyWhenNewVariableProduct() = launch {
This `fun` needs a comment explaining its purpose, and maybe a more descriptive name. Perhaps `saveAsDraftIfNewVariableProduct`?

2021-05-27 16:36 UTC, nbradbury commented
@ThomazFB I'm finished with my first round. Code looks good, just left a np about adding a comment.

I did find the screen transitions a bit jarring when the variable product is auto-generated, but I'll leave to @Garance91540 to say if we need to address that.

2021-05-28 08:39 UTC, Garance91540 requested changes
Hi @ThomazFB , I agree with Nick regarding the transitions: especially after the user selects "Variable product" in the bottom sheet, there's a different screen flashing (product list?) before we land on the new product page. Is it possible to open the new variable product page directly, with the ghost landing screen if needed? (instead of the different screen flashing)

For the rest of the screen transitions, is it possible to align the style to the rest of the screens?

I've noticed a lot of small UI fixes too, I reported them [here](https://apptestingo2.wordpress.com/2021/05/05/to-test-woocommerce-android-6-6/#comment-8146) before, will they be addressed in a separate PR?

Thank you! Getting so close 💪

2021-05-28 10:22 UTC, ThomazFB commented
Hey @Garance91540 and @nbradbury, thanks for the review! I'm unsure about the transition mentioned, not sure if I'm not detecting it or it's not happening at my device, here's the capture of how the bottom sheet is transitioning for every product type, do you mean that we shouldn't dismiss the sheet before calling the next view?

https://user-images.githubusercontent.com/5920403/119969103-86051380-bf84-11eb-86e1-8a2d70ba977c.mp4

>For the rest of the screen transitions, is it possible to align the style to the rest of the screens?

Not sure if I understood correctly @Garance91540, by aligning the transitions styles do you mean the forward and backward animations? Or it's something else that's misaligned?

>I've noticed some small UI fixes too, I reported them here before, will they be addressed in a separate PR?

Oh, I should've replied that earlier, sorry for that, G. I'm making available your suggestions in this PR that I'll be making available today: https://github.com/woocommerce/woocommerce-android/pull/4102

2021-05-28 11:08 UTC, ThomazFB commented
>I'm seeing a Done button in the "Add Attribute" screen. We don't show that when editing an existing variation. Shouldn't that be dropped, since it was decided we wouldn't require the user to keep tapping Done through the variation flow?

Hey @nbradbury, do you mean the done button when we're creating the first variation flow? Correct me if I'm wrong, but I think the expected change would be the `Attribute List` and the `Add Attribute Terms` to have the `next` button, and the last one, which is the `Add Attributes`, should show the `Done` button, to finally create the brand new Variation. But I'm tackling this change in this PR here: #4102, is that what you mean?

2021-05-28 11:09 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
> +    fun storeSilentlyWhenNewVariableProduct() = launch {
True! Thanks for that! Changed the method here: https://github.com/woocommerce/woocommerce-android/pull/4024/commits/aaeaf500ea889f6f589d2e15e01df42d18c026b1

2021-05-28 12:00 UTC, nbradbury commented
> do you mean the done button when we're creating the first variation flow? Correct me if I'm wrong, but I think the expected change would be the `Add Attributes` and the `Add Attribute Terms` to have the `next` button, and the last one, which is the `Attributes List`, should show the `Done` button

My understanding was that these buttons wouldn't appear anywhere in the flow, except for "Update" and "Publish" in the primary detail screen. The initial discussion was that requiring users to tap "Done" in every screen, and showing a discard dialog if they backed out, was overwhelming given the number of screens involved. So instead changes are automatically saved to the product draft.

@Garance91540 @adamzelinski I think the above could use some clarification/verification, since it seems to come up a lot.

2021-05-28 12:20 UTC, Garance91540 commented
Hi @nbradbury, by default there should be no "Done" button as you pointed out. But since the Variation flow has multiple steps, we decided to show a "Next" button in place of the "Done" button to notify merchants they need to select this CTA to continue. 

<img width="1481" alt="Screen Shot 2021-05-28 at 2 17 46 PM" src="https://user-images.githubusercontent.com/28450084/119982733-840c7600-bfbf-11eb-8150-a57dab62d06c.png">

The "Next" CTA only becomes enabled in the top nav when merchants have entered some input in the 
"Add Attributes" and "Add Options" screens

2021-05-31 09:45 UTC, AliSoftware commented
Code freeze for 6.8 happening today, so I'm moving the milestone to 6.9.

2021-06-10 18:01 UTC, shiki commented
>  I agree with Nick regarding the transitions: especially after the user selects "Variable product" in the bottom sheet, there's a different screen flashing (product list?) before we land on the new product page.

@Garance91540 @nbradbury Can you please help me understand this outstanding animation issue? I cannot tell the difference of what's changed. 

This is how the animation looks like in `develop`:


https://user-images.githubusercontent.com/198826/121573962-085cf100-c9e3-11eb-9869-f24e66e78bbf.mov

The bottom sheet is dismissed, the product list is visible for a moment, and then the new product page is shown. 

And this is the animation in this PR:


https://user-images.githubusercontent.com/198826/121574330-625db680-c9e3-11eb-90f9-b54ed6e0f455.mov

They seem to be the same as `develop`. 😬 

Would you mind sharing a video of the transition that you found to be undesirable? If it's the same as `develop`, could we perhaps tackle that separately instead of in this PR?

2021-06-10 20:54 UTC, nbradbury commented
@shiki Looks like there's been some confusion about the transitions. The ones I was referring to weren't related to creating the variable product, but instead to the auto-generation of a variation of a variable product. In that situation, I was seeing multiple screens slide in and out.

But I just tried it again on two devices and I'm no longer seeing that issue, so perhaps it was already addressed?

2021-06-11 14:30 UTC, shiki commented
@nbradbury Could have been fixed somewhere else since I merged `develop` in this branch. 🤷 🎉

2021-06-11 16:05 UTC, Garance91540 approved these changes
> Would you mind sharing a video of the transition that you found to be undesirable? If it's the same as develop, could we perhaps tackle that separately instead of in this PR?

Both videos you sent seem fine to me! So all good on my end 👯

2021-06-11 17:05 UTC, shiki commented
Thanks, @Garance91540! 

@nbradbury Would you mind reviewing this PR again and see if there's anything that should be addressed? I reserved some time next sprint to take care of this. Good chance for me to refresh on Android too. 😅

2021-06-11 17:14 UTC, nbradbury commented
@shiki Will do! I'm not sure I'll be able to get to it today, but I can get to it first thing next week.

2021-06-11 17:49 UTC, shiki commented
That's fine! Thank you.

2021-06-11 19:46 UTC, nbradbury approved these changes
Looks good! :shipit:

2021-06-11 19:46 UTC, merged