Issue/4011 change attributes navigation flow
woocommerce/woocommerce-android pull request #4102
Opened 2021-05-28 10:17 UTC by ThomazFB

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-06-03 04:32 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt
> -            numVariations == product.numVariations &&
The `numVariations` field is a count controlled by the site, and it's modified as Variations get deleted or created, this doesn't essentially change the Product entity, since Product and Variations are treated as separate models connected through remote ID mapping, using this field as a modification condition causes the UI to think that the Product was updated and requires an update, when actually if this field changed the update already happened.

With that said, I'm removing this field from the `isSameProduct` method to remove the bug where the `update` button show up at the `ProductDetailFragment` when it shouldn't.

2021-06-03 04:36 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListFragment.kt
> -
Since the `VariationListFragment` no longer have access to the Attributes view flow, I'm removing all code related to the menu item calling the `AddAttributeFragment` navigation route and moving this call to the ProductDetailFragment through the ProductDetailCardBuilder

2021-06-03 04:36 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
> +
Relates to this: https://github.com/woocommerce/woocommerce-android/pull/4102/files#r644477680

2021-06-03 04:40 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationRepository.kt
> +class VariationRepository @Inject constructor(
This repository owns behaviors related to Variations that must be available at other Variation-related viewModels, so I'm renaming it to a more wide Variation responsibility instead of being a repository made only for the `VariationListViewModel`

2021-06-03 06:58 UTC, ThomazFB commented
Hey @Garance91540, this PR delivers your last change proposal around Variations, let me know if this meets the intended objective.

2021-06-03 09:56 UTC, anitaa1990 reviewed
The code changes look good @ThomazFB! Nice work 🥇 I just left a few nitpicks in the code.

And had a few minor issues while testing:
 - The Next button is visible in Add Attribute and Add Attribute terms screen even when I haven't changed anything. Is that expected? The PR description says the button will only be displayed if there have been some changes to the screen.
<img src="https://user-images.githubusercontent.com/22608780/120626239-190be500-c480-11eb-966b-c30369357cb2.png" width="300"/>


- The click area of the `X` icon could be a bit bigger. From what I see in other image icons, we seem to be setting a fixed width and height of `image_major_50`. I'm not sure if that is the correct process to follow but it would be nice to increase that click area.
<img src="https://user-images.githubusercontent.com/22608780/120626193-0b565f80-c480-11eb-95de-643757cdb758.png" width="300"/>


- If the attribute terms are not clickable, it would be nice to remove the selectable background here. It feels misleading.
<img src="https://user-images.githubusercontent.com/22608780/120626056-ecf06400-c47f-11eb-9b64-b86c016b5832.png" width="300"/>

2021-06-03 09:56 UTC, anitaa1990 commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
> +                    resources.getString(string.product_variation_single_count)
np: We have a [method](https://github.com/woocommerce/woocommerce-android/blob/f58a86ae0a17c44a6102f6770c7032d53e539dbd/WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt#L71) in `StringUtils` that simplifies this if else condition. Example [here](https://github.com/woocommerce/woocommerce-android/blob/b86665115ee9066966a716e3952f860af2ee9622/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt#L183-L182). What do you think about using that?

2021-06-03 09:56 UTC, anitaa1990 commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt
> +            }
Nice <3

2021-06-03 22:26 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt
> +                    resources.getString(string.product_variation_single_count)
Hey Anitaa! Awesome suggestion, I wasn't aware of this function, good tip! I've added it here: 8ae10d8ff363398ddd626cb799595745f0130e01

2021-06-03 22:39 UTC, ThomazFB commented
Thank you so much for taking some of your time to review this PR, @anitaa1990. The PR is ready for a second round and I've submitted changes regarding your comments:

> The Next button is visible in Add Attribute and Add Attribute terms screen even when I haven't changed anything. Is that expected? The PR description says the button will only be displayed if there have been some changes to the screen.

Yes, this is expected! I did that intentionally. I decided to set the `Next` button visibility rule to consider if there are at least any Attribute properly configured to proceed with a Variation creation, I've done so because a Product can have the Attributes configured beforehand if it's not a new Variable Product scenario, so instead of forcing the merchant to do changes that aren't necessarily needed, they can just create the First variation with the current Product Attributes configuration.

In a scenario where the user is creating the Variable Product from scratch, since there will be no Attributes configured previously, then the `Next` button will appear only if there's any change done there and the scenario you described will be fulfilled. This behavior is also true for the `Done` button at `AttributeListFragment`, meanwhile, the `AddAttributeTermsFragment` `Next` button expects the selected Terms list to include at least one Term.

> The click area of the X icon could be a bit bigger. From what I see in other image icons, we seem to be setting a fixed width and height of image_major_50. I'm not sure if that is the correct process to follow but it would be nice to increase that click area.

I agree! I decided to use the borderless selection background to enable the click ripple to be a bit bigger and circular to follow the Android common behavior for this kind of icon button, here are the changes: acf330d6580bcc291dc35ffeec601ef0e289ce1f

>If the attribute terms are not clickable, it would be nice to remove the selectable background here. It feels misleading.

Good catch! I've fixed this here: d923d729067a79d3700a5bb01e929c8f14993c5c

Let me know what you think about these changes and thank you!

2021-06-04 07:24 UTC, Garance91540 requested changes
Hi Thomaz, nice work, here are my notes:

<img width="551" alt="Screen Shot 2021-06-04 at 8 56 42 AM" src="https://user-images.githubusercontent.com/28450084/120759003-cc251e80-c512-11eb-8921-8deed6cbd525.png">

<img width="638" alt="Screen Shot 2021-06-04 at 8 56 36 AM" src="https://user-images.githubusercontent.com/28450084/120759022-d21aff80-c512-11eb-93dd-f37a7a79ad27.png">

<img width="575" alt="Screen Shot 2021-06-04 at 8 59 09 AM" src="https://user-images.githubusercontent.com/28450084/120759268-2625e400-c513-11eb-8548-607f66694809.png">

<img width="845" alt="Screen Shot 2021-06-04 at 9 21 38 AM" src="https://user-images.githubusercontent.com/28450084/120762182-4905c780-c516-11eb-94c4-31b21c7079ad.png">

As per the convo on Slack, I also added this new feedback screen when users create their first variation

<img width="463" alt="Screen Shot 2021-06-04 at 9 23 34 AM" src="https://user-images.githubusercontent.com/28450084/120762447-8d916300-c516-11eb-9647-1ca81e760dca.png">

Let me know if you have questions

2021-06-04 10:18 UTC, anitaa1990 approved these changes
LGTM :shipit: Will wait till design review is addressed before merging!

2021-06-04 11:23 UTC, ThomazFB commented
Hey @Garance91540, Thanks for your feedback, I've uploaded some changes fixing your suggestions, here they are:

Fix 1
==========
![image](https://user-images.githubusercontent.com/5920403/120793257-0db2cb00-c50d-11eb-8907-16df83fd1bf5.png)

Fixed! Here's the result:
<img src="https://user-images.githubusercontent.com/5920403/120793367-2fac4d80-c50d-11eb-9df1-53e374a42615.png" width="540" height="1170" />

Fix 2
==========
![image](https://user-images.githubusercontent.com/5920403/120793478-4fdc0c80-c50d-11eb-8276-5d8820742052.png)

Fixed! Here's the result:
<img src="https://user-images.githubusercontent.com/5920403/120793523-5c606500-c50d-11eb-8c5e-7b22a60a61bc.png" width="540" height="1170" />

Fix 3
==========
![image](https://user-images.githubusercontent.com/5920403/120793840-caa52780-c50d-11eb-9bcb-346ad23f5a6f.png)

So, this one is getting addressed here on a dedicated PR: https://github.com/woocommerce/woocommerce-android/pull/4125

Comments
==========
I would like to suggest tackling the price warning and the new `Attributes created` view in a separate PR, since this one is becoming a large one and it's already fixing a lot of pre-existing views, would that be ok? @anitaa1990 @Garance91540

2021-06-04 14:21 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/MenuItemExt.kt
> +}
@ThomazFB I don't think we should do this for items individually, the issue @Garance91540 mentioned is impacting the whole app (check #3632).
IMO this shouldn't be fixed in this PR, nor blocking it, but should be fixed in a separate PR that fixes the whole app.

2021-06-04 16:22 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/MenuItemExt.kt
> +}
Thanks for this heads up @hichamboushaba, that's valuable information. I can remove this modification then and leave room for the centralized fix for the whole app. Is this ok for you @Garance91540 ?

2021-06-07 08:03 UTC, Garance91540 requested changes
Hi Thomaz, 

**Fix 1**
I noticed there was a weird padding between the helper text and the "Option name" text box (see Figma for exact padding height) https://d.pr/i/Fm23fp

**Fix 2**
As "Done" signals the end of the creation flow and users [still have one more step](https://d.pr/i/5UWVW7) to carry out before generating their variation in the latest designs, "Next" here is more intuitive 

> I would like to suggest tackling the price warning and the new Attributes created view in a separate PR, since this one is becoming a large one and it's already fixing a lot of pre-existing views, would that be ok? @anitaa1990 @Garance91540

No problem!

2021-06-07 16:20 UTC, shiki commented
Hi, @Garance91540! I'm taking over for Thomaz since he's AFK.

> Fix 2
As "Done" signals the end of the creation flow and users still have one more step to carry out before generating their variation in the latest designs, "Next" here is more intuitive

Done in bb718e1. Here's the before and after:

Before | After 
--------|-------
<img src="https://user-images.githubusercontent.com/198826/121054014-2cb59500-c779-11eb-9bb5-40a86b912bf6.png" width="300">       |       <img src="https://user-images.githubusercontent.com/198826/121054027-2f17ef00-c779-11eb-915d-a937da0274d1.png" width="300">

> Fix 1
I noticed there was a weird padding between the helper text and the "Option name" text box (see Figma for exact padding height) https://d.pr/i/Fm23fp

This one requires a structural change which could lead to a regression. Not to mention this PR is getting longer and we might lose some context along the way. 😅  I created a separate issue to tackle this. Is that okay? https://github.com/woocommerce/woocommerce-android/issues/4140

2021-06-07 21:01 UTC, shiki commented
@Garance91540 I created a separate PR for the padding: https://github.com/woocommerce/woocommerce-android/pull/4141

2021-06-09 12:23 UTC, Garance91540 approved these changes
Perfect, thanks! Totally ok to address the rest in a separate PR

2021-06-09 13:41 UTC, shiki commented
Thanks, Garance!

2021-06-09 13:41 UTC, merged