Shipping Labels: Finish Customs form
woocommerce/woocommerce-android pull request #4103
Opened 2021-05-28 15:33 UTC by hichamboushaba

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-05-31 17:04 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/model/CustomsPackage.kt
> +            weight = weight!!,
As we are validating the data on UI side, we can assume that this is not null here, and if for some reason it's null, early crashing is better than creating a label with wrong data, and will help us identify the bug earlier.

2021-05-31 17:04 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModel.kt
> +            productId = uniqueId,
This fixes #4094

2021-06-03 16:15 UTC, Garance91540 requested changes
Hi Hicham! The only thing I can see is that the text in the "Customs" row of the main Task List should update from "fill out customs form" to "Customs form completed" after it's completed https://d.pr/i/DELVMa

2021-06-03 16:46 UTC, hichamboushaba commented
> Hi Hicham! The only thing I can see is that the text in the "Customs" row of the main Task List should update from "fill out customs form" to "Customs form completed" after it's completed https://d.pr/i/DELVMa

Thanks @Garance91540 for the review, I noticed it yesterday and fixed it in 0e2f9420d96e7f101f28674329e7cac924e0a9f5, but I didn't update the video 🤦 
<img width="352" alt="Screen Shot 2021-06-03 at 17 45 50" src="https://user-images.githubusercontent.com/1657201/120681722-94c35d00-c493-11eb-9a19-a9c22ce5e5c4.png">

2021-06-04 07:38 UTC, Garance91540 approved these changes
👏

2021-06-11 10:49 UTC, nbradbury commented
@hichamboushaba Just a note that I've assigned myself to this and wanted to make sure you were aware of the conflicts.

2021-06-11 10:55 UTC, hichamboushaba commented
> @hichamboushaba Just a note that I've assigned myself to this and wanted to make sure you were aware of the conflicts.

Thanks for the heads up @nbradbury, I'll fix them right now.

2021-06-11 15:21 UTC, nbradbury commented
@hichamboushaba I found a couple of minor issues, feel free to address them separately if you'd rather not hold up this PR.

- If you enter information into the customs form and hit the back button, there's no "discard confirmation" - should one be necessary?
- If you fail to enter a required field, such as phone number or zip code, you get the warning that the field is required. But if you then type something, the warning doesn't go away. Also, the warning under the phone number is different than the rest and doesn't really make sense.
![required](https://user-images.githubusercontent.com/3903757/121709919-0b211a00-caa7-11eb-82f0-3fecba16cae7.png)

2021-06-11 15:23 UTC, nbradbury commented on WooCommerce/src/main/kotlin/com/woocommerce/android/model/CustomsPackage.kt
> +            weight = weight!!,
It'd be good to add this comment to the code, because looking at it I would think using `!!` on nullable values is a bug.

2021-06-11 15:29 UTC, hichamboushaba commented
Thanks @nbradbury for the review.

> If you enter information into the customs form and hit the back button, there's no "discard confirmation" - should one be necessary?

We don't have them in any of the shipping labels form, if they are required, then we need to add them to all the screens, and we can do it in a separate PR, @Garance91540 WDYT about the necessity of "discard confirmation" dialogs here?

> If you fail to enter a required field, such as phone number or zip code, you get the warning that the field is required. But if you then type something, the warning doesn't go away. Also, the warning under the phone number is different than the rest and doesn't really make sense.

This is unrelated to this PR, and I noticed it too, fixing it would require some big changes to the logic of this screen, can you create a ticket for this one? or I can do it myself later 🙂

2021-06-11 15:33 UTC, nbradbury commented
> This is unrelated to this PR, and I noticed it too, fixing it would require some big changes to the logic of this screen, can you create a ticket for this one?

Filed #4177 for this.

2021-06-11 15:55 UTC, hichamboushaba commented
> Filed #4177 for this.

Thanks @nbradbury, I took the liberty to update the issue to mention that it happens in the Address form, and not the customs form 🙂.
Can you approve this PR now, or you are still checking something else? 🙏

2021-06-11 15:56 UTC, nbradbury approved these changes
Looks great! :shipit:

2021-06-11 15:57 UTC, merged