Issue/4039 printing guide
woocommerce/woocommerce-android pull request #4168
Opened 2021-06-10 21:29 UTC by ctarda

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-06-10 23:52 UTC, adamzelinski requested changes
Looks great @ctarda just one small change could we please just move the illustration up a little. I think 32px padding will be enough. 
![121600394-6523d000-ca12-11eb-88e3-f2bec48c7257](https://user-images.githubusercontent.com/74938219/121610999-9fd14b00-ca9a-11eb-8e4a-4277f07a5d25.png)

2021-06-11 13:08 UTC, ctarda commented
Thanks for taking a look @adamzelinski . I pushed an update to reduce the top padding:

<img src="https://user-images.githubusercontent.com/2722505/121691075-96dd7b00-ca94-11eb-8bb1-e66be88ce642.png" width="350"/>

2021-06-11 15:58 UTC, Garance91540 commented
Hi Cesar! the tutorial looks good but I have feedback on the Order Details screen https://d.pr/i/8Unx7L (maybe you have planned to address this later in a separate PR!). We should be displaying the "Collect Payment" button as a Primary button, then the "Issure refund" as a secondary button, and the "Learn more..." as a text button

<img width="325" alt="Screen Shot 2021-06-11 at 5 56 57 PM" src="https://user-images.githubusercontent.com/28450084/121714764-74704f80-cade-11eb-9208-5818a2c589b6.png">

2021-06-11 16:38 UTC, malinajirka commented
Thanks for bringing this up @Garance91540! We'll implement that in a separate PR when we get closer to the release so we don't need to hide this change behind a feature flag. I've added a task [here](https://github.com/woocommerce/woocommerce-android/issues/3726) to make sure we don't forget about it! ;)

2021-06-11 16:57 UTC, malinajirka approved these changes
Thanks @ctarda, great job! ;) 

One minor thing I just noticed is that the other sub-screens on OrderDetail have "x" icon in the toolbar (in the top left corner) but "Printing Instructions" screen has "<-" arrow in the toolbar. We can fix this by adding reference to this newly added fragment [here](https://github.com/woocommerce/woocommerce-android/blob/c64e7dee071088b35dc8e313ba00f05c8cb105ef/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt#L401).

Other than that, this is good to go 🥳

2021-06-11 16:57 UTC, malinajirka commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="print_receipt_label_info_step_count_1" translatable="false">1</string>
Good call setting these strings as non-translatable! 👏

2021-06-11 20:17 UTC, ctarda commented
Thanks @malinajirka 

I touched MainActivity, now the instructions show the x:

<img src="https://user-images.githubusercontent.com/2722505/121744097-6287b000-cad0-11eb-89a6-8390cd632f29.png" width="350"/>

2021-06-14 01:27 UTC, adamzelinski approved these changes

2021-06-14 09:39 UTC, ctarda commented
Merging now. Thanks for the review y'all!

2021-06-14 09:39 UTC, merged