Issue/3725 use backend feature flag for payments
woocommerce/woocommerce-android pull request #4175
Opened 2021-06-11 14:01 UTC by kidinov

Parent issue #3725 

~Please review https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2024 first~

Adds fetching of feature flag from the backend if site eligible for card-present payments. It's false by default.

It does the call in 2 cases:
* The app came to the foreground with a timeout of 10 mins
* The user changes a site

### How to test
Open Charles.

* Open the app and notice `payments/accounts` call. Hide the app and open again - a call should not be performed. Wait 10 mins and open the app. The call should be performed.
* Switch site in settings - call should be performed.
* Build release version. Notice that collect money buttons in order details and manages reader in settings are not visible. Kill the app and change Charles `card_present_eligible` flag to true. Notice that the aforementioned buttons are visible

2021-06-14 09:03 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
> +            CARD_READER -> PackageUtils.isDebugBuild() || CardPresentEligibleFeatureChecker.isCardPresentEligible
@malinajirka Please confirm that this logic is correct. So payments are on if it's on locally OR it's ON on the remote. This way we can keep testing on debug builds

2021-06-14 10:36 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
> +            CARD_READER -> PackageUtils.isDebugBuild() || CardPresentEligibleFeatureChecker.isCardPresentEligible
I think we don't need the local flag for debugging - we can include our testing store in the beta (mine is already included). More info p91TBi-5cf-p2 or ping Allen to include you;).

2021-06-14 11:09 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
> +            CARD_READER -> PackageUtils.isDebugBuild() || CardPresentEligibleFeatureChecker.isCardPresentEligible
Make sense. Done there https://github.com/woocommerce/woocommerce-android/pull/4175/commits/251b052ae266215fed2b5e3d9121b143d0515cda

2021-06-15 12:18 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
> +    private val checkIfPaymentsEligible: RateLimitedTask = object : RateLimitedTask(
TIL about RateLimitedTask ;)

2021-06-15 12:21 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
> +            CARD_READER -> PackageUtils.isDebugBuild() || CardPresentEligibleFeatureChecker.isCardPresentEligible
My comment was super confusing, sorry - what I meant is that we don't need to fake-enable-it for the debug builds. So I was suggesting we use `PackageUtils.isDebugBuild() && CardPresentEligibleFeatureChecker.isCardPresentEligible`. The current logic should be fine as well, but if we don't release the feature in this code freeze the beta users will have access to the logic even on Android before it's "officially" ready for the beta. Wdyt?

2021-06-15 12:30 UTC, malinajirka requested changes
Thanks @kidinov! Good job - I like the usage of the RateLimitedTask.

I think I found two bugs
Bug 1:
1. Open Settings on a store which is eligible for CPP
2. Notice "Manage Card Reader" button is present
3. Change site to a store which is NOT eligible for CPP
4. Notice you get navigated back to settings and "Manage Card Reader" is still visible
- We might want to consider navigating the user back to the homescreen on site switch

Bug 2:
1. Open Settings on a store which is eligible for CPP
2. Switch Site to a store which is not eligible
3. Use charles to block the response from the server
4. Notice the flag is true as long as the request is ongoing -> also notice it remains true if the request completely fails
- We might want to consider manually changing the flag to false on site switch

2021-06-15 13:31 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
> +            CARD_READER -> PackageUtils.isDebugBuild() || CardPresentEligibleFeatureChecker.isCardPresentEligible
```
PackageUtils.isDebugBuild() && CardPresentEligibleFeatureChecker.isCardPresentEligible
```

With this logic, we won't ever have the feature ON on the release build.

```
The current logic should be fine as well, but if we don't release the feature in this code freeze the iOS beta users will have access to the logic even on Android before it's "officially" ready for the beta. Wdyt?
```

Hmm, I was under impression that the backend is smart enough to turn it on/off per store AND platform. Am I wrong?

2021-06-15 14:53 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
> +            CARD_READER -> PackageUtils.isDebugBuild() || CardPresentEligibleFeatureChecker.isCardPresentEligible
>  AND platform

I don't think they do that. I mean they could implement it, but AFAIK it's currently not there.

> With this logic, we won't ever have the feature ON on the release build.

Yes, that's correct. Until we are ready to say that the beta is ready to be used in production, we don't want to show it in production. Just to be clear - we plan to remove the `PackageUtils.isDebugBuild() && ` part in the next few weeks. But Until we are sure it's ready to be used in production I'd prefer to play it safe and keep it disabled in release builds. Does it make sense? Wdyt?

2021-06-16 06:32 UTC, kidinov commented
@malinajirka good catch with a bug, thanks! The fix is here - https://github.com/woocommerce/woocommerce-android/pull/4175/commits/17bb6f6159a316c548fd1bf45bce1509322fd9ff

2021-06-16 06:35 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/FeatureFlag.kt
> +            CARD_READER -> PackageUtils.isDebugBuild() || CardPresentEligibleFeatureChecker.isCardPresentEligible
Got it. Change is here https://github.com/woocommerce/woocommerce-android/pull/4175/commits/ae24cf5f4d7fb8a782f4e18f0c1a67ed747b5bfc

2021-06-16 11:13 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
> +            GlobalScope.launch { cardPresentEligibleFeatureChecker.doCheck() }
Not a blocker, just a remark, we shouldn't really use `GlobalScope` directly.
The official recommendation is to inject it, to allow replacing it later or for tests, do you think it'll be useful for us to inject it using Dagger?
We can try using a qualifier annotation to inject it, which will make the usage like this:
```
@Inject @AppScope lateinit var scope: CoroutineScope
```

2021-06-16 13:25 UTC, malinajirka approved these changes
Thanks @kidinov! The changes look good to me and all seems to work as expected. I've left one minor note but feel free to merge this PR without making any changes. I think the chances that someone will notice the difference in the behavior are very low anyway.

2021-06-16 13:25 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/payment/CardPresentEligibleFeatureChecker.kt
> +        isCardPresentEligible.set(false)
I'm wondering if we always want to assume that the flag has been turned off - I think in 99% of cases when a site becomes part of the beta it'll remain there. We might want to consider setting it to false only on a site change, wdyt?

2021-06-16 13:34 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/payment/CardPresentEligibleFeatureChecker.kt
> +        isCardPresentEligible.set(false)
I was thinking about this in a way that we want to be on a safe side and the safe side here is to keep it off. So, if for some reason (e.g. a mistake) we turn this flag on on the backend, then this endpoint will be broken then at least it by default will eventually turned off and people won't see feature which is not ready/broken

2021-06-16 13:35 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
> +            GlobalScope.launch { cardPresentEligibleFeatureChecker.doCheck() }
I think we should not use `GlobalScope` in general. Here it's used as temporary thing while we will run the feature in beta. Having its injectable will kind of give a wrong single that it's ok to use, while it's not =)

2021-06-16 13:42 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/payment/CardPresentEligibleFeatureChecker.kt
> +        isCardPresentEligible.set(false)
I agree with you that it's the safest thing to do from a point of view that we want to make sure not to show the collect payment button when we shouldn't. But I'm a bit worried that when merchants use this feature in production, they might open the app and very quickly open an order -> collect payment button won't be visible unless the request finished before they opened the order. My guess is that this scenario will be more common than scenario that we turn off a flag for a store - not mentioning the edge case where the endpoint is also broken. 

Let's ask others @allendav @ctarda, wdyt? To give you some context, the current behavior is that if we haven't checked the beta flag in the last ten minutes, we manually turn the flag off (set to false) and send a request to the server. Until the response arrives, the app assumes the merchant is not part of the beta.

2021-06-16 14:11 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
> +            GlobalScope.launch { cardPresentEligibleFeatureChecker.doCheck() }
Respectfully I disagree 🙂, there are some cases where a background task has to be tied to the application's lifecycle and not some other component, and for this case, using `GlobalScope` is OK, the official documentation states this: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-global-scope/ (Legitimate use-cases)
For those cases, Android's best practices are to avoid using it directly, but using it indirectly using injection, to make changing or customizing it easily later https://developer.android.com/kotlin/coroutines/coroutines-best-practices#global-scope, and here:

> If it turns out that the CoroutineContext of your applicationScope matches the GlobalScope or ProcessLifecycleOwner.get().lifecycleScope one, you can directly assign them as follows:
> class MyApplication : Application() {
>   val applicationScope = GlobalScope
> }
> You still get all the benefits mentioned above and you can easily change it if needed in the future.
> 
https://medium.com/androiddevelopers/coroutines-patterns-for-work-that-shouldnt-be-cancelled-e26c40f142ad

2021-06-16 14:39 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
> +            GlobalScope.launch { cardPresentEligibleFeatureChecker.doCheck() }
Hmm, I briefly checked all 3 links and everywhere it states `don't use GlobalScope` or `avoid GlobalScope` =). The API even marked as `Delicate`

The only valid case like in the example:

```
// A global coroutine to log statistics every second, must be always active
@OptIn(DelicateCoroutinesApi::class)
val globalScopeReporter = GlobalScope.launch {
    while (true) {
        delay(1000)
        logStatistics()
    }
}
```

It's not the case here and probably the example I copy-pasted above better to do with WorkManager

2021-06-16 14:52 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
> +            GlobalScope.launch { cardPresentEligibleFeatureChecker.doCheck() }
I quoted a direct snippet from the Medium article that says to use it, and in the official best practices they are passing `GlobalScope` as the default parameter, so I won't say they say `don't use it` 🙂.

As I said, sometimes you need to run something and tie it to the application's lifecycle, and not some component, let's say for example this part in our codebase: https://github.com/woocommerce/woocommerce-android/blob/09fed7a7ec75313856514d6de4cbdb7d15f1eb5c/WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt#L143-L156
It has to run independently of the activities lifecycle, so if it was using `suspendable` functions, we would need a way to launch it, and then we'll need some kind of scope, and then we have three ways:
1. GlobalScope directly, not recommended, and no discussion on this.
2. Creating our own `CoroutineScope` tied to the Application lifecycle and injecting it.
3. Similar to the 2nd solution, but instead inject `GlobalScope`

My understanding of the above articles is that the 2 last solutions are similar, if you want to customize something, then create your own `CoroutineScope`, if not, you can use `GlobalScope`, but using the injection, if you decide to customize something later you can do it.

Thanks for keeping the discussion, I enjoy this kind of discussions 🙂

2021-06-16 15:11 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
> +            GlobalScope.launch { cardPresentEligibleFeatureChecker.doCheck() }
I removed `GlobalScope` and started to use custom `app in foreground scope` https://github.com/woocommerce/woocommerce-android/pull/4175/commits/86074aeb4bc78157cf3c43f7bec58bc6aa320b1e

2021-06-16 15:24 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
> +            GlobalScope.launch { cardPresentEligibleFeatureChecker.doCheck() }
Thanks for making the change, I still won't cancel it when the app goes to the background though 🙂, because we need its result, and we'll cache either way.

And sorry if my comments make it like you need to make any changes here, that wasn't my intention at all, I was just discussing the subject, as `GlobalScope` is used in another place in the app, and wanted to see if injecting it would be useful for future tasks.

2021-06-16 15:25 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
> +            GlobalScope.launch { cardPresentEligibleFeatureChecker.doCheck() }
Interesting discussion and I really like that you introduced "inForeground" scope ❤️

2021-06-17 06:54 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
> +            GlobalScope.launch { cardPresentEligibleFeatureChecker.doCheck() }
> I still won't cancel it when the app goes to the background though 🙂, because we need its result, and we'll cache it either way.

If you cancel coroutine it doesn't mean that it somehow magically stops unless you use the suspended function (which I do in this case) or manually check if it's active. So depends on when the cancelation happens we either will cache the result or not. But it's ok in this case, we want to have the most relevant result with "false" by default

> And sorry if my comments make it like you need to make any changes here, that wasn't my intention at all, I was just discussing the subject, as GlobalScope is used in another place in the app, and wanted to see if injecting it would be useful for future tasks.

I like the discussion! Thanks! =) But I personally don't think that making global scope injectable is a good idea. It might spread the bad practice across the code. If there is a need to have an application scope background runner I would go with WorkManager

2021-06-17 06:54 UTC, merged

2021-06-17 12:19 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/payment/CardPresentEligibleFeatureChecker.kt
> +        isCardPresentEligible.set(false)
> But I'm a bit worried that when merchants use this feature in production, they might open the app and very quickly open an order -> collect payment button won't be visible unless the request finished before they opened the order.

Agree, but this scenario actually in place even without this line, because we keep it OFF by default. 

Often, feature flags are the call performed on the "splash" screen. With our current approach, I don't think that it's possible to make it correct for every edge case.

2021-06-17 20:19 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/payment/CardPresentEligibleFeatureChecker.kt
> +        isCardPresentEligible.set(false)
> Agree, but this scenario actually in place even without this line, because we keep it OFF by default.

Unless they start the app from scratch (clean run), it won't be `false` right? I don't think many merchants (android users in general) close open apps, so the chances that the app is in the background are imho very high. But the current code sets the flag to false even when you follow these steps
1. Open app - flag fetched and it's true
2. Use the app for 10-9999 minutes
3. Put it to background 
4. Bring it back to the foreground after lets say 1 second
5. The flag is `false` now even though the chances that we didn't turn off the remote flag are veeeery high

or another even more common scenario

1. Open app - flag fetched and it's true
2. Use the app for 10+ minutes
3. Click on "Print receipt" (OS printing activity is started)
4. Click on Print
5. The flag is false, since we got back from the OS printing activity

I think it's fine that when the user starts the app from scratch, the flag is `false` until the request finishes (we could store it in SharedPreferences if we wanted to handle this case). But the current code seems unnecessary strict. Am I missing something vital or do you think my concerns are valid?

2021-06-18 14:24 UTC, ctarda commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/payment/CardPresentEligibleFeatureChecker.kt
> +        isCardPresentEligible.set(false)
To (hopefully) put things in perspective... 

The rollout of the feature will be phased: first to the 5-10 merchants picked for beta 1, then to merchants in the US enrolled into WCPay, then to all merchants in the US, then to other countries...

My point with that is that, with time, more and more merchants will be gated into the feature. I appreciate that we all are trying to do what's best from an UX point of view, but I am not sure up to what point it's worth trying to cover every single edge case, with that context in mind. I am not sure if this helps though 😊

2021-06-18 14:51 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/payment/CardPresentEligibleFeatureChecker.kt
> +        isCardPresentEligible.set(false)
Thanks for the input @ctarda! We are basically choosing between two options, both of which are not perfect - they don't work in some edge cases. The difference between these two solutions is 1-3 lines, so the effort is also almost identical. So I think we are keeping the fact that this is just for a few months in mind. However, the tough question is which of these two we should choose :).

2021-06-23 07:05 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/payment/CardPresentEligibleFeatureChecker.kt
> +        isCardPresentEligible.set(false)
@malinajirka 

The examples you posted make a lot of sense. It just I'm not sure if we should be safe against your examples or this one:

* Backend makes a mistake and returns `true` to everyone
* It takes time to fix it and they shot down the endpoint
* Everyone who got `true` and doesn't kill the app will be in "beta" for quite some time even if the app goes to the background 


This scenario is super not realistic, but the impact can be big. 

After some thinking, I agree that the approach I took here is too much. I'll change on

```
if (!result.isError) isCardPresentEligible.set(result.model?.isCardPresentEligible ?: false)
        else isCardPresentEligible.set(false)
```

2021-06-23 12:31 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/payment/CardPresentEligibleFeatureChecker.kt
> +        isCardPresentEligible.set(false)
> This scenario is super not realistic, but the impact can be big.

I agree that the impact if there was a bug on the backend would be big. Having said that even if we showed the "Manage card reader" and "Collect payment" buttons in production, it wouldn't be that terrible. Users without readers wouldn't be able to use it anyway - they'd just see buttons which should be hidden. So I think changing the code is a good call.

> After some thinking, I agree that the approach I took here is too much. I'll change on
> if (!result.isError) isCardPresentEligible.set(result.model?.isCardPresentEligible ?: false)
        else isCardPresentEligible.set(false)

Will this solution cover [the scenario after the user changes site](https://github.com/woocommerce/woocommerce-android/pull/4175#pullrequestreview-683940310)?

2021-06-23 13:42 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/payment/CardPresentEligibleFeatureChecker.kt
> +        isCardPresentEligible.set(false)
> Will this solution cover the scenario after the user changes site?

Yes, because this call is synchronous now on site switch action