issue/4239-payments-clipped-send-receipt
woocommerce/woocommerce-android pull request #4242
Opened 2021-06-22 19:37 UTC by nbradbury

Fixes #4239 - The problem was due to a fixed height being used for the dialog, which caused the "Send receipt" button to be clipped. This PR prevents the clipped button by using a `minHeight` on the dialog.

![success](https://user-images.githubusercontent.com/3903757/122988319-9932b580-d36f-11eb-93ae-a02bc627fe0d.png)

@kidinov I assigned you as the reviewer since you submitted the [fixed size PR](https://github.com/woocommerce/woocommerce-android/pull/4223) and I wanted to make sure you're okay with this change.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-06-23 08:10 UTC, kidinov commented on WooCommerce/src/main/res/layout/fragment_card_reader_payment.xml
> +        android:layout_height="wrap_content"
@nbradbury Nick, we have to keep the size of the dialog fixed, otherwise, it will be "jumping" depends on the state of the flow. This problem should be solved by setting the right margins/sizes of the content. Basically, we need to follow the design exactly - they use fixed-size dialogs there as well

2021-06-23 11:09 UTC, nbradbury commented on WooCommerce/src/main/res/layout/fragment_card_reader_payment.xml
> +        android:layout_height="wrap_content"
@kidinov Understood, I restored the fixed dialog height in ca57a26 and was able to resolve the issue by simply removing the bottom padding from the dialog.

2021-06-23 12:06 UTC, kidinov commented on WooCommerce/src/main/res/layout/fragment_card_reader_payment.xml
> -        android:paddingBottom="@dimen/major_150"
With this change, we make the bottom padding smaller than the one from the design. I know that the current implementation a bit behind the design, but maybe, just hiding `amount_label` for this state will make things better? At least we will closer to the design. 

Ideally, we would like to add `back to order` button. Maybe not as part of this PR though.

The design:
![image](https://user-images.githubusercontent.com/4923871/123091516-1e7e9e80-d432-11eb-9db6-b5a16555d90d.png)

The look when I pass null in `PaymentSuccessfulState` as `amountWithCurrencyLabel`.  Attaching primary button to the top of the secondary probably will end up in proper layout
![image](https://user-images.githubusercontent.com/4923871/123093249-22132500-d434-11eb-8a01-7e9fb86d2b77.png)

2021-06-23 13:50 UTC, nbradbury commented on WooCommerce/src/main/res/layout/fragment_card_reader_payment.xml
> -        android:paddingBottom="@dimen/major_150"
@kidinov Perhaps we should just close this PR and you submit that as a new one?

2021-06-23 13:56 UTC, kidinov commented on WooCommerce/src/main/res/layout/fragment_card_reader_payment.xml
> -        android:paddingBottom="@dimen/major_150"
I personally wouldn't bother to close and open another one, but if you want, I don't mind =)

2021-06-23 14:31 UTC, nbradbury commented on WooCommerce/src/main/res/layout/fragment_card_reader_payment.xml
> -        android:paddingBottom="@dimen/major_150"
@kidinov I'm fine to keep this open, just figured you'd already made the changes :) However, now that I re-read your comment I realize you're suggesting we hide the payment amount, and I'm not sure we want to do that. That seems like important info, and it's in the designs.

2021-06-24 06:47 UTC, kidinov commented on WooCommerce/src/main/res/layout/fragment_card_reader_payment.xml
> -        android:paddingBottom="@dimen/major_150"
> However, now that I re-read your comment I realize you're suggesting we hide the payment amount, and I'm not sure we want to do that. That seems like important info, and it's in the designs.

@nbradbury My bad! A screenshot I posted in my comment is from [the IOS screen in Figma](vaw3DvewbUwuQnPXpdNGGH-fi-241%3A3999) and it doesn't contain the payment amount. For Android indeed it's there. Not sure if it's a mistake or should be like that @Garance91540 ?

2021-06-24 15:14 UTC, Garance91540 commented
>  Not sure if it's a mistake or should be like that @Garance91540 ?

The amount should be present in the modal:

<img width="223" alt="Screen Shot 2021-06-24 at 5 13 50 PM" src="https://user-images.githubusercontent.com/28450084/123288136-9373d600-d50f-11eb-8008-6ea74d4f772f.png">

cc @allendav @ctarda if you get the chance to add it back on iOS in the future :)

2021-06-25 16:27 UTC, nbradbury commented
@Garance91540 We have a dilemma with this dialog. It has a fixed height, which doesn't leave enough room for the "Send receipt" button (it cuts it off at the bottom). We have a few options:

- Increase the height of the dialog from 388dp to 398dp
- Reduce the size of the image
- Reduce the margins between views

Thoughts?

2021-06-29 09:41 UTC, Garance91540 commented
>@Garance91540 We have a dilemma with this dialog. It has a fixed height, which doesn't leave enough room for the "Send receipt" button (it cuts it off at the bottom).

Hi @nbradbury, I arranged the components of the modal to make sure they all fit in a 280 x 388 modal:

<img width="388" alt="Screen Shot 2021-06-29 at 11 40 00 AM" src="https://user-images.githubusercontent.com/28450084/123775669-df879780-d8ce-11eb-8a4e-fbf7666bcc42.png">

Can you tell me which part doesn't work?

2021-06-29 11:01 UTC, nbradbury commented
>  I arranged the components of the modal to make sure they all fit in a 280 x 388 modal:

@Garance91540 Ah, okay - I wasn't aware the illustration also had a fixed height, because the vector itself has a height of 117dp. Changing the illustration to a fixed height fixes the problem.

@kidinov I made the illustration height fixed in 46889cb so this is ready for another round.

![receipt](https://user-images.githubusercontent.com/3903757/123786421-a7209300-d8a7-11eb-884f-6b81b4c93d01.png)

2021-06-29 13:12 UTC, kidinov requested changes

2021-06-29 13:12 UTC, kidinov commented on WooCommerce/src/main/res/layout/fragment_card_reader_payment.xml
> +            android:layout_height="@dimen/payments_illustration_height"
Won't it break the proportions of the images we put in this view then? We put different images in this view and they should have different sizes depending on the step in the flow. For instance:

![image](https://user-images.githubusercontent.com/4923871/123803122-acf09580-d8f4-11eb-9ea8-e1dca17140b9.png)

I would just use the image of the correct size for the payment complete step (`img_celebration`)

2021-06-30 08:04 UTC, kidinov commented on WooCommerce/src/main/res/layout/fragment_card_reader_payment.xml
> +            android:layout_height="@dimen/payments_illustration_height"
I left a comment yesterday, but now it's missing o_O.

What I was saying is that making it fixed height for all the illustrations means that for other than the "successful" state we will show pictures with incorrect height. For instance, here it has to be 124dp

![image](https://user-images.githubusercontent.com/4923871/123924353-900a9f80-d992-11eb-8204-940fe664962e.png)

Maybe just to use the vector image (`img_celebration` light and dark variant) of the correct size keeping `wrap_content` in both dimensions?

2021-06-30 15:36 UTC, nbradbury commented
@kidinov Sorry this seemingly simple PR has dragged on so long! I checked the layout margins with those Garance posted in her screenshot above, and it turns out we were off in several places. I corrected this in 2e9b2ba, and it resolves the problem with the clipped button.

![margins](https://user-images.githubusercontent.com/3903757/123989985-61db8e80-d997-11eb-97f8-677ec9cde577.png)

2021-07-01 06:30 UTC, kidinov approved these changes
@nbradbury nothing to be sorry about. We spoke with @malinajirka already and we think that the current approach with mapping state to the UI makes things more complicated than they should be. 1 layout per all states creates tight coupling between states and that's why any change can cause bad side effects. It might be a good idea to separate states in different layouts on the next stage of the project development.

Looks good now!

2021-07-01 06:31 UTC, merged

2021-07-01 14:55 UTC, Garance91540 commented
Hi @nbradbury and @kidinov are you planning to add the "Back to order" link later on? https://d.pr/i/w9bcZE

2021-07-02 07:30 UTC, kidinov commented
@Garance91540 my understanding was that it's not part of the beta. And do we really need this on android? The back button is always on the screen anyway

2021-07-02 12:21 UTC, Garance91540 commented
Hi @kidinov , yes  the "back to order" button should be there in our final version, to provide a nice final path for our users (back button can be interpreted as going back to the last step, so the payment step). 

I'm not super aware of what's in the beta and what's not, that's why I asked if we were planning to add this button later :) (totally cool if it's not part of the beta, but I don't want us to forget about it)