Issue/3725 dialog same size
woocommerce/woocommerce-android pull request #4247
Opened 2021-06-23 10:29 UTC by kidinov

Parent issue #3725

It makes the connection dialog fixed-sized. Also, it tweaks a bit multiple readers available:

* Added type of reader according to the design
* Dialog fixed-sized so it doesn't jump (still no approval from UX/UI)

<img width="399" alt="Screenshot 2021-06-23 at 11 23 46" src="https://user-images.githubusercontent.com/4923871/123081104-449e4180-d426-11eb-8aab-bbc4ea6607e4.png">

### Notes:
* In [the design](vaw3DvewbUwuQnPXpdNGGH-fi-110%3A46067), there is one more button, which we don't have. After beta? 
* Error states for `MissingPermissionsError`, `LocationDisabledError`,  `BluetoothDisabledError` are not in the design anymore. Error states currently in design don't have `hintLabel`. Shell we remove `hintLabel` and update `headerLabel` so we still tell what is the reason behind the error?

@malinajirka 

### Videos:
https://user-images.githubusercontent.com/4923871/123081140-51bb3080-d426-11eb-9688-6a1f61f7f44d.mp4

https://user-images.githubusercontent.com/4923871/123081128-4cf67c80-d426-11eb-9e91-01c4eb277dd1.mp4

### How to test
Settings -> Manage card readers -> Connect

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-06-23 10:30 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/payment/CardPresentEligibleFeatureChecker.kt
> +        else isCardPresentEligible.set(false)
cc @malinajirka the changed we agreed on

2021-06-23 17:06 UTC, malinajirka commented
> In the design, there is one more button, which we don't have. After beta?

It seems the link you used leads to a dead-end. What button do you mean? 

> Error states for MissingPermissionsError, LocationDisabledError, BluetoothDisabledError are not in the design anymore, that's why I didn't touch them yet. Error states currently we have in design don't have hintLabel at all.
Shell we remove hintLabel and update headerLabel so we still tell what is the reason behind the error?

It seems the designs were updated since the last time I saw them. I'd stick with the previous designs which had the hint label displayed and only two buttons visible - try again and cancel. Or use whatever is easier to implement - we just need to make sure to display enough context to the user about the error.


> Error states for MissingPermissionsError, LocationDisabledError, BluetoothDisabledError are not in the design

All the error types should follow exactly the same design - the only difference are the texts.

Is still still wip since you are waiting on a final decision about the hints? If it's not wip, we might want to consider aligning the buttons to the bottom. Wdyt?
<img width="140" alt="Screenshot 2021-06-23 at 12 02 30" src="https://user-images.githubusercontent.com/2261188/123138837-1cf5ac00-d41b-11eb-83d1-d6dd74f1d415.png">

2021-06-24 08:54 UTC, kidinov commented
@malinajirka 

> It seems the link you used leads to a dead-end. What button do you mean?

Github changes our shortened links to something wrong. I meant that screen:

![image](https://user-images.githubusercontent.com/4923871/123221870-0cefd200-d4d8-11eb-8ae9-fd835ea71b2b.png)

Notice `back to order` button

> It seems the designs were updated since the last time I saw them. I'd stick with the previous designs for the beta which had the hint label displayed and only two buttons visible - try again and cancel. Or use whatever is easier to implement - we just need to make sure to display enough context to the user about the error.

Yes, it's changed. 
Ok, I'll change the text then and will follow the new design. I think it's the easiest way for now
https://github.com/woocommerce/woocommerce-android/pull/4247/commits/d1a001c69264c7bad947e36bbcb27c693a1b3f03

> 1.Is still still wip since you are waiting on a final decision about the hints?
> If it's not wip, we might want to consider aligning the b uttons to the bottom. Wdyt?

There is one more button in the design, and the styles of the buttons are not the same as on other screens. So yes, as a temporary solution I'm pushing it down.

> Is it possible that the Cancel button has different height depending on the screen? It seems like it from the first video you recorded.

I see it on video, but according to the code, it should not happen =). Also, currently testing on a device it doesn't happen. Maybe the fact I pushed the buttons bottom changed it

2021-06-24 08:56 UTC, kidinov commented on WooCommerce/src/main/res/layout/fragment_card_reader_payment.xml
> +        android:background="?attr/colorSurface"
cc @malinajirka fix for the bug you noticed

2021-06-24 14:00 UTC, malinajirka commented on WooCommerce/src/main/res/values-ar/strings.xml
> -    <string name="card_reader_connect_bluetooth_disabled_hint">تم تعطيل البلوتوث</string>
⚠️ Changing "string.xml" for other languages than english will cause conflicts during the release process - moreover, GlotPress will consider it as new items anyway. We should always update only the main strings.xml. Could you please revert this change and update only strings.xml? Thanks! 

P.S. Just bear in mind that changing the strings will mean that the translators will need to translate them again - so consider whether it's worth it.

2021-06-24 14:47 UTC, malinajirka requested changes
Thanks @kidinov! I've reviewed the code and tested the changes and it LGTM except of the strings.xml. When that's fixed I think we can merge this PR ;).

2021-06-24 15:41 UTC, Garance91540 commented
Hi @malinajirka and @kidinov ! Just FYI, in order for us to get a notification we should review a PR, it's better to add @woocommerce/mobile-designers  as reviewers so either @adamzelinski or I can review the said PR :)

2021-06-24 15:42 UTC, Garance91540 approved these changes
Modals are looking good! The only thing I'd like to flag is that the "Cancel" button has a fixed 32px vertical padding on all modals.

<img width="408" alt="Screen Shot 2021-06-24 at 5 40 56 PM" src="https://user-images.githubusercontent.com/28450084/123292598-7c36e780-d513-11eb-8608-b4616742db4c.png">

2021-06-25 07:11 UTC, kidinov commented on WooCommerce/src/main/res/values-ar/strings.xml
> -    <string name="card_reader_connect_bluetooth_disabled_hint">تم تعطيل البلوتوث</string>
I didn't know! Thanks. Probably it will be a good thing to put in the convention.md file =)

https://github.com/woocommerce/woocommerce-android/pull/4247/commits/e30f33f0ef0482626701ec6acedf8254449af2f2

2021-06-25 09:03 UTC, kidinov commented
@malinajirka @nbradbury @Garance91540 please go through the flow again. In order to fix that https://github.com/woocommerce/woocommerce-android/pull/4247#pullrequestreview-691920374 I had to change the layout completely

2021-06-28 13:07 UTC, malinajirka approved these changes
I'm sorry, I reviewed this on Friday but I forgot to merge it 😞.

LGTM!

2021-06-28 13:07 UTC, merged

2021-06-29 12:44 UTC, Garance91540 commented
Hi @kidinov , yes it seems like we don't have documentation yet, so removing the link to the documentation makes sense 😅

Can we align on this modal for the error modal with 2 buttons? there's a 32px left, right, bottom padding around the last button. I tagged you on Figma in it so you can see the exact padding around each component
<img width="277" alt="Screen Shot 2021-06-29 at 2 42 55 PM" src="https://user-images.githubusercontent.com/28450084/123799434-84629e80-d8e8-11eb-96a2-e62eb285bc86.png">