Suppress back when sw update in progress
woocommerce/woocommerce-android pull request #4264
Opened 2021-06-24 20:17 UTC by malinajirka

Parent issue #3957 

This is still a draft since we haven't decided if we really want to preventing the user from leaving the dialog. If the update gets stuck in the Stripe SDK the user won't have another option than to kill the app.

Merge instructions:
1. #4261 needs to be merged first
2. Remove "do not merge" label
3. Merge this PR

This PR prevents the user from leaving the update software dialog when an update is in progress - this is recommended in[ Stripe's documentation](https://stripe.com/docs/terminal/readers/bbpos-chipper2xbt).

To test
1. Connect to a reader
2. Leave the "update available" dialog by pressing back
3. Tap on "Update Reader's software"
4. Tap on "update"
5. Try leaving the dialog by pressing back and notice it doesn't work when an update is in progress

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-06-25 13:20 UTC, malinajirka commented
We discussed two solutions
1. Show a snackbar with "Cancel anyway" action when the user presses back. Something like "Canceling an ongoing update is not recommended".
2. Show a cancel button with a message on the dialog itself when the user presses back. 

Effort for 2 is a higher, but probably still relatively low - since the UX will be better with `2` let's give it a try and see.

2021-06-28 08:30 UTC, kidinov commented
@malinajirka are you going to implement effort #2 in this PR?

2021-06-28 13:05 UTC, malinajirka commented
@kidinov Yes I'm planning to implement it in this draft PR when everything else for the beta is ready - it's a low priority issues.

2021-07-07 15:41 UTC, malinajirka commented
Update on this issue -> I've added the cancel button, but it seems cancelling an ongoing update is not supported in v1.x of the SDK (see [this issue](https://github.com/stripe/stripe-terminal-android/issues/119)). So I'm thinking we shouldn't introduce the cancel button after all - wdyt @kidinov ?

2021-07-08 07:01 UTC, malinajirka commented
This PR is ready for review now - it contains the issue mentioned in the "Known issues" section, but thinking about it again, it's still probably an improvement. Wdyt @kidinov ?

2021-07-08 07:03 UTC, adamzelinski approved these changes

2021-07-08 07:04 UTC, malinajirka commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="card_reader_software_update_progress_cancel_warning">Canceling an ongoing software update is not recommended.</string>
📓 I made this text up, we might want to update it. Let me know if you have any suggestions. Thanks

2021-07-08 07:32 UTC, kidinov commented
> Update on this issue -> I've added the cancel button, but it seems cancelling an ongoing update is not supported in v1.x of the SDK (see this issue). So I'm thinking we shouldn't introduce the cancel button after all - wdyt @kidinov ?

Agree because it will kind of indicate that this is normal behavior, while it is not

> it contains the issue mentioned in the "Known issues" section, but thinking about it again, it's still probably an improvement. Wdyt @kidinov ?

Definitely. Especially the progress bar

2021-07-08 08:25 UTC, kidinov requested changes
Looks good! Left couple of ideas in the comments

2021-07-08 08:25 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateDialogFragment.kt
> +        dialog!!.setOnKeyListener(object : OnKeyListener {
In `CardReaderPaymentDialog` it's done like:

```
    override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
        return object : Dialog(requireContext(), theme) {
            override fun onBackPressed() {
                viewModel.onBackPressed()
            }
        }
    }
```

Any specific reason to do it differently here?

2021-07-08 08:25 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateDialogFragment.kt
>          dialog!!.setCanceledOnTouchOutside(false)
Matter of taste probably, but imho, more kotlin way would be:

```
        with (requireDialog()) {
            setCanceledOnTouchOutside(false)
            requestWindowFeature(Window.FEATURE_NO_TITLE)
            setOnKeyListener(object : OnKeyListener {
                override fun onKey(dialog: DialogInterface?, keyCode: Int, event: KeyEvent?): Boolean {
                    return if (keyCode == KeyEvent.KEYCODE_BACK) {
                        return viewModel.onBackPressed()
                    } else {
                        false
                    }
                }
            })
        }
```

2021-07-08 08:25 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModel.kt
> +        data class UpdatingState(
I would just go with 2 different states: `UpdatingState` and `UpdateCancelingState`. 1 to 1 mapping between VM states and View states should make the code more straightforward. 

With this approach, you also could have the interface marker `StateWithProgress` and then `updateProgress` can be a very simple method. Currently, the method is confusing, because what you actually check if we currently in "UpdateCancelingState"  or in just normal `UpdatingState` and then depending on it you either copy the state or create a new one, but it's not clear from the first sight

2021-07-08 08:25 UTC, kidinov commented on WooCommerce/src/main/res/layout/dialog_card_reader_update.xml
>          android:layout_height="@dimen/progress_bar_mid"
Do we need it to be that tall even if it's `LinearProgressIndicator` ?

2021-07-08 08:25 UTC, kidinov commented on WooCommerce/src/main/res/layout/dialog_card_reader_update.xml
> +        android:id="@+id/update_reader_progress_warning_tv"
Would it make sense to use the same font size and color as update_reader_progress_description_tv? I think It looks not really consistent currently

2021-07-08 08:25 UTC, kidinov commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="card_reader_software_update_progress_indicator">%1$s %%</string>
I think there is should not be space between the number and `%`. At least it what most articles from Google advice =)

2021-07-08 08:37 UTC, malinajirka commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="card_reader_software_update_progress_indicator">%1$s %%</string>
Interesting, in Czech language there must be a space -> "10%" without a space is an adjective. Anyway, it seems that English doesn't use the space. Good catch :).

2021-07-08 08:44 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateDialogFragment.kt
> +        dialog!!.setOnKeyListener(object : OnKeyListener {
Nope, no good reason ;).  Fixed in ad0f72fbfa24c09de42d06fe73e7e5b112c9bb06 and 150cb44cbe915fd04db8ebb832f98659ee61bf69

2021-07-08 08:44 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateDialogFragment.kt
>          dialog!!.setCanceledOnTouchOutside(false)
Fixed in ad0f72fbfa24c09de42d06fe73e7e5b112c9bb06

2021-07-08 08:45 UTC, malinajirka commented on WooCommerce/src/main/res/layout/dialog_card_reader_update.xml
>          android:layout_height="@dimen/progress_bar_mid"
Fixed in b38397d355159932369973656ed2d47f5c514583

2021-07-08 08:45 UTC, malinajirka commented on WooCommerce/src/main/res/layout/dialog_card_reader_update.xml
> +        android:id="@+id/update_reader_progress_warning_tv"
Fixed in fb8a897c60b0e4cd4060b968f707a9de2b068794

2021-07-08 08:45 UTC, malinajirka commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="card_reader_software_update_progress_indicator">%1$s %%</string>
Fixed in e37f8119d5b84438e30cdb495746511a56d97ef3

2021-07-08 11:01 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModel.kt
> +        data class UpdatingState(
> Currently, the method is confusing, because what you actually check if we currently in "UpdateCancelingState" or in just normal UpdatingState and then depending on it you either copy the state or create a new one, but it's not clear from the first sight

That's actually not the case, the method was only checking if it's already in Updating state or still in Explanation state and either updated progress or created the UpdatingState.

> I would just go with 2 different states: UpdatingState and UpdateCancelingState. 1 to 1 mapping between VM states and View states should make the code more straightforward.

I've considered this approach before but I wasn't sure about it. Tbh I'm still not sure - I made teh changes in ba3c253bc37023768cae3189658814aa1f8ef6b7 and 6598369980da98f27920ecb0f92f236e06f79790. Let me know what you think, we can still revert them. I personally like that we have two separate states but I don't think it made the code more straightforward :D.

2021-07-08 11:50 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/update/CardReaderUpdateViewModel.kt
> +        data class UpdatingState(
>  I personally like that we have two separate states but I don't think it made the code more straightforward :D.

Agree that it's not that straightforward as I would imagine, but I still would keep this approach. Especially I like how this method looks like now:

```
    fun onBackPressed() {
        return when (val currentState = viewState.value) {
            is UpdatingState -> showCancelButton(currentState)
            is UpdatingCancelingState -> viewState.value = UpdatingState(currentState.progress)
            else -> triggerEvent(ExitWithResult(FAILED))
        }
    }
```

compare to


```
    fun onBackPressed() {
        val currentState = viewState.value
        return if (currentState is UpdatingState) {
            showCancelButton(currentState)
        } else {
            triggerEvent(ExitWithResult(FAILED))
        }
```

2021-07-08 11:52 UTC, kidinov commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="card_reader_software_update_progress_cancel_warning">Canceling an ongoing software update is not recommended.</string>
I would just remove the dot at the end. I don't see that we use it in other paces

2021-07-08 11:53 UTC, kidinov approved these changes
It looks good to me. If you will decide to remove the dot from the message, then just do it and go ahead and merge it

2021-07-09 07:00 UTC, merged