nick/reader-found-animation
woocommerce/woocommerce-android pull request #4325
Opened 2021-06-30 16:33 UTC by nbradbury

This PR adds a simple fade-out/fade-in animation when a reader is found. Note that this needs to be approved by a designer before merging.

![fade](https://user-images.githubusercontent.com/3903757/123998119-2b097680-d99f-11eb-9822-e0f95cd50c27.gif)

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-06-30 16:33 UTC, nbradbury commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectFragment.kt
> +            if (viewState is ViewState.ReaderFoundState) {
I'm not wild about having this logic here. I considered adding an `illustationAnimation` to the various ViewStates which would be an enum containing `NONE`, `FADE`, `VECTOR` values, so the logic for which animation to show would be handled by the view model. That seemed like overkill to me, but happy to make that change if the reviewer thinks it's a better approach.

2021-07-01 13:07 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectFragment.kt
> +            if (viewState is ViewState.ReaderFoundState) {
I'm personally ok with keeping the animation logic in the view layer. One, if not only, logic I don't mind having in the view layer. Your solution re-uses the same code path, just adds an animation to the "reader found" state, which I like.

2021-07-01 13:08 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectFragment.kt
> +            if (viewState is ViewState.ReaderFoundState) {
I'm personally ok with keeping the animation logic in the view layer. One, if not only, logic I don't mind having in the view layer. Your solution re-uses the same code path, just adds an animation to the "reader found" state, which I like.

2021-07-01 13:27 UTC, malinajirka requested changes
Thanks @nbradbury! Nice improvement 👏 . I've left a few comments - the one marked with ⚠️ is the only one I think we should discuss before merging this PR. Let me know what you think ;).

2021-07-01 13:27 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooAnimUtils.kt
> +    fun getFadeInAnim(target: View, animDuration: Duration = DEFAULT_DURATION): ObjectAnimator {
❓ Have you considered passing lambdas for "onStart/onEnd" instead of providing a getter for the ObjectAnimators? I personally like how the WooAnimUtils encapsulates animation logic so it doesn't leak into Fragments/Activities/Views.

Something like this
```
fun fadeIn(
        target: View,
        animDuration: Duration = DEFAULT_DURATION,
        onStart: ((Animator) -> Unit)? = null,
        onEnd: ((Animator?) -> Unit)? = null
    ) {
        with(ObjectAnimator.ofFloat(target, View.ALPHA, 0.0f, 1.0f)) {
            duration = animDuration.toMillis(target.context)
            interpolator = LinearInterpolator()
            addListener(object : AnimatorListenerAdapter() {
                override fun onAnimationStart(animation: Animator) {
                    onStart?.invoke(animation)
                    target.visibility = View.VISIBLE
                }

                override fun onAnimationEnd(animation: Animator?) {
                    super.onAnimationEnd(animation)
                    onEnd?.invoke(animation)
                }
            })
            start()
        }
    }
```

Wdyt?

2021-07-01 13:27 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectFragment.kt
> +                moveToState(binding, viewState)
⚠️ This introduces a very edge case race condition as the ViewModel.viewState stops being the only source of truth. 
I'd consider wrapping this code with `if(viewModel.viewStateData.value is ViewState.ReaderFoundState)`. 


One more thing I'd consider is adding "isResumed" check before we start the fadein animation, so the end result would look like this:
```
    if (viewModel.viewStateData.value is ViewState.ReaderFoundState) moveToState(binding, viewState)
    if (lifecycle.currentState == Lifecycle.State.RESUMED) fadeIn.start()
```
Wdyt?

2021-07-01 18:36 UTC, nbradbury commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectFragment.kt
> +                moveToState(binding, viewState)
Very good call. I just added this in f518e05.

2021-07-01 18:41 UTC, nbradbury commented on WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooAnimUtils.kt
> +    fun getFadeInAnim(target: View, animDuration: Duration = DEFAULT_DURATION): ObjectAnimator {
I'm not convinced this is a better approach than sticking with an `AnimatorListenerAdapter` in the fragment. All this does is provide a wrapper for that listener, and my preference would be to use the listener directly.

2021-07-01 18:49 UTC, malinajirka approved these changes
LGTM - not merging as it's waiting for a design review. Feel free to merge it when that's finished ;).

2021-07-01 20:48 UTC, adamzelinski approved these changes

2021-07-02 10:51 UTC, merged