Store payment receipts into persistent storage
woocommerce/woocommerce-android pull request #4326
Opened 2021-06-30 17:09 UTC by malinajirka

Parent issue #4039

This PR adds support for storing payment receipts into shared preferences. I considered storing them into a database, but decided against it. The main reason was that we plan to add receiptUrl to the OrderModel on the backend. When that's implemented the app won't need to manually store receipts.

To test:
Prerequisite - the store is included in the card reader beta
1. Open detail of an unpaid order in US
2. Tap on "Collect payment" button
3. Complete the payment
4. Verify that "RECEIPT_PREFIX:....." entry with receipt URL is in shared preferences
5. Log out of the app and verify the entry gets deleted

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-06-30 19:41 UTC, nbradbury commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
> +    private fun removePreferencesWithDynamicKey(editor: Editor) {
This would benefit from a comment explaining its purpose.

2021-06-30 19:43 UTC, nbradbury requested changes
Code looks good, I just had one recommendation about adding a comment.

2021-07-01 03:11 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
> +    private fun removePreferencesWithDynamicKey(editor: Editor) {
Good call - fixed in https://github.com/woocommerce/woocommerce-android/pull/4326/commits/29d1da4879f9b7682e95af54bb0eeba9a6b50d18

2021-07-01 12:32 UTC, nbradbury approved these changes
Looks good, thanks for the comment! :shipit:

2021-07-01 12:33 UTC, merged