Introduce preview receipt UI
woocommerce/woocommerce-android pull request #4329
Opened 2021-07-01 03:22 UTC by malinajirka

Parent issue #4039

Merge instructions:
1. Make sure #4326 is merged
2. Remove "Do not merge" label
2. Merge this PR

This PR adds "See receipt" button to order detail screen and introduced ReceiptPreview fragment.

Note: The PR contains over 500lines of changes, but a lot of it are tests. I recommend reviewing it by commits.

<img src="https://user-images.githubusercontent.com/2261188/124059613-fa522d00-d9f0-11eb-8148-b46785d3a78f.png" width="250px" />
<img src="https://user-images.githubusercontent.com/2261188/124059617-fc1bf080-d9f0-11eb-9708-36fc6234693c.png" width="250px" />
<img src="https://user-images.githubusercontent.com/2261188/124059759-3d140500-d9f1-11eb-9709-90f87f473ab1.gif" width="250px" />

To test:
Prerequisites: Use card present payment ready site and order.
1. Open order detail of an unpaid order in US dollars (Notice the "See receipt" button is not visible)
2. Tap on Collect Payment
3. Complete the payment flow
4. Dismiss the "Payment successful" dialog
5. Notice the order detail screen gets updated and "See receipt" button is visible
2. Tap on "See receipt"
3. ReceiptPreview screen is shown - you should see a progress dialog while the receipt is being loaded
4. Tap on Print and notice you get redirected to the OS printing screen
5. Go back and tap on Send Email and notice an email client with pre-filled content is shown

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-07-01 13:43 UTC, kidinov requested changes
The code is nice and clean. Works good as well. I left couple of possible improvements you can consider to implement. 

Just 1ct to the bucket of having receipts be handed on the backend - reinstalling of the app or using another device makes user loose all the receipts

2021-07-01 13:43 UTC, kidinov commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/ReceiptPreviewViewModelTest.kt
> +    fun `verify progress state has correct values`() {
Does this and the next test follows the convention?

2021-07-01 13:43 UTC, kidinov commented on WooCommerce/src/main/res/layout/fragment_receipt_preview.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Maybe to use FrameLayout for sake of performance? It looks like that you don't use anything from ConstraintLayout here anyway

2021-07-01 13:43 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/ReceiptPreviewViewModel.kt
> +    fun onPrintResult(result: PrintJobResult) {
It looks like that you have exactly the same method in `CardReaderPaymentViewModel`. Maybe to extract it in some `ReceiptTrackingHelper` or something

2021-07-01 13:43 UTC, kidinov commented on WooCommerce/src/main/res/layout/order_detail_payment_info.xml
> +                android:paddingStart="0dp"
If you tap and press the button you'll see that text is not centered against the ripple effect but at left top corner. Also, missing left padding looks like a visual bug to me, so probably better to use padding here instead of margin

2021-07-01 13:43 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/ReceiptPreviewFragment.kt
> +                is LoadUrl -> binding.receiptPreviewPreviewWebview.loadUrl(it.url)
Maybe add

```
                    binding.receiptPreviewPreviewWebview.settings.loadWithOverviewMode = true
                    binding.receiptPreviewPreviewWebview.settings.useWideViewPort = true
```

So the we show the whole receipt, without zooming?

2021-07-01 15:25 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/ReceiptPreviewViewModel.kt
> +    fun onPrintResult(result: PrintJobResult) {
I considered this but I don't think it's worth it. When we need to copy-paste this code one more time, I agree it'll be better to extract it.

2021-07-01 15:25 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/ReceiptPreviewViewModelTest.kt
> +    fun `verify progress state has correct values`() {
Ohh, power of habit - fixed in https://github.com/woocommerce/woocommerce-android/pull/4329/commits/f9cb3423db28de752016476db244ff9d0ae13e3e

2021-07-01 15:25 UTC, malinajirka commented on WooCommerce/src/main/res/layout/fragment_receipt_preview.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Fixed in https://github.com/woocommerce/woocommerce-android/pull/4329/commits/51475dbe195c58bebe22957ddd74d8b3e46c9861

2021-07-01 15:37 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/ReceiptPreviewFragment.kt
> +                is LoadUrl -> binding.receiptPreviewPreviewWebview.loadUrl(it.url)
I tried this but it didn't change anything - it still loads the receipts so the width fits the screen and the user needs to scroll down. I'm not sure why.

2021-07-01 15:39 UTC, malinajirka commented on WooCommerce/src/main/res/layout/order_detail_payment_info.xml
> +                android:paddingStart="0dp"
Nice catch, fixed in 9d9405998e4048e0e72d05e62cd740532090f7f5

2021-07-01 15:48 UTC, malinajirka commented
Updated designs of the "see receipt" button
<img src="https://user-images.githubusercontent.com/2261188/124152995-a16aaf00-da59-11eb-8c0b-1ef9a3077d31.gif" width="250px" />

2021-07-02 06:49 UTC, adamzelinski approved these changes

2021-07-02 08:16 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/ReceiptPreviewFragment.kt
> +                is LoadUrl -> binding.receiptPreviewPreviewWebview.loadUrl(it.url)
Hm, weird. It does change things for me

Before:
![image](https://user-images.githubusercontent.com/4923871/124243480-9a5da280-db26-11eb-8349-388499c45040.png)

After:

![image](https://user-images.githubusercontent.com/4923871/124243721-d8f35d00-db26-11eb-94ff-1e2f08ce5af8.png)

I like the second variant more

2021-07-02 13:17 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/ReceiptPreviewFragment.kt
> +                is LoadUrl -> binding.receiptPreviewPreviewWebview.loadUrl(it.url)
Interesting, it looks like as per the screenshots in the description on my side ([link](https://user-images.githubusercontent.com/2261188/124059617-fc1bf080-d9f0-11eb-9708-36fc6234693c.png)).

I'll update the code.

2021-07-02 14:14 UTC, malinajirka commented
@kidinov I've updated the webview to display fully zoomed out receipts in - db8874c9b07361e5ae43abce3c64c4381221864f. However, I can't test it on my side, since it works for me even without the code -> I tested it on my hw device and 3 emulators 🤷 . Feel free to update the code as necessary ;). Thanks!

2021-07-05 07:33 UTC, kidinov approved these changes
Perfect!

2021-07-05 07:33 UTC, merged