issue/viewpager_indicator
woocommerce/woocommerce-android pull request #4368
Opened 2021-07-06 13:59 UTC by nbradbury

This PR moves the view pager indicator out of the login prologue and into its own re-usable widget. The reason for this is the [payment tutorial](https://github.com/woocommerce/woocommerce-android/issues/4341) requires a similar indicator and it made sense to make the existing widget re-usable.

To test, simply step through the login prologue and verify the swipeable view pager works as expected. I recommend testing on a real device as view pagers can be flaky on emulators.

![Screenshot_20210706_095424](https://user-images.githubusercontent.com/3903757/124612283-33026400-de40-11eb-9fe2-a8bc96fc4e46.png)

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-07-07 09:23 UTC, kidinov requested changes
Works and looks good! I would just consider to move some logic inside of the PagerIndicator so it can be more like a "plug-and-play" component

2021-07-07 09:23 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueFragment.kt
> +        binding.viewPagerIndicator.setupFromViewPager(binding.viewPager, listener)
What do you think if we remove `listener` from `setupFromViewPager` signature, and internally, inside `WCViewPageIndicator`. Also, we could actually move the following code:

```
        binding.viewPager.addOnPageChangeListener(object : ViewPager.SimpleOnPageChangeListener() {
            override fun onPageSelected(position: Int) {
                binding.viewPagerIndicator.setSelectedIndicator(position)
            }
        })
```

Inside `WCViewPagerIndicator` like that:

```
class WCViewPagerIndicator @JvmOverloads constructor(
    context: Context,
    attrs: AttributeSet? = null,
    defStyleAttr: Int = 0,
    defStyleRes: Int = 0
) : LinearLayout(context, attrs, defStyleAttr, defStyleRes) {
    private val indicators = ArrayList<ImageView>()
    private var pageCount: Int = 0

    fun setupFromViewPager(viewPager: ViewPager) {
        this.pageCount = viewPager.adapter?.count ?: 0

        orientation = HORIZONTAL
        val padding = context.resources.getDimensionPixelSize(R.dimen.margin_small)

        for (page in 0 until pageCount) {
            ImageView(context).also { imageView ->
                imageView.setImageResource(R.drawable.ic_tab_indicator)
                imageView.isSelected = page == 0
                imageView.setPadding(padding, 0, padding, 0)
                this.addView(imageView)
                indicators.add(imageView)

                imageView.setOnClickListener {
                    viewPager.currentItem = page
                }
            }
        }

        viewPager.addOnPageChangeListener(object : ViewPager.SimpleOnPageChangeListener() {
            override fun onPageSelected(position: Int) {
                setSelectedIndicator(position)
            }
        })
    }

    private fun setSelectedIndicator(index: Int) {
        for (i in 0 until pageCount) {
            indicators[i].isSelected = i == index
        }
    }
}
```

I think it's quite reasonable to expect that `PageIndicator` that works with `ViewPager`, will select indicators and move pages out of the box without need of seting it up everytime.

This way we, also increase code reusability when we will use the same page indicator for the case of payment tutorial

2021-07-07 16:08 UTC, nbradbury commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueFragment.kt
> +        binding.viewPagerIndicator.setupFromViewPager(binding.viewPager, listener)
@kidinov That is a **much** cleaner approach, thanks for pointing it out. I made that change in a3a3209.

2021-07-08 07:09 UTC, kidinov approved these changes
Looks good now! There is a small comment left. Please go ahead with merging if you think that it makes sense to make it private or not

2021-07-08 07:09 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCViewPagerIndicator.kt
> +    fun setSelectedIndicator(index: Int) {
I think we could make it `private`, wdyt?

2021-07-08 10:44 UTC, nbradbury commented on WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCViewPagerIndicator.kt
> +    fun setSelectedIndicator(index: Int) {
Done in dc9ecf3.

2021-07-08 12:08 UTC, merged