Shipping labels: show a discard changes dialog
woocommerce/woocommerce-android pull request #4386
Opened 2021-07-08 13:46 UTC by hichamboushaba

Closes #4257, this adds a discard changes dialog if the shipping labels form has some changes.

<img width="352" alt="Screen Shot 2021-07-08 at 14 43 48" src="https://user-images.githubusercontent.com/1657201/124932510-0c3c5d00-dffb-11eb-8c73-25e1d0c5656b.png">

#### Testing
1. Create an order eligible for shipping label creation.
2. Open the order details in the app.
3. Click on "Create shipping label"
4. Click on back button.
5. Confirm that you can leave the form without any warning.
6. Click on "Create shipping label" a second time.
7. Finish some steps.
8. Click on back button on the main screen of the form.
9. Confirm that a discard changes dialog is shown.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-07-08 18:35 UTC, nbradbury commented
@hichamboushaba If I rotate the device while the discard dialog is showing, the dialog disappears and the back button stops working.

![back](https://user-images.githubusercontent.com/3903757/124973546-aa2f2800-dff9-11eb-81f3-61f7aee130be.gif)

2021-07-08 18:41 UTC, nbradbury commented
@hichamboushaba I did a little research into the bug I mentioned above, and it turns out the problem lies [here in WooDialog](https://github.com/woocommerce/woocommerce-android/blob/a2a97f666245b21ae8a7f30443083d4e56e00ab0/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dialog/WooDialog.kt#L30). Even though the dialog isn't showing, there's still a reference to it, so that code assumes it's already showing.

Shall we treat that as a separate issue, or do you want to fix it here?

2021-07-08 19:55 UTC, nbradbury requested changes
@hichamboushaba This all looks good except for the issue with the dialog.

2021-07-09 11:32 UTC, hichamboushaba commented
> @hichamboushaba I did a little research into the bug I mentioned above, and it turns out the problem lies [here in WooDialog](https://github.com/woocommerce/woocommerce-android/blob/a2a97f666245b21ae8a7f30443083d4e56e00ab0/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dialog/WooDialog.kt#L30). Even though the dialog isn't showing, there's still a reference to it, so that code assumes it's already showing.
> 
> ~Shall we treat that as a separate issue, or do you want to fix it here?~
> 
> **Update:** It looks like the problem is due to not calling `WooDialog.onCleared()` in the fragment.

Thanks @nbradbury for catching this, I'll need to remind myself to test device rotation 🙂.
Ready for another round.

2021-07-09 12:21 UTC, nbradbury approved these changes
:shipit:

2021-07-09 12:21 UTC, merged