Improve input validation for shipping labels address form
woocommerce/woocommerce-android pull request #4401
Opened 2021-07-12 12:37 UTC by hichamboushaba

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-07-12 16:28 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressViewModel.kt
> +        operator fun get(field: Field): InputField<*> {
There is one additional enhancement that I'm planning for this screen, which is focusing on the first errored field, and for this change, this operator will come in handy.
I will do this in a separate PR though.

2021-07-12 16:30 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/InputField.kt
> +abstract class InputField<T : InputField<T>>(open val content: String) : Parcelable, Cloneable {
The usage of the generic type here, is to allow returning the child's type in the `validate` function below (check here for more information https://stackoverflow.com/a/29566159/5494024)

2021-07-12 17:07 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/InputField.kt
> +    }
Mark `hashCode` and `equals` as final to avoid overriding them using `data classes` kotlin generation, because it will skip the non-overriden fields (error and hasBeenValidated), and would give wrong results.

2021-07-12 20:41 UTC, nbradbury commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/InputField.kt
> +abstract class InputField<T : InputField<T>>(open val content: String) : Parcelable, Cloneable {
This comment might be better in the code than outside it.

2021-07-12 20:42 UTC, nbradbury commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/InputField.kt
> +    }
Same as above, why not include this comment in the code itself?

2021-07-12 20:45 UTC, nbradbury commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressFragment.kt
> +            new.address2Field.takeIfNotEqualTo(old?.address1Field) { field ->
This is comparing `address2Field` to `address1Field`.

2021-07-12 20:58 UTC, nbradbury commented
When I go to the Shipping Address screen, it already shows an error message under Name even though the user hasn't entered anything yet. I don't know if it's a big deal, but it is a change from `develop`.

![shipping](https://user-images.githubusercontent.com/3903757/125354944-68242000-e332-11eb-8ad5-7def01662d6a.png)

2021-07-12 21:01 UTC, nbradbury requested changes
@hichamboushaba This is a very nice improvement over the existing way of validating, nice work! I'm done with my first round and made a few minor comments, and pointed out one bug regarding address that does need to be fixed.

2021-07-13 09:16 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/InputField.kt
> +abstract class InputField<T : InputField<T>>(open val content: String) : Parcelable, Cloneable {
You are right, I added it in `62f0d8e`

2021-07-13 09:17 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/InputField.kt
> +    }
done also in 62f0d8e

2021-07-13 09:17 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelAddressFragment.kt
> +            new.address2Field.takeIfNotEqualTo(old?.address1Field) { field ->
Thanks for catching this, I fixed it in a477cf0

2021-07-13 09:21 UTC, hichamboushaba commented
Thanks for the review @nbradbury, ready for another round.

> When I go to the Shipping Address screen, it already shows an error message under Name even though the user hasn't entered anything yet. I don't know if it's a big deal, but it is a change from develop.

I think this case was just missing before, as the goal is to highlight the element that causes the address non-validation, and for your case, the validator will return `NameMissing`, as it's the first thing being checked, this was done before for address1 field, but was missing for phone and name, so I added it.

2021-07-13 10:52 UTC, nbradbury approved these changes
Great work! :shipit:

2021-07-13 10:52 UTC, merged