Suppress `LargeClass` Detekt rule for tests
woocommerce/woocommerce-android pull request #4403
Opened 2021-07-12 16:27 UTC by wzieba

## Description

As discussed internally (p91TBi-5lF-p2#comment-5301) this PR suppresses `LargeClass` rule for test classes.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-07-12 19:01 UTC, shiki approved these changes
Using `develop`, I tested with `./gradlew detektAll`. I removed the `@Suppress` manually and I got these:

```
 shiki   develop U:2  ❲r❳ 2.6.4  ❲n❳ v14.4.0  ~/Projects/wooandroid/wooandroid-develop  ./gradlew detektAll

> Task :detektAll FAILED
complexity - 40min debt
        LargeClass - 649/600 - [CardReaderPaymentViewModelTest] at /Users/shiki/Projects/wooandroid/wooandroid-develop/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModelTest.kt:70:7
        LargeClass - 641/600 - [OrderDetailViewModelTest] at /Users/shiki/Projects/wooandroid/wooandroid-develop/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt:57:7

Overall debt: 40min


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':detektAll'.
> Build failed with 2 weighted issues.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
1 actionable task: 1 executed
```

Using this PR, I added random code in `OrderDetailViewModel` to make it a large class. I got this error: 

```

> Task :detektAll FAILED
complexity - 20min debt
        LargeClass - 702/600 - [OrderDetailViewModel] at /Users/shiki/Projects/wooandroid/wooandroid-develop/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt:79:7

Overall debt: 20min


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':detektAll'.
> Build failed with 1 weighted issues.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
1 actionable task: 1 executed
```

And I didn't get errors pertaining to `CardReaderPaymentViewModelTest` and `OrderDetailViewModelTest`. 

So I believe this is working correctly. The test classes are ignored for `LargeClass` while everything else (`e.g. OrderDetailViewModel`) is still checked for the rule.

2021-07-12 19:02 UTC, shiki commented
Obviously, now I just realized that I'm not really part of @woocommerce/android-developers so I can't merge this PR. 😅 Please merge it for me!

2021-07-13 07:46 UTC, kidinov commented on config/detekt/detekt.yml
> +    excludes: ['**/test/**', '**/androidTest/**']
I wouldn't exclude `androidTest`, because if we are talking about UI (espresso) tests then they can and should be writing in a concise way. Integration tests are not so common but they also can be written in a nice way - nothing stops us from it =)

2021-07-13 07:47 UTC, kidinov requested changes
Looks good to me! Just maybe consider removing `androidTest` from the exclusion?

2021-07-13 09:32 UTC, wzieba commented on config/detekt/detekt.yml
> +    excludes: ['**/test/**', '**/androidTest/**']
Sure, I'll do this in sec, just one concern:

> they also can be written in a nice way 

Do you think that disabling `LargeClass` will allow us to write tests (in general) in not a nice way? Maybe we shouldn't suppress this at all - or do you think it could be just a case only for UI tests?

2021-07-13 10:28 UTC, kidinov commented on config/detekt/detekt.yml
> +    excludes: ['**/test/**', '**/androidTest/**']
My point is just that historically unit tests class is basically a set of related but mostly independent tests which are placed in one class. And we consider this is ok 

For UI/integration tests that executed on the actual device, usually, it's better to separate, extract clickers/checkers per screen/flow, or whatever to keep the code readable and easier to fix the test in case of a change in the flow

2021-07-13 10:29 UTC, kidinov approved these changes
Thank you! Looks good

2021-07-13 10:29 UTC, merged

2021-07-13 10:30 UTC, wzieba commented on config/detekt/detekt.yml
> +    excludes: ['**/test/**', '**/androidTest/**']
Gotcha, that sounds totally reasonable - thanks for additional context!

2021-07-13 10:36 UTC, wzieba commented
@shiki 

> Obviously, now I just realized that I'm not really part of @woocommerce/android-developers so I can't merge this PR. 😅 Please merge it for me!

Today we've changed some of the permissions settings (p91TBi-5zV-p2) so next time you should be good with merging PRs in the Android repo too 😄 .