[Product Image Uploads] Step 3 - Display image upload details screen
woocommerce/woocommerce-android pull request #4432
Opened 2021-07-14 07:51 UTC by anitaa1990

Fixes #4331 

**This PR is part of a work in progress feature so it is merged against a feature branch. It is in draft till #4411 can be reviewed and merged**

### Changes
- Clicking on the `Details` button on the error snackbar displayed when image upload fails, redirects to a new screen. 
- This screen displays the list of images that failed to upload, along with the error message. 

### Notes
- This change will need to be added to `ProductDetailFragment` and `VariationDetailFragment` as well. I plan to tackle those in a separate PR since this one already includes a lot of change.
- Unit tests for `ProductImagesViewModel` will be taken care of in another PR.

### Screenshots
<img src="https://user-images.githubusercontent.com/22608780/125584213-b6814c0c-2769-4d52-8585-d37d8f38ffe7.gif" width="300"/>

### Testing
- Try to upload an image with an extension, other than `png, jpeg, jpg or gif`. There is local validation in FluxC so any images without these extensions will result in an error.
- Verify that the error snackbar is displayed with a DETAILS button. Click on the `Details` button and note that you are redirected to a new screen that displays a list of errors.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-07-14 14:23 UTC, kidinov requested changes
Looks good! I left a couple of comments, but have to wrap it up for today. I'll continue tomorrow =)

2021-07-14 14:23 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListFragment.kt
> +    private val mediaUploadErrorListAdapter: MediaUploadErrorListAdapter by lazy {
Why not to inject it with dagger?

2021-07-14 14:23 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListAdapter.kt
> +                MediaUploadErrorDiffUtil(
Matter of taste but imho this formatting looks confusing. Maybe just:

```
            val diffUtil = MediaUploadErrorDiffUtil(field, value)
            val diffResult = DiffUtil.calculateDiff(diffUtil, true)
```
?

2021-07-14 14:23 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListViewModel.kt
> +    val mediaUploadErrorList: LiveData<List<ProductImageUploadUiModel>> = _mediaUploadErrorList
Any reason to have this list as separate livedata? To me it looks like that this list is part of the view state

2021-07-14 14:23 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListFragment.kt
> +            Observer {
can be just 

```
viewModel.mediaUploadErrorList.observe(
            viewLifecycleOwner, { mediaUploadErrorListAdapter.mediaErrorList = it }
        )
```

`Observer` is not needed

2021-07-15 03:43 UTC, anitaa1990 commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListFragment.kt
> +    private val mediaUploadErrorListAdapter: MediaUploadErrorListAdapter by lazy {
Do you mean Hilt? Using Hilt for injecting the adapter? I didn't see a use case for it to be honest 😅 Is that an added benefit for injecting it with Hilt?

2021-07-15 03:45 UTC, anitaa1990 commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListViewModel.kt
> +    val mediaUploadErrorList: LiveData<List<ProductImageUploadUiModel>> = _mediaUploadErrorList
I thought about that but we don't really set a cap for the number of images a merchant can upload. So considering, we might at some point have someone upload 50 images at a stretch and 30 of them fails, a `livedata` would be a better usecase here than using the `ViewState`, which is only recommended for storing smaller data.

2021-07-15 03:47 UTC, anitaa1990 commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListAdapter.kt
> +                MediaUploadErrorDiffUtil(
👍 Fixed in b1dda34

2021-07-15 03:50 UTC, anitaa1990 commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListFragment.kt
> +            Observer {
You're right 😄 But it makes it easier to read when it's set as `Observer` so I implemented it that way 😅

2021-07-15 07:47 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListFragment.kt
> +    private val mediaUploadErrorListAdapter: MediaUploadErrorListAdapter by lazy {
Hilt is an extra layer on dagger. 

> Is that an added benefit for injecting it with Hilt?

There are several:
* Consistency across the codebase
* No need to change the code in the injection site (e.g. in your case in `MediaUploadErrorListFragment`) if constructor of `MediaUploadErrorListAdapter` changes
* You kind of have an illusion of inversion of control. Not really because we can not create fragments, but still imho it's better

2021-07-15 07:49 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListFragment.kt
> +            Observer {
It's just Android Studio complains

![image](https://user-images.githubusercontent.com/4923871/125750105-ec70e407-1560-4787-9c17-31e5cbbffdd2.png)

I think it make sense - why to not use the feature of the language?

2021-07-15 08:12 UTC, kidinov commented
Found a small bug (not the PR related but the project related):
* Turn on "don't keep activities"
* Click add photos
* Pick a photo
* Notice that the "select an upload method" dialog still visible

Otherwise looks and works good 👍

2021-07-15 09:41 UTC, anitaa1990 commented
> Found a small bug (not the PR related but the project related):
Turn on "don't keep activities"
Click add photos
Pick a photo
Notice that the "select an upload method" dialog still visible

This is a bug that is happening in the `develop` and release version of the app as well so unrelated to the changes in this PR :) So I'll open an issue for this and that this can be tackled separately 👍

2021-07-15 10:06 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListFragment.kt
> +    private val mediaUploadErrorListAdapter: MediaUploadErrorListAdapter by lazy {
I agree with @anitaa1990 on this, Hilt/Dagger will add a small build overhead for each type we add to the graph, and the overhead is not bothering us as we can get many benefits, especially the ability to swap dependencies for tests.

But for a recyclerview adapter, IMO the benefits don't justify it 🙂, and would be a restriction on the other hand, as we won't be able to pass objects that are not part of the graph to the Adapter's constructor easily, for example, we have the habit to pass lambdas as event listeners to the Adapter's constructor, if it was injected using Hilt, we won't be able to do it, and we would be required to have an interface for the listener, and inject the implementation as well...

2021-07-15 11:55 UTC, kidinov approved these changes
Good job 👍

Please go ahead with merging if [the comment](https://github.com/woocommerce/woocommerce-android/pull/4432/files#r670220200)
not really resonates with you

2021-07-16 04:08 UTC, anitaa1990 commented
Thank you for the review @kidinov! I'll merge this PR now 👍

2021-07-16 04:08 UTC, merged