issue/4413-payment-onboarding-basic-loading-ui
woocommerce/woocommerce-android pull request #4434
Opened 2021-07-14 10:46 UTC by nbradbury

This PR adds a very basic loading UI for the payment onboarding. There's a lot to be added here, including a loading animation and dark mode, but it's a start :)

![loading](https://user-images.githubusercontent.com/3903757/125609151-39be92e3-8fdf-4b89-8fe0-a675c8675fe0.png)

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-07-14 12:53 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/BaseOnboardingFragment.kt
> +abstract class BaseOnboardingFragment : Fragment {
❓ I'm a bit confused, I thought we discussed that we won't be introducing a fragment per screen. Did you encounter any issues replacing the layouts dynamically within one fragment?
I'm also not sure if we should be introducing a "Base" fragment using inheritance. But let's discuss that after we discuss the first point.

2021-07-14 13:55 UTC, nbradbury commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/BaseOnboardingFragment.kt
> +abstract class BaseOnboardingFragment : Fragment {
> I thought we discussed that we won't be introducing a fragment per screen.

I totally derped on that. I had it in my mind that we have a separate fragment for each state 🤦 I'll put this into draft state and change it.

2021-07-14 14:09 UTC, nbradbury commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/BaseOnboardingFragment.kt
> +abstract class BaseOnboardingFragment : Fragment {
That being said, one nice thing about using separate fragments is each fragment can take care of its own animations, button clicks, etc. If we use one fragment with separate layouts, then the logic for each layout is contained in a single fragment, which isn't ideal. What's the benefit of inflating separate layouts over using separate fragments?

2021-07-14 14:24 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/BaseOnboardingFragment.kt
> +abstract class BaseOnboardingFragment : Fragment {
What I had in mind was using almost the same structure that we use for Connect and Payments flows with the difference that we'd have a different layout for each state. The view state in that structure contains even the button listeners (function references) - example [here](https://github.com/woocommerce/woocommerce-android/blob/f2f2d93bf1b9cab3598ac08cadc59612bf03aa55/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt#L317). 

>  If we use one fragment with separate layouts, then the logic for each layout is contained in a single fragment, which isn't ideal

I assume you planned to have a single VM and share it between all the fragments, right? I feel like most of the logic will be contained within the VM anyway. The fragment would contain just mapping from viewstate -> view, handling navigation/events and animations. Moreover, we could even create a "ViewHolder like" wrapper for each state to separate it if needed.

> What's the benefit of inflating separate layouts over using separate fragments?

I feel like it'd be easier to grasp and maintain. The view layer should be very simple either case and since we'll share a single VM I feel like having `number of states + 1` fragments might be too much. 

All in all I think both approaches will work. I personally like the idea of different layouts more, but it's about a personal preference I guess. Let me know what you decide and I'll continue with the review ;)! Thanks

2021-07-16 13:39 UTC, nbradbury commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/BaseOnboardingFragment.kt
> +abstract class BaseOnboardingFragment : Fragment {
> I assume you planned to have a single VM and share it between all the fragments, right? I feel like most of the logic will be contained within the VM anyway. 

Sorry for the late reply! Yes, a single shared VM would be ideal.

> we could even create a "ViewHolder like" wrapper for each state to separate it if needed.

Hopefully that won't be necessary.

2021-07-22 12:41 UTC, nbradbury commented
@malinajirka I've taken this out of draft. There's a lot missing here, but as we discussed on Slack we decided it would be better to merge this now and deal with the individual layouts separately.

2021-07-23 09:19 UTC, malinajirka requested changes
Thanks @nbradbury! I've reviewed the code and left some suggestions/questions. Let me know what you think ;).

2021-07-23 09:19 UTC, malinajirka commented on WooCommerce/src/main/res/drawable/img_woocommerce_payments.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
⚠️ It seems this image broke during the import/optimization process - the fonts look weird
<img width="366" alt="Screenshot 2021-07-23 at 11 16 32" src="https://user-images.githubusercontent.com/2261188/126761993-d2b10a64-bf3d-46c1-a794-dc5e7fece548.png">

2021-07-23 09:19 UTC, malinajirka commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="payment_onboarding_title">In-person payments</string>
🔍 We have been using "card_reader_" prefix for strings related to the in-person payments. We might want to consider sticking with it for consistency, wdyt?

2021-07-23 09:19 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/BaseOnboardingFragment.kt
> +package com.woocommerce.android.ui.prefs.cardreader.onboarding
⚠️ It seems this class is not used in the code and AFAIU we don't plan to use it, right?

2021-07-23 09:19 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingLoadingFragment.kt
> +package com.woocommerce.android.ui.prefs.cardreader.onboarding
⚠️ It seems this class is not used in the code and AFAIU we don't plan to use it, right?

2021-07-23 09:19 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingFragment.kt
> +        // showOnboardingLayout(binding, R.layout.fragment_card_reader_onboarding_loading)
🔍 I believe we can remove this line as state changes are handled in `iewModel.viewStateData.observe`. Wdyt?

2021-07-23 09:19 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingFragment.kt
> +    private fun showOnboardingLayout(binding: FragmentCardReaderOnboardingBinding, @LayoutRes layoutRes: Int) {
💡 I'm wondering if we could replace this whole method with 
```
        binding.container.removeAllViews()
        LayoutInflater.from(requireActivity()).inflate(layoutRes, binding.container, true)
```
and set `android:animateLayoutChanges="true"` on the `container`. 

The animation would be handled by the system and the code would be much simpler, wdyt?

2021-07-23 09:19 UTC, malinajirka commented on WooCommerce/src/main/res/layout/fragment_card_reader_onboarding.xml
> +    <FrameLayout
❓ I'm wondering if we need the parent `ConstraintLayout` - it seems the only child is the framelayout, so perhaps we could remove the `ConstraintLayout` completely, wdyt?

2021-07-23 10:44 UTC, nbradbury commented
Sorry @malinajirka, I kind of blindly submitted this as-is. I made your suggested changes so ready for another round.

2021-07-23 11:53 UTC, malinajirka approved these changes
No reason to apologize, great job working on this! ;) 🚢

2021-07-23 11:53 UTC, merged