issue/4413-pending-requirements-button
woocommerce/woocommerce-android pull request #4535
Opened 2021-07-30 18:39 UTC by nbradbury

This PR adds a "Skip" button to the "pending requirements" screen of the onboarding flow. When tapped, this directs the user to the "Manage card reader" screen.

![pending](https://user-images.githubusercontent.com/3903757/127697102-a52fb33c-d483-4a66-9fc4-994627d10424.png)

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-08-02 09:54 UTC, malinajirka reviewed
Thanks for working on this @nbradbury! I've left a few questions to better understand the decisions ;).

2021-08-02 09:54 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
> +            abstract val onButtonActionClicked: (() -> Unit?)?
💡 We might want to consider replacing this with `open val onButtonActionClicked: (() -> Unit?)? = null` to avoid adding the lambda to all the states even though they don't have any buttons right now. Wdyt?

2021-08-02 09:54 UTC, malinajirka commented on WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_stripe.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
⚠️ Could you please elaborate why we need to have a parent here? Also could we perhaps use FrameLayout instead since there is only one child? Wdyt?

2021-08-02 09:54 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
> +        handleResult<String>(CardReaderOnboardingFragment.KEY_READER_ONBOARDING_RESULT) {
❓ I'm still relatively new to the navigation component, however, I'm wondering what is the benefit of going back to the MainSettingsFragment => can't we navigate to "CardReaderDetailFragment" directly from the onboarding flow? We'll be navigating there also every time the onboardingChecks succeeds (not just when the user taps on skip). I don't think it matters that much, it just feels weird that the MainSettingsFragment needs to know about this behavior even though it's just an entry point. Wdyt?

2021-08-02 12:07 UTC, nbradbury commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt
> +        handleResult<String>(CardReaderOnboardingFragment.KEY_READER_ONBOARDING_RESULT) {
My rationale here was to avoid adding another destination to the nav graph, since settings already navigates to the manage card reader screen. But given that there are several situations where we'll go from onboarding -> manage screen, it makes sense to add a new destination. I'll change this and ping you when it's ready.

2021-08-02 14:42 UTC, nbradbury commented on WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_stripe.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
The problem I was hoping to address was trying to keep the "Learn more" label fixed to the bottom, which meant leaving it outside the scroll view and therefore requiring another parent. But that ended up not working well, especially in landscape. I'll change this.

2021-08-02 14:48 UTC, nbradbury commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
> +            abstract val onButtonActionClicked: (() -> Unit?)?
**TIL**

2021-08-02 17:16 UTC, nbradbury commented
@malinajirka This is ready for another round. I ended up moving the `ScrollView` to the main onboarding fragment, to make sure any sub-screen that needs to scroll can do so. I also updated the navigation graph to include a destination from the onboarding screen to the manage card reader screen.

2021-08-03 08:59 UTC, malinajirka requested changes
Thanks @nbradbury! The code looks good overall. I've left two super minor nitpick, however, I noticed the "skip" button is rendered on top of "Contact support" on my device in landscape.
![Screenshot_20210803-103600_WooCommerce (Dev)](https://user-images.githubusercontent.com/2261188/127985291-e9adb692-f618-4734-8a5b-e3902ef4346e.jpg)

I was curious about the layout and I tried to fix this issue in `issue/4413-skip-button-jirka-test`. It's definitely not the only solution and perhaps it introduces another bug - but I thought I'd share it in case you'd find it useful ;). (P.S. this approach works only when it's nested in a scrollview, so don't rely on the AS preview, since the scrollview lives in a parent so AS doesn't know about it).

2021-08-03 08:59 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
> +                override val onButtonActionClicked: (() -> Unit?)?,
🔍 Nitpick: We might want to consider removing `?` operator here, since "WCPayAccountPendingRequirementsState" state should always contain a button -> we limit the number of possible combinations when we remove the nullability operator.

2021-08-03 08:59 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
> +        object NavigateToManageCardReader : Event()
🔍 Nitpick: "Manage card reader" is a user facing string, we call it "CardReaderDetail" in code. We might want to consider renaming this. Wdyt?

2021-08-03 11:43 UTC, nbradbury commented
> I was curious about the layout and I tried to fix this issue in `issue/4413-skip-button-jirka-test`

Thanks for that, I was struggling to get this view working on various screens. I'm wondering, though, if it would be better to simplify this to a vertical `LinearLayout`. That takes care of every screen size and orientation, at the expense of having the "Learn more" label fixed to the bottom on portrait.

2021-08-03 11:55 UTC, malinajirka commented
> @malinajirka Thanks for that, I was struggling to get this view working on various screens. I'm wondering, though, if it would be better to simplify this to a vertical LinearLayout. That takes care of every screen size and orientation, at the expense of having the "Learn more" label fixed to the bottom on portrait.

I'd personally prefer to stick with constraint layout. I think it's more extensible/flexible and we don't know how will this screen evolve. If we continue having troubles with these visible/invisible/gone views, I'd prefer to split "fragment_card_reader_onboarding_stripe.xml " into multiple layouts - one for pending/overdue/rejected/etc states. But since it seems to work now, I wouldn't worry about it until we find the real need. 

Having said  all that, I think this is again mostly about personally preference than one being better than the other, so feel free to migrate it to LinearLayout ;).

2021-08-03 14:20 UTC, nbradbury commented
@malinajirka I went ahead and stuck with a constraint layout using your suggestion. Ready for another round!

2021-08-03 14:45 UTC, malinajirka approved these changes
LGTM and works as expected, thanks! ;)

2021-08-03 14:45 UTC, merged