Issue/4413 onboarding generic error
woocommerce/woocommerce-android pull request #4541
Opened 2021-08-02 19:51 UTC by nbradbury

Parent issue #4413 - this PR implements the generic error state for the onboarding flow. Note that there were no designs for this screen, so a design review is required.

**Do not merge:** #4535 needs to be merged first.

![generic](https://user-images.githubusercontent.com/3903757/127914387-29c9b7d0-0ebd-4bf1-9504-33c40975d826.png)

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-08-03 08:30 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
>              }
Not your change, but just to consider in the next PRs - make it `.exhaustive`  maybe?

2021-08-03 08:43 UTC, kidinov approved these changes
Looks good! Just 2 things to consider:

* Shell be the content be centered between the top and "close" button? Maybe I'm wrong but it looks it's the case for other error screens
* Maybe as part of the another PR probably would be nice to check if all View IDs and the layouts (currently they are `fragment...` ) are following the convetion we voted couple of weeks ago - https://github.com/woocommerce/woocommerce-android/blob/develop/CONVENTION.md#view-ids

2021-08-03 08:43 UTC, kidinov commented on WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_stripe.xml
> +        android:id="@+id/learn_more_container"
nit: shell we call it `learnMoreContainer` to follow the view's IDs convention?

2021-08-03 17:34 UTC, nbradbury commented
> Shell be the content be centered between the top and "close" button? Maybe I'm wrong but it looks like it's the case for other error screens

@kidinov You're right, that screen is a little off. I updated it to more closely match the other onboarding screens in 9f072b4.

![generic](https://user-images.githubusercontent.com/3903757/128060360-3c7453b0-36f8-45d0-be6b-28cdb3c0a88b.png)

2021-08-04 06:45 UTC, kidinov commented
@nbradbury it's approved, from my side, let's see what @woocommerce/mobile-designers will say =)

2021-08-04 06:54 UTC, adamzelinski commented
Hey @nbradbury, I've done a design for Android and iOS for this error. Could we please use this instead.

CC: @Garance91540 

<img width="1382" alt="Screen Shot 2021-08-04 at 4 49 47 pm" src="https://user-images.githubusercontent.com/74938219/128135224-36595615-8679-4dd9-a416-a76d6df68c2c.png">

2021-08-04 08:23 UTC, Garance91540 approved these changes
Agreeing with Adam's changes ;)

2021-08-04 08:23 UTC, Garance91540 requested changes
^

2021-08-04 10:39 UTC, nbradbury commented
@adamzelinski @Garance91540 I'll update this to match the design (thank you!), but I'm wondering why we need to say "Unable to verify In-Person Payments for this store" twice?

2021-08-04 12:09 UTC, nbradbury commented
@kidinov I've updated the screen to match the above design. If it's okay with you, I'd prefer to merge this now and if there's any feedback about the wording we can address that later.

![generic](https://user-images.githubusercontent.com/3903757/128178209-a35e2f42-f90a-48a6-aac3-227db6c3d7bc.png)

2021-08-04 12:21 UTC, kidinov commented
@nbradbury totally ok with me =)

2021-08-04 16:03 UTC, Garance91540 approved these changes

2021-08-04 16:03 UTC, merged