issue/4525-support-push-notifications-for-all-stores
woocommerce/woocommerce-android pull request #4673
Opened 2021-08-24 12:21 UTC by anitaa1990

Closes: #4525 

### Description
This PR adds some logic around supporting push notifications for all stores. The changes include:
- Set `site=null` in `[NotificationRegistrationHandler](https://github.com/woocommerce/woocommerce-android/blob/daf6168ee7646683b15590a8ccc9699e25d362c5/WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationRegistrationHandler.kt#L24) when registering the device for notifications. This allows the backend to send push notifications for all the stores the user is logged into from the app.
- Multiple notifications in android are bundled based on the `group`, defined by us, as developers. Currently, the logic for group notifications is:
	- There are 3 different types of notifications we support: new order, new review and Zendesk notifications. All 3 types of notifications are grouped separately.
	- Notifications for different stores are displayed separately, similar to how Gmail app - display notifications for separate accounts in separate groups.
- So the logic is to group notifications based on a `groupId` as well as the `siteId`.
- When notifications are clicked, if the `selectedSiteId` does not match the `siteId` from the notification, we update the `selectedSite` and then redirect the user to appropriate screen for that store.
- Added unit tests and updated existing unit tests.

### Testing instructions
#### Orders
<table>
  <tbody>
    <tr>
      <th>Scenario</th>
      <th>Expected Behaviour</th>
    </tr>
    <tr>
      <td>1 order from Store 1 only (the current actibe store in the app should be Store1)</td>
      <td>
		<ul>
          <li>1 notification should be received in the app.</li>
          <li>Clicking on the notification should:
			<ul>
		      <li>Open the order detail for Store1</li>
		      <li>The notification should be dismissed from the notification tray</li>
		    </ul>
		  </li>
          <li>Repeat this scenario again but instead of clicking on the notification, dismiss it. Notice that it is no longer displayed in the notification tray.</li>
        </ul>
	   </td>
    </tr>
	<tr>
      <td>1 order from Store 2 only (the current active store in the app should be Store1)</td>
      <td>
		<ul>
          <li>1 notification should be received in the app.</li>
          <li>Clicking on the notification should:
			<ul>
		      <li>Open the order detail for Store2 (even though the current active store was Store1)</li>
		      <li>The notification should be dismissed from the notification tray</li>
		    </ul>
		  </li>
          <li>Repeat this scenario again but instead of clicking on the notification, dismiss it. Notice that it is no longer displayed in the notification tray.</li>
        </ul>
	   </td>
	</tr>
	<tr>
      <td>2 orders from Store 1 only (the current active store in the app should be Store1)</td>
      <td>
		<ul>
          <li>2 notifications should be received in the app. They should be grouped together.</li>
          <li>Clicking on the one notification should:
			<ul>
		      <li>Open the order detail for that order</li>
		      <li>Only that notification should be dismissed from the notification tray.</li>
		      <li>The second notification should still be visible. Clicking on this second notification should open the order detail for this order.</li>
		    </ul>
		  </li>
          <li>Repeat this scenario again but instead of clicking on the the first notification, dismiss it. Notice that the first notification is no longer displayed in the notification tray.</li>
        </ul>
	   </td>
	</tr>
	<tr>
      <td>2 orders from Store 2 only (the current active store in the app should be Store1)</td>
      <td>
		<ul>
          <li>2 notifications should be received in the app. They should be grouped together.</li>
          <li>Clicking on the one notification should:
			<ul>
		      <li>Open the order detail for that order (even though the current active store is Store1, clicking on this notification changes the current active store to Store2)</li>
		      <li>Only that notification should be dismissed from the notification tray.</li>
		      <li>The second notification should still be visible. Clicking on this second notification should open the order detail for this order.</li>
		    </ul>
		  </li>
          <li>Repeat this scenario again but instead of clicking on the the first notification, dismiss it. Notice that the first notification is no longer displayed in the notification tray.</li>
        </ul>
	   </td>
	</tr>
	<tr>
      <td>2 orders from Store 1 and 2 orders from Store 2</td>
      <td>
		<ul>
          <li>4 notifications should be received in the app. Store1 notifications should be grouped separately and Store2 notifications should be grouped separately.</li>
          <li>Clicking on the the 1st notification from Store1 notification should:
			<ul>
		      <li>Open the order detail for that order</li>
		      <li>Only that notification should be dismissed from the notification tray.</li>
		    </ul>
		  </li>
          <li>Clicking on the the 1st notification from Store2 notification should:
			<ul>
		      <li>Open the order detail for that order for that Store.</li>
		      <li>Only that notification should be dismissed from the notification tray.</li>
		    </ul>
		  </li>
          <li>Dismiss the 2nd notification from Store1:
			<ul>
		      <li>Only that notification should be dismissed from the notification tray. The notification from the 2nd order from Store2 should still be visible</li>
		    </ul>
		  </li>
          <li>Dismiss the 2nd notification from Store2:
			<ul>
		      <li>Only that notification should be dismissed from the notification tray. No notifications should be displayed in the notifications tray.</li>
		    </ul>
		  </li>
        </ul>
	   </td>
	</tr>
	<tr>
      <td>2 orders from Store 1 and 2 orders from Store 2</td>
      <td>
		<ul>
          <li>4 notifications should be received in the app. Store1 notifications should be grouped separately and Store2 notifications should be grouped separately.</li>
          <li>Click on the Store1 notifications as a group:
			<ul>
		      <li>It should open the order list for that store</li>
		      <li>Store1 notifications should no longer be displayed in the notification tray.</li>
		    </ul>
		  </li>
          <li>Click on the Store2 notifications as a group:
			<ul>
		      <li>It should open the order list for that store</li>
		      <li>Store2 notifications should no longer be displayed in the notification tray.</li>
		    </ul>
		  </li>
        </ul>
	   </td>
	</tr>
	<tr>
      <td>2 orders from Store 1 and 2 orders from Store 2</td>
      <td>
		<ul>
          <li>4 notifications should be received in the app. Store1 notifications should be grouped separately and Store2 notifications should be grouped separately.</li>
          <li>Dismiss the Store1 notifications as a group:
			<ul>
		      <li>Store1 notifications should no longer be displayed in the notification tray.</li>
		    </ul>
		  </li>
          <li>Click on the Store2 notifications as a group:
			<ul>
		      <li>Store2 notifications should no longer be displayed in the notification tray.</li>
		    </ul>
		  </li>
        </ul>
	   </td>
	</tr>
	<tr>
      <td>2 orders from Store 1 and 2 orders from Store 2</td>
      <td>
		<ul>
          <li>4 notifications should be received in the app. Store1 notifications should be grouped separately and Store2 notifications should be grouped separately.</li>
          <li>Dismiss all the notifications in the tray by clicking on the `Clear` button.
			<ul>
		      <li>All notifications should be dismissed</li>
		    </ul>
		  </li>
        </ul>
	   </td>
	</tr>
  </tbody>
</table>

#### Reviews
<table>
  <tbody>
    <tr>
      <th>Scenario</th>
      <th>Expected Behaviour</th>
    </tr>
    <tr>
      <td>1 review from Store 1 only (the current active store in the app should be Store1)</td>
      <td>
		<ul>
          <li>1 notification should be received in th [...]

2021-08-31 12:09 UTC, anitaa1990 commented
@hafiz, the issue you found in #4691 is fixed in this commit: 56aacc3. Turns out it was very simple and I didn't want to open a separate PR for this 😄 

@hichamboushaba thank you for reviewing this PR :) I apologise for the number of test scenarios in this PR to test. Also I just committed a fix for #4691 that Hafiz found in 56aacc3.

2021-08-31 15:47 UTC, hichamboushaba requested changes
Great work Anitaa 👏, I found two issues after testing:
1. the code here https://github.com/woocommerce/woocommerce-android/blob/09f53dbe54415a1c156d7d3bbc011d5e27500f85/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsActivity.kt#L115-L125 doesn't make sense anymore, so it should be deleted I think.
2. To finish the tests, I had to remove the app's data, because after upgrading from previously installed one, I kept getting notifications only for the site which was selected before upgrading, and after upgrading, switching sites didn't have any impact on notifications, I kept getting them for the previous one always. I tried to confirm that we send the token after upgrade, and we do, so I'm thinking there is some logic in backend that doesn't refresh the site when we send the same token 🤔

2021-08-31 15:47 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/model/Notification.kt
> +    fun getGroup(channelId: String): String = "$channelId $remoteSiteId"
just a question, and probably I'm missing something 🙂, why not use the `channelType.getChannelId()` instead of passing the `channelId` as parameter? I know `getChannelId` returns Int, but it should be fine, since we just need unique identifier.

2021-08-31 15:47 UTC, hichamboushaba commented on WooCommerce/src/test/kotlin/com/woocommerce/android/push/NotificationMessageHandlerTest.kt
> +    fun `display two new order notification details for different stores correctly`() {
np, it's not a blocker, but this is different from the convention about tests naming (https://github.com/woocommerce/woocommerce-android/blob/develop/CONVENTION.md)

2021-09-01 09:07 UTC, anitaa1990 commented on WooCommerce/src/test/kotlin/com/woocommerce/android/push/NotificationMessageHandlerTest.kt
> +    fun `display two new order notification details for different stores correctly`() {
Ooh, thanks for the reminder! I updated the test names in ae52ace 👍

2021-09-01 09:10 UTC, anitaa1990 commented on WooCommerce/src/main/kotlin/com/woocommerce/android/model/Notification.kt
> +    fun getGroup(channelId: String): String = "$channelId $remoteSiteId"
Ah, that's a good point! I guess I wanted the `channelId` to be the same across notifications 😅 . Having the actual string resource passed in this method (which is the channelId used when creating the channels), as opposed to having the resource id as an int here.

2021-09-01 09:25 UTC, anitaa1990 commented
Thank you for the review @hichamboushaba 😄 

> doesn't make sense anymore, so it should be deleted I think.

That's a really good catch! Thank you! Removed in c4a10fb.

> To finish the tests, I had to remove the app's data, because after upgrading from previously installed one, I kept getting notifications only for the site which was selected before upgrading, and after upgrading, switching sites didn't have any impact on notifications, I kept getting them for the previous one always. 

That's weird! The code to validate if a notification has to be sent or not, can be found [here](https://opengrok.a8c.com/source/xref/trunk/wp-content/lib/push-notifications/filters/10-should-deliver-to-woocommerce.php?r=230451#47). If the `site_id` is null, we assume the app supports multi site notifications and initiate the push notification. Ah, maybe for that particular token that existed before this PR change, the `site_id` is not null so the notification might not be initiated 🤔

2021-09-01 09:33 UTC, hichamboushaba commented
> That's weird! The code to validate if a notification has to be sent or not, can be found here. If the site_id is null, we assume the app supports multi site notifications and initiate the push notification. 

Just to be sure it's nothing on my end, were you able to reproduce the issue?

> Ah, maybe for that particular token that existed before this PR change, the site_id is not null so the notification might not be initiated 🤔

Yes, I think the backend keeps track of the old `site_id`, but why it does so? I'm trying to find the code responsible of storing the tokens

2021-09-01 09:40 UTC, anitaa1990 commented
> Just to be sure it's nothing on my end, were you able to reproduce the issue?

So I had logged into my normal test site in the app (Store1). I switched sites to a different one (Store2) and then tested the changes in this PR. I got notifications for Store1 (even though I'm logged into Store2 at the moment). I am assuming this is a variation to the same issue you mentioned since the token for Store1 is still valid somewhere and that's why the notification is not received for Store2 (even though it's the currently active one).

I tried initiating a notification from MC dashboard and I am able to receive the notification correctly so there must be the logic in the API that needs changing.

2021-09-01 09:40 UTC, hichamboushaba commented
@anitaa1990 I think I found something, but I'm not sure yet.
This code here: https://opengrok.a8c.com/source/xref/trunk/public.api/rest/wpcom-json-endpoints/class.wpcom-json-api-push-notifications-register-device-endpoint.php?r=225350#136, it iterates over the existing fields of the previous token, and updates only the ones that we sent new values for.

But in FluxC, we omit the `selected_blog_id` if it's null: https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/2423bd14c411aa76dd727939bbf082948a9d1a42/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/notifications/NotificationRestClient.kt#L72, which probably means that we don't update it if it was already present, and would explain the behavior I noticed.

I wonder if there is an easy way to force `token` refresh on our side, we can probably add a code to be executed once after the update to 7.5 🤔

2021-09-01 09:45 UTC, anitaa1990 commented
> This code here: opengrok.a8c.com/source/xref/trunk/public.api/rest/wpcom-json-endpoints/class.wpcom-json-api-push-notifications-register-device-endpoint.php?r=225350#136, it iterates over the existing fields of the previous token, and updates only the ones that we sent new values for.
But in FluxC, we omit the selected_blog_id if it's null: wordpress-mobile/WordPress-FluxC-Android@2423bd1/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/notifications/NotificationRestClient.kt#L72, which probably means that we don't update it if it was already present, and would explain the behavior I noticed.

Nice find! We should be able to update the `blog_id` in the API since it's not the same as the previous token (in that it's absent). I'll move this discussion to Slack and ping Jeremy since he's at a much better than me to decide if we can update the logic on the API side. Thanks @hichamboushaba!

2021-09-03 05:22 UTC, anitaa1990 commented
@hichamboushaba The API changes for this has been approved [here](https://code.a8c.com/D66286). It's not yet deployed (I don't have access and Aaron is afk till Tuesday). Given that it's a day before code freeze and it's a big change, I think we can wait till Tuesday to deploy this and test in this PR before merging. That way we have a couple of weeks for the feature to be tested before it's released to beta. WDYT?

2021-09-03 08:40 UTC, hichamboushaba commented
I agree @anitaa1990, let's move it to 7.6 to have a chance to catch any issues before releasing it 👍

2021-09-13 10:30 UTC, anitaa1990 commented
Hey @hichamboushaba, the API changes will be deployed later today. Would you be able to test that change from this PR, once the deployment is completed?

2021-09-13 12:20 UTC, hichamboushaba commented
Hey @anitaa1990, yes, I can test them, I'll check with Aaron when they are merged to retest the PR.

2021-09-14 12:06 UTC, anitaa1990 commented
I tested the API changes by following these steps and everything works great 🎉 
- Install the latest `develop` version on a test device and login to the app.
- Pull the changes from this PR and install this version in the same device.
- Try initiating notifications from 2 of your test stores and verify that notifications are received in the app for both those stores.

cc @hichamboushaba, can you take a look at this one tomorrow please! Thank you!

2021-09-15 14:45 UTC, hichamboushaba commented
@anitaa1990 I tried to retest this, but I'm finding a weird thing, even if I uninstall the app, I keep getting notifications for only the first store in my list of sites, you can get notifications from all stores when you uninstall/reinstall the app?

2021-09-15 16:47 UTC, hichamboushaba approved these changes
It turned out it's working for me, I'm receiving notifications for all stores even when upgrading :tada: 

When I first tested, I used a test account, for which the notifications didn't work for one of my 2 stores. So I tested the same account with an older version, and it didn't work either, so just something in my wp.com settings.
When I tested with my main account, everything works as expected.

Great work @anitaa1990, I'll hold on merging until you figure out what did cause the issue on your side.

2021-09-15 17:31 UTC, hichamboushaba commented
Something else that I noticed when testing, we keep re-sending the same token when changing stores, even though doesn't have any effect now, I tracked it to this line: https://github.com/woocommerce/woocommerce-android/blob/8bca773c000e74c2ece957204f24cf2745f98d96/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt#L428
I wonder if it's worth an optimization or not, and surely not part of this PR.

2021-09-15 18:11 UTC, anitaa1990 commented
Thanks for testing @hichamboushaba! 

 > When I first tested, I used a test account, for which the notifications didn't work for one of my 2 stores. So I tested the same account with an older version, and it didn't work either, so just something in my wp.com settings.
When I tested with my main account, everything works as expected.

I tested with a secondary device and I was able to receive notifications from 2 stores without having to clear the app data 🎉 I assume the issue I had was something to do with my primary device being buggy 🤦‍♀️

2021-09-15 18:26 UTC, anitaa1990 commented
> Something else that I noticed when testing, we keep re-sending the same token when changing stores, even though doesn't have any effect now, I tracked it to this line:

That's a good point! I'll fix this in a separate PR, if that's ok with you 👍 Thanks for the reminder 😄

2021-09-16 08:26 UTC, merged