Implemented support for update cancelation
woocommerce/woocommerce-android pull request #4747
Opened 2021-09-08 07:23 UTC by kidinov

Closes: #

### Description

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-09-08 13:30 UTC, malinajirka requested changes
Thanks for working on this @kidinov! It looks good overall. I encountered one scenario in which I expected a bit different behavior.

1. Start connecting
2. Start Update
3. Tap on cancel -> I'd expect to end up on the "Cancel anyway" state, but it actually cancels the flow without any warning.
Imo, the first tap on cancel should be identical to tapping on "back" button. Wdyt?

2021-09-08 13:30 UTC, malinajirka commented on libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/BluetoothReaderListenerImpl.kt
> +        cancelUpdateAction = cancelable
💡 🔍 Nitpick:  Originally non-stripe classes in CardReaderModule were stateless with two partial exceptions
1. `CardReaderManagerImpl.isInitialized` 
2. `ConnectionManager.readerStatus`

However, both of these cases were actually handled by Stripe SDK and the module was just a middleman.

We decided to introduce some StateFlows which make the classes stateful, but the classes are still acting just as a middle man. However, introducing `cancelUpdateAction` field breaks this pattern and tbh I'm not sure it's worth it. Debugging issues in stateful classes is incomparable more complicated than in stateless classes. One solution we previously used to avoid keeping state within CardReaderModule was an introduction of a wrapper around Stripe's class and passing the state back to the client eg. `CardReader` and `CardReaderImpl` or `PaymentData`. I'd personally consider using the same pattern here. Wdyt?

2021-09-09 09:57 UTC, kidinov commented on libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/BluetoothReaderListenerImpl.kt
> +        cancelUpdateAction = cancelable
This is the way I started to implement it first. I was passing cancel action via `InstallationStarted`. It didn't look nice tbh from the code point of view - we mixing state with behavior (neither current approach looks nice though =) ). 

Also, I was concerned that it's almost definitely a memory leak - we don't know the lifecycle of the `Cancelable`, but we can guess that's it can be longer than a ViewModel

I can try to make a branch with this approach and we can assess it. Will it make sense?

2021-09-09 10:58 UTC, malinajirka commented on libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/BluetoothReaderListenerImpl.kt
> +        cancelUpdateAction = cancelable
> Also, I was concerned that it's almost definitely a memory leak - we don't know the lifecycle of the Cancelable, but we can guess that's it can be longer than a ViewModel

If we kept the cancelable in the vm and vm's life would be shorter, then it wouldn't  be a memory leak, would it?


Either way, if you already considered this approach and it didn't look good I think there is no need to create a branch with it. Thanks though ;).

2021-09-09 11:40 UTC, kidinov commented
@malinajirka I changed this behavior there - https://github.com/woocommerce/woocommerce-android/pull/4747/commits/5db8b211606c839ca14553389cd92572d118d2a1

Visually it's like that now:

https://user-images.githubusercontent.com/4923871/132679343-d02a5d11-9e0e-4f3a-9ffe-e8186c0b3ec9.mp4

2021-09-10 06:56 UTC, malinajirka approved these changes
LGTM, thanks for the changes!

2021-09-10 06:56 UTC, merged