Issue/4962 Connection dialog disappears after required update
woocommerce/woocommerce-android pull request #4965
Opened 2021-10-07 11:47 UTC by kidinov

Closes: #4962 

### Description

The PR:
* Makes `readersStatus` the single source of truth of the connection status. It was causing in some cases that we were triggering ExitWithResult twice
* Cancels coroutine which open the update dialog after it's been opened. It was causing the firing of  the `ShowUpdateInProgress` multiple times

### Testing instructions

1. Make an update required via `TerminalWrapper`
2. Try to collect money for an order
3. Notice that after the required update succeeds collection flow keeps going

### Images/gif

https://user-images.githubusercontent.com/4923871/136378150-cf3e21d4-d9c2-4477-b534-62a4bc8b3859.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-10-07 11:48 UTC, kidinov commented
@AnirudhBhat @malinajirka asking you both to review this, because the change is quite important

2021-10-08 06:40 UTC, AnirudhBhat commented
Good job @kidinov! I've tested the PR and it works as expected. The code looks good to me as well. But, I'll also wait for @malinajirka's opinion on this.

2021-10-11 09:49 UTC, malinajirka requested changes
Thanks @kidinov! Great idea to simplify the `connection status handling` and making sure we have a single source of truth. I like the approach a lot. However, I'm a bit worried the code in the VM has to many "secret" dependencies right now -> eg. it needs to know when to listen for sw updates when to listen for connection updates, when to cancel the listeners -> I'm wondering if we could simplify it somehow. Wdyt?

2021-10-11 09:49 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +        updateStatusJob = launch {
❓ Should we cancel the previous `updateStatusJob` here? 

Example scenario
1. onCardReaderManagerInitialized
2. Connect clicked
3. Connection fails
4. Retry clicked
5. onCardReaderManagerInitialized invoked again, but the previous `updateStatusJob` wasn't canceled.

Or could we register for the updates in `init` of the VM and listen for them all the time to simplify the "state handling"?

2021-10-11 09:49 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +                updateStatusJob?.cancel()
❓ I'm wondering why we need to cancel the job here. You mentioned `Cancels coroutine which open the update dialog after it's been opened. It was causing the firing of the ShowUpdateInProgress multiple times` in the description. However, I'm missing the reason why it matters. It's imo okay that we trigger the ShowUpdateInProgress multiple times as long as the update is in progress - it has very minor performance hit, but I assume that's not the main issue, right? Could you please elaborate, thanks!

I'm asking, because the more we create dependencies between the states the more difficult it'll be to get oriented in the VM and understand the logic. Also the more difficult it will be to re-use the cardReaderModule in other parts of the app.

Wdyt?

2021-10-11 09:49 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +        launch {
❓ Similar as the above, do we need to cancel the previous job here? If the connection fails and the user taps on "retry" we'll invoke `connectToReader` again, right?

2021-10-11 09:49 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +            listenToConnectionStatus(cardReaderManager)
⚠️ If the listening starts before the `startConnectionReader` is invoked, the VM might display "connection failed" state, wdyt?

2021-10-11 09:49 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
>          cardReaderManager.readerStatus.collect { status ->
💡 In general, I prefer avoiding states as much as possible, however, in this case I think it might simplify the logic. What if we registered to connection status updates in `init` of the VM. We'd store the previous state and show "connectionFailed" only when the previous state was "connecting". We wouldn't need any logic related to when to start and stop listening for the updates. Wdyt?

2021-10-11 12:13 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +                updateStatusJob?.cancel()
That's the main fix for the problem. I can not explain why this happens, but from my understanding, there is some kind of race condition between the "update 95% progress" event and the "connected" event. The first one tries to navigate to the Update dialog, the second attempts to close Connect dialog with the result pretty much at the same time

2021-10-11 12:31 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +        updateStatusJob = launch {
Good catch! https://github.com/woocommerce/woocommerce-android/pull/4965/commits/2191e3c0b2f71738a091f92649023a319fbe90d9

> Or could we register for the updates in init of the VM and listen for them all the time to simplify the "state handling"?

It would be nice, but then the issue won't be fixed, because we apparently can fire `ShowUpdateInProgress` just once

2021-10-11 12:32 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +                updateStatusJob?.cancel()
AFAIU [this PR](https://github.com/woocommerce/woocommerce-android/pull/4979/files) will fix the issue of navigation back to the initiator of the connection flow - do we still need to manually cancel the job here?

2021-10-11 13:46 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
>          cardReaderManager.readerStatus.collect { status ->
But we get an instance of `CardReaderManager` only in `onCardReaderManagerInitialized` or do you propose to refactor this too?

2021-10-11 13:51 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +        launch {
If I am not mistaken we have the same problem with all "launch {" calls in this VIewModel (in v1 too). We restart the whole flow in case of an error but we use VM scope. Probably it makes sense to create a separate scope and clean this up in another PR, wdyt?

2021-10-11 13:55 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +            listenToConnectionStatus(cardReaderManager)
Indeed this is what happens, although not visible to a user. Depending on what you think [here](https://github.com/woocommerce/woocommerce-android/pull/4965#discussion_r726133474) it might be get fixed by bigger change in the approach though

2021-10-11 14:10 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +        launch {
I don't think we do. The code in v1 is written in sequential order and each launch terminates either with a success or an error - none of them is an infinite listener.
The discovery in v1 runs even after the `connectToReader` is initiated (they run in parallel) - but both of them finish with success/error before the flow is restarted. 
Wdyt?

2021-10-11 14:14 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +        updateStatusJob = launch {
> because we apparently can fire ShowUpdateInProgress just once

ohh I see, the issue is that we can't invoke 
```
findNavController().navigateSafely(
                        CardReaderConnectDialogFragmentDirections
                            .actionCardReaderConnectDialogFragmentToCardReaderUpdateDialogFragment(
                                requiredUpdate = true
                            )
                    )
```
twice. This is related to the other comments, I'll reply there.

2021-10-11 14:20 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
>          cardReaderManager.readerStatus.collect { status ->
I see, perhaps `init` is not the best place. But I think we could keep `isInitialized` state in the VM and subscribe/startListening for the updates just once. We completely changed the design of the card reader module in v2 and I believe we need to make these adjustments to keep the code maintainable. Wdyt?

2021-10-12 08:39 UTC, kidinov commented
Closed in favour 
https://github.com/woocommerce/woocommerce-android/pull/4990
and 
https://github.com/woocommerce/woocommerce-android/issues/4989

2021-10-12 08:39 UTC, closed without merging