Issue/4864 jetpack benefits bottom banner
woocommerce/woocommerce-android pull request #4995
Opened 2021-10-12 14:43 UTC by hichamboushaba

Closes: #4864 

### Description
This PR adds a bottom banner that allows checking the Jetpack benefits when the current site doesn't have full Jetpack, it can be dismissed by the user, and will be re-displayed after 5 days from dismissal date.

Clicking on the banner will be handled in a separate PR.

### Testing instructions
1. You need a site that has Jetpack CP for this test.
2. Open the app, and select the Jetpack CP site.
3. Open MyStore, and confirm that you can see the bottom banner.
4. Click on the "X" button to dismiss it.
5. Close the app and open it again, and confirm that it's not getting displayed again.
6. Change the time of your device to advance it by 5 days or more.
7. Open the app again, and confirm that you can see the bottom banner now.

Please test using a regular site, and confirm that the banner is never displayed for it.

### Images/gif
| Light | Dark |
| --- | --- |
| <img width="733" alt="Screen Shot 2021-10-13 at 12 31 30" src="https://user-images.githubusercontent.com/1657201/137124945-f6f1778d-49e4-4b8a-bb3c-27bfd7f9247a.png"> |<img width="733" alt="Screen Shot 2021-10-13 at 12 31 50" src="https://user-images.githubusercontent.com/1657201/137124958-ed8cb209-f39a-45a1-bbec-3b5536d8ef2e.png"> |

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-10-14 00:18 UTC, ghost approved these changes

2021-10-15 08:31 UTC, hichamboushaba commented
@hafizrahman will you have a chance to take a look at this PR 🙂 ?

2021-10-15 12:19 UTC, hafizrahman commented
I missed it, sorry. Will review today.

2021-10-15 12:36 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/AppBarLayoutExt.kt
> +fun AppBarLayout.verticalOffsetChanges(): Flow<Int> {
Interesting use of Flow here! Very cool 💯

2021-10-15 12:57 UTC, hafizrahman requested changes
Everything works well in my test, there's just one visual bug that I found.

2021-10-15 12:57 UTC, hafizrahman commented on WooCommerce/src/main/res/layout/view_jetpack_benefits_bottom_banner.xml
> +    <androidx.appcompat.widget.AppCompatTextView
The sentence is cut-off here in my emulator, with the "Jetpack" word missing. I have the "Largest" setting in Font Size, Pixel 4XL API 30 Android R 11.0:

<img src="https://user-images.githubusercontent.com/266376/137489439-7697b7cb-d071-42ca-845f-aa2a9ff1cb9a.png" width="35%" />

2021-10-15 12:57 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
> +        JETPACK_BENEFITS_BANNER_DISMISSAL_DATE
Not a blocker: For merchants who have multiple stores and frequently switch between them, it might get annoying that the banner keep showing up after being dismissed, if they're switching sites throughout the day. This might not end up being a problem though, so probably fine to let this be until we hear actual feedbacks about it.

2021-10-15 13:28 UTC, hichamboushaba commented on WooCommerce/src/main/res/layout/view_jetpack_benefits_bottom_banner.xml
> +    <androidx.appcompat.widget.AppCompatTextView
I had a `maxLines = 1` to avoid wrapping this line, but now that I think about it, wrapping is better than cutting it completely, and it won't occur unless the font settings have been changed.

Thanks for catching this.

2021-10-15 13:29 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
> +        JETPACK_BENEFITS_BANNER_DISMISSAL_DATE
If we have it linked to the account or device, I'm afraid we won't display it as needed, so let's leave it like this for now, and we can change it later if we needed.

2021-10-15 13:32 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/AppBarLayoutExt.kt
> +fun AppBarLayout.verticalOffsetChanges(): Flow<Int> {
Yes, the cool thing about reactive streams is the ability to convert callback-based events to a nicer and easier-to-read API.
For RxJava there is a library that offers bindings like this for a ton of Views' events: https://github.com/JakeWharton/RxBinding, and there are some libraries for Flow also, but I suspect they have an API for the `verticalOffsetChanges` built-in, since it's not used that much, and I didn't want to add an additional library just for this.

2021-10-18 09:33 UTC, hafizrahman approved these changes

2021-10-18 09:34 UTC, hafizrahman commented
LGTM now.

2021-10-18 09:34 UTC, merged