Issue/4878 Location fetching error handling
woocommerce/woocommerce-android pull request #5001
Opened 2021-10-13 11:00 UTC by kidinov

Closes: #4878 

### Description

The PR adds handling of the errors for location fetching endpoint. When a merchant doesn't have an address set in WC Pay, then the backend returns a specific error. We show a screen with an explanation and a button that opens a web view on the settings page where a merchant can set an address.

Other errors were handled in a generic way - we should that we couldn't connect to a reader

### Testing instructions

** Your site should have the current develop (3.1.1) version of WCPay install, please contact me if you don't know where to download that**

** Missing address**
1. Remove WC pay address via wp-admin
2. Adjust `CardReaderConnectViewModel::connectToReader:332` to `val cardReaderLocationId = if (cardReader.locationId != null) null else cardReader.locationId` (this way we always featch a location id from the backend)
3. Try to connect to a reader
4. Notice specific dialog 
5. Notice that web view opens and you can change the address
6. Try to fill out the address
7. Try to connect to a reader
8. Notice that you can connect now

**Generic error**
1. Do 2 from the previous list
2. Try to connect to a reader a disable internet
3. Notice error dialog

### Images/gif

https://user-images.githubusercontent.com/4923871/137124006-10f938ba-d587-47a8-97a6-dd470ef9680c.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-10-13 12:36 UTC, malinajirka requested changes
Thanks @kidinov! The code looks good overall.

I've left one comment which is not technically related to this PR and a couple minor comments. 

However, the flow didn't work for me when I tested it on my device - the url redirects me to a page which doesn't allow me to enter any address + scroll doesn't work in the webview (see video for details). It seems the page is calypso's page of the first site connected to my account - I'd expect to see wpadmin page of the site I'm connected to in the app, not calypso of a different site.

https://user-images.githubusercontent.com/2261188/137131508-07033383-9aa6-4645-9bf1-ec7079044770.mp4


Issue 2:
1. Tap on Enter site address
2. Press back
3. Tap on "Connect to reader"
4. Notice the reader is never found - when you cancel the discovery and start it again, it works (it seems we don't cancel the discovery when the user leaves the webview)

2021-10-13 12:36 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +            val cardReaderLocationId = cardReader.locationId
💡 Technically not related to this PR: I'm wondering if all this code belongs to the ViewModel - registration to a location feels like a responsibility of the CardReaderModule. Wdyt - should we consider moving it to the module?

2021-10-13 12:36 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
> +    fun `given location fetching fails address, when user clicks on connect button, then show address error state`() =
Possible typo: `fails address` instead of `missing address`

2021-10-13 12:36 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
> +
We might want to consider adding a test for: "On enter store address button clicked", wdyt?

2021-10-13 13:19 UTC, kidinov commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
> +
Good point. Done here - https://github.com/woocommerce/woocommerce-android/pull/5001/commits/beba0a18dfc76d87cd305926e25f622bc869ea1f

2021-10-13 13:20 UTC, kidinov commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
> +    fun `given location fetching fails address, when user clicks on connect button, then show address error state`() =
Fixed here - https://github.com/woocommerce/woocommerce-android/pull/5001/commits/beba0a18dfc76d87cd305926e25f622bc869ea1f

2021-10-13 13:27 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +            val cardReaderLocationId = cardReader.locationId
I was thinking about that and even started to implement it this way. But then decided to leave it in the main app. My reasoning was that this solution is basically a temporary workaround because for the first iteration we don't want to implement full-fledged location management.

When we will implement location management then probably we will need to fetch all created locations and show them to a user so they can pick one from the list. This probably should not be a part of the CardReaderModule.

Also, I was thinking about proper error propagation for this case and CardReaderModule API changes that might be significant

Having said that I am really not strong about this decision and open to change my mind because I definitely see reasons why it should be in the module too

2021-10-13 14:04 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt
> +            val cardReaderLocationId = cardReader.locationId
> My reasoning was that this solution is basically a temporary workaround because for the first iteration we don't want to implement full-fledged location management.

👍 

> When we will implement location management then probably we will need to fetch all created locations and show them to a user so they can pick one from the list. This probably should not be a part of the CardReaderModule.

I'm not sure about this part. AFAIU the location created in this new flow will be used only for the card reader - in other words, it won't be flow for setting a store address, right? Moreover, the locations live on Stripe's backend, right? If that's the case, I believe keeping it within the card reader module would make more sense. Especially, since any app which will want to re-use the card reader module, will need to implement these flows as well.

> Also, I was thinking about proper error propagation for this case and CardReaderModule API changes that might be significant

I can't foresee any issues right now - I think the "connection flow" can return something like "missing address" -> the app shows  an error dialog with a button which starts a completely different flow for creating/attaching an address.


Let's discuss this later, it's definitely out of the scope of this PR.

2021-10-14 10:15 UTC, kidinov commented
@malinajirka  thanks for the findings!

I've implemented a workaround for issue number 1: https://github.com/woocommerce/woocommerce-android/pull/5001/commits/06610a8e0e531b95737cb676d772b93ab9f8ee1b

And have created an issue on the issue number 2:  https://github.com/woocommerce/woocommerce-android/issues/5009

2021-10-14 10:39 UTC, malinajirka approved these changes
Great job @kidinov! It works as expected. I've left one minor comment but feel free to merge this PR.

2021-10-14 10:39 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
> +    fun `given location fetching missing address, when user clicks enter address, then emits open chrome event`() =
🔍 Nitpick: Since tests serve also as a documentation, we might want to consider mentioning the difference in the test name so the reader doesn't need to read the code. Perhaps something like this might work:

Test 1: `given address empty on selfhosted site, when user clicks enter address, then opens unauthenticated webview`
and 
`given address empty on wpcom site, when user clicks enter address, then opens authenticated webview`

Wdyt?

2021-10-14 10:53 UTC, kidinov commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModelTest.kt
> +    fun `given location fetching missing address, when user clicks enter address, then emits open chrome event`() =
The naming was improved! https://github.com/woocommerce/woocommerce-android/pull/5001/commits/45951b25b0c87fa5bd38f92e4fa98e653ac65e4d

2021-10-14 11:07 UTC, merged