UI to select order statuses filters
woocommerce/woocommerce-android pull request #5039
Opened 2021-10-19 14:44 UTC by JorgeMucientes

Work in progress: #4934 

### Description

The task of filtering orders by order status was too big to create a single PR for it. In fact, this PR is already big enough (sorry about that 😞 ). So I will split it in at least 2 PRs. This is the first part. 
In this PR I've added the essential UI to open filters flow in order list screen and select any combination of order statuses to filter. There are some things that are work in progress (I will indicate this in code) so no need to review them. 

Important pieces missing in this PR that will come in part II here #5087
- Loading order status from APIs call
- Update order list screen with selected filters
- Unit testing for viewModel

### Testing instructions
Open Order List and click the filters button. Play around selecting and unselecting different options, and check the filter screen is updated accordingly.  Behaviors to keep in mind. 

- [x] Order status filters is multi-choice
- [x] When any order status is selected, “All” option should be unselected
- [x] If “All” option is selected, then all the rest of the selected filters should be unselected
- [x] “Clear” button will wipe out all selections and will default to “All” option
- [x] Back button will display a confirmation dialog before discarding selected filters
- [x] If all options are unelected, option "All" option must be checked. This behavior is not included in this PR, but is fixed here #5087

https://user-images.githubusercontent.com/2663464/137933974-f6218c3d-011e-474c-a8af-237327632269.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-10-19 14:50 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/OrderFilterListViewModel.kt
> +            FilterListOptionUiModel(REFUNDED_KEY, "Refunded"),
For testing purposes. Will be removed along with the `STATUS_KEY` values once this is properly loaded from API

2021-10-28 10:52 UTC, hichamboushaba requested changes
Great job @JorgeMucientes, but there is a blocking issue of losing all the filter options when the activity is re-created.

And a personal opinion, I hope you don't mind it 🙂, but it's not blocking, and you don't need to change anything if you don't agree: I think that the choice of re-using the same ViewModel for the three screens will make the code harder to read, now without the date range options, it's already challenging to follow and understand what's going, and adding the date ranges will just add complexity later.

2021-10-28 10:52 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainNavigationRouter.kt
> +    fun showOrderFilters()
I think that the `MainNavigationRouter` is mainly for global and top-level navigations, (the `showAddProduct` is an exception that just slipped in a PR I think), since showing order filters is an `OrderListFragment` specific, then it can live just inside the fragment, and you can use `findNavController` in it.

The `MainNavigationRouter` was needed also to accommodate a special architecture of navigation that we had before where all the top-level fragments weren't part of the navigation graph, and couldn't use `findNavController`, but now it's different.

2021-10-28 10:52 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/ui/OrderFilterCategoryListFragment.kt
> +        super.onCreateOptionsMenu(menu, inflater)
Is there a reason why the super call is being last here? I'm asking because the `menu.clear()` won't be useful now, if the activity (or a parent fragment) decided to put options, they will be added in the `super` call 🤔

2021-10-28 10:52 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/ui/OrderFilterListViewModel.kt
> +    val orderFilterCategoryViewState: LiveData<OrderFilterCategoryListViewState> = _orderFilterCategoryViewState
Having those LiveDatas in a shared viewModel and without being saved to the `savedStateHandle` creates an issue in case of activity re-creation or process death, if you enable `don't keep activities` in the developer options, then you open the status filter screen, then you navigate to another app, and come back, the list of filters will be lost completely, and not just the selected options, but all options:
<img width="326" alt="Screen Shot 2021-10-28 at 11 26 25" src="https://user-images.githubusercontent.com/1657201/139239340-d7549322-de79-4516-95cf-b16532291518.png">

I think using the helper class `LiveDataDelegate` will help avoiding this issue here.

2021-10-28 10:52 UTC, hichamboushaba commented on WooCommerce/src/main/res/layout/fragment_order_filter_list.xml
> +        android:id="@+id/filterList_btnFrame"
np, this doesn't follow the view ids' naming [conventions](https://github.com/woocommerce/woocommerce-android/blob/b793c31d7149ead6edc2531a20c2f900afaaeb46/CONVENTION.md#view-ids) 🙂

2021-10-28 10:52 UTC, hichamboushaba commented on WooCommerce/src/main/res/layout/order_filter_option_item.xml
> +        android:button="@null"
a question just for me to learn, what's the role of this line?

2021-10-28 11:31 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/ui/OrderFilterCategoryListFragment.kt
> +package com.woocommerce.android.ui.orders.filters.ui
np, the `ui` is already part of the parent package, so adding it a second time is not needed, and is not consistent with the rest of the app 🙂

2021-10-28 17:28 UTC, JorgeMucientes commented
@hichamboushaba Thanks for the thorough review! I know it was a long one. 
>And a personal opinion, I hope you don't mind it...

Please do! I'm always keen on great feedback. 

Totally agree with your point about splitting the view models into 2. It's something I've been thinking about while developing. On one hand it was easier for me to share the state between screens, but on the other the view model ended up with more logic and complexity than I initially expected. I'm already working on splitting it and I will add those changes as part of this PR ##5104. So no worries if you don't see those changes applied here. 


>there is a blocking issue...

Great catch, totally missed that, and it's a big deal. I've been living in ignorance thinking the AndroidX view models state not only survived config changes but system-initiated process death too 🤦🏼  

Since I'm working on splitting the view models into 2 I think it would be better if I fix this "saving state" issue there. Otherwise, I'll have to do the same work twice. This feature is hidden under a feature flag so it should not be a problem to merge it with this bugs knowing that they will be addressed in another PR before enabling the feature. I can add you the the PR with the refactor + the fixes if you want. Is that ok? 

For the rest of the suggestions, I'll fix them in this PR and let you know once this is ready for merging.

2021-10-28 17:31 UTC, hichamboushaba commented
> Since I'm working on splitting the view models into 2 I think it would be better if I fix this "saving state" issue there.

Yes, no worries @JorgeMucientes, once you address the other points, please ping me, and I'll approve the PR, then you can fix the saving state issue in another PR 🙂

2021-10-29 09:42 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainNavigationRouter.kt
> +    fun showOrderFilters()
Aah! ok makes sense, plus it's way more straight forward to use nav controller directly from fragment. [Done](https://github.com/woocommerce/woocommerce-android/pull/5039/commits/9fe050df22bd73f9ff10d6920f44feef3989e202)

2021-10-29 09:42 UTC, JorgeMucientes commented on WooCommerce/src/main/res/layout/fragment_order_filter_list.xml
> +        android:id="@+id/filterList_btnFrame"
True! I was unsure those conventions were up to date since I barely see them applied over the code, so I kind of reused the naming pattern I saw for product filters feature. 
I've [renamed](https://github.com/woocommerce/woocommerce-android/pull/5039/commits/670837b4a8076e4cf08294c0bb608cbf56b3fcd2) the ids to follow the naming conventions. Although I have not renamed the layout fragment files to follow them as I think we are not applying those anywhere. Not even for the activity or fragment files shown as examples [conventions](https://github.com/woocommerce/woocommerce-android/blob/b793c31d7149ead6edc2531a20c2f900afaaeb46/CONVENTION.md#:~:text=feature_name%20_%20layout_type-,Examples,-feedback_survey_activity)

Maybe we should update the conventions for these?

2021-10-29 09:43 UTC, JorgeMucientes commented on WooCommerce/src/main/res/layout/order_filter_option_item.xml
> +        android:button="@null"
Nothing to learn here :( I simply reused the existing layout from [product_filter_option_list_item.xml](https://github.com/woocommerce/woocommerce-android/blob/7a37069e78abc56a7bc165bed73067b6f0e20590/WooCommerce/src/main/res/layout/product_filter_option_list_item.xml)

I think it doesn't have any effect. In fact, it's not an existing xml attr for ImageView or View. I've removed it.

2021-10-29 09:46 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/ui/OrderFilterCategoryListFragment.kt
> +package com.woocommerce.android.ui.orders.filters.ui
Ouch, did not realised that we had that parent package. I will remove the nested ui package. It is kind of confusing though, because inside this parent ui package we have repositories (i.e `AddonRepository`, `OrderListRepository`, etc) I'd say most of the repos we have are in the ui package. That's the reason I added that ui package to then add `orders.filters.data` package and place my repository there.

2021-10-29 09:47 UTC, hichamboushaba commented on WooCommerce/src/main/res/layout/fragment_order_filter_list.xml
> +        android:id="@+id/filterList_btnFrame"
Actually, the conventions are pretty new, and that's why they are not respected everywhere.

For the ids, as we were using kotlin synthetics before, we need to have some sort of scoping embedded in the id, to differentiate between them, but with ViewBinding, it's not needed anymore, and that's why added those conventions without them.
For the class file, I'm OK with keeping it as is, as you said, it hasn't been applied to any file for now.

2021-10-29 09:49 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/ui/OrderFilterCategoryListFragment.kt
> +package com.woocommerce.android.ui.orders.filters.ui
Yes, the repositories being part of the `ui` package is weird, it was done before I joined too, we can discuss it internally to see what's the best approach here, either to move the repositories inside a specific `data` package, or remove the `ui` from the parent package.

2021-10-29 09:51 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/ui/OrderFilterCategoryListFragment.kt
> +package com.woocommerce.android.ui.orders.filters.ui
I'll remove this nested ui package in a following PR, otherwise I'm going to have a lots of conflicts with my other code changes in the stacked branches.

2021-10-29 09:52 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/ui/OrderFilterCategoryListFragment.kt
> +package com.woocommerce.android.ui.orders.filters.ui
OK, no worries 🙂

2021-10-29 10:04 UTC, JorgeMucientes commented on WooCommerce/src/main/res/layout/fragment_order_filter_list.xml
> +        android:id="@+id/filterList_btnFrame"
Makes sense, I  like it way more without the scoping prefix in the view id, simpler and more readable. 
Well I'll follow this conventions from now on. Thanks for clarifying this point 👍🏼

2021-10-29 10:27 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/ui/OrderFilterCategoryListFragment.kt
> +        super.onCreateOptionsMenu(menu, inflater)
No reason at all, quick copy pasting from `ProductFilterListFragment.onCreateOptionsMenu()` did that 😓 Should've paid more attention. 
I've moved it to the top of the method as I can't find any reason to why is at the end. As you mentioned, if any kind of parent sets any options, the menu will be overridden. 
I now wonder if I should refactor that in `ProductFilterListFragment` as well, although is OOS for this PR. 
Good catch!

2021-10-29 10:29 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/filters/ui/OrderFilterListViewModel.kt
> +    val orderFilterCategoryViewState: LiveData<OrderFilterCategoryListViewState> = _orderFilterCategoryViewState
As discussed below, this will be fixed in an upcoming PR, as this feature is feature flagged.

2021-10-29 10:29 UTC, hichamboushaba approved these changes
Thanks @JorgeMucientes for the fixes, nice work.

2021-10-29 10:29 UTC, merged