Jetpack CP: force fetching sites on site picker to run additional checks
woocommerce/woocommerce-android pull request #5105
Opened 2021-10-28 17:16 UTC by hichamboushaba

Closes: #4857 

### Description
Since currently we need to run some additional checks for sites that use Jetpack CP, and since those checks are part of `WooCommerceStore` and not `SiteStore`, we need to force fetching the sites on the site picker, instead of relying on the sites that exist on the database, since the sites fetched using `SiteStore` by the login library might not contain accurate data.
The current implementation of the `SitePicker` always fetches the sites, but if there are sites in the DB, it doesn't show the loading view, this PR changes this by forcing the loading view if one of the sites is using Jetpack CP.

|Scenario | Before | After |
| --- | ------ | ------ |
| Login using site's URL | ![login_site_url_before](https://user-images.githubusercontent.com/1657201/139302890-9d092474-de93-4c4c-855b-857eaf3a4df8.gif) |  ![login_site_url_after](https://user-images.githubusercontent.com/1657201/139302917-aa781151-8607-49c6-81b5-46e606d80aa4.gif) |
| Login using WPCom account |  ![login_wpcom_before](https://user-images.githubusercontent.com/1657201/139303046-6fe5ae18-7ef9-43f4-a1d0-a0d5459874f4.gif) | ![login_wpcom_after](https://user-images.githubusercontent.com/1657201/139303062-e17a8238-5d20-4f54-86a7-c3c553ba06ae.gif) |

### Testing instructions
#### No Regression
Confirm that there is no regression when using an account that's not connected to any Jetpack CP sites.

#### Jetpack CP sites
##### Login using WPCom
1. You need a site that uses a Jetpack CP plugin (WCPay preferably)
2. Open the app and connect using your WordPress.com account
3. When you get to the site picker, confirm that you see the skeleton view, before seeing a complete list of the sites.

##### Login using the site's URL
1. You need a site that uses a Jetpack CP plugin (WCPay preferably)
2. Open the app and connect using the site's URL
3. When you get to the site picker, confirm that you see a circular progress bar, and then the app connects you automatically.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-11-04 10:19 UTC, hafizrahman requested changes
When the skeleton view (for login using wpcom account), or the circular progress bar (for login using site address), are shown, the "Log in with another account" is shown in red and tappable, but it doesn't do anything.

Should we maybe hide the button instead during this process? Or make it work and have it cancel the current log in.

2021-11-04 10:51 UTC, hichamboushaba commented
> When the skeleton view (for login using wpcom account), or the circular progress bar (for login using site address), are shown, the "Log in with another account" button is shown in red and tappable, but it doesn't do anything.
> 
> Should we maybe hide the button instead during this process? Or make it work and have it cancel the current log in.

Nice catch @hafizrahman, I think this bug has been here for a long time, but since we don't show the skeleton unless the sites' loading takes a long time, no one noticed it.
I'll try to fix it.

2021-11-05 11:11 UTC, hichamboushaba commented
Even though I think showing the button might be better here, there is a lot of cases to handle, and I can't be sure I'm not breaking anything if I assign a click listener here, so I opted for hiding it instead for now, ready for another round @hafizrahman 
![wpcom](https://user-images.githubusercontent.com/1657201/140501837-03ba2d72-66b6-4a14-bc8b-792ca8cedd84.gif)

2021-11-08 08:44 UTC, hafizrahman approved these changes

2021-11-08 08:45 UTC, hafizrahman commented
LGTM now.

2021-11-08 08:45 UTC, merged