Jetpack CP: UI for Install Jetpack from App
woocommerce/woocommerce-android pull request #5170
Opened 2021-11-05 06:53 UTC by hafizrahman

## Description

This is the first part for the "Jetpack CP: Install Jetpack from app" feature: https://github.com/woocommerce/woocommerce-android/issues/4865#issuecomment-956128458

This PR adds the UI elements and navigation related to the functionality. There is no functionality yet and the intent of this PR is just to check the design and test the user interface.

**exception:** The circular loading animation is not yet decided, so for now it is still using a temporary animation.

2021-11-09 15:13 UTC, hichamboushaba approved these changes
Nice work @hafizrahman 💯, I left just one nitpick comment, but feel free to ignore it and merge if you like 🙂

2021-11-09 15:13 UTC, hichamboushaba commented on WooCommerce/src/main/res/layout/dialog_jetpack_install_progress.xml
> +                android:id="@+id/progress_icon"
np, putting the `icon` prefix on a layout seems confusing, I understand why you did it, but still, I would call it `header_layout` or something similar, WDYT?

2021-11-09 15:49 UTC, hichamboushaba requested changes
I just noticed all the files are kept on the `mystore` package, I think they should be moved to their own package.
Even the JetpackBenefitsDialog should've been moved, but I missed it when I worked on this, so if you can move everything to a new package, or at least move the new files.

2021-11-09 15:49 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/JetpackInstallProgressDialog.kt
> +package com.woocommerce.android.ui.mystore
We need to move those files to their proper package, for example: `com.woocommerce.android.ui.jetpack`, I missed this on my initial review.

2021-11-11 06:25 UTC, hafizrahman commented
Thank you for your feedbacks @hichamboushaba 

This is ready for another review.

2021-11-11 08:40 UTC, hichamboushaba approved these changes
Thanks for the fixes @hafizrahman 👍 
There is a conflict blocking the merge though

2021-11-12 07:35 UTC, hafizrahman commented
Thanks for the approval @hichamboushaba 

I've fixed the conflict, merging now.

2021-11-12 07:35 UTC, merged