Add products UI test
woocommerce/woocommerce-android pull request #5235
Opened 2021-11-12 21:27 UTC by designsimply

### Description

This PR introduces a UI test that checks the content of the products list, and every individual product detail screen. It uses Espresso matches to build assertions.

### Testing instructions

1. Run the test in `ProductsUITest.kt` and it should pass.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-11-15 12:15 UTC, pachlava requested changes, later dismissed
Good job @designsimply  🎉 

I started from running the test on `Pixel 4a` and it passed. Also, I messed with the assertions a bit, deliberately making them to fail, and saw they were really failing the test if test data wasn't found 👍 

I left quite a bit of review notes, many of them are about naming and styling. Some of them I consider important, others are subjective (I mentioned this in such cases).

While the test still can be extended in both products list (`stock_status` check) and individual product page (navigation bar, `(...)` menu button, price, inventory, product type) areas, I think this PR can be merged once it's adjusted in accordance with some of my review notes, and once there are no complaints from Lint check. After that, more detailed matchers can be built in a follow-up PR.

2021-11-15 12:15 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/ProductListScreen.kt
> +        // this just checks scrolling
Since the method name is quite self-explanatory, does this comment add any new information?

2021-11-15 12:15 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/ProductListScreen.kt
> +    fun scrollToProduct(productTitle: String): ProductListScreen {
Note for future (for myself, too): the `scrollTo...` method is the first candidate to be extracted from `ProductsListScreen` and `ReviewsListScreen` to helpers.

2021-11-15 12:15 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/ProductListScreen.kt
> +    fun assertProductCardMatchesMockData(product: ProductData): ProductListScreen {
A note on naming for the method. This method accepts ProductData as a parameter. An instance of ProductData can be created from any source: mocks, arrays, etc... but this method will still work, and will work in the same way for all cases. Because of this, I think the `MatchesMockData` part creates a somewhat false impression that this will work with mocks only. In reality, this screen does not care about the data source (which is good!)

```suggestion
    fun assertProductCard(product: ProductData): ProductListScreen {
```

2021-11-15 12:15 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/ProductListScreen.kt
> +        // check the card information against the json data
Because of the mentioned reason, this comment is not really needed

```suggestion
```

2021-11-15 12:15 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/ProductListScreen.kt
> +        )
A few notes on the structure of this assertion:

1. What the assertion does in the end (line 56) is checking that the object with ID equal to `R.id.productInfoContainer` (and other properties declared inside of `matcherForProductCard`) has an ID equal to `R.id.productInfoContainer`. This will always be the case. I see more value in having something like a check for visibility, for example (`ViewMatchers.isDisplayed()`) instead of `ViewMatchers.withId(R.id.productInfoContainer)`.
2. The syntax of Espresso matchers (`withId`,`withText`, `withChild`...) is quite self-explanatory. Because of this, imo, adding the comments inside the matchers is needed in non-typical cases only, when having a comment is necessary and helps with understanding the matcher.
3. This point is subjective. It's my opinion, and it's about my perception of the code. I find it easier to see the whole matcher presented as one logical chunk, instead of it being divided into three parts (`matcherForProductCard`, `productCardMatch` (btw, I see a lot of similarity in these two names 😉  ), and the assertion itself in the end). I mean this:

```kotlin
        Espresso.onView(
            Matchers.allOf(
                ViewMatchers.withId(R.id.productInfoContainer),
                ViewMatchers.withChild(
                    Matchers.allOf(
                        ViewMatchers.withId(R.id.productName),
                        ViewMatchers.withText(product.name)
                    )
                )
            )
        )
            .check(ViewAssertions.matches(ViewMatchers.isDisplayed()))
```

2021-11-15 12:15 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/ProductListScreen.kt
>      }
This is a second candidate to be extracted to helpers.

Also, me being extra nitpicky about naming (I think naming is very important): `selectSingleProductByName` name implies that there's a possibility to select multiple products?

2021-11-15 12:15 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/ReviewData.kt
> +)
The `ReviewData.kt` file (as its name suggests) is used to store the `ReviewData` class. Adding a `ProductData` data class introduces inconsistency between file name and its content. I think this can be solved in two ways: creating a separate new file for `ProductData`, or renaming the `ReviewData.kt` to something like `DataClasses.kt`. I lean towards the latter, because it means fewer files, and better overview. But I'm open to suggestions.

2021-11-15 12:15 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/ProductsUITest.kt
> +                .goBackToProductsScreen()
One advantage the current screens structure provides us with, is the ability to use method chaining, and be free from the need to create constants:

```suggestion
            ProductListScreen()
                .scrollToProduct(productData.name)
                .assertProductCardMatchesMockData(productData)
                .selectSingleProductByName(productData.name)
                .assertProductDetails(productData)
                .goBackToProductsScreen()
```

2021-11-15 12:15 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/ProductsUITest.kt
> +    fun productListCheck() {
By looking at this test name, it's hard to tell what's done inside. I think adding more detail would help.

On a general note: I find using `Check` word in the test names somewhat redundant, because we already know this is a test, and it should check 🙂 .

2021-11-15 12:15 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/ProductsUITest.kt
> +    }
Very low prio and subjective: while this does not contradict any style guides, and works perfectly, generally, helping functionы that are used in tests are located after the tests code, allowing the person seeing the code the first time to concentrate on the test code, see the function call, and then see the function itself, while already having some context about why and where it's used.

2021-11-18 12:42 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/ProductListScreen.kt
> +        // this just checks scrolling
Done in b61e6ef536b9450ab36f7705861d6abc6d5c6e82

2021-11-18 12:46 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/ProductListScreen.kt
> +    fun assertProductCardMatchesMockData(product: ProductData): ProductListScreen {
Done in 69929cce0679644693fe531c113eac6983f01259

2021-11-18 12:46 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/ProductListScreen.kt
> +        // check the card information against the json data
Done in 69929cce0679644693fe531c113eac6983f01259

2021-11-18 12:46 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/ProductListScreen.kt
> +        )
Done in 69929cce0679644693fe531c113eac6983f01259

2021-11-18 12:54 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/ReviewData.kt
> +)
Done in 118c5b3253f71ed86298c9d024f3cfee48dacfb4.

2021-11-18 12:54 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/ProductsUITest.kt
> +    fun productListCheck() {
Done in 118c5b3253f71ed86298c9d024f3cfee48dacfb4.

2021-11-18 12:58 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/ProductsUITest.kt
> +                .goBackToProductsScreen()
Done in 1f44767ec690b3689f718698a0a4b855e6fdbda7.

2021-11-18 12:59 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/ProductListScreen.kt
>      }
Second point done in 1f44767ec690b3689f718698a0a4b855e6fdbda7.

2021-11-18 13:10 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/ProductsUITest.kt
> +    }
Done in 894278d525e247b2dd04c4ada6ba3fbb84f4c92c.

2021-11-23 13:15 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/ProductListScreen.kt
> +    fun scrollToProduct(productTitle: String): ProductListScreen {
Done in 07e3c08b627189d622c88af1bf2ce05dd867101e.

2021-11-23 13:15 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/ProductListScreen.kt
>      }
First point done in 07e3c08b627189d622c88af1bf2ce05dd867101e.

2021-11-23 13:18 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/reviews/ReviewsListScreen.kt
> -
This was not used, so I removed it, because now there's a similar method that selects by title.

2021-11-24 00:03 UTC, pachlava commented
This PR was created by @designsimply, and I was a reviewer. At a certain point, I had to switch from the reviewing role to a development one, and to implement my own suggestions. Therefore, I can't review my own additions, so I'm asking for your review, @mokagio 🙂 Thank you! (and thanks to @designsimply for working on this!)

2021-11-24 05:49 UTC, mokagio approved these changes
Looking good. Tests passed locally 👍

2021-11-24 05:49 UTC, mokagio commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/SingleProductScreen.kt
> +            // all direct children of the same container:
Why is it important that they are all siblings? 🤔 

Also, because the view is hierarchical, would the assertion done like this always be true for the root view? I'm not actually sure about the answer because I don't know Espresso and I don't know whether `withChild` considers only direct subviews or nested subviews as well 🤔 

Regardless, the assertion at the end is for the matching view to be displayed and (again, as far as I can tell / understand) this syntax works fine for that scenario.

---

To be explicit: This is just a question about the rationale behind the syntax without any implicit suggestion to change it 😄 👍

2021-11-24 05:49 UTC, mokagio commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/DataClasses.kt
> +// this file does not contain human-readable product descriptions,
Nitpick

```suggestion
// that file does not contain human-readable product descriptions,
```

Reading "this file" makes me think of the file were the comment is, not the one just mentioned.

2021-11-24 05:49 UTC, mokagio commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/Screen.kt
> +                ViewActions.click()
I can't believe there's a `click()` method in a mobile testing library! 

I mean, yes I guess Android (and iOS) support input devices, but, realistically, tapping would be how most users interact with the view... 🙃

2021-11-24 05:49 UTC, mokagio commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/ProductsUITest.kt
> +    @get:Rule(order = 3)
Is there a reason this is not `order = 2`?

```suggestion
    @get:Rule(order = 2)
```

2021-11-24 09:53 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/SingleProductScreen.kt
> +            // all direct children of the same container:
Yes, `withChild` will only look into the direct subviews. In order to have it global, we'd have to use `hasDescendant`, and in such case, caring about hierarchy would really be not that useful. Not saying it's super-useful in the current case, but at least we are making sure that these objects are all inside the same container (i.e. siblings), which adds a bit more confidence in the visual layout 😅 

I'm trying different kinds of matchers in different methods, and not sure if it actually affects anything, so far it feels like an experiment. 🤷

2021-11-24 09:54 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/DataClasses.kt
> +// this file does not contain human-readable product descriptions,
Good catch, thanks!

2021-11-24 09:59 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/util/Screen.kt
> +                ViewActions.click()
Yup, that _is_ weird. 🙂 I'll take a look if there's a tap...

2021-11-24 10:19 UTC, pachlava commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/main/ProductsUITest.kt
> +    @get:Rule(order = 3)
Thanks for noticing! Changing it to `2` does not break the tests, so 'fixed' it in 2309053bf7af73986c5569b00400bb930ffe2d07 for both files.

2021-11-24 11:47 UTC, pachlava commented
Thanks for reviewing @mokagio !

2021-11-25 01:43 UTC, mokagio commented on WooCommerce/src/androidTest/kotlin/com/woocommerce/android/screenshots/products/SingleProductScreen.kt
> +            // all direct children of the same container:
> Yes, `withChild` will only look into the direct subviews. In order to have it global, we'd have to use `hasDescendant`

Excellent. Thank you for the clarification. `TIL` 😄 

> I'm trying different kinds of matchers in different methods, and not sure if it actually affects anything, so far it feels like an experiment. 🤷

That's super valuable learning 👍 You should P2 it 😄

2021-11-25 01:47 UTC, mokagio commented
> Thanks for reviewing @mokagio !

Thank you for picking this up. :shipit:

2021-11-25 13:49 UTC, pachlava commented
Oh, I actually forgot to hit merge 🤦 😅

2021-11-25 13:50 UTC, merged