Add prominent/overflow publish option for draft and pending review products
woocommerce/woocommerce-android pull request #5249
Opened 2021-11-16 00:45 UTC by SowmiaS

Closes: #4361
### Why This is Important
Right now, when you want to publish a draft product/pending review, customers have to navigate to Product Settings and change the Product Status and then press Update. It's a long process. Having a prominent Publish button would save them time.
### Description
So Publish option is shown either as a **prominent button or in the overflow menu** for draft/pendingreview products.
**If there are unsaved changes then the publish option is shown in the overflow menu else as a prominent button.**

**Design**
The Publish text should be in **all caps** for a prominent button or **camelcase** when an overflow menu. 

### Testing instructions

**Testcase 01:**
Open a Draft/Pending Review product
Then Prominent publish button should be shown.

**Testcase 02:**
Open a Draft/Pending Review product
Then make some changes to the product
Then Prominent save button should be shown.
And publish button should be listed in the overflow menu.

**Testcase 03:**
Open a publish/privately published product
The publish button should not be shown

**Testcase 04:**
Click add product button
Then Prominent publish button should be shown.

**Applies to all test cases:**
Prominent button text should be in all caps.
Overflow menu options should be camelcase.

### Images/gif
**Before**

**After**

https://user-images.githubusercontent.com/4975407/141874807-96c780e3-4be1-4031-a20c-e4a3e7d7589b.mp4

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-11-16 06:37 UTC, anitaa1990 commented
Thank you for working on this @SowmiaS! Since this PR changes the flow of draft products a bit, I'm going to ping our designer @adamzelinski to take a look 👍 

If we proceed with this change, we would also want to have a similar flow on the iOS platform as well

2021-11-16 15:16 UTC, shiki commented
Also, note that this https://github.com/woocommerce/woocommerce-android/issues/4361 change was requested mainly to be in line with the current behavior of iOS. 🤪 

Requested by Garance: p91TBi-5oi-p2#comment-5239

2021-11-18 06:21 UTC, anitaa1990 commented
Thanks for the context @shiki! In that case, I'll assign the PR to myself and start the review :)

2021-11-18 06:21 UTC, anitaa1990 commented
@SowmiaS, I get this crash when `Do not keep activities` is enabled and I make some changes to a Pending Review product.
```
2021-11-18 11:50:07.258 408-408/com.woocommerce.android.prealpha E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.woocommerce.android.prealpha, PID: 408
    kotlin.UninitializedPropertyAccessException: lateinit property saveMenuItem has not been initialized
        at com.woocommerce.android.ui.products.ProductDetailFragment.showSaveMenuItem(ProductDetailFragment.kt:452)
        at com.woocommerce.android.ui.products.ProductDetailFragment.access$showSaveMenuItem(ProductDetailFragment.kt:55)
        at com.woocommerce.android.ui.products.ProductDetailFragment$setupObservers$1.invoke(ProductDetailFragment.kt:212)
        at com.woocommerce.android.ui.products.ProductDetailFragment$setupObservers$1.invoke(ProductDetailFragment.kt:210)
        at com.woocommerce.android.viewmodel.LiveDataDelegate.observe$lambda-0(LiveDataDelegate.kt:47)
        at com.woocommerce.android.viewmodel.LiveDataDelegate.lambda$Hn2RsfhY4Ofph0qrc1LoLNzbP2s(Unknown Source:0)
        at com.woocommerce.android.viewmodel.-$$Lambda$LiveDataDelegate$Hn2RsfhY4Ofph0qrc1LoLNzbP2s.onChanged(Unknown Source:6)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:468)
        at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:88)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:3028)
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3079)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:3030)
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3079)
        at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:510)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
```

2021-11-18 06:42 UTC, anitaa1990 requested changes

2021-11-18 06:42 UTC, anitaa1990 commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt
> +
<3 Thanks for adding the unit tests here 😄

2021-11-18 07:32 UTC, adamzelinski approved these changes

2021-11-23 09:40 UTC, SowmiaS commented
Good catch @anitaa1990. Thanks for testing in Do not keep activities mode. I have analyzed the issue and found the below.

**When the process death is initiated**, 'setupObservers(viewModel)' function is called in onViewCreated, and **the observer starts to listen before the menu is being recreated**. In the ViewModel, the saved state is restored (a lit quick than fetching from the server) and events are being fired before the menu is being recreated.

Now I have fixed the issue by changing the lateinit properties of save menu item and publish menu item to nullable property and adding null safety to it.

But I think we should start observing live data ( live data that is only related to menu changes ) only after onCreateOptionsMenu. so that menu items will always be created.

WDYT? @anitaa1990  @shiki 🙂 

**Activity Lifecycle for reference**
[android-lifecycle](https://github.com/xxv/android-lifecycle](https://github.com/xxv/android-lifecycle)
onCreate -> onCreateView -> onViewCreated -> onStart -> onResume ->onCreateOptionsMenu -> onPrepareOptionsMenu.

2021-11-26 05:51 UTC, anitaa1990 approved these changes
Looks good :shipit: Thanks for working on this @SowmiaS!

2021-11-26 06:08 UTC, merged