Issue/4991 memory leaks
woocommerce/woocommerce-android pull request #5268
Opened 2021-11-18 15:49 UTC by atorresveiga

Fix memory leaks in Reviews and Product Reviews views

Closes: #4991  #4992 

### Description
This PR fixes some memory leaks in Reviews and Product Reviews views.
In SkeletonView, parentView and actualView were not released after the fragment onDestroyView() was called. This was leaking ReviewListFragment and ProductReviewsFragment. The same was happening with reviewsAdapter and productAdapter in ReviewListFragment, ProductReviewsFragment, and ProductListFragment, not releasing these references in onDestroyView() was leaking the views.
The solution to these issues was to release the references in the Fragment's onDestroyView() and let the GC do his magic.

### Testing instructions
To test the issues navigate to the view you want to check and return to back to MyStore. Wait a few seconds until LeakCanary displays a notification indicating a retained object. Next, let LeakCanary finishes the heap processing and, you should be able to see the leak trace to the references that prevent that retained object from being garbage collected.

#### Test scenarios:

- **reviewsAdapter memory leak**
   MyStore --> Reviews --> MyStore 
   MyStore --> Products --> Product Details -->  Product Reviews --> MyStore

- **parentView and actualView memory leak**
   MyStore --> Reviews --> MyStore (go back to MyStore when the SkeletonView is still displayed)

- **productAdapter memory leak**
   MyStore --> Products --> MyStore 

### Images/gif
#### Before

| reviewsAdapter memory leak | productAdapter memory leak | parentView memory leak |
| --- | --- | --- |
| ![reviewsAdapter](https://user-images.githubusercontent.com/18119390/142443709-1b787b92-a01e-4546-a86a-fce0e42fcc7e.gif) |  ![productAdapter](https://user-images.githubusercontent.com/18119390/142443686-4c21ce42-977d-40cc-ba54-2a357ad17042.gif) | ![parentView](https://user-images.githubusercontent.com/18119390/142443663-b61d8f87-4462-41e1-8b89-a805681a3739.gif) |

#### Result
![resultOk](https://user-images.githubusercontent.com/18119390/142446707-25d476f7-90b2-4310-86eb-24929bbf4bac.gif)

2021-11-19 11:24 UTC, 0nko requested changes
Looks good! There are some minor lint errors, otherwise we're good to merge once those are fixed.

2021-11-19 11:24 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/reviews/ProductReviewsFragment.kt
> +        _reviewsAdapter = ReviewListAdapter( this)
Extra space, will cause lint check to fail.

2021-11-19 11:24 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewListFragment.kt
> +        _reviewsAdapter = ReviewListAdapter( this)
Same: lint issue.

2021-11-19 16:14 UTC, atorresveiga commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/reviews/ProductReviewsFragment.kt
> +        _reviewsAdapter = ReviewListAdapter( this)
Fixed!

2021-11-19 16:49 UTC, 0nko commented
The lint check is still failing. This issue was already fixed but you're out of sync with the main repo.

2021-11-22 20:25 UTC, 0nko approved these changes
LGTM.

2021-11-22 20:25 UTC, merged