Jetpack CP: Proper UI states to match install state
woocommerce/woocommerce-android pull request #5325
Opened 2021-11-24 04:40 UTC by hafizrahman

### Description
This is the third part for the "Jetpack CP: Install Jetpack from app" feature: #4865. 

This PR connects [the previous repo/vm work](https://github.com/woocommerce/woocommerce-android/pull/5287) to the UI so that it reflects the state of actual installation progress.

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-11-25 14:20 UTC, hichamboushaba requested changes
Really great job @hafizrahman, I just left one remark regarding the Dialog's lifecycle on configuration changes.

2021-11-25 14:20 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/JetpackInstallProgressDialog.kt
> +        viewModel.installJetpackPlugin()
On each configuration change (screen rotation, language change...), the dialog will be recreated, so we will be calling the `installJetpackPlugin` on each launch.
To avoid this, it's better to move this call to the ViewModel's `init` block, the View doesn't need to control the start, it just observes the progress.

2021-11-26 03:20 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/JetpackInstallProgressDialog.kt
> +        viewModel.installJetpackPlugin()
Oh thanks for catching this! This was how I used to test it (since when testing there's no other instantiation for the viewmodel and so init wasn't getting called), and I forgot to replace it.

2021-11-26 12:02 UTC, hichamboushaba approved these changes
Nice work @hafizrahman 👍

2021-11-26 12:02 UTC, merged