Handle stripe extension status
woocommerce/woocommerce-android pull request #5375
Opened 2021-11-30 06:11 UTC by AnirudhBhat

Closes: #5328

Also, includes business logic (designs are pending) for #5331, #5329, #5330

### Description

This PR adds support for handling the Stripe Terminal Gateway extension check during IPP onboarding. Follows the logic outlined here pdfdoF-fW-p2 

Here's a gist of the logic it follows 
1. If both WCPay and stripe terminal gateway are installed and activated, then return appropriate state which indicates that (We will be showing the dialog for user in the later PR when the designs are ready)
2. If both WCPay and Stripe Terminal are installed but none of them activated, ask user to activate WCPay
3. If both WCPay and Stripe Terminal are installed but Stripe Terminal plugin is activated as well, even then ask user to activate WCPay
4. If None of them are installed, ask user to install WCPay
5. If only Stripe Terminal plugin is installed, but not activated. Ask user to install WCPay
6. If Stripe Terminal plugin is installed and activated, proceed with the Stripe Terminal for IPP

Please note that the designs for #5331, #5329, #5330 are TBD. Also, the code for this feature was written in TDD fashion. I would suggest looking at the test files first to make sense of the feature.

### Testing instructions

## TC1
1. Install both WCPay and Stripe Terminal plugin on your WooCommerce store
2. Navigate to the IPP menu via settings
3. 💥 The app crashes. Because, the designs are TBD and will be fixed when the designs are ready
4. Ensure in the code that onboarding checker class correctly returns `WcpayAndStripeActivated` state in this case (Although unit tests already check this)

## TC2
1. Install both WCPay and Stripe Terminal plugin on your WooCommerce store. But don't activate neither of those
2. Navigate to the IPP menu via settings
3. Make sure app asks you to activate WCPay

## TC3
1. Install both WCPay and Stripe Terminal plugin on your WooCommerce store. Activate Stripe plugin
2. Navigate to the IPP menu via settings
3. Make sure app asks you to activate WCPay

## TC4
1. Uninstall both WCPay and Stripe Terminal plugin on your WooCommerce store.
2. Navigate to the IPP menu via settings
3. Make sure app asks you to install WCPay

## TC5
1. Install but don't activate Stripe Terminal plugin on your WooCommerce store.
2. Navigate to the IPP menu via settings
3. Make sure app asks you to install WCPay

## TC6
1. Install and activate Stripe Terminal plugin on your WooCommerce store.
2. Navigate to the IPP menu via settings
3. Make sure app proceeds with the onboarding

## TC7
1. Install and activate Stripe Terminal plugin on your WooCommerce store.
2. Navigate to the IPP menu via settings
3. Make sure app proceeds with the onboarding
4. Make sure that the plugin type is stored in shared preference (via Flipper or any other tool)

## TC8
1. Install and activate WCPay plugin on your WooCommerce store.
2. Navigate to the IPP menu via settings
3. Make sure app proceeds with the onboarding
4. Make sure that the plugin type is stored in shared preference (via Flipper or any other tool)

### Images/gif

https://user-images.githubusercontent.com/1331230/143990933-74e5f045-1ee8-4948-8e14-96398961b518.mp4

https://user-images.githubusercontent.com/1331230/143991808-0b9ceaf5-a094-414d-abc9-bd41b31e9834.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-11-30 09:42 UTC, AnirudhBhat commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
> +    private fun isStripePluginInstalled(pluginInfo: WCPluginSqlUtils.WCPluginModel?): Boolean = pluginInfo != null
Do you think we should have a single method that takes pluginInfo as parameter instead of 2 different ones?
`isPluginInstalled(wcPayPluginInfo)`
`isPluginInstalled(stripePluginInfo)`

similarly for other methods
`isPluginVersionSupported(wcPayPluginInfo)`
`isPluginActivated(wcPayPluginInfo)`

2021-11-30 12:47 UTC, malinajirka requested changes
Thank you @AnirudhBhat! ❤️  I really love that you added so many tests which verify all the different scenarios!! That's a great way to document our intentions and increase maintainability. Great job!

The PR works as expected. I've left some comments and I'm looking to hear what you think about them :)! 

One thing I'd like you to consider next time is to split such PRs into multiple smaller PRs. I think it's beneficial for both the reviewer and the author. Smaller PRs are much easier and faster to review and the author gets feedback sooner. I think one PR per the GitHub issues this PR touches (#5328, #5331, #5329, #5330) would have been optimal - or maybe even splitting it even more per "task" on each issue.  What do you think about such approach?

2021-11-30 12:47 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
> +    fun setCardReaderOnboardingCompletedPluginType(
💡 We might want to consider merging `setCardReaderOnboardingCompleted` and `setCardReaderOnboardingCompletedPluginType` into one entry. The main reason for that is to make sure we can't save meaningless data into the storage - eg. `onboardingCompleted = false` with `onboardingCompletedPluginType = WCPay` (which contradict each other). That could help future devs (or future us) who don't have the context with maintainability.

It could be something like an enum with "ONBOARDING_COMPLETED_WITH_WCPAY/ONBOARDING_COMPLETED_WITH_STRIPE_EXTENSION/ONBOARDING_NOT_COMPLETED". But this is just an example to better explain what I mean.

 Wdyt?

2021-11-30 12:47 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
> +    @Suppress("ReturnCount", "ComplexMethod", "NestedBlockDepth")
We added the `returnCount` and `ComplexMethod` suppressions since the method contained just a bunch of single line `ifs` with `return` statements = no additional complexity. However, after this change, I believe the Detekt check is actually valid and we might want to try simplifying the method - extracting it into sub-methods. Wdyt?

2021-11-30 12:47 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
> +    @Suppress("ReturnCount", "ComplexMethod", "NestedBlockDepth")
We added the `returnCount` and `ComplexMethod` suppressions since the method contained just a bunch of single line `ifs` with `return` statements = no additional complexity. However, after this change, I believe the Detekt warning is actually valid and we might want to try simplifying the method - extracting it into sub-methods. Wdyt?
P.S. Read all the comments first as there are other comments which might make this suggestion irrelevant. Thanks!

2021-11-30 12:47 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
> +            CardReaderOnboardingState.StripeTerminal.UnsupportedVersion -> "stripe_unsupported_version"
💡  We might want to consider mentioning `stripe extension` explicitly on these track events. Stripe is used by both WCPay and Stripe Extension so omitting the `extension` part might be a bit misleading, wdyt?

📓 It'd be great to add a comment to iOS tickets when we merge this PR to make sure we use the same event names. We should also add the events to the spreadsheet.

2021-11-30 12:47 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
> +                    viewState.value = when (state.pluginType) {
❓ I like this `pluginType` parameter. Any reason you decided not to use it for`CardReaderOnboardingState.StripeTerminal.UnsupportedVersion`?
Something like `data class PluginUnsupportedVersion(val pluginType: PluginType) : CardReaderOnboardingState()` could work, wdyt?

2021-11-30 12:47 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
> +        data class WcPayAndStripeInstalledState(
🔍 Nitpick: It seems this state contains some dummy data - we might want to consider making the fact that they are not ready more explicit, to make sure we don't forget to update them and also to make sure it's easily noticable on the UI. Something like:
```
// TODO cardreader Implement state when the designs are ready
val contactSupportLabel = UiString.UiStringText("NOT IMPLEMENTED")
            val learnMoreLabel = UiString.UiStringText("NOT IMPLEMENTED")
``` 
Wdyt?

2021-11-30 12:47 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
> +const val SUPPORTED_STRIPE_TERMINAL_VERSION = "5.8.1"
⚠️ It seems you are using "Stripe Terminal" terminology throughout the PR. My understanding is that Stripe Terminal refers to a card reader (aka terminal) from Stripe. Did you perhaps wanted to use "Stripe Extension" instead?

2021-11-30 12:47 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
> +    fun `given wcpay and stripe are installed, when stripe is not activated, then onboarding complete triggered`() =
💡 The word `triggered` feels a bit off to me, since the checker simple returns the state. We might want to consider renaming this to " then onboarding complete returned". I'd also be consistent with the rest of the methods. Same applies to the other method which uses `triggered`. Wdyt?

2021-11-30 12:47 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
> +    @Test
💡 We might want to consider adding tests for the current production version => test that when the feature flag is off, WCPay flow is always used no matter the state of Stripe Extension. Wdyt?

2021-11-30 12:47 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
> +        val wcPayPluginInfo = wooStore.getSitePlugin(selectedSite.get(), WooCommerceStore.WooPlugin.WOO_PAYMENTS)
💡 I find the following block a bit difficult to navigate and reason about. I tried to simplify it a bit. Let me know what you think about it - `issue/5328-handle-stripe-extension-status-jirka-attempts` branch.

I made the following changes:
1. Extracted the "both plugins installed" check into a method.
2. Made `isPluginInstalled` and `isPluginActivated` methods accept PluginType.
3. Introduced `getPreferredPlugin` which returns the plugin which should be used.
4. Moved supported version constants into PluginType.

Let me know what you think about it :). If you'd decide to use it, feel free to cherry pick my commit.

2021-11-30 12:47 UTC, malinajirka commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="card_reader_onboarding_stripe_terminal_not_setup_header">Finish setup Stripe Terminal Gateway in your store admin</string>
⚠️ I believe it's called `WooCOmmerce Stripe Payment Gateway` - https://wordpress.org/plugins/woocommerce-gateway-stripe/. Should we update the resources, wdyt?

2021-12-01 05:51 UTC, AnirudhBhat commented
@malinajirka Thanks for the review! I'm really sorry for this long PR. I completely agree with keeping PRs small. I started out with exactly that in my mind. However, as I kept developing and adding code I kinda got lost in the flow and ended up working on 4 issues (fixes for all of them happen to surround around the same logic).

2021-12-01 07:04 UTC, AnirudhBhat commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
> +    fun setCardReaderOnboardingCompletedPluginType(
I like the idea! However, my concern is how would some other part of the screen with no knowledge of the IPP plugin type query for the current onboarding completion status from shared preference?

for example: 
`fun isCardReaderOnboardingCompleted(localSiteId: Int, remoteSiteId: Long, selfHostedSiteId: Long)`
Here, with the above approach, the method needs to know the plugin type to query the onboarding completion status. Correct?

2021-12-01 09:07 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
> +    fun setCardReaderOnboardingCompletedPluginType(
The methods could look like this
fun getCardReaderOnboardingCompletedStatus(localSiteId: Int, remoteSiteId: Long, selfHostedSiteId: Long): NewEnumType

fun setCardReaderOnboardingCompletedStatus( localSiteId: Int, remoteSiteId: Long, selfHostedSiteId: Long, pluginType: PluginType)

So I believe they don't need to know the plugin type in other to query the status - the method would return one of `ONBOARDING_COMPLETED_WITH_WCPAY/ONBOARDING_COMPLETED_WITH_STRIPE_EXTENSION/ONBOARDING_NOT_COMPLETED`. Only the code which needs to update the flag needs to know the plugin type, but that's the OnboardingChecker which does know it already. Wdyt?

2021-12-01 09:08 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
> +    fun setCardReaderOnboardingCompletedPluginType(
We could even go as far as adding two query methods one
getCardReaderOnboardingCompletedStatus
and
isCardReaderOnboardingCompleted
The second one would internally invoke getCardReaderOnboardingCompletedStatus and check if the status is != ONBOARDING_NOT_COMPLETED.

2021-12-01 12:51 UTC, malinajirka commented
>  I'm really sorry for this long PR.

Please, no worries at all :)! 

> However, as I kept developing and adding code I kinda got lost in the flow

We've all fallen into this trap many times. Tbh this PR isn't that big, it's still manageable, but I wanted to mention it rather sooner than later.

2021-12-02 05:34 UTC, AnirudhBhat commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
> +    fun setCardReaderOnboardingCompletedPluginType(
Refactored here https://github.com/woocommerce/woocommerce-android/pull/5375/commits/71c01e025c75900286ebfe52cab8d1292a9692ca

2021-12-02 05:38 UTC, AnirudhBhat commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
> +            CardReaderOnboardingState.StripeTerminal.UnsupportedVersion -> "stripe_unsupported_version"
>We might want to consider mentioning stripe extension explicitly on these track events. Stripe is used by both WCPay and Stripe Extension so omitting the extension part might be a bit misleading, wdyt?

Good point! Done https://github.com/woocommerce/woocommerce-android/pull/5375/commits/4cbc161deaf4abb1133939b8346419d4d27df0d8#diff-1a0eaa705f4ade1040ad64adb842cf43fb2fa7d114a02f72444c594c66a0d3e7R169

>It'd be great to add a comment to iOS tickets when we merge this PR to make sure we use the same event names. We should also add the events to the spreadsheet.

I'll make sure to comment on the iOS ticket and update the spreadsheet

2021-12-02 05:42 UTC, AnirudhBhat commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
> +                    viewState.value = when (state.pluginType) {
Oops! I thought I had the same implementation for `UnsupportedVersion` as well. Refactored it here https://github.com/woocommerce/woocommerce-android/pull/5375/commits/4cbc161deaf4abb1133939b8346419d4d27df0d8

2021-12-02 05:44 UTC, AnirudhBhat commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
> +const val SUPPORTED_STRIPE_TERMINAL_VERSION = "5.8.1"
Yes! Somehow in my mind, It registered Stripe Terminal == Stripe Extension. Thanks for pointing this out. Fixed it here https://github.com/woocommerce/woocommerce-android/pull/5375/commits/ced240c0af80071d763b70ad94f2dc17a8d4333f

2021-12-02 05:44 UTC, AnirudhBhat commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
> +    fun `given wcpay and stripe are installed, when stripe is not activated, then onboarding complete triggered`() =
Agree! Fixed it here https://github.com/woocommerce/woocommerce-android/pull/5375/commits/6331f67bf68b5f8d397102cd24936b8c767e6fe4

2021-12-02 05:45 UTC, AnirudhBhat commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
> +    @Test
Absolutely! Added here https://github.com/woocommerce/woocommerce-android/pull/5375/commits/6acc31b52d0fcc4e23918305f5df217c9ac536b9
Thanks!

2021-12-02 05:46 UTC, AnirudhBhat commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="card_reader_onboarding_stripe_terminal_not_setup_header">Finish setup Stripe Terminal Gateway in your store admin</string>
Yes! Done https://github.com/woocommerce/woocommerce-android/pull/5375/commits/b1f140ee58e8d735c8651c93a2e54dc5b695bb1c

2021-12-02 10:21 UTC, AnirudhBhat commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
> +        val wcPayPluginInfo = wooStore.getSitePlugin(selectedSite.get(), WooCommerceStore.WooPlugin.WOO_PAYMENTS)
I figured it was hard to read and planned to refactor in a separate PR. Thanks a lot for taking the time to refactor this piece. I liked your version more! Thank you! Cherry-picked the commit here https://github.com/woocommerce/woocommerce-android/pull/5375/commits/1102f67636467f2f85ba604c313115df124a5dea

2021-12-02 10:49 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
> +    private fun isStripePluginInstalled(pluginInfo: WCPluginSqlUtils.WCPluginModel?): Boolean = pluginInfo != null
I'm sorry I completely missed this comment during my first review pass 😞 . 

Good question! Since the variables `wcPayPluginInfo` and `stripePluginInfo` already show what they are about and reading `isPluginInstalled(wcPayPluginInfo)` gives me all the context about what is going on, I personally prefer the generic version `isPluginInstalled`. Which is the current state :)

2021-12-02 10:50 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
> +    fun setCardReaderOnboardingCompletedPluginType(
Awesome, thanks for adding the tests! ❤️

2021-12-02 11:01 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
> +                if (it is OnboardingCompleted) {
🚫 I think this might not work as expected: The flag is used to check if the store is ready to accept in person payments. When the user for example uninstalls the plugin or Stripe blocks their account I think the app should reset the flag. Wdyt?


P.S. Thinking about it `onboarding` might not be the best term for this whole flow/logic/... Because the current implemention is not used just during the first time use but even to check that the store is still ready to accept in person payments. But improving that is definitely outside of the scope of this PR.

2021-12-02 11:07 UTC, malinajirka commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="card_reader_onboarding_stripe_terminal_not_setup_hint">You’re almost there! Please finish setting up WooCommerce Stripe Payment Gateway to start accepting Card-Present Payments.</st
⚠️ In user facing texts the feature is called `In-Person Payments`. We probably should update the resource to stay consistent with the other resources. Thanks!

2021-12-02 11:10 UTC, malinajirka requested changes
Thanks so much @AnirudhBhat! Great work! I've left two comments which I'd like to discuss before merging this PR, but it looks and works great overall!

2021-12-03 05:38 UTC, AnirudhBhat commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="card_reader_onboarding_stripe_terminal_not_setup_hint">You’re almost there! Please finish setting up WooCommerce Stripe Payment Gateway to start accepting Card-Present Payments.</st
Do you mean like this?
`Finish setup In-Person Payments in your store admin` and similarly for the other one

2021-12-03 08:01 UTC, malinajirka commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="card_reader_onboarding_stripe_terminal_not_setup_hint">You’re almost there! Please finish setting up WooCommerce Stripe Payment Gateway to start accepting Card-Present Payments.</st
Sorry, I should have been more explicit
```suggestion
    <string name="card_reader_onboarding_stripe_terminal_not_setup_hint">You’re almost there! Please finish setting up WooCommerce Stripe Payment Gateway to start accepting In-Person Payments.</string>
```

2021-12-03 08:10 UTC, AnirudhBhat commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="card_reader_onboarding_stripe_terminal_not_setup_hint">You’re almost there! Please finish setting up WooCommerce Stripe Payment Gateway to start accepting Card-Present Payments.</st
Cool! Thanks for clarifying! In that case, I believe I should do similar changes for WCPay resource as well. Correct?

It looks like this in its current state
`<string name="card_reader_onboarding_wcpay_not_setup_hint">You’re almost there! Please finish setting up WooCommerce Payments to start accepting Card-Present Payments.</string>`

2021-12-03 08:25 UTC, AnirudhBhat commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
> +                if (it is OnboardingCompleted) {
Oops! Thank you for catching this! Fixed it here https://github.com/woocommerce/woocommerce-android/pull/5375/commits/979b2d9477d3915a62b8160605800e6737708a3d

2021-12-03 08:28 UTC, malinajirka commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="card_reader_onboarding_stripe_terminal_not_setup_hint">You’re almost there! Please finish setting up WooCommerce Stripe Payment Gateway to start accepting Card-Present Payments.</st
Ohh, I missed that it's there as well. Yes, if you could update it, it'd be great!

2021-12-03 08:32 UTC, malinajirka approved these changes
Thanks so much for working on all of this! LGTM 🚢

2021-12-03 10:26 UTC, merged