Enable Gradle Cache
woocommerce/woocommerce-android pull request #5484
Opened 2021-12-20 14:56 UTC by malinajirka

### Description

This PR enables Gradle Cache by default. It should speed up local build times - especially after switching branches. More info https://docs.gradle.org/current/userguide/build_cache.html

### Testing instructions

Run eg. ` ./gradlew woocommerce:assembleWasabiDebug --scan` and make sure Gradle Cache is enabled.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-12-20 16:09 UTC, wzieba approved these changes
Looks good to me! Leaving unmerged for owl team review.

2021-12-21 16:56 UTC, oguzkocer requested changes
@malinajirka I left a comment about disabling build cache in CI, let me know what you think!

2021-12-21 16:56 UTC, oguzkocer commented on .circleci/config.yml
> +          command: sed -i "s/org.gradle.caching=true/org.gradle.caching=false/" gradle.properties
I don't think this is necessary. The builds are started from a clean environment, so the cache is only created by the CI running the previous jobs. WCAndroid doesn't have remote build cache enabled, but even if it did, as long as the cache is created from clean environments I think it's safe to trust. The release builds may be the only one worth putting it in, but Gradle has proved to be reliable in terms of how it caches and invalidates them for changes, so my preference would be to avoid adding extra logic around it.

2021-12-22 09:26 UTC, malinajirka commented on .circleci/config.yml
> +          command: sed -i "s/org.gradle.caching=true/org.gradle.caching=false/" gradle.properties
👍 Even better, removed in 9e4f5b72892ab3307706842fe8388babe58ae9a5. Thanks for the feedback!

2021-12-22 16:16 UTC, oguzkocer approved these changes
Thanks again for the PR @malinajirka! :shipit:

2021-12-22 16:16 UTC, merged