Update links for ordering M2 card reader and viewing the manual
woocommerce/woocommerce-android pull request #5620
Opened 2022-01-11 07:30 UTC by AnirudhBhat

Closes: #5619 

### Description

Update the purchase URL and the link to the user guide, to point to those corresponding to the Stripe M2 reader.

For context see pdfdoF-kx-p2

### Testing instructions

Log in to an eligible store, navigate to Settings > In-Person Payments.

1. Tap Order Card Reader. The app should present a web view, that will navigate to a 404 error, as the actual purchase URL has not been published yet.
2. Tap Card Reader Manual. The app should present a web view with the Stripe M2 user guide. 

**Note:** Regarding step 2. On Android 12, the device may prompt to download the manual rather than displaying the manual in the web view as soon as you tap "Stripe M2 card reader manual". 

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-01-11 08:34 UTC, malinajirka requested changes
Thanks for working on this @AnirudhBhat! I have left one important comment. The PR is following the ticket/p2 post, but I'm not sure it's what we actually want. The original plan (six weeks ago) was to keep links to manuals of both readers.

2022-01-11 08:34 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/hub/CardReaderHubViewModel.kt
> +                label = UiString.UiStringRes(R.string.card_reader_m2_manual_card_reader),
⚠️ I'm wondering if we need to keep the link to the BBPOS manual in the app. Users who already purchased the reader might need to access it in the future. Wdyt? (cc @ctarda)

2022-01-11 08:36 UTC, AnirudhBhat commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/hub/CardReaderHubViewModel.kt
> +                label = UiString.UiStringRes(R.string.card_reader_m2_manual_card_reader),
Thanks for bringing this up! I had the exact same doubt and asked this in our slack channel here p1641885835060300-slack-C025A8VV728

2022-01-11 08:39 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/hub/CardReaderHubViewModel.kt
> +                label = UiString.UiStringRes(R.string.card_reader_m2_manual_card_reader),
Nice, I missed that! Let's continue the convo on slack and share only the result of that discussion here.

2022-01-12 05:56 UTC, AnirudhBhat commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/hub/CardReaderHubViewModel.kt
> +                label = UiString.UiStringRes(R.string.card_reader_m2_manual_card_reader),
As per our discussion, I have added back the BBPOS Chipper card reader manual.

2022-01-12 06:00 UTC, AnirudhBhat commented
@malinajirka As per our internal Slack discussion, I have added back support for viewing the BBPOS Chipper card reader manual.

**Reason for adding back: ** Even though the Sale of BBPOS Chipper ends on February 1, 2021. Stripe supports it till 2024 and there are merchants who are currently using BBPOS Chipper in production.

2022-01-12 09:07 UTC, malinajirka approved these changes
Works as expected, thank you for working on this @AnirudhBhat! I'm merging this PR, but it'd be great if we added a reminder to double-check the purchase url works before this code reaches production. (I've added mine, but the more people double check this the better)

2022-01-12 09:07 UTC, merged

2022-01-12 09:49 UTC, AnirudhBhat commented
Absolutely! Will make sure to check the purchase URL before it gets released. Thank you!