Fix for next button enabled/disabled state in RefundByItem screen
woocommerce/woocommerce-android pull request #5691
Opened 2022-01-26 17:26 UTC by atomtec

Closes: #5628 

### Description

The Refund screen should have next button enabled if either Refund Fees , Refund Shipping or  any of the product is selected for refund . This assertion however breaks in the following scenario, 

1. Go Orders tab and select an order with at least one fee item.
2. Tap on the Issue Refund button. 
3. Now switch on the shipping and refund fees toggle . 
4. Switch off one of them , the next button becomes disabled 
5. Alternatively switch on any or both the toggles (this will occur even without fee item) . Now click on select all product  items followed by select none , observe that next button is disabled after selecting none , even though the other refund switch(es) is/are still in ON state .

### Root Cause 
When shipping or fees refund is switched on or off individually or when product refund items are selected the next button state is enabled or disabled depending upon product refund amount + shipping or product refund + fees . So when fees refund is switching  between on or off state the shipping refund amount is not considered similarly  in case for shipping  refund switch the fees refund is missed.
In case of refunding the product item , the next button toggles based only on the condition if one or more item is selected or not. This does not consider shipping or refund amount at all . So even shipping and /or fees switch is in ON state , unselecting all refund items will disable the next button

### Fix 
This fix checks for all the three refund categories  before toggling the state of the next button .

### Issue Video 
**![5628](https://user-images.githubusercontent.com/20752243/151200374-9c1e66a5-dc66-490a-b6d9-13410f62bc7a.gif)**

### Testing instructions

1. Go Orders tab and select an order with at least one fee item.
2. Tap on the Issue Refund button. 
3. Keep any one switch in ON state viz .. refund fees , refund shipping or any one product item selected for refund  .
4. Change the state of other switch or/and remove all selected item from the product . Observe that next button remains enabled as long as the as the refund amount is not zero . i.e there is at least one valid fees,shipping or item selected for return.
5. The next button will be off iff and only iff there some money to be returned 

### Video after Fix 

https://user-images.githubusercontent.com/20752243/151201246-f26c1e9b-48ac-4153-8e5f-54847a26e15b.mp4

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-01-27 10:21 UTC, hichamboushaba requested changes
Nice work @atomtec, it works well, but I think we can improve things and avoid repetition:

Since the `isNextButtonEnabled` logic is always linked to the state of `productsRefund` and `shippingRefund` and `feesRefund`, we can compute it from their values instead of providing it in the constructor, using a computed property, I mean something like:
```kotlin
data class  RefundByItemsViewState(
       ... // Same, just exclude isNextButtonEnabled
) {
   val isNextButtonEnabled: Boolean
         get() = productsRefund.add(shippingRefund).add(feesRefund) > BigDecimal.ZERO
}
```
WDYT?

Another point, `detekt` is complaining about the formatting of the code, you can use the gradle task `detektAll` to check the status on your machine.

2022-01-28 19:32 UTC, atomtec commented
> Nice work @atomtec, it works well, but I think we can improve things and avoid repetition:
> 
> Since the `isNextButtonEnabled` logic is always linked to the state of `productsRefund` and `shippingRefund` and `feesRefund`, we can compute it from their values instead of providing it in the constructor, using a computed property, I mean something like:
> 
> ```kotlin
> data class  RefundByItemsViewState(
>        ... // Same, just exclude isNextButtonEnabled
> ) {
>    val isNextButtonEnabled: Boolean
>          get() = productsRefund.add(shippingRefund).add(feesRefund) > BigDecimal.ZERO
> }
> ```
> 
> WDYT?
> 
> Another point, `detekt` is complaining about the formatting of the code, you can use the gradle task `detektAll` to check the status on your machine.

Hi @hichamboushaba 
That is a great idea , I have done the same . 
I have checked with detektAll the build is passing in my machine.

2022-01-31 00:15 UTC, hichamboushaba approved these changes
This looks good, thanks for the fix @atomtec 

I think we should plan to add some unit tests to this in the future.

2022-01-31 00:15 UTC, merged

2022-01-31 18:12 UTC, atomtec commented
> This looks good, thanks for the fix @atomtec
> 
> I think we should plan to add some unit tests to this in the future.

Yes true that !!