Issue/5696 handle fee selection
woocommerce/woocommerce-android pull request #5912
Opened 2022-02-21 23:12 UTC by ThomazFB

Closes: #

### Description

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-02-25 12:25 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationFormFragment.kt
> +                binding.paymentSection.feeButton.isEnabled = show.not()
I'm currently disabling the fees button when we're syncing the Order price to avoid confusion with outdated info inside the Fee view when editing.

2022-02-28 19:22 UTC, hichamboushaba requested changes
Really nice work @ThomazFB, but there is a blocking issue, in the edit flow, there is a data loss whenever the `onResume` callback is triggered, check comments for more details.

2022-02-28 19:22 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationFormFragment.kt
> +            feeValue.isVisible = false
np, you don't need to change it, just personally I found it a bit hard to read this part, maybe using a simple `if/else` statements on `has fees` vs `doesn't` would be easier to read, but it's a personal choice 🙂.

2022-02-28 19:22 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationViewModel.kt
> +        get() = _orderDraft.value.feesLines.firstOrNull()
This is used only in `onFeeButtonClicked`, WDYT about moving it inside the function? I feel like having it as a property indirectly causes the ViewModel to care about more stuff, while being a part of the function makes it a local variable, that we don't care about unless we are reading this function.

Also a remark regarding the logic, I know currently we disable the `fees` button while syncing the order, but if we didn't, this would cause an issue of passing the deleted fee to the fees screen if the button was clicked during sync, I feel like we should handle this, as we may forget about it if for some case we decided to keep the button enabled on some cases, so what do you think about updating the logic to this:
```kotlin
_orderDraft.value.feesLines.firstOrNull { it.name != null }
```

2022-02-28 19:22 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationViewModel.kt
> +        }
np, this works well, but it's less optimised, we delete the previous fee before adding a new one always, this would always cause the backend to delete the previous entry and generate a new one with a new ID, WDYT about checking if we have a previous one, then updating it, otherwise add a new one. so the logic should be:
```kotlin
        val newFee = (draft.feeLines.firstOrNull() ?: Order.FeeLine.EMPTY).copy(
            name = ORDER_CUSTOM_FEE_NAME,
            total = feeValue
        )
```
or something in those lines 🤔

2022-02-28 19:22 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/fees/OrderCreationFeeFragment.kt
> +        editFeeViewModel.start()
This block is causing an issue, when we are in the edit flow, whenever we rotate the screen or navigate to another app, all user data is lost.
I think a cleaner and easier to maintain approach would be to make the ViewModel initialization automatically in the `init` block like what we did in the shipping screen, WDYT?

Just a hint, if you decide to use the `init` app, you may need to add `drop(1)` to the `feeAmountEditText.value` to avoid overriding the current value with `0`.

2022-03-01 04:01 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationFormFragment.kt
> +            feeValue.isVisible = false
I understand your point, I also think this is not the best reading experience too, I decided to go like this because of the two conditionals attached to the existence of the fee object itself, but of course, it's possible to improve how it was done here. Here's the fix: https://github.com/woocommerce/woocommerce-android/pull/5912/commits/9253c521afb8112e31d2aa0d92a9fa42e60611d7. Let me know what you think!

2022-03-01 04:02 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationViewModel.kt
> +        get() = _orderDraft.value.feesLines.firstOrNull()
I should've removed this property, at first I considered it would be used a lot, but it wasn't the case, your point about the ViewModel caring about more stuff is perfectly fair too. Thanks! Here's the fix: https://github.com/woocommerce/woocommerce-android/pull/5912/commits/43283fc0339cafc2c778e7f856baf100054995fa

2022-03-01 04:04 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationViewModel.kt
> +        }
Great suggestion! I definitely should've considering about reusing the current fee instead of creating and deleting all the time 🤦. Here's the fix: https://github.com/woocommerce/woocommerce-android/pull/5912/commits/3327beb1537f2ef6c66ba27c43977acd0ff1db94.

2022-03-01 04:05 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/fees/OrderCreationFeeFragment.kt
> +        editFeeViewModel.start()
That was a rookie mistake of mine, thanks for catching it! Here's the fix: https://github.com/woocommerce/woocommerce-android/pull/5912/commits/5652feb38a8dca41a1d27a01fef04cc11fc4a872

2022-03-01 04:07 UTC, ThomazFB commented
@hichamboushaba thank you a lot for the review, great suggestions indeed! The PR is ready for a second round!

2022-03-01 10:35 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationViewModel.kt
> +        get() = _orderDraft.value.feesLines.firstOrNull()
Thanks @ThomazFB for the change.

WDYT about the second part of my remark, about using `firstOrNull { it.name != null }` instead of plain `firstOrNull()`?

2022-03-01 10:37 UTC, hichamboushaba approved these changes
Nice work @ThomazFB, thanks so much for the last changes, I left one last [question](https://github.com/woocommerce/woocommerce-android/pull/5912#discussion_r816646545) regarding the calculation of the current fee during when the edit button is clicked, so I won't merge to give you a chance to check it.

2022-03-01 16:23 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationViewModel.kt
> +        get() = _orderDraft.value.feesLines.firstOrNull()
Sorry, I forgot to submit this improvement, I agree with your point. Here's the fix: https://github.com/woocommerce/woocommerce-android/pull/5912/commits/c01fb2b53c1a64833a08072b6ee8087c6e314778

2022-03-01 16:24 UTC, ThomazFB commented
@hichamboushaba sorry about this last remark of yours, it's fixed now, thanks for your thoughtful review! 🙇

2022-03-01 17:00 UTC, merged