Added unsupported stripe and wcpay in a country state
woocommerce/woocommerce-android pull request #5919
Opened 2022-02-23 09:06 UTC by kidinov

Closes: #

### Description

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-02-23 09:12 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
>                  is CardReaderOnboardingState.StripeAccountCountryNotSupported ->
I didn't change here anything, but shouldn't we also specify something about stripe in the error message here? @malinajirka

2022-02-23 09:16 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
>                  is CardReaderOnboardingState.StripeAccountCountryNotSupported ->
I think we opted for the easiest solution since it probably won't be common that a store manager sets a different country in their Stripe account and on their store. Having said that, we could improve the UX and be explicit about it.

2022-02-23 12:59 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
>                  is CardReaderOnboardingState.StripeAccountCountryNotSupported ->
Wdyt about this change regarding this 107326f83238daba6acbd78c7c389a1df464254d ?

2022-02-24 14:21 UTC, malinajirka requested changes
Thanks @kidinov! Great work :). Found one possible easy to fix blocker but other than that looks great 👏 !

2022-02-24 14:21 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/CardReaderTracker.kt
> +                "${getPluginNameReasonPrefix(state.preferredPlugin)}_is_not_supported_in_{${state.countryCode}}"
🚫 It seems there are extra `{ }`around the country code => example: `"reason":"stripe_extension_is_not_supported_in_{CA}"`. Is that intentional?

P.S. It'd be great to add test for it, thanks!

2022-02-24 14:21 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModel.kt
>                  is CardReaderOnboardingState.StripeAccountCountryNotSupported ->
I like it, nice improvement!

2022-02-24 14:21 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
> +    fun `given Canada store, when stripe ext activated, then plugin is not supported in country returned`() =
💡 We might want to consider adding "the opposite" test to this one. Something like `given US store, when stripe ext activated, then plugin is not supported in country iS NOT returned`.

2022-02-24 14:21 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModelTest.kt
> +    fun `given wcpay not not supported in coutnry, when learn more clicked, then app shows learn more section`() =
🔍 There seem to be two typos `wcpay not not supported` and `coutnry` instead of `country`.

2022-02-24 14:21 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModelTest.kt
> -            assertThat(viewStateData.onRefreshAfterUpdatingClicked != null).isTrue
🔍 Is the removal of ` assertThat(viewStateData.onRefreshAfterUpdatingClicked != null).isTrue` intentional?

2022-02-25 07:56 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/CardReaderTracker.kt
> +                "${getPluginNameReasonPrefix(state.preferredPlugin)}_is_not_supported_in_{${state.countryCode}}"
Good catch, thank you. Fixed - 1074a57172334ff98380d4c9516bcf161fb09f27 (+test)

2022-02-25 08:01 UTC, kidinov commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModelTest.kt
> +    fun `given wcpay not not supported in coutnry, when learn more clicked, then app shows learn more section`() =
Fixed - 1074a57172334ff98380d4c9516bcf161fb09f27

2022-02-25 08:25 UTC, kidinov commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingCheckerTest.kt
> +    fun `given Canada store, when stripe ext activated, then plugin is not supported in country returned`() =
Done 6c5ca67d43a22a34ed4d79b9d5e66261ad43768d

2022-02-25 08:26 UTC, kidinov commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModelTest.kt
> -            assertThat(viewStateData.onRefreshAfterUpdatingClicked != null).isTrue
Yep, is not nullable anyway

2022-02-25 08:49 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingViewModelTest.kt
> -            assertThat(viewStateData.onRefreshAfterUpdatingClicked != null).isTrue
I see, thanks!

2022-02-25 08:56 UTC, malinajirka approved these changes
Thanks, LGTM 🚢

2022-02-25 09:19 UTC, merged