Issue/5648 Refactoring of the payment navigation
woocommerce/woocommerce-android pull request #6021
Opened 2022-03-15 14:00 UTC by kidinov

Closes: #5648

### Description

The PR is not final, it's more a **POC**. For now, I want to understand if this approach is actually something we ok to take and then I'll polish it if it is

Before we had 3 different navigation flows for:
* A normal order
* Simple payment
* IPP settings
<img src="https://user-images.githubusercontent.com/4923871/158393092-c6aa26f1-070c-4940-9a01-6bf66269b6a2.jpg" width="500">
<img src="https://user-images.githubusercontent.com/4923871/158393101-ecfabeb8-9296-4956-9a3c-76020e808dff.jpg " width="500">
<img src="https://user-images.githubusercontent.com/4923871/158393097-e21df81b-1bbf-45f1-b3eb-21c701cf8308.jpg" width="500">

The PR makes it 1 flow with 2 parameters:
* Collect payment
* Show card-reader settings

<img src="https://user-images.githubusercontent.com/4923871/158393328-2cab662a-7180-45cd-a552-f60f52e5e5f0.jpg " width="500">

The idea is to remove all the back and forth navigation. It should be just "start the payment flow with a parameter and forget" approach

Please play with this, look

### Testing instructions

Try the flows:
* IPP for a normal order
* Simple payment flow
* IPP settings

It is known that navigation is not final so pay attention to the cases when a dialog appears and then disappears right away (in my testing it's not visible)

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-03-15 15:57 UTC, nbradbury commented
@kidinov I think your approach is fine here, and it's so much better than having three navigation flows. The only thing I noticed - and you're probably already aware of this - is that the "In person payments" fragment appears behind the dialog when the flow is started from simple payment or order detail, and it didn't use to be that way.

![1](https://user-images.githubusercontent.com/3903757/158418961-595d6306-a7a6-401f-8c97-30b9c391e098.png)

2022-03-15 16:03 UTC, kidinov commented
@nbradbury  thank you for taking a look here 🙏

> The only thing I noticed - and you're probably already aware of this - is that the "In person payments" fragment appears behind the dialog when the flow is started from simple payment or order detail, and it didn't use to be that way.

Yep, something I need to look into if we like the approach

2022-03-16 03:56 UTC, malinajirka commented
Thanks for working on this @kidinov ! I like the approach very much! Having a single starting point makes the usage of the flow simpler and less error prone. Passing the parameters which allow us to slightly modify the flow depending on the starting location feels ok and maintainable.

When I was testing this PR I noticed a few user facing changes, I'm not sure if these are part of the POC or if they'd be present even in the final implementation:
- Welcome dialog is shown even when we start the flow from App Settings - might be ok to keep it, I'm not sure.
- The onboarding loading screen is shown even when the onboarding succeeds/is completed => before, the loading screen was shown only when the user entered the onboarding from app settings, now it's visible even when they enter from Order Detail => this might be a no-go from the design perspective, but I think we can come up with a reasonable solution.
- As Nick pointed out, an empty fragment is shown behind the dialogs => also imho a no-go from a design perspective, but again I think we can find a solution.
- Bugs, eg -> when I cancel the payment flow I'm navigated back to onboarding flow.


All in all I like the approach and I'd go ahead with it. Only if you already know about user-facing changes which we might need to introduce, I'd discuss them first with the design team.

2022-03-16 11:19 UTC, kidinov commented
@malinajirka Thank you for your feedback! I fixed/improved most of the issues you mentioned

The only difference now with what it used to be:
* We show "welcome" dialog if onboarding never happened on a device if a user goes to the IPP settings (IMHO It's not bad at all)
* We show an "onboarding" screen every time we use payments. Technically it's a good thing because in case something with a store setup wrong we'll show a good message to a user, but it's a one extra screen

@adamzelinski @joe-keenan could you please take a look? Is the change ok?

https://user-images.githubusercontent.com/4923871/158578213-c10d9ab4-fe5c-415e-b108-4a3be591fec0.mp4
https://user-images.githubusercontent.com/4923871/158578200-02d02ce7-9e56-4a02-a3af-24b2c8698c37.mp4
https://user-images.githubusercontent.com/4923871/158578175-60890bce-2a3b-47b6-974c-9673bbd3eb35.mp4

2022-03-16 17:08 UTC, malinajirka commented
> We show an "onboarding" screen every time we use payments. Technically it's a good thing because in case something with a store setup wrong we'll show a good message to a user, but it's a one extra screen

It was the case even before, but the app just didn't navigate to it unless there was an onboarding error. The app first checked if the onboarding is completed and navigated to the flow only when it was not completed and showed the corresponding error. So technically the only change this PR introduces is that it shows the onboarding loading screen even when the onboarding is completed.

We discussed with Garance if we should navigate to the onboarding every time, but she was against it, since the onboarding flow is fullscreen. We were even thinking about changing the Onboarding flow to a dialog but decided against to limit the scope. We agreed that since the onboarding error is shown only when the onboarding is not completed, it's a good enough solution.

I'd personally also avoid switching to fullscreen onboarding flow unless necessary as it feels a bit weird -> it kind of goes against the point of having all the other flows in dialogs. Just my two cents :).

2022-03-16 17:11 UTC, nbradbury commented
> I'd personally also avoid switching to fullscreen onboarding flow unless necessary as it feels a bit weird -> it kind of goes against the point of having all the other flows in dialogs. Just my two cents :).

I agree.

2022-03-16 17:25 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/simplepayments/SimplePaymentsDialogViewModel.kt
> -            saveCountryForTracking()
Not needed anymore because we go via onboarding for all the flows

2022-03-17 07:12 UTC, joe-keenan commented
Hey, I’m not sure what decision has been made, but regarding the videos you posted, @kidinov, it’s a little bit weird to present the first onboarding modal when you tap on the IPP settings menu item. I’m not against showing the modal at all – just the timing of it is weird. 
We’ve established a pattern where people expect that if they tap on a settings row, it will slide right to go to a new screen, and I think we should keep this. If we want to show a modal, then we should slide right to the next screen, then display the modal once that screen has loaded.

For the other videos, like the other comments, I agree that it’s very confusing to show the onboarding modal, then show the IPP screen, then go back and show a different modal. If the IPP step could be integrated into the sequence of modals, then it would be a lot less confusing.

I still feel like I might be missing something. I would have to go and look at Garance’s original proposal that @malinajirka mentioned in his comment before I could give you more detailed feedback, sorry!

2022-03-30 17:12 UTC, nbradbury commented
@kidinov I see that the discussion on this has died down but it's still being updated. Is this awaiting another review?

2022-03-31 02:21 UTC, malinajirka commented
Thanks @nbradbury for proactively asking about this, truly appreciate it!!! 

We've had a long discussion about this and other inconsistencies between Android and iOS on p2s and Slack. We agreed on 2 UI/UX changes to the flow
1. Show the "Welcome to IPP" dialog after the app knows that onboarding has been completed and the store is ready to accept IPP. Before this PR, we'd show it right after the user clicked on "Collect Payment" no matter the onboarding state.
2. Show a loading dialog while the app is checking if onboarding is completed - currently, we plan to reuse the "Scanning for readers" dialog, but this might change since we are seeing some UI glitches.

Either case, since this is very related to IPP, I'll assign myself and start reviewing it. Having said that, since this is a relatively complex PR, feel free/encouraged to do a double review :).

2022-03-31 05:45 UTC, malinajirka requested changes
Great job @kidinov, we are very close to merging this PR! Really nice improvements to the code which will make it easier to use IPP in other flows and also bring consistency among the places which already use the flow.

I've left some in-code questions and a shared a couple of concerns and ideas.

I also noticed the "Card" row in Simple Payments flow is not visible unless the user finished onboarding -> My understanding is that this PR introduces `onboarding checks` into the Simple Payment flow -> would it make sense to update the logic so the "Card" row is visible even before the onboarding is completed? Note: It's fine to do this in a separate PR or perhaps even preferred. I'd just consider creating an explicit ticket for it unless it already exists. Wdyt?

The only UI issue I noticed is the UI glitch you mentioned on Slack - there is noticable "blink" after the app navigates to "connect flow" from the "checker". I think we might be able to get rid of it if we don't navigate to the tutorial screen unless we know it'll be shown as per my comment. 

Let me know what you think about all this :).

2022-03-31 05:45 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/tutorial/CardReaderTutorialDialogFragment.kt
> +        if (!appPrefs.getShowCardReaderConnectedTutorial()) {
❓ Have you consider running this check in [CardReaderConnectViewModel](https://github.com/woocommerce/woocommerce-android/blob/b89571df1e26cbb4c2f816fcafbb550b6db7a899/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt#L410) and skipping this destination completely when it's not shown? It might solve the "ui glitch/blinking" issue. If you did, could you please elaborate a bit why you opted for the current solution? Thanks!

2022-03-31 05:45 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/tutorial/CardReaderTutorialDialogFragment.kt
> +        when (val param = requireArguments().getParcelable<CardReaderFlowParam>("cardReaderFlowParam")) {
⚠️  Have you considered using type safe navArgs 
```
val args: CardReaderTutorialDialogFragmentArgs by navArgs()
```
instead of manually loading the arguments?

2022-03-31 05:45 UTC, malinajirka commented on WooCommerce/src/main/res/navigation/nav_graph_card_reader_flow.xml
> +        <argument
💡  It seems that we specify the argument in all the destinations but also override them in all the actions. Tbh I don't have much experience with the navigation component so I might be missing something vital, but I'm wondering if this is needed. Can we have the arguments just at the destination level?

2022-03-31 05:45 UTC, malinajirka commented on WooCommerce/src/main/res/navigation/nav_graph_card_reader_flow.xml
> +    <fragment
🚫 It seems that the onboarding fragment never navigates to the connect flow. However, when the Stripe account has pending requirements, the app displays "continue/skip" button on the onboarding screen and the user should be able to accept payment in such scenario => is this flow supported in the current implementation? Sorry, I completely forgot about this flow until now, that's why I haven't mentioned it sooner.

2022-03-31 05:45 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
> +    fun `given card reader is connecting, when user clicks on accept card, then start card reader payment flow`() =
💡  It seems that these tests 
`given card reader is ....., when user clicks on accept card, then start card reader payment flow`
are now identical, since the logic has changed and we navigate to the card reader flow no matter what. Perhaps, having a single test `when user clicks on accept card, then start card reader flow` might be enough and would be less confusing, wdyt?

2022-03-31 05:45 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
> +    fun setCardReaderWelcomeDialogShown() =
❓ The welcome dialog will be shown just once per app - not once per site as before. Is this an intended change? Tbh I'm not sure which is better, just double checking.

2022-03-31 12:06 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
> +    fun setCardReaderWelcomeDialogShown() =
This is intentional. Also, not 100% sure that this is the best approach, but I think most merchants want to see this once. It doesn't bring much value to see it once per site, but I might be missing something

2022-03-31 12:18 UTC, kidinov commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderDetailViewModelTest.kt
> +    fun `given card reader is connecting, when user clicks on accept card, then start card reader payment flow`() =
Good catch! Removed the duplicated - ab71e19c95569b6cc9f32c2e9bf563499f2094ff

2022-03-31 12:52 UTC, kidinov commented on WooCommerce/src/main/res/navigation/nav_graph_card_reader_flow.xml
> +    <fragment
Oh right, before we were checking the flow in fragment and I missed that.

Fixed now - dcc3baa19e300ca653c5949a5dd291041971a80a

2022-03-31 13:05 UTC, kidinov commented on WooCommerce/src/main/res/navigation/nav_graph_card_reader_flow.xml
> +        <argument
Indeed not needed - dc943f52991a04ad4acdcbd07f747004033d0688

2022-03-31 13:18 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/tutorial/CardReaderTutorialDialogFragment.kt
> +        if (!appPrefs.getShowCardReaderConnectedTutorial()) {
I haven't because I didn't see an issue here. The issue a spoke about was the transition from the StatusChecker to CardReaderConnectionDialog. They look the same now, but during transition, it might possible to notice that the first  disappears  before the second dialog appears

it makes sense to keep this line here, because we open this dialog from 2 places, this way there is no need to have the code in 2 places:

<img width="631" alt="image" src="https://user-images.githubusercontent.com/4923871/161063496-0d64928b-56bf-4a2c-9d65-84edc2620bab.png">

2022-03-31 13:20 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/tutorial/CardReaderTutorialDialogFragment.kt
> +        when (val param = requireArguments().getParcelable<CardReaderFlowParam>("cardReaderFlowParam")) {
Good call! 181a7bd88ecc2957703293048b4f84f14b82f6f0

2022-03-31 13:25 UTC, kidinov commented
@malinajirka thanks for the review!

> I also noticed the "Card" row in Simple Payments flow is not visible unless the user finished onboarding -> My understanding is that this PR introduces onboarding checks into the Simple Payment flow -> would it make sense to update the logic so the "Card" row is visible even before the onboarding is completed (we could use the existing CardReaderPaymentCollectibilityChecker)? Note: It's fine to do this in a separate PR or perhaps even preferred. I'd just consider creating an explicit ticket for it unless it already exists. Wdyt?

Indeed would be an improvement - https://github.com/woocommerce/woocommerce-android/issues/6127

> The only UI issue I noticed is the UI glitch you mentioned on Slack - there is noticable "blink" after the app navigates to "connect flow" from the "checker". I think we might be able to get rid of it if we don't navigate to the tutorial screen unless we know it'll be shown as per my comment.

Before it was going through the Welcome Dialog. Now it's gone, but still blinking is visible. I already tried to play with animations, but the result is not really satisfying. We might consider doing something more radical then what I'm trying to avoid  for now

2022-04-01 03:16 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
> +    fun setCardReaderWelcomeDialogShown() =
I agree, it seems like a minor thing but might be worth bringing this up on Slack so it's consistent with iOS. I wouldn't block this PR on the discussion as we can update it any time. Wdyt?

2022-04-01 05:27 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/tutorial/CardReaderTutorialDialogFragment.kt
> +        if (!appPrefs.getShowCardReaderConnectedTutorial()) {
Ohh, right .... I got confused.

I've played with it for a bit and it seems the navigation component by default first popups the checkerDialog and then adds the connectionDialog. If we remove the `popUpTo` and popup from the connect dialog, the glitch disappears.

```
Index: WooCommerce/src/main/res/navigation/nav_graph_card_reader_flow.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/res/navigation/nav_graph_card_reader_flow.xml b/WooCommerce/src/main/res/navigation/nav_graph_card_reader_flow.xml
--- a/WooCommerce/src/main/res/navigation/nav_graph_card_reader_flow.xml	(revision 181a7bd88ecc2957703293048b4f84f14b82f6f0)
+++ b/WooCommerce/src/main/res/navigation/nav_graph_card_reader_flow.xml	(date 1648790539863)
@@ -29,9 +29,7 @@
             app:popUpToInclusive="true" />
         <action
             android:id="@+id/action_cardReaderStatusCheckerDialogFragment_to_cardReaderConnectDialogFragment"
-            app:destination="@id/cardReaderConnectDialogFragment"
-            app:popUpTo="@+id/cardReaderStatusCheckerDialogFragment"
-            app:popUpToInclusive="true" />
+            app:destination="@id/cardReaderConnectDialogFragment"/>
     </dialog>
 
     <fragment
@@ -121,7 +119,7 @@
             app:exitAnim="@null"
             app:popEnterAnim="@null"
             app:popExitAnim="@anim/activity_fade_out"
-            app:popUpTo="@+id/cardReaderConnectDialogFragment"
+            app:popUpTo="@+id/cardReaderStatusCheckerDialogFragment"
             app:popUpToInclusive="true" />
         <action
             android:id="@+id/action_cardReaderConnectDialogFragment_to_cardReaderUpdateDialogFragment"
@@ -130,7 +128,7 @@
             app:exitAnim="@null"
             app:popEnterAnim="@null"
             app:popExitAnim="@anim/activity_fade_out"
-            app:popUpTo="@+id/cardReaderWelcomeDialogFragment"
+            app:popUpTo="@+id/cardReaderStatusCheckerDialogFragment"
             app:popUpToInclusive="true" />
     </dialog>
     <dialog

```
However, this is not a solution as it works only for the `order detail -> collect payment` path. It'd be hacky but we could theoretically check in kotlin what is the previousBackStackEntry and set `popUpTo` based on that. It's hacky, but we are mis-using dialogs so I guess we might need to end up with some hacks. I thought I'd share this mostly as brainstorming - perhaps it'll help you come up with some other idea. Wdyt?

2022-04-01 05:37 UTC, malinajirka approved these changes
Thanks for all the changes @kidinov!

I've retested it and I think we can merge this PR. However, the UI glitch between checkerDialog and connectionDialog is not optimal (I left some thoughts [here](https://github.com/woocommerce/woocommerce-android/pull/6021#discussion_r840244065)). I'd do our best to find a solution for it asap. If we won't find a solution, I'd at least opt for changing the design of the checkerDialog so it's not so visible that it's a bug.

I'm not merging this PR for two reasons
1. I think it's better to wait for Monday's freeze in case we missed something to have extra 14 days of development testing.
2. I want to give others chance to also review this PR since it's quite big.

Having said that, I'll leave the final decision to you. Feel free to merge it as is today. Great job working on this!

2022-04-01 05:45 UTC, malinajirka requested changes
I found one bug after all - the `pendingRequirements` skip button doesn't popUp the screen so it remains in the background.
<img src="https://user-images.githubusercontent.com/2261188/161202322-056700db-328f-4329-8aa0-55738d3242c4.png" width="250px" />

2022-04-01 05:52 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/tutorial/CardReaderTutorialDialogFragment.kt
> +        if (!appPrefs.getShowCardReaderConnectedTutorial()) {
Btw looking at `trunk` it seems we were not using `popUpTo` and `popUpToInclusive` before. I understand we were not using it for `connect -> payment` transition as that would originally go through the parent (e.g. OrderDetail). However, I'm missing how come we didn't need it for `connect -> tutorial` and similar transitions and how come we need it now?

2022-04-01 07:50 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
> +    fun setCardReaderWelcomeDialogShown() =
I want to P2 our resulting flow and talk with iOS folks about what they have and what they think about syncing it. Even without this PR we have quite some differences

2022-04-01 09:33 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/tutorial/CardReaderTutorialDialogFragment.kt
> +        if (!appPrefs.getShowCardReaderConnectedTutorial()) {
> I've played with it for a bit and it seems the navigation component by default first popups the checkerDialog and then adds the connectionDialog. If we remove the popUpTo and popup from the connect dialog and we update actions of the connect dialog, the glitch disappears (because checkerDialog remains on the UI). Check the patch below.

This is a great catch. I haven't thought in this direction at all. I'll try to find a workaround

> Btw looking at trunk it seems we were not using popUpTo and popUpToInclusive before. I understand we were not using it for connect -> payment transition as that would originally go through the parent (e.g. OrderDetail). However, I'm missing how come we didn't need it for connect -> tutorial and similar transitions and how come we need it now?

This is actually not needed because the back button is blocked anyway on the Tutorial dialog, but I think it's right way to go here because we don't want to go back from Tutorial to Connection, right?

> it.setCancelable(false)

2022-04-01 09:57 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/tutorial/CardReaderTutorialDialogFragment.kt
> +        if (!appPrefs.getShowCardReaderConnectedTutorial()) {
@malinajirka it's blinking with your patch too for me :(

Uploading 04-01--12-56.mp4…

2022-04-01 12:31 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/tutorial/CardReaderTutorialDialogFragment.kt
> +        if (!appPrefs.getShowCardReaderConnectedTutorial()) {
@malinajirka I come up with the following workaround for now c572d0d62b103c5b5eb60ba1c1773f69c80066ee . Please let me know if you have a better idea

2022-04-01 13:29 UTC, kidinov commented
@malinajirka 

https://github.com/woocommerce/woocommerce-android/pull/6021#pullrequestreview-928455581
Fixed the bug - d3073a0b6ea3b7ac0efc1955423ce7d4e62c7dbe

> I don't think we need to do it in this PR, but it seems we don't have a unit test for this scenario. That's why it was easy to miss in the first place. Might be worth adding a test for it, wdyt?

Done - 62839004a6f86a918967cf17e30f2b4c912fefd6

2022-04-04 04:49 UTC, malinajirka requested changes
Thanks for the changes @kidinov! 

The UI glitch is gone, great job! However, I noticed that after the changes the connection dialog is never poped-up from the backstack during the payment flow. I've tested a successful, failed and canceled payment and the connection dialog keeps hanging on the screen when I leave the payment flow.

https://cloudup.com/cs7ByakyKy4

2022-04-04 10:27 UTC, kidinov commented
@malinajirka 

as discussed removed the workarounds and changed the UI a5310baef27923a364527b2a408f16cad84bf6d4

2022-04-05 02:55 UTC, malinajirka requested changes
It seems that both OrderDetail and IPP Settings flows always crash when I attempt to open them:
```
2022-04-05 09:53:12.511 4851-4851/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.woocommerce.android.prealpha, PID: 4851
    java.lang.NoSuchMethodException: com.woocommerce.android.ui.orders.details.OrderDetailFragmentArgs.fromSavedStateHandle [class androidx.lifecycle.SavedStateHandle]
        at java.lang.Class.getMethod(Class.java:2103)
        at java.lang.Class.getMethod(Class.java:1724)
        at com.woocommerce.android.viewmodel.NavArgsLazy.getValue(SavedStateHandleExt.kt:35)
        at com.woocommerce.android.viewmodel.NavArgsLazy.getValue(SavedStateHandleExt.kt:24)
        at com.woocommerce.android.ui.orders.details.OrderDetailViewModel.getNavArgs(OrderDetailViewModel.kt:70)
        at com.woocommerce.android.ui.orders.details.OrderDetailViewModel.access$getNavArgs(OrderDetailViewModel.kt:50)
        at com.woocommerce.android.ui.orders.details.OrderDetailViewModel$start$1.invokeSuspend(OrderDetailViewModel.kt:123)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:256)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at com.woocommerce.android.ui.orders.details.OrderDetailViewModel.start(OrderDetailViewModel.kt:122)
        at com.woocommerce.android.ui.orders.details.OrderDetailFragment.setupObservers(OrderDetailFragment.kt:248)
        at com.woocommerce.android.ui.orders.details.OrderDetailFragment.onViewCreated(OrderDetailFragment.kt:133)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
```

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.woocommerce.android.prealpha, PID: 5406
    java.lang.NoSuchMethodException: com.woocommerce.android.ui.orders.cardreader.statuschecker.CardReaderStatusCheckerDialogFragmentArgs.fromSavedStateHandle [class androidx.lifecycle.SavedStateHandle]
        at java.lang.Class.getMethod(Class.java:2103)
        at java.lang.Class.getMethod(Class.java:1724)
        at com.woocommerce.android.viewmodel.NavArgsLazy.getValue(SavedStateHandleExt.kt:35)
        at com.woocommerce.android.viewmodel.NavArgsLazy.getValue(SavedStateHandleExt.kt:24)
        at com.woocommerce.android.ui.orders.cardreader.statuschecker.CardReaderStatusCheckerViewModel.getArguments(CardReaderStatusCheckerViewModel.kt:29)
        at com.woocommerce.android.ui.orders.cardreader.statuschecker.CardReaderStatusCheckerViewModel.checkStatus(CardReaderStatusCheckerViewModel.kt:41)
        at com.woocommerce.android.ui.orders.cardreader.statuschecker.CardReaderStatusCheckerViewModel.access$checkStatus(CardReaderStatusCheckerViewModel.kt:20)
        at com.woocommerce.android.ui.orders.cardreader.statuschecker.CardReaderStatusCheckerViewModel$1.invokeSuspend(CardReaderStatusCheckerViewModel.kt:36)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:256)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at com.woocommerce.android.ui.orders.cardreader.statuschecker.CardReaderStatusCheckerViewModel.<init>(CardReaderStatusCheckerViewModel.kt:35)
        at com.woocommerce.android.DaggerWooCommerceRelease_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get(DaggerWooCommerceRelease_HiltComponents_SingletonC.java:4783)
        at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$1.create(HiltViewModelFactory.java:100)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:69)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:84)
        at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:109)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:171)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:139)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:44)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:31)
        at com.woocommerce.android.ui.orders.cardreader.statuschecker.CardReaderStatusCheckerDialogFragment.getViewModel(CardReaderStatusCheckerDialogFragment.kt:17)
        at com.woocommerce.android.ui.orders.cardreader.statuschecker.CardReaderStatusCheckerDialogFragment.initObservers(CardReaderStatusCheckerDialogFragment.kt:34)
        at com.woocommerce.android.ui.orders.cardreader.statuschecker.CardReaderStatusCheckerDialogFragment.onViewCreated(CardReaderStatusCheckerDialogFragment.kt:30)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
2022-04-05 09:54:40.783 5406-5406/? E/AndroidRuntime:     at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
        at android.os.Handler.handleCallback(Handler.java:938)
  [...]

2022-04-05 13:31 UTC, malinajirka approved these changes
The above issues is unrelated to this PR and is fixed in https://github.com/woocommerce/woocommerce-android/pull/6166.

I've retested the flow and it looks great! Good call on removing the workaround and changing the UI of the "statusChecker" dialog - it feels more maintainable and cleaner now 👏 .

Great work on all the things in this PR 🙇 🥇 

🚢 :shipit:

2022-04-05 13:31 UTC, merged