Issue/5870 load inbox notes from api
woocommerce/woocommerce-android pull request #6030
Opened 2022-03-16 18:03 UTC by JorgeMucientes

Closes: #

### Description

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-03-16 19:37 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/compose/utils/SpannedTextUtils.kt
> +
Compose does not support directly Spanned types for "TextViews", so I've added this that transforms an `Spanned` to the required `AnnotatedString`

2022-03-16 19:38 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/inbox/InboxViewModel.kt
> -        delay(2000)
Removing hardcoded testing data a replacing it for a real call to the API

2022-03-16 19:39 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/inbox/InboxViewModel.kt
> +        }.toAnnotatedString()
This code will be out of the ViewModel soon.

2022-03-17 11:42 UTC, hafizrahman requested changes
This works well! I left a few minor comments and questions.

2022-03-17 11:42 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/inbox/InboxViewModel.kt
>      @Suppress("MagicNumber", "LongMethod")
np: this is probably not needed anymore?

2022-03-17 11:42 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/inbox/InboxViewModel.kt
> +    private fun getRelativeDateToCurrentDate(createdDate: String): String {
np: since there's a possibility this function will not return relative date, I wonder if we need to make this name more clear. I was thinking `formatCreationDate` but it feels too simple? 🤔

2022-03-17 11:42 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/inbox/Inbox.kt
> +@Suppress
`@Suppress` Probably a leftover code?

2022-03-17 11:42 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/compose/utils/SpannedTextUtils.kt
> +
This is nice! 💯

2022-03-21 10:15 UTC, hafizrahman approved these changes

2022-03-21 10:16 UTC, hafizrahman commented
Thanks for the changes! This LGTM aside from the existing conflicts.

2022-03-24 16:13 UTC, merged