Coupon repository and real data fetching
woocommerce/woocommerce-android pull request #6109
Opened 2022-03-28 21:27 UTC by 0nko

This PR integrates the coupon data-fetching using the `CouponStore`. A new `CouponRepository`, which is used by the ViewModel and it maps the `CouponDataModel` to the new `Coupon` app model, which will become useful later.

The main change here is that I've refactored the currency and the coupon description formatting logic. This is now done in the ViewModel. The main reason for this change is that the `CurrencyFormatter` must be used to properly format the coupon `amount`. Previously, the formatting was done during the composition and the `CurrencyFormatter` can't be injected there.

2022-03-28 21:28 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponList.kt
> -    if (amount == null || discountType == null) {
The UI layer (Compose, in our case) shouldn't contain any "busines" logic. The ViewModel should be the true representation model of the UI state and Compose should merely display it. This way, by testing the ViewModel, we can test the UI with a high degree of confidence without the lengthy instrumentation tests 🙂.

2022-03-29 06:11 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListViewModel.kt
> +    }
Nice!

2022-03-29 07:26 UTC, hafizrahman requested changes

2022-03-29 07:26 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListViewModel.kt
> +        fun formatAffectedArticles(includedProductsCount: Int, includedCategoriesCount: Int): String {
Thank you for working on this! I tested this and seems like we have an edge case to handle for the affected articles's formatting.

I have this test coupon:
<img width="85%" alt="Screen Shot 2022-03-29 at 13 37 05" src="https://user-images.githubusercontent.com/266376/160548860-e1386770-eabe-47f4-8fdf-72456b81b2d9.png">

and it's displayed on this app this way:
![Screen Shot 2022-03-29 at 13 38 20](https://user-images.githubusercontent.com/266376/160549021-765a4ed3-f8fc-4884-94e2-2d4a19d8a352.png)

I looked at iOS and here's how the string formatting differs in there ([source code](https://github.com/woocommerce/woocommerce-ios/blob/daba32d494d3f8dcba6c84d3c4c55c515edd80ab/WooCommerce/Classes/Model/Coupon%2BWoo.swift#L84-L87)):

```
- When only specific products or categories are defined: Display "x Products" or "x Categories"
- When specific products/categories and exceptions are defined: Display "x Products excl. y Categories" etc.
- When both specific products and categories are defined: Display "x Products and y Categories"
- When only exceptions are defined: Display "All excl. x Products" or "All excl. y Categories"
```

2022-03-29 07:26 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponList.kt
> -    if (amount == null || discountType == null) {
Thanks for the clarification! I wasn't sure here before because I thought this is essentially just formatting string for display purposes, based on data given to the component.

2022-03-29 09:36 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListViewModel.kt
> +        fun formatAffectedArticles(includedProductsCount: Int, includedCategoriesCount: Int): String {
Thanks! I'll update the logic.

2022-03-29 09:40 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListViewModel.kt
> +        fun formatAffectedArticles(includedProductsCount: Int, includedCategoriesCount: Int): String {
Or maybe we can push this to a separate PR just so we can land this faster? Since the rest of the work depends on this PR. WDYT?

2022-03-29 20:05 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListViewModel.kt
> +        fun formatAffectedArticles(includedProductsCount: Int, includedCategoriesCount: Int): String {
Sorry, I missed your comment and I already implemented it. I replaced "all" with "everything", I think it sounds more grammatically correct. WDYT @itsmeichigo? Now it's like this:
```
- When only specific products or categories are defined: Display "x products" or "x categories"
- When specific products/categories and exceptions are defined: Display "x products excl. y categories" etc.
- When both specific products and categories are defined: Display "x products and y categories"
- When only exceptions are defined: Display "everything excl. x products" or "everything excl. y categories"
```
![image](https://user-images.githubusercontent.com/1522856/160697638-ee7a42e9-233e-4196-a1ab-f76f0d3b4af6.png)

2022-03-31 13:42 UTC, 0nko commented
@hafizrahman Ready for another round.

2022-03-31 14:05 UTC, hafizrahman approved these changes
Thanks for handling the edge cases! This looks good to me now.

2022-03-31 14:05 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListViewModel.kt
> +        fun formatAffectedArticles(includedProductsCount: Int, includedCategoriesCount: Int): String {
Thanks for working on it! I think I missed your comment the first time. I like the use of "everything" as well, the wording flows nicely to me.

2022-03-31 14:06 UTC, merged