Issue/6168 handling bug related to receipt email
woocommerce/woocommerce-android pull request #6190
Opened 2022-04-07 10:04 UTC by kidinov

Closes: #6168

### Description

The PR adds:
* Setting receipt emails when Stripe Plugin used
* Settings receipt email when WCPay version <4.0.0 is used

### Testing instructions

Stripe dashbaord can be used to verify that it works
* Try stripe payment, notice that receipt email is sent
* Try Wcpay payment, notice that receipt email is sent
* Try Wcpay payment with modified code:
```
val wcPayPluginInfo = wooStore.getSitePlugin(selectedSite.get(), WooCommerceStore.WooPlugin.WOO_PAYMENTS)
            ?.apply { version = "4.0.0" }
```
> CardReaderOnboardingChecker::95
notice that receipt email is not sent

<img width="430" alt="image" src="https://user-images.githubusercontent.com/4923871/162172920-81d08030-c1b4-4cf7-8ca3-cde46e6c30c0.png">
<img width="248" alt="image" src="https://user-images.githubusercontent.com/4923871/162173368-e8f3b301-7f59-4531-bbe2-4a3469d3b11f.png">

### Images/gif

No visual changes this PR brings

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-04-08 04:27 UTC, malinajirka requested changes
Thanks for working on this @kidinov! I've left a few suggestions, let me know what you think.

2022-04-08 04:27 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
> +        if (version != null && preferredPlugin != null) {
🚫 Unless I'm missing something, we might end up in an inconsistent state. 
1. WCPay version 1.2.3 is used
2. We store `wcpay` and `1.2.3` into shared prefs
3. Stripe with unknown version is used
4. We store `stripe` and version `1.2.3` remains in the shared prefs

I'm not saying it's a real scenario, but the code seems to allow it.

💡 I'd personally vote for having only a single `set` method in the shared preferences - we originally had two methods, one for `plugin` and one of `onboardingState` and it bit us -> it became very difficult to follow and we sometimes ended up with inconsistent state stored in the shared prefs. If we are worried about the name, I think we can simply call it `setCardReaderOnboardingData` or something like that. Wdyt?

2022-04-08 04:27 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
> +                wcpayCanSendReceipt = isWCPayCanSendReceipts(site),
💡 I'm wondering if a person without the domain knowledge would be able to follow this code. What if we renamed it to something like `pluginSendsReceiptsAutomatically` (I don't think we need to mention WCPay, since the method handles even Stripe Extension). Another option is to add a comment explaining the domain, wdyt?

2022-04-08 09:15 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
> +        if (version != null && preferredPlugin != null) {
I even was trying to make PluginType keeping the version but it was way to big of a change

Like your approach here - done 45f4a8de905e6ba169251072681507ca5a6ad864

2022-04-08 09:18 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt
> +                wcpayCanSendReceipt = isWCPayCanSendReceipts(site),
I think my naming is simply incorrect. This is indeed about if the plugin can send receipts or not. Fixed - 974fef80b13cf9ce2969e45e18168d4d0e8b159f

2022-04-11 05:55 UTC, malinajirka approved these changes
Thanks @kidinov! I've reviewed and tested the app and it all LGTM. Left one minor comment, but it's ready for merge even now.

2022-04-11 05:55 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
> +const val WCPAY_STYLED_RECEIPTS_SUPPORT_VERSION = "4.0.0"
❓ Sorry, I missed this during the first review. I'm wondering how this is related to `styled receipts` (except of the fact that the backend team worked on styled receipts at the same time)? Feels like this PR is about `automatic receipts` not `styled receipts`. What do you think about renaming this constant?

2022-04-11 09:52 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt
> +const val WCPAY_STYLED_RECEIPTS_SUPPORT_VERSION = "4.0.0"
The style of the receipts changed when WCPay started to send them because WC email template is used, but I agree that the main here is the fact that WCPay can send a receipt. Renamed - 01d3da4d9eeb57f41b0ea222975df76bfeba71c0

2022-04-11 09:52 UTC, merged