Products: Makes "new features card" and "sort-filter card" not sticky anymore
woocommerce/woocommerce-android pull request #6221
Opened 2022-04-10 22:09 UTC by irfano

Closes: #3260 

### Description
New features card and Sort-Filter card were sticky in products screen. Only Sort-Filter card is mentioned in issue #3260, but new features card was also sticky. In iOS, they both are not sticky. 
This PR moves new features card and Sort-Filter card to the scroll, so they're not sticky anymore.

### Testing instructions

- Go to the Products tab.
- Scroll down the product list. You should have enough products to be able to scroll.
- Notice new features and Sort-Filter cards are going up by scrolling down.

### Images/gif

| before  | after |
| ------------- | ------------- |
| ![Screenshot_20220411_003244](https://user-images.githubusercontent.com/2471769/162641166-c66936da-9d8a-4aea-9bfe-f79037ef7c9d.png) | ![Screenshot_20220411_004621](https://user-images.githubusercontent.com/2471769/162641292-41bc98bf-da58-4d22-a038-57a6ab73d0b7.png) |

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-04-10 22:31 UTC, irfano commented on WooCommerce/src/main/res/layout/fragment_product_list.xml
> +                    android:nestedScrollingEnabled="true"
Before, there where `RecyclerView`, `FeatureWIPNoticeCard`, and `ProductSortAndFiltersCard` in `fragment_product_list.xml`. I put these into a NestedScrollView, and set `android:nestedScrollingEnabled` true for RecyclerView.

Alternatively, we could update [ProductListAdapter](https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListAdapter.kt) to support multiple view types and use only one `RecyclerView` without an extra `NestedScrollView`. But in that way, we would have to use a generic view holder instead of [ProductItemViewHolder](https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductItemViewHolder.kt), and manipulate the adapter's data. I couldn't find any strong reason to choose this method.

2022-04-11 16:03 UTC, hichamboushaba approved these changes
Works well, thanks @irfano, I'm pre-approving, but I left some comments, the most important one to fix is the usage of `match_parent` instead of `0dp` (match_constraint).

2022-04-11 16:03 UTC, hichamboushaba commented on RELEASE-NOTES.txt
> +- [*] Makes "new features card" and "sort-filter card" not sticky anymore. [https://github.com/woocommerce/woocommerce-android/pull/6221]
I'm not sure this kind of change warrants a user-visible changelog entry, but I don't think it'll cause any harm 🙂.

2022-04-11 16:03 UTC, hichamboushaba commented on WooCommerce/src/main/res/layout/fragment_product_list.xml
> +                android:layout_height="match_parent">
A question, shouldn't this be `wrap_content` since it's inside a ScrollView?

2022-04-11 16:03 UTC, hichamboushaba commented on WooCommerce/src/main/res/layout/fragment_product_list.xml
> +                    android:layout_width="match_parent"
This should be set to `0dp` (MATCH_CONSTRAINT) to make it clear it's constrained.

2022-04-11 16:03 UTC, hichamboushaba commented on WooCommerce/src/main/res/layout/fragment_product_list.xml
> +                    android:layout_width="match_parent"
Same as above.

2022-04-11 16:03 UTC, hichamboushaba commented on WooCommerce/src/main/res/layout/fragment_product_list.xml
> +                    android:layout_height="match_parent"
Same as above.

2022-04-11 16:36 UTC, irfano commented on RELEASE-NOTES.txt
> +- [*] Makes "new features card" and "sort-filter card" not sticky anymore. [https://github.com/woocommerce/woocommerce-android/pull/6221]
I know it's a small change, but I thought we must add everything to release notes even if it's very small. This is like just an animation change, so I guess I can skip this small change.

2022-04-11 17:05 UTC, hichamboushaba commented on RELEASE-NOTES.txt
> +- [*] Makes "new features card" and "sort-filter card" not sticky anymore. [https://github.com/woocommerce/woocommerce-android/pull/6221]
No worries at all, you don't have to revert it if you don't want to 🙂.

2022-04-11 18:24 UTC, irfano commented on WooCommerce/src/main/res/layout/fragment_product_list.xml
> +                android:layout_height="match_parent">
Good catch! I remember there was a problem when it was `wrap_content`, but I couldn't see any problem now. It should be `wrap_content`. 👍🏻

2022-04-11 19:18 UTC, irfano commented on WooCommerce/src/main/res/layout/fragment_product_list.xml
> +                    android:layout_width="match_parent"
Done!

2022-04-11 19:29 UTC, irfano commented on WooCommerce/src/main/res/layout/fragment_product_list.xml
> +                    android:layout_height="match_parent"
When `layout_height` of RecyclerView is set to `match_parent`, ConstraintLayout can't compute its height, and RecyclerView can't be shown. Because the height of the ConstraintLayout in ScrollView is `wrap_content`.

So, I'm keeping `layout_height` of RecylerView `match_parent`.

2022-04-11 19:44 UTC, irfano commented
Thanks for your review @hichamboushaba. You can review again. I made changes you suggested, except `layout_height` of RecyclerView.

2022-04-12 11:47 UTC, hichamboushaba requested changes
@irfano your remark about the recyclerview height led me to check what other things those changes did impact, and apparently it'll have a noticeable side-effect on the recyclability of the RecyclerView, as it will expand more than the screen's height, which would mean more creating more Views than it should, which could lead to some performance issues for stores with big number of products.
Check how it appears in the Layout inspector:
| Before | After |
| ----- | ----- |
| <img width="392" alt="Screen Shot 2022-04-12 at 11 26 20" src="https://user-images.githubusercontent.com/1657201/162952786-f785feb4-4bb5-4346-b46a-74cdedff3e16.png"> | <img width="392" alt="Screen Shot 2022-04-12 at 11 21 17" src="https://user-images.githubusercontent.com/1657201/162952802-2e448a9c-8ba8-432c-90ab-29279f81b9c8.png"> | 


Another issue that I noticed is an issue with the FAB on the screen, it disappears on first launch of the fragment:
<img width="400" src="https://user-images.githubusercontent.com/1657201/162953099-9226ab01-0c8b-46cb-8ad7-0884b36f7819.gif"/>

2022-04-12 12:49 UTC, irfano commented
> @irfano your remark about the recyclerview height led me to check what other things those changes did impact, and apparently it'll have a noticeable side-effect on the recyclability of the RecyclerView, as it will expand more than the screen's height, which would mean more creating more Views than it should, which could lead to some performance issues for stores with big number of products.

It seems we lose the recycling feature of RecylerView if we use it in a NestedScrollView. The problem is determining RecylerView's height in a NestedScrollView. As a solution, I can manually calculate the height from the top to the bottom bar, and give it to the RecyclerView as a constant height, but I think that's not a good solution. 

I think it's better to go with the alternative solution, supporting multiple view types in RecyclerView. I'll close this PR, and open new one for the alternative solution.

Thanks for catching this important issue!

2022-04-12 12:51 UTC, irfano commented
> Another issue that I noticed is an issue with the FAB on the screen, it disappears on first launch of the fragment:

I couldn't reproduce this. I'll want you to test it again in the new PR.

2022-04-12 14:21 UTC, closed without merging