Issue/6201 card reader manuals add fragment file
woocommerce/woocommerce-android pull request #6228
Opened 2022-04-11 15:00 UTC by rossanafmenezes

Closes: #6201 

### Description

Adding the Fragment file to connect to the compose screen #6143 and the xml layout file #6202 

- [x ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-04-11 15:18 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/manuals/CardReaderManualsFragment.kt
> +//    private val viewModel: CardReaderManualsViewModel by viewModels()
I commented out this line to avoid lint errors on the unused private val. I could have removed it but decided to leave here just to let you know it's gonna be there as soon as I start working on the CardReaderManualsScreen.kt file

2022-04-12 02:38 UTC, malinajirka requested changes
Thanks @rossanafmenezes, it looks good overall. However, I found one possible issue, let me know what you think :).

2022-04-12 02:38 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/manuals/CardReaderManualsFragment.kt
> +    private var _binding: FragmentCardReaderManualsBinding? = null
⚠️ I believe that unless we clear the property in OnDestroyView, it'll create a memory leak. This is something Google should have solved for us imo, but here we are and we need to handle it manually.

1. The fragment is created
2. View of the fragment is created and `_binding` is initialized
3. Fragment is put on the backstack (eg. user navigates to a different screen)
4. Fragment's OnDestroyView is invoked, but the fragment is still alive on the backstack
5. 💥 The _binding is still referencing the view even though the fragment is never going to use it again, it already invoked `onDestroyView` => this is a memory leak, we are keeping a reference to the view and the garbage collector cannot collect it and free up the memory until the whole fragment is destroyed or until we override _binding with a new view.

We can solve this using two methods:
1. Do not store the binding into a field at all, use only local variables (example [here](https://github.com/woocommerce/woocommerce-android/blob/0edec453e588017d1ab6e285bda31623d3967766/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentDialogFragment.kt#L62))
2. Clear the field in onDestroyView
```
override fun onDestroyView() {
    super.onDestroyView()
    _binding = null
}
```

I usually prefer `1` unless we need to have it stored. I'm not sure though if you'll need it or not.

Wdyt?

2022-04-12 10:19 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/manuals/CardReaderManualsFragment.kt
> +    private var _binding: FragmentCardReaderManualsBinding? = null
Absolutely! You are 100% right.  I had handled that on my test file but completely slipped my mind when I PRed this one. So sorry!

2022-04-12 11:50 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/manuals/CardReaderManualsFragment.kt
> +    private var _binding: FragmentCardReaderManualsBinding? = null
No worries at all - there is nothing to apologize for :). 

Either option feels fine, let me know when you update the PR and I'll approve it and merge it 🚢 .

2022-04-12 14:31 UTC, malinajirka approved these changes
Thanks, LGTM 🎉

2022-04-12 14:33 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/manuals/CardReaderManualsFragment.kt
> +    private var _binding: FragmentCardReaderManualsBinding? = null
Just for the record and future reference, we discussed approaches 1 and 2 I outlined above. However, as it turned out with Compose we need to create the binding in OnCreateView and therefore option 1 doesn't feel right (it makes sense only when the binding is created in OnViewCreated).

2022-04-12 14:36 UTC, merged