[Coupons] Add option to add/edit description
woocommerce/woocommerce-android pull request #6495
Opened 2022-05-11 11:14 UTC by hichamboushaba

Closes: #5535 

### Description
This PR adds the option to add/edit the description of the coupon.
I decided to add a reusable screen called `SimpleTextEditorFragment` similar to what we are doing with `AztecEditorFragment`, we can reuse this screen for some parts in order creation (customer note uses a similar design), I decided also to avoid using a `done` in the menu, a `back` action is considered as a positive action, similar to what we are doing with `AztecEditorFragment`.

### Testing instructions

### Images/gif
<img width="260" alt="Screen Shot 2022-05-11 at 12 10 56" src="https://user-images.githubusercontent.com/1657201/167836259-e5bd4bcd-fa4c-47cc-84f1-a57d8d5c2433.png"> <img width="260" alt="Screen Shot 2022-05-11 at 12 11 09" src="https://user-images.githubusercontent.com/1657201/167836264-1e30a865-24f5-4919-991e-a191b6bf3dc3.png"> <img width="260" alt="Screen Shot 2022-05-11 at 12 11 17" src="https://user-images.githubusercontent.com/1657201/167836265-a3a62293-376d-4562-a166-bcea13cce657.png">

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-05-11 11:57 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/edit/EditCouponNavigator.kt
> +    fun navigate(fragment: Fragment, target: EditCouponNavigationTarget) {
Since we will be having multiple navigation events for the coupon edit screen, I created the sealed class `EditCouponNavigationTarget` and this Navigator class, to align with the pattern we use in other screens.

2022-05-11 11:58 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/texteditor/SimpleTextEditorFragment.kt
> + *   "{[SIMPLE_TEXT_EDITOR_RESULT]}{[SimpleTextEditorFragmentArgs.requestCode] if present}".
I added the `requestCode` parameter to make it possible to use the screen multiple times from the same origin, this is similar to what we are doing in AztecEditorFragment, the difference is that instead of passing the `requestCode` in a `Bundle`, I'm using it to update the `key` itself, let me know what you think.

2022-05-12 10:26 UTC, hafizrahman requested changes
In general this looks good! I left a small question about actually using request code.

2022-05-12 10:26 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/texteditor/SimpleTextEditorFragment.kt
> + *   "{[SIMPLE_TEXT_EDITOR_RESULT]}{[SimpleTextEditorFragmentArgs.requestCode] if present}".
In general I like this way because the `handleResult` part becomes more simple.

2022-05-12 10:26 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/edit/EditCouponNavigator.kt
> +                    )
Do you think it's worth adding and using actual request code here, at least to make the usage more clear since this is the first example usage for `SimpleTextEditorFragment`?

2022-05-12 20:09 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/edit/EditCouponNavigator.kt
> +                    )
IMO the comment in `SimpleTextEditorFragment` should be enough to clarify the usage, especially since it mentions the part `if present`.
I'm afraid If we pass the `requestCode` here knowing it's optional and it's not needed, would make it look like it's mandatory, which is not what we want. For the majority of screens, the requestCode won't be needed, having to text fields that use full-screen editor in the same screen is not common in our app.

2022-05-13 09:56 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/edit/EditCouponNavigator.kt
> +                    )
@hafizrahman did you have a chance to check my comment above? if we can merge this to avoid having to deal with conflicts later 🙏

2022-05-13 11:17 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/edit/EditCouponNavigator.kt
> +                    )
Yup, just got the chance to get to this PR. Thanks for explaining, that sounds good to me, I missed the part where we don't want to make it mandatory.

2022-05-13 11:17 UTC, hafizrahman approved these changes

2022-05-13 11:17 UTC, merged