Issue/6494 expiry date
woocommerce/woocommerce-android pull request #6505
Opened 2022-05-12 20:11 UTC by hichamboushaba

Closes: #6494 

### Description
This PR adds support for editing the expiry date.
For the date picker, I had two options:
1. Use the MaterialDatePicker from the Fragment using events.
2. Create a Compsable date picker.

I went with the second approach, because it was a nice challenge, and also because Google is working on composable [implementations](https://issuetracker.google.com/issues/197942880), which means migrating to them would be easier.

Another point, regarding the scenario for deleting the expiry date, I went with a Dialog that shows two buttons for selecting the action (edit vs delete), this aligns with the iOS implementation (they use an action sheet).

### Testing instructions

### Images/gif
https://user-images.githubusercontent.com/1657201/168159961-6e15fcc6-4303-49f8-8ee6-edfae5f93e02.mov

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-05-16 06:41 UTC, hafizrahman requested changes
A few initial thoughts and discoveries while testing:

I think it's cool you can recreate the date picker in Compose pretty quickly! Shows how powerful Compose is. 👍🏼  ✨ 

Currently, if the calendar dialog is opened and the orientation is changed, the calendar disappears.

Next, when using "Large" system font setting and more, coupled with the landscape orientation, the buttons at the bottom is cut off:
![Screenshot_20220516_132707](https://user-images.githubusercontent.com/266376/168532041-42dccc95-0da7-4fb5-8adc-d071f008ac57.png)

Next, the two-buttons "Edit Expiry" and "Delete Expiry" dialog felt a little unusual to me, mostly because I have seen a lot of similar dialog in Android apps:

![Screenshot_20220516_133923](https://user-images.githubusercontent.com/266376/168533637-1f99bdf3-e457-400c-a56e-07093dd4abf8.png)


I then tried to figure out what the equivalent of iOS Action Sheet for Android. [This SO conversation](https://stackoverflow.com/questions/47645736/android-equivalence-of-ios-actionsheet) recommends either using Bottom Sheet Dialog, or an [Alert Dialog with list](https://developer.android.com/guide/topics/ui/dialogs#AddingAList). In the old [Material Design for iOS documentation for Action Sheet](https://material.io/develop/ios/supporting/action-sheet), the design also looks a lot like Bottom Sheet Dialog. Or maybe we can use a dialog with three options (Cancel, Edit, Delete)?

Overall I think it's not a big deal, it still works and probably worth re-iterating later. Curious what @woocommerce/mobile-designers think about it.

2022-05-16 16:11 UTC, hichamboushaba commented
Thanks @hafizrahman for the review 👍 

> Currently, if the calendar dialog is opened and the orientation is changed, the calendar disappears.

This is something that happens in many places in the app, but since we are using Compose now, and saving things to the SavedState is easier, I agree with you that we should implement it, it's fixed now with the two commits: [af5754a](https://github.com/woocommerce/woocommerce-android/pull/6505/commits/af5754ab2b3643ee6572cc8b686870d2cc8c5f6c) and [5187091](https://github.com/woocommerce/woocommerce-android/pull/6505/commits/51870914eb962d7ddc012e189ec6513b624b46dc)

> Next, when using "Large" system font setting and more, coupled with the landscape orientation, the buttons at the bottom is cut off

Nice catch, I spent some time optimizing the layout to be more responsive, and it was a good exercise in learning how [IntrinsicSize](https://developer.android.com/jetpack/compose/layouts/intrinsic-measurements) works in Compose.
I tried to have a design that matches what the `MaterialDatePicker` does:
| portrait | landscape |
| ---- | ---- |
| <img width="395" alt="Screen Shot 2022-05-16 at 15 53 30" src="https://user-images.githubusercontent.com/1657201/168635781-6852469b-8aba-4bd9-9cf4-dbc4d1b79d49.png"> | <img width="879" alt="Screen Shot 2022-05-16 at 15 53 14" src="https://user-images.githubusercontent.com/1657201/168635813-6beb52dc-9a8a-4823-bab0-a9ead2995585.png"> |
| <img width="399" alt="Screen Shot 2022-05-16 at 15 32 48" src="https://user-images.githubusercontent.com/1657201/168636002-cabf6f1d-ab2a-46f0-9290-693e2a895b33.png"> | <img width="888" alt="Screen Shot 2022-05-16 at 15 33 23" src="https://user-images.githubusercontent.com/1657201/168636104-11a7039e-9c50-4168-8317-4c3810b8fc01.png"> |
| <img width="869" alt="Screen Shot 2022-05-16 at 15 29 28" src="https://user-images.githubusercontent.com/1657201/168636175-4b761bc1-a198-4f24-84aa-4bfced530d40.png"> | <img width="1237" alt="Screen Shot 2022-05-16 at 15 29 49" src="https://user-images.githubusercontent.com/1657201/168636183-f977abb5-ecd4-4fac-9953-d1c9f795b612.png"> |

> I then tried to figure out what the equivalent of iOS Action Sheet for Android

It's not about direct equivalent. Yes, we have a bottom sheet in Android, but we don't use them for this kind of interaction in the app, if you check for example the `Image type picker` in the app, you'll see that we use a dialog in Android, while iOS uses an action sheet, as it's the natural thing for both platforms.
This being said, the design is temporary, and I'm already waiting for the designer's feedback p1652435227178049-slack-C02TD63FZA8, and as this is behind a feature flag, I believe it's OK to merge it, and update the design later when we get a final response.

2022-05-16 17:23 UTC, hichamboushaba commented on WooCommerce/build.gradle
> +        ]
This allows using the `OptIn` annotation which is better than declaring components as experimental, and ending with tons of warnings.

For this case, the clients don't have to care that the `DatePickerDialog` is using an experimental API, so when the component opts in, callers will be able to call it without any special setup.

2022-05-17 02:45 UTC, hafizrahman requested changes
I'm very impressed by the landspace mode redesign. Awesome and thanks for implementing that! It's great that it's now preserved on config change as well.

A couple of things that I just noticed:

1. If I go to a previous month and select a date, the month has this swipe animation but then opens to the same month. That animation does not feel necessary to me (since it opens to the same month). Video here to show what I meant:


https://user-images.githubusercontent.com/266376/168717393-f8b60334-dad2-4a2c-9047-f88ed780b1f5.mov

[In Material date picker documentation](https://material.io/components/date-pickers), it says that:

> Accessibility
> On mobile, a date picker should allow users to enter dates manually by inputting text, without using the picker. This interaction allows multiple input methods and makes it accessible to those using assistive technology.
> On mobile, the input picker should be available from the calendar pickers via the edit icon.

Do you think this is something we can implement right away? I can also make a separate issue if we want to go forward without it first.

2022-05-17 07:53 UTC, hichamboushaba commented
Thanks @hafizrahman 
> If I go to a previous month and select a date

Nice catch, I'll try to investigate why it happens, but IMO it's not a blocker 🙂.

> Do you think this is something we can implement right away?

I don't think we should implement it for the coupons project, the component follows the same behavior as `MaterialDatePicker`, which doesn't offer this possibility.
This is something we should think about for the whole app, and if we find it necessary, then it should be done for all parts where we use date pickers (like Products' sale scheduling).

2022-05-18 06:51 UTC, hafizrahman approved these changes
Thank you for addressing my points! This is good to go now I feel (aside from the existing conflicts) 👍🏼 👍🏼

2022-05-18 17:31 UTC, hichamboushaba commented
Thanks @hafizrahman for the review, I'll merge this as, and I'll have a separate PR for the dialog adjustments to align with the design changes.

2022-05-18 17:31 UTC, merged