Remove product variations banner from Products tab
woocommerce/woocommerce-android pull request #6551
Opened 2022-05-19 20:29 UTC by rossanafmenezes

Closes: #

### Description

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-05-19 21:08 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
> +    @Inject
fixed

2022-05-20 10:05 UTC, hafizrahman requested changes

2022-05-20 10:05 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
> -        showProductWIPNoticeCard(true)
Thanks for working on this! It works fine in my test.

It's not a big deal but I wonder what you think about modifying this to `showProductWIPNoticeCard(false)` instead (and then add comment here why we're hiding it but not outright deleting).

That way we don't have to comment out any code. In the future if we want to restore the banner, we only need to set this to true again without un-commenting anything. It might also make the code simpler to follow. It will probably save a few seconds, though, that's why I think it's not a big deal really 😅 

What do you think?

2022-05-20 10:09 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
> -        showProductWIPNoticeCard(true)
Hi @hafizrahman ! Thank you for reviewing it. That was my first approach, but commenting it out was suggested here p1652980622932019-slack-CGPNUU63E

I can absolutely do that if it is a better approach.

2022-05-20 10:29 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
> -        showProductWIPNoticeCard(true)
Fwiw I believe we should not leave any commented out code in the codebase. We can always restore the code if needed using git. For this scenario, since there is a very high chance we'll want to re-use the code, I'd personally lean towards using `showProductWIPNoticeCard(false)` - since we want to keep the code, just hide an announcement for now. Also adding a comment on top of `showProductWIPNoticeCard(false)` with an explanation why it's set to false would be great.

2022-05-20 10:34 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
> -        showProductWIPNoticeCard(true)
Thank you for the input @malinajirka! In that case, I will make the changes and set it to false.

2022-05-20 14:51 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt
> +        //set to false to remove the new feature banner temporarily
fixed

2022-05-23 03:04 UTC, hafizrahman approved these changes
LGTM, nice work @rossanafmenezes ! :shipit:

2022-05-23 03:04 UTC, merged