[Coupons] implement saving
woocommerce/woocommerce-android pull request #6589
Opened 2022-05-24 17:19 UTC by hichamboushaba

Closes: #6580 

### Description
This PR adds the saving logic to the edit coupon screen:
1. It shows a progress dialog when the saving is in progress.
2. Shows a success snackbar and navigates up when saving finishes successfully.
3. Shows an error snackbar if saving fails.

### Testing instructions
#### Happy path
1. Make sure coupons beta toggle is enabled.
2. Open coupon details.
3. Click on menu, then edit coupon.
4. Make some changes to the coupon.
5. Click on Save.
6. Confirm a progress dialog is shown.
7. Confirm a snackbar is shown when the API request finishes, and you are navigated back to the coupon details.
8. Confirm the coupon details have been updated as well.

#### Unhappy path
1. Make sure coupons beta toggle is enabled.
2. Open coupon details.
3. Click on menu, then edit coupon.
4. Make some changes to the coupon.
5. Enable airplane mode.
6. Click on Save.
7. Confirm an error snackbar is shown.

### Images/gif
https://user-images.githubusercontent.com/1657201/170095244-e4f1f419-0b56-4a02-a509-8ac88dcbc293.mov

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-05-25 10:23 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/edit/EditCouponViewModel.kt
> +                    triggerEvent(ShowSnackbar(R.string.coupon_edit_coupon_update_failed))
❓ Do we want to use / show the actual error message for this?

For example, if set a Percentage Discount Coupon's amount to more than `100` and press Save, the API returns a useful error message ("Invalid discount amount"). This feels like something that's useful for merchants to know.

2022-05-25 10:23 UTC, hafizrahman requested changes
This all looks good to me in general, just left a question about displaying error message.

2022-05-25 10:28 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/edit/EditCouponViewModel.kt
> +                    triggerEvent(ShowSnackbar(R.string.coupon_edit_coupon_update_failed))
(Ugh I meant this as a general question instead of a change request, sorry!)

2022-05-25 13:53 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/edit/EditCouponViewModel.kt
> +                    triggerEvent(ShowSnackbar(R.string.coupon_edit_coupon_update_failed))
This is a nice improvement, I added it in [83ac3e3](https://github.com/woocommerce/woocommerce-android/pull/6589/commits/83ac3e36f5d4650efa9520a5788615d30e2fa66d), I had to introduce a separate event class to allow passing both a String or a String resource, but I think it's worth it, let me know what you think.

2022-05-27 01:40 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/edit/EditCouponViewModel.kt
> +                    triggerEvent(ShowSnackbar(R.string.coupon_edit_coupon_update_failed))
Thank you! Great improvement :) 👍🏼

2022-05-27 01:40 UTC, hafizrahman approved these changes
:shipit: Thanks for working on saving!

2022-05-27 01:40 UTC, merged