[Coupons] Product category selector functionality: selecting and submitting
woocommerce/woocommerce-android pull request #6634
Opened 2022-05-27 11:43 UTC by hichamboushaba

Part of 6362

### Description
This PR builds upon the previous PR #6602, it adds the following functionality:
- Displays the selection status.
- Handles changing selection.
- Returns the updated selection to parent fragment.
- Adds a clear selection button.

### Testing instructions

1. Make sure coupons beta toggle is enabled.
2. Open coupon details.
3. Click on Menu, then edit coupons.
4. Click on "Select product categories".
5. Confirm the selected categories are shown as checked.
7. Test the clear selection button.
8. Change the selection of categories.
9. Click on "Done" (or "Select X categories") and confirm the included categories of the coupon are updated.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-05-31 04:37 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/selector/ProductCategorySelectorScreen.kt
> +                    maxLines = 1
Since we're limiting the maximum line, probably worth adding overflow as well.

2022-05-31 04:38 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/selector/ProductCategorySelectorScreen.kt
> +                    maxLines = 1
Added in https://github.com/woocommerce/woocommerce-android/pull/6634/commits/688a456584e95e07f6ab61b0ddb4a9d2a20747d4

2022-05-31 07:46 UTC, hafizrahman requested changes

2022-05-31 07:46 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/selector/ProductCategorySelectorScreen.kt
> +                }
When a Category with really long text is selected, the Check icon is not shown. Video:

https://user-images.githubusercontent.com/266376/171120268-050508bf-2d0c-40b6-8d4c-3d93825f4eae.mov

2022-05-31 08:18 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/selector/ProductCategorySelectorScreen.kt
> +                }
Added fix in https://github.com/woocommerce/woocommerce-android/pull/6634/commits/4978b23f36d5f762b83b173f2f682a2d78e4cf53

2022-05-31 08:43 UTC, hafizrahman approved these changes

2022-06-02 15:21 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/selector/ProductCategorySelectorScreen.kt
> +                }
Thanks Hafiz for identifying this issue, I pushed another commit to have an alternative solution: [38588b8](https://github.com/woocommerce/woocommerce-android/pull/6634/commits/38588b8f8448d8672ac374c8d9ce9661f1b1b863), I think using a Box with `paddings` is a little fragile, normally a `Row` for this is the right solution, so I investigated a bit why the long text causes the icon to have a `zero` width, and I found a solution in this StackOverflow answer https://stackoverflow.com/a/68972289, the solution was simple, just adding a `weight` modifier.
I also updated the way we handle the check icon visibility, to make it similar to how `View.INVISIBLE` works in the View system, this avoids cutting the text in different places when checking/unchecking the category.

2022-06-06 11:47 UTC, merged