Fix promo screenshots translation
woocommerce/woocommerce-android pull request #6901
Opened 2022-07-08 14:53 UTC by hichamboushaba

### Description
We had some inconsistencies in the Glotpress keys used for promo screenshots metadata:
1. The Glotpress file used the keys `app_store_screenshot-...`
2. The lane `update_appstore_strings` used the keys `play_store_screenshot_...`

This meant that when updating the metadata for the screenshots, it doesn't get picked up by Glotpress.

This PR fixes the inconsistency by updating the keys in the `pot` file, and fixes the lane `download_promo_strings` accordinely.

### Testing instructions
1. Checkout this branch.
2. Run `bundle exec fastlane update_appstore_strings version:5.6`.
3. Check the last commit, and confirm the pot file was updated correctly with the new metadata.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-07-08 14:53 UTC, hichamboushaba commented on Gemfile.lock
> +   2.3.7
A second, I'll update the ruby version to avoid this downgrade.

2022-07-08 15:02 UTC, hichamboushaba commented on Gemfile.lock
> +    rmagick (4.2.5)
I didn't commit this on the previous PRs, I assumed it should done, let me know if it's not the case.

2022-07-08 15:17 UTC, AliSoftware requested changes
Need to revert the `Gemfile.lock` change, but otherwise looks good.

Tested by running:
 - `bundle exec fastlane update_appstore_strings version:5.6` as instructed (even if we're on version `9.5` and not `5.6` but eh 🤷  doesn't affect the test for the screenshot keys 😛 )
 - `xgettext -o - WooCommerce/metadata/PlayStoreStrings.pot` on the updated `.pot` file, and validated that it didn't print any warning about syntax error in the `.pot` file after those new originals got inserted in it.

So all good to ship once `.lock` file removed.

2022-07-08 15:17 UTC, AliSoftware commented on Gemfile.lock
> +    rmagick (4.2.5)
Nope, this shouldn't.

The likely culprit for it to be added here is because you used `bundle install --with screenshots` while working on screenshots, which [adds this dependency to `rmagick` only when that group is enabled](https://github.com/woocommerce/woocommerce-android/blob/trunk/fastlane/Pluginfile#L5-L7).
We use this gem to do image composition to assemble the final promo screenshots, but don't want it to be a dependency needed for everyday developers otherwise (because that gem in turn needs `imagemagick` to be `brew install`'d on your system… and it can be its own can of worms…).
That's why we only add this `rmagick` dependency opt-in when you use `--with screenshots`, but don't add it otherwise nor commit it to git.

To solve this you can:
 - Either just remove the update of the `Gemfile.lock` from this PR, like if you never commited it — probably the easiest way
 - Or alternatively disable the `--with screenshots` (via `bundle config unset with` to disable the options set by this `--with` flag), then re-run `bundle install` to update the `Gemfile.lock` back without that `rmagick` dependency.

2022-07-08 15:53 UTC, hichamboushaba commented on Gemfile.lock
> +    rmagick (4.2.5)
Done, I actually avoided commiting the file because of the `--with screenshots`, but then I checked the `.lock` file in `WPAndroid`, and found that it included `rmagick`, so thought I should do it too 😅.

I reverted the change using a `reset --hard` then force pushed it, I hope this fine 🙂.

2022-07-08 15:55 UTC, AliSoftware commented on Gemfile.lock
> +    rmagick (4.2.5)
Oh interesting it might have been committed by mistake in WPAndroid at some point I guess then 🤔

2022-07-08 15:56 UTC, AliSoftware approved these changes
:shipit: !

2022-07-08 16:06 UTC, merged

2022-07-11 14:46 UTC, AliSoftware commented on Gemfile.lock
> +    rmagick (4.2.5)
FYI: It turns out I was probably wrong about it not having to be commited… and also we might have a larger issue at hand… in all our repos, which all seem to include `rmagick` in their `Gemfile.lock` while it's supposed to be optional and thus not included 🤔  Something fishy is going on there.

So in theory I wouldn't expect `rmagick` to be there in the `Gemfile.lock` in any of our repos, but in practice it is, so while we'll need to figure out why at some point in a separate investigation, for the time being we've had to re-introduce it in https://github.com/woocommerce/woocommerce-android/pull/6913#pullrequestreview-1034445930 to unblock code freeze, until we understand what's happening with all that.