Fix payment navigation during new more flow
woocommerce/woocommerce-android pull request #7085
Opened 2022-08-02 04:42 UTC by kidinov

Closes: #7083

### Description

The PR:
* Removes onboarding check before hub screen in the "more" flow
* Fixes other issues caused by the change

### Testing instructions

* Run both "more" and order collection payment flows
* Try back navigation as well

### Images/gif

https://user-images.githubusercontent.com/4923871/182293263-c50542ba-5f36-4782-815b-985b41a08e3c.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-08-05 15:41 UTC, malinajirka requested changes
Thanks for working on this @kidinov!

I don't see an issue in the code, but I noticed the Simple Payments flow doesn't work when initiated from the OrderList - see the video below.

https://user-images.githubusercontent.com/2261188/183112554-54df5965-8a89-430d-9e66-90df8b68e0e6.mp4

2022-08-08 06:13 UTC, kidinov commented
@malinajirka that's expected and been broken in another PR. It'll be fixed by either [changing navigation ](p1659693078210029/1659692713.631499-slack-C0354HSNUJH) (if approved by designers) or in another PR

2022-08-09 07:31 UTC, malinajirka approved these changes

2022-08-09 07:31 UTC, malinajirka commented
Thanks for the clarification.

2022-08-09 07:31 UTC, merged