Run onboarding check on the ipp hub screen in async way
woocommerce/woocommerce-android pull request #7095
Opened 2022-08-03 09:20 UTC by kidinov

Closes: #7024

### Description

The PR adds onboarding check to be done in async manner on the hub screen

### Testing instructions

* Try the case when onboarding complete
* Try the case when onboarding failes
* Try the case when onboarding check return "choose payment provider" state

### Images/gif

https://user-images.githubusercontent.com/4923871/182571787-6d823f6e-fc21-4e14-8ae1-10d73e2dcf6f.mp4

https://user-images.githubusercontent.com/4923871/182571809-15d0b551-7192-4995-b7db-b5b7fc1301c8.mp4

https://user-images.githubusercontent.com/4923871/182572813-e306c483-af83-47fc-b55e-1a4d147d6028.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-08-03 09:24 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt
> +        val errorText: UiString?,
Click on the error doesn't do anything here. It's another [issue](https://github.com/woocommerce/woocommerce-android/issues/7096)

2022-08-03 09:25 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt
> +                is OnboardingCompleted -> createOnboardingCompleteState(isCardReaderPluginExplicitlySelected())
Please confirm that this logic is valid regarding showing multiple plugin selection button

2022-08-05 16:01 UTC, malinajirka requested changes
Thanks @kidinov!

It's possible I missed some conversation, but if I haven't I believe the current behavior changes the way "Two Payment Gateways Installed" situation worked before. I believe that when the onboarding returns 'ChoosePaymentGatewayProvider' we should treat it as if onboarding was not completed at all - greyed out "Manage Card Reader" and the new bottom bar informing the user that onboarding is not completed. 

When we want to determine whether to show or not show the "Change Payment Gateway" I think we might want to use `appPrefsWrapper.isCardReaderPluginExplicitlySelected`, wdyt?

I'm not sure how the behavior in this PR works - does it automatically pick WCPay when both plugins are installed or which plugin is used if the user doesn't choose any plugin and they start connecting to a reader?

2022-08-05 16:01 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubAdapter.kt
> +        notifyDataSetChanged()
🔍 Nitpick: Just wondering if you considered using DiffUtil. I guess it's quite a simple screen and it might not be worth it - perhaps your train of thoughts was exactly the same? :P

2022-08-08 06:17 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubAdapter.kt
> +        notifyDataSetChanged()
I have and it feels that for 4-5 simple rows it won't bring much UX improvement while some code complexity for sure

2022-08-08 08:35 UTC, kidinov commented
@malinajirka

Indeed, I was confused with the naming of `ChoosePaymentGatewayProvider`. It means `we have 2 plugins active and non has been chosen so far`. 

We could probably look into this not like in the error because we handle it nicely during onboarding check (we ask what plugin to use), but we do not run the check on "manage readers" and probably the improvement does not worth the effort in this case

Changed here - 51dc80b2bf0ba15b3ff760fb5d81561dd2f10215

2022-08-09 09:02 UTC, malinajirka approved these changes
Thanks @kidinov! The code and the app look good overall. I have a couple questions/suggestions which are not blocking this PR - feel free to merge it.

1. We might want to consider updating the PR description so when someone opens this PR in the future (eg. during beta testing) they can quickly see the expected behavior. We could perhaps mention that "Choose Payment Gateway" video is not applicable anymore, wdyt? Also one thing worth adding is the expected behavior - eg. it is expected that click on "Finish setup" doesn't do anything yet.
2. I'm wondering why we need to listen to `onResume` - is it just because we want to refresh the state after the app comes from the background? Either case, I'd consider adding a documentation test for it, since I think all future devs will be asking the same question since observing onResume is not something we usually do. Wdyt?
3. I noticed when I click on the bottom bar, it always applies even the "Continue setup" selector. I assume this will be fixed in a follow up PR, just wanted to mention it to be sure.

2022-08-09 09:34 UTC, kidinov commented
@malinajirka 

> We might want to consider updating the PR description so when someone opens this PR in the future (eg. during beta testing) they can quickly see the expected behavior. We could perhaps mention that "Choose Payment Gateway" video is not applicable anymore, wdyt?

Yep, I updated that a bit

> Also one thing worth adding is the expected behavior - eg. it is expected that click on "Finish setup" doesn't do anything yet.

That's been here [in the comment ](https://github.com/woocommerce/woocommerce-android/pull/7095#discussion_r936440480)

> I'm wondering why we need to listen to onResume - is it just because we want to refresh the state after the app comes from the background? 

That's because onboarding states can be changed by a user even without leaving the app, for instance, selection of the plugin during onboarding check in  `Select Payment Method -> Card` will lead to the "completed onboarding"

> Either case, I'd consider adding a documentation test for it, since I think all future devs will be asking the same question since observing onResume is not something we usually do. Wdyt?

Not sure, what is `a documentation test`? 

> I noticed when I click on the bottom bar, it always applies even the "Continue setup" selector. I assume this will be fixed in a follow up PR, just wanted to mention it to be sure.

Good catch! Nope, not fixed. Will do

Merging it now, recording small things to fix, otherwise, we won't have much chance to release it this week

2022-08-09 09:34 UTC, merged

2022-08-09 09:54 UTC, kidinov commented
@malinajirka 

> I noticed when I click on the bottom bar, it always applies even the "Continue setup" selector. I assume this will be fixed in a follow up PR, just wanted to mention it to be sure.

It looks like tricky issue. Clicking on the side of the "link" highlights that. Not sure if this is a bug or a feature. The same issue in our current implementation:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/4923871/183619517-158ddc5d-dbde-464e-a936-c7fd3e19159f.png">

2022-08-09 10:21 UTC, kidinov commented
@malinajirka fixed that 19d55f8ec7d0a1e417024b56c0a0ea8b4cc399e2

2022-08-09 11:28 UTC, malinajirka commented
> Yep, I updated that a bit

Thanks!

> That's been here https://github.com/woocommerce/woocommerce-android/pull/7095#discussion_r936440480

Ohh, right. Sorry

> That's because onboarding states can be changed by a user even without leaving the app, for instance, selection of the plugin during onboarding check in Select Payment Method -> Card will lead to the "completed onboarding"

Hmm, we usually handle this by restarting the screen/flow when navigating back or using `setResult`. Using onResume has other side-effects - eg. refreshing happens after configuration change or when the app is put into background or when a different app is drawn on top of this app, etc.. I'm not worried about the solution per se, I'm just a slightly worried future devs might not understand if they can remove the call from onResume or they'll be tempted to do more stuff in onResume/onViewDrawn which usually isn't considered a good practice in VMs. Having said all that, no need to change anything - just things which are imo worth considering

> Not sure, what is a documentation test?

A regular unit test which main purpose is documenting the behavior. Eg. if we decided to remove the call from onResume and handle the situation differently in the future, the test might help the devs to make such decision and trust that it doesn't break anything.

> @malinajirka fixed that https://github.com/woocommerce/woocommerce-android/commit/19d55f8ec7d0a1e417024b56c0a0ea8b4cc399e2

Noice, Thanks!

2022-08-10 03:19 UTC, kidinov commented
@malinajirka 

> A regular unit test which main purpose is documenting the behavior. Eg. if we decided to remove the call from onResume and handle the situation differently in the future, the test might help the devs to make such decision and trust that it doesn't break anything.

Good point. Created an issue on that