Issue/7299 site credentials mismatch
woocommerce/woocommerce-android pull request #7330
Opened 2022-09-01 15:01 UTC by hichamboushaba

Closes: #7299 

### Description
This PR fixes the above issue by making sure we show the account mismatch screen when connecting using site-credentials to a site that has Jetpack connected to a different account.

The message was updated to reflect that it's not an account mismatch per se, but it's the fact that the used credentials are for an account that's not connected to Jetpack.
The screen doesn't allow much now, but it will be improved in upcoming PRs, and it's still better than the misleading "Jetpack Required" screen that we were using before.

### Testing instructions
1. Prepare a site that has two accounts, where one of them is connected to Jetpack.
2. Open the app, and sign in using the site address.
3. Use site credentials for login, and enter credentials of the non-connected account.
4. Confirm the app shows the correct error screen.

### Images/gif
<img width=360 src="https://user-images.githubusercontent.com/1657201/187946815-8a38a742-f136-43e1-8d88-7d36f19e2068.png" />

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-09-01 15:03 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/AccountRepository.kt
> +    fun getUserAccount(): AccountModel? = accountStore.account.takeIf { it.userId != 0L }
The AccountStore adds a default account, and we don't want it to be returned here.

2022-09-01 15:05 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerRepository.kt
> +            it?.origin == SiteModel.ORIGIN_WPCOM_REST
When the user signs in using site credentials, we retrieve the site using XMLRPC, then we cache it, but for the site picker, we care only about sites that were returned using the WPCom API /me/sites, as they are the ones we can connect to.

2022-09-05 09:58 UTC, hafizrahman requested changes

2022-09-05 09:58 UTC, hafizrahman commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="login_jetpack_not_connected">It looks like your account is not connected to %1$s\'s Jetpack</string>
```suggestion
    <string name="login_jetpack_not_connected">Sorry, only the account on %1$s that is connected to the Jetpack plugin is able to manage the store in this app.</string>
```

What do you think about rewording the message this way?

- I think it gives better clarity on what's happening. Instead of only saying the account is not connected to JP, we also explain what it means if the account is connected.
- If the merchant copies the error text and shared it to our support, I think it might help troubleshoot the exact issue better.

2022-09-05 09:58 UTC, hafizrahman commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="login_jetpack_not_connected">It looks like your account is not connected to %1$s\'s Jetpack</string>
I also wonder if we can reword the button "Login with another account" to "Login with the connected account" to make the next action be super clear to the merchants.

2022-09-05 10:05 UTC, hichamboushaba commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="login_jetpack_not_connected">It looks like your account is not connected to %1$s\'s Jetpack</string>
As I explained on the PR description, this state is temporary, we will be providing a way to connect the account to Jetpack from the app, so the wording you suggested won't work with it (check https://github.com/woocommerce/woocommerce-android/pull/7342).
The "Login with another account" button is a secondary action only if they used the wrong account, but managing the site using the entered account is the primary action, and will be supported soon.

2022-09-06 10:19 UTC, hichamboushaba commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="login_jetpack_not_connected">It looks like your account is not connected to %1$s\'s Jetpack</string>
@hafizrahman did you get a chance to check my reply here? 🙏

2022-09-06 10:24 UTC, hafizrahman approved these changes
Thanks for the explanation! :) All good from my end, then.

2022-09-06 10:25 UTC, merged