[Login] Explanation for account invitation when having an account mismatch using a WPCom site
woocommerce/woocommerce-android pull request #7491
Opened 2022-10-06 13:42 UTC by hichamboushaba

Part of: #7307

### Description

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-10-07 05:41 UTC, hafizrahman requested changes
I made a mistake by testing with a secondary account that already has other sites connected. This might have uncovered something:

<img src="https://user-images.githubusercontent.com/266376/194475382-7f53b346-180b-4d5a-a43a-d9de0cf88b6d.png" width="42%" />

Question: do we want to add the explanation to this type of screen as well?

Additionally, backscroll is working oddly on this screen, although I don't know if it's affected by this PR or not (if not, let me know and I'll make issues for it):

https://user-images.githubusercontent.com/266376/194475575-7fd092ac-9a2d-4cd3-911c-570e66005e98.mov

1. Pressing back opens the list of sites instead of going to the previous steps,
2. Pressing back when the list of sites are shown doesn't do anything.

2022-10-07 15:12 UTC, hichamboushaba commented
> I made a mistake by testing with a secondary account that already has other sites connected. This might have uncovered something, since the screen I see is now different:

@hafizrahman are you sure you tested using the correct branch? with this branch, the "View Connected Stores" button won't be shown in any case, can you please double check?

> Pressing back opens the list of sites instead of going to the previous steps

First, we are dealing with two activities and multiple fragments, so returning to the previous step would be very challenging.
And also from a UX perspective, the previous step is `password` entry, and it doesn't make sense to go back to it, since the account is valid, it's just that the site is not connected, so going back to the list of stores might give a valid flow to the user if they want to use an alternative site.

An additional point, this navigation logic just there by default, but with this PR, and as per point 4 in the description above, I made it in purpose, since we will now hide the "View Connected Stores" button, and we need to keep a way to check the list if needed.

2022-10-07 16:13 UTC, hichamboushaba commented
@hafizrahman for your information, the last commit is just do remove some unused code that I noticed.

2022-10-08 13:55 UTC, hafizrahman commented
>  are you sure you tested using the correct branch? with this branch, the "View Connected Stores" button won't be shown in any case, which makes me think the test was done an older version, can you please double check?

Oh huh, I'm sorry about the note above, then. I selected the right branch `issue/7307-wpcom-sites` using the canary build for Android Studio at the same time that I was testing at the same time, and that happened. Returned to my regular Android Studio install and the situation doesn't happen 🤔 

Thanks for explaining the reasoning behind the back button behavior! I understand the challenges now. Everything works good in my checks now 👍🏼

2022-10-08 13:55 UTC, hafizrahman approved these changes

2022-10-08 13:56 UTC, merged