IAP: Core logic
woocommerce/woocommerce-android pull request #7521
Opened 2022-10-12 12:30 UTC by kidinov

Closes: #7512

### Description

The PR adds core logic with some (many) shortcomings. The more specific to our case logic will be one layer above of this

### Testing instructions

Nothing to test yet

### We are going to iterate, so consider this code as the first iteration. It doesn't go to trunk and will be reviewed/tested again

2022-10-12 14:06 UTC, malinajirka requested changes
Thanks for working on this @kidinov! Quite a lot of work you've done 🙇 👏  .

However, I find it very difficult to review - there is no description, the whole PR contains 600lines of code (I believe our limit without unit tests is 300 - I'm not sure why it's not applied), and the whole PR is a single commit. I'd like to be able to follow your train of thoughts so I can understand the decisions and the code. That's unfortunately not possible at the moment. I feel like it's especially important for a feature I don't have much experience with and requires understanding of the official APIs. Would you please consider splitting it into multiple commits and multiple PRs and providing PR descriptions? Thank you!

2022-10-12 14:06 UTC, malinajirka commented on libs/iap/src/main/java/com/woocommerce/android/iap/pub/model/IAPPurchaseResponse.kt
> +data class IAPPurchase(
❓ Are all these details necessary for the app module? They seem like IAP internal details the app might not need to know about, wdyt?

2022-10-12 14:59 UTC, kidinov commented on libs/iap/src/main/java/com/woocommerce/android/iap/internal/core/IAPExt.kt
> +package com.woocommerce.android.iap.internal.core
Just some convenience extensions to the billing library classes

2022-10-12 15:01 UTC, kidinov commented on libs/iap/src/main/java/com/woocommerce/android/iap/internal/core/IAPInMapper.kt
> +internal class IAPInMapper {
This is a mapper class to map all the incoming types to the internal, billing library specific types

2022-10-12 15:03 UTC, kidinov commented on libs/iap/src/main/java/com/woocommerce/android/iap/internal/core/IAPLifecycleObserver.kt
> +internal class IAPLifecycleObserver(
The class that receives lifecycle callbacks from a lifecycle owner. The goal is to keep the `BillingClient` connected while the lifecycle owner alive (between `created` and `destroyed`

2022-10-12 15:06 UTC, kidinov commented on libs/iap/src/main/java/com/woocommerce/android/iap/internal/core/IAPLifecycleObserver.kt
> +    suspend fun waitTillConnectionEstablished() = suspendCoroutine<Unit> {
Connection is asynchronous. This method makes it possible to suspend until `BillingClient` is connected. Pretty much all interactions with IAP can be done only when it is connected

2022-10-12 15:10 UTC, kidinov commented on libs/iap/src/main/java/com/woocommerce/android/iap/internal/core/IAPManager.kt
> +internal class IAPManager(
Main hub to the library. Allows:
* To fetch all purchases of a specific type (subscriptions or IAP)
* To initiate a purchase of the specified product
* To fetch product information of the specified product

2022-10-12 15:12 UTC, kidinov commented on libs/iap/src/main/java/com/woocommerce/android/iap/internal/core/IAPManager.kt
> +                    iapPurchasesUpdatedListener.waitTillNextPurchaseEvent(it)
New purchases are delivered to the callback which has to be passed during the creation of the `BillingClient`, that's why here we wait till it gets delivered

2022-10-12 15:17 UTC, kidinov commented on libs/iap/src/main/java/com/woocommerce/android/iap/internal/core/IAPManagerFactory.kt
> +internal object IAPManagerFactory {
Factory to avoid bringing dagger in the module

2022-10-12 15:18 UTC, kidinov commented on libs/iap/src/main/java/com/woocommerce/android/iap/internal/core/IAPOutMapper.kt
> +internal class IAPOutMapper {
Mapper class to map all the `outcoming` types from the internal billing library specific types

2022-10-12 15:30 UTC, kidinov commented on libs/iap/src/main/java/com/woocommerce/android/iap/internal/core/IAPPurchasesUpdatedListener.kt
> +internal class IAPPurchasesUpdatedListener(
Listener which is passed to the `BillingClient` and where all updates regarding purchases come. Currently used in the most simple way - it lets to suspend until the next purchase event comes

2022-10-12 15:35 UTC, kidinov commented on libs/iap/src/main/java/com/woocommerce/android/iap/internal/model/IAPProductDetailsResponse.kt
> +internal sealed class IAPProductDetailsResponse {
The sealed class serves as internally used result to `queryProductDetails`

2022-10-12 15:36 UTC, kidinov commented on libs/iap/src/main/java/com/woocommerce/android/iap/pub/model/IAPBillingErrorType.kt
> +sealed class IAPBillingErrorType(val debugMessage: String) {
Mapped to a sealed class all possible errors `responseCode` which `BillingResult` can have

2022-10-12 15:37 UTC, kidinov commented on libs/iap/src/main/java/com/woocommerce/android/iap/pub/model/IAPParams.kt
> +sealed class IAPProduct(val productId: String, val productType: IAPProductType) {
Income parameters that library can take

2022-10-12 15:38 UTC, kidinov commented on libs/iap/src/main/java/com/woocommerce/android/iap/pub/model/IAPProductInfo.kt
> +data class IAPProductInfo(
Product information that library consumer can use to display information about product that is for sale

2022-10-12 15:46 UTC, kidinov commented on libs/iap/src/main/java/com/woocommerce/android/iap/internal/core/IAPManager.kt
> +                return@withContext handleFetchPurchasesSuccess(purchasesResult, iapProductType)
Purchase returned from `queryPurchasesAsync` doesn't contain product details (name, id, price, currency, etc) so I have to fetch product details for every purchase here. Every purchase can contain several products 🤷‍♂️

2022-10-12 15:47 UTC, kidinov commented on libs/iap/src/main/java/com/woocommerce/android/iap/pub/model/IAPPurchaseResponse.kt
> +sealed class IAPPurchaseResponse {
The sealed class that contains info about request for purchases

2022-10-12 15:56 UTC, kidinov commented on libs/iap/src/main/java/com/woocommerce/android/iap/pub/model/IAPPurchaseResponse.kt
> +data class IAPPurchase(
Well, I don't know. I haven't seen what we want to show to a user, and what flow it will be, so I think it's better to remove some extra info if it won't be needed than to rush adding it before the deadline. 

Also, I have not decided yet, if the network calls will be done in the module, or follow a similar approach to `cardreader` and move to the main module. Depending on that, the information that needs to be returned can be different

2022-10-13 14:45 UTC, malinajirka approved these changes
I've scanned through the PR and it LGTM overall. I haven't done a full review as discussed, since all the code is subject to changes. We'll review it when it's working all together. The possible downside of this approach is that making changes later will be more difficult, but that's a risk worth taking in this case.

Thanks @kidinov !

2022-10-14 08:11 UTC, merged