Feature/7510 account creation UI
woocommerce/woocommerce-android pull request #7534
Opened 2022-10-13 17:03 UTC by JorgeMucientes

Closes: #7510

### Description
Adds UI to the first step of the store creation flow: Account creation. 
This PR also includes adding Android Navigation starting from `LoginActivity` so we can use nav_grapths from now on in the store creation flow. I presume login simplification will also follow this road when decoupling from the authentication library. 

This also adds a feature flag to only display the store creation access point for debug builds. Please don't pay much attention to the newly added "Get started" button in `LoginPrologue` as the design is not final. 

### Testing instructions
- Open the app and navigate to the new screen for account creation
- Check that "Accept terms of Service" opens the correct website
- Check that back navigation works as expected

### Images/gif

https://user-images.githubusercontent.com/2663464/195638535-180d742d-9bc8-4d49-8708-37e36ba619bf.mp4

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-10-14 11:19 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
>      }
This code is a bit hacky, we should be able to get rid of it once we have the login completely decoupled from the auth lib. In the meantime android navigation would have to coexist with the old way of starting new fragments using `supportFragmentManager` and thus we'll have to keep this. 

One thing that caught my attention and I could not explain why  is`navController.backQueue.count()` is equal to 2, when only one fragment has been added to the back stack -> `LoginPrologueFragment` . I tried debugging this to see what's inside that queue but it stays "collecting data" forever: 

![Screenshot 2022-10-14 at 13 16 18](https://user-images.githubusercontent.com/2663464/195834525-23f1c58c-405d-4bf6-a4fb-0fdf4b08aede.png)

2022-10-14 11:33 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt
>      }
I ended up handling it in a different way:

```kotlin
    private fun handleBackPress() {
        AnalyticsTracker.trackBackPressed(this)
        if (supportFragmentManager.backStackEntryCount != 0) {
            supportFragmentManager.popBackStack()
        } else if (navHostFragment.childFragmentManager.backStackEntryCount == 0) {
            finish()
        }
    }
```

But still would appreciate if you might know the answer to why the `backQueue.count()` was equal to 2.

2022-10-14 11:34 UTC, JorgeMucientes commented on WooCommerce/src/main/res/navigation/nav_graph_login.xml
> +<navigation xmlns:android="http://schemas.android.com/apk/res/android"
Created this one so we can start adding new screens for login simplification here.

2022-10-14 12:06 UTC, hichamboushaba commented
> I presume login simplification will also follow this road when decoupling from the authentication library.

You are right, and it will be done using one of two approaches:
1. Keep using a separate LoginActivity for login flow.
2. Go with a signle-activity approach by moving the login to MainActivity in a separate navgraph.

Personally I'm leaning towards approach 2.
But anyway, what you've done here would simplify things for us too, as we can just take the graphs you are creating and inject them either to a new LoginActivity or MainActivity.

2022-10-14 12:46 UTC, 0nko requested changes
Looking good, but I'm seeing a crash when I rotate the prologue screen:

```
Process: com.woocommerce.android.prealpha, PID: 19556
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.woocommerce.android.prealpha/com.woocommerce.android.ui.login.LoginActivity}: java.lang.ClassCastException: com.woocommerce.android.ui.login.LoginPrologueFragment cannot be cast to androidx.navigation.fragment.NavHostFragment
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5456)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5362)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.ClassCastException: com.woocommerce.android.ui.login.LoginPrologueFragment cannot be cast to androidx.navigation.fragment.NavHostFragment
	at com.woocommerce.android.ui.login.LoginActivity.onCreate(LoginActivity.kt:179)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5456) 
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5362) 
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loop(Looper.java:223) 
	at android.app.ActivityThread.main(ActivityThread.java:7656) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

2022-10-14 12:46 UTC, 0nko commented on WooCommerce/src/main/res/navigation/nav_graph_login.xml
> +<navigation xmlns:android="http://schemas.android.com/apk/res/android"
👏 Nice, I actually had to do this for my logged-out webview experiment. But maybe we can eventually just use a single activity in the future?

2022-10-14 15:10 UTC, JorgeMucientes commented
> Personally I'm leaning towards approach 2.
But anyway, what you've done here would simplify things for us too, as we can just take the graphs you are creating and inject them either to a new LoginActivity or MainActivity.

Yes, I agree the end result should be a single activity approach too @hichamboushaba . But unless I'm missing something that'd be possible once we have a complete decoupled from auth lib login flow. During the progressive refactor where both approaches have to coexist in parallel y thin the only feasible approach is to keep `LoginActivity` as the host of the new `nav_graph` login. Once we are done with A/B tests and have the new login flow working then migrate it to `MainActivity` 

@0nko can you provide what version of Android are you testing that on? or if you followd any particular flow before rotating? I'm unable to reproduce the crash

2022-10-14 15:17 UTC, hichamboushaba commented
> But unless I'm missing something that'd be possible once we have a complete decoupled from auth lib login flow. During the progressive refactor where both approaches have to coexist in parallel y thin the only feasible approach is to keep LoginActivity as the host of the new nav_graph login.

I didn't investigate yet, but I believe we can make the code dynamic in the parts where we launch `LoginActivity`: launching the activity if the feature flag is not enabled, and use the new navgraph when it's enabled. I'll experiment with this next week.
But anyway, this doesn't affect you at all, since now with nav_graphs, we can use them from multiple places, and what you did here is the good start 👍.

2022-10-15 12:43 UTC, 0nko commented
@JorgeMucientes I tested it on the emulator running Android 11 (with `Don't keep activities` enabled).

2022-10-17 15:57 UTC, JorgeMucientes commented
Hey @onko ready for another round 🙏🏼 

I fixed a couple issues related to the navigation. I couldn't reproduce the crash initially because it only happened when coming from the `LoginPrologueCarouselFragment` or the `LoginSurveyFragment` which is never triggered in debug. Anyway crahs fixed alongside some back navigation issues when `startOver` method was invoked.

2022-10-17 17:13 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueFragment.kt
> +            prologueFinishedListener?.onGetStartedClicked()
Just a question @JorgeMucientes, I've been experimenting with the infra for the simplified login, and I've taken your branch as the base of my PR, then I noticed this line.

Is there some reason for passing through a listener here and not calling `findNavController` directly? I understand we had to do this dance before because the fragment switching was happening using the LoginActivity, but it shouldn't be needed for this action as it's using NavController, WDYT?
You don't need to change anything, I just want to see if I'm missing something, otherwise it can be changed later.

2022-10-17 19:42 UTC, 0nko approved these changes
Looking good, thanks for the fix! 👍

2022-10-17 21:33 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueFragment.kt
> +            prologueFinishedListener?.onGetStartedClicked()
You are right! This approach is probably a leftover. I first added the "Get Started" button to the fragment and then I added the refactor to use Android Navigation from `LoginActivity`. There's actually no reason to use the `listener` approach any more. I'll refactor that in my upcoming PR. Thanks for bringing this up 👍🏼

2022-10-18 08:02 UTC, merged