Feature/7510 error handling
woocommerce/woocommerce-android pull request #7584
Opened 2022-10-20 15:11 UTC by JorgeMucientes

Closes: #7510 

### Description
This add needed changes to deal with all the possible errors from account creation. 

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-10-21 12:58 UTC, hafizrahman commented
> Type "[Jorgemucientes@gmail.com](mailto:Jorgemucientes@gmail.com)" as email and check -> email already exist

Just wanted to note that in WordPress.com, it has what I think is a more actionable error message. We might want to consider something similar in the future:

![Screen Shot 2022-10-21 at 19 57 40](https://user-images.githubusercontent.com/266376/197201378-56085e98-bbb4-4900-8941-6ec17f3be8a6.png)

2022-10-21 13:05 UTC, hafizrahman requested changes
In my test and around 0:16 in the video, the error message for the password field is also shown and replicated under the email address field. I think it makes more sense for it to only appear on the specific input field. Wdyt?

2022-10-21 13:19 UTC, hafizrahman commented
❓ Is it indeed planned to have all validation done after pressing the "Get started" button? I can understand the existing email address checking will need network call, but curious if some checks can be done in real time instead (e.g: email/password length, password strength). Might be a bit better user experience, although definitely not a blocker.

2022-10-21 15:41 UTC, JorgeMucientes commented
Thanks for the review @hafizrahman 🙏🏼 

> In my test and around 0:16 in the video, the error message for the password field is also shown and replicated under the email address field. I think it makes more sense for it to only appear on the specific input field. Wdyt?

Dammit, I don't know how I missed that bug, specially while I was doing the screen recording 😅 . Good catch 👍🏼. Fixed it! 

> Is it indeed planned to have all validation done after pressing the "Get started" button? ...

Good point. Yes! in fact, most of the validation are handled locally inside `validateCredentials()` from `SignUpRepository`. So, no API request is fired if those validations are not satisfied.  The fact that validations are triggered after clicking "Get started" is to make sure the user has finished entering the credentials. We could validate right after the Text field losses focus, but I don't see major gains from that. Wdyt?

2022-10-21 15:45 UTC, JorgeMucientes commented
> Just wanted to note that in WordPress.com, it has what I think is a more actionable error message. We might want to consider something similar in the future (especially since even in our current design we also already have similar design pattern of label text with tappable link for ToS):

Yes, that would be a more actionable error, but kind of redundant as we are already going to offer  a direct CTA to "Log in" inside the screen (not implemented yet tough, waiting for final designs in Figma: HyVloP5FipZzyPVenH2euI-fi-1262%3A61796)

2022-10-23 10:17 UTC, hafizrahman approved these changes

2022-10-23 10:17 UTC, hafizrahman commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="signup_email_invalid_input">The email is invalid.</string>
Suggestion for a more actionable error message:

```suggestion
    <string name="signup_email_invalid_input">Please enter an invalid email address.</string>
```

2022-10-23 10:17 UTC, hafizrahman commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="signup_email_invalid_input">The email is invalid.</string>
```suggestion
    <string name="signup_email_invalid_input">Please enter a valid email address.</string>
```

2022-10-23 10:22 UTC, hafizrahman commented
This now LGTM, I added a small error message improvement. Have a look and feel free to merge PR afterward.

>  The fact that validations are triggered after clicking "Get started" is to make sure the user has finished entering the credentials. We could validate right after the Text field losses focus, but I don't see major gains from that. Wdyt?

Yeah, I think there's trade-offs for either real-time validation (user can be sure they only submit correct values, but can also be slow on slower connection), or validation after submission (less networking-intensive, but if user makes several mistakes or unsure what their mistakes are, it's extra steps for them to submit over and over). But in any case there's no major gains for now, let's just go with what's already there :)

2022-10-23 12:11 UTC, merged