Add tag to zendesk with IPP plugins statuses
woocommerce/woocommerce-android pull request #7624
Opened 2022-10-25 11:18 UTC by kidinov

Closes: #7603

### Description

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-10-25 12:00 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/support/help/HelpViewModel.kt
> +            if (fetchSitePluginsResult.isError) {
🔍 Nitpick: We might consider having a single return statement in this function and remove the code duplication.

```
val tags = if (fetchSitePluginsResult.isError) {
                listOf(SITE_PLUGINS_FETCHING_ERROR_TAG)
            } else {
                val wcPayPluginInfo = wooStore.getSitePlugin(selectedSite.get(), WooPlugin.WOO_PAYMENTS)
                val stripePluginInfo = wooStore.getSitePlugin(selectedSite.get(), WooPlugin.WOO_STRIPE_GATEWAY)

                determineWcPayTag(wcPayPluginInfo) + determineStripeTag(stripePluginInfo)
            }

            triggerEvent(ContactPaymentsSupportClickEvent.CreateTicket(ticketType, tags))
```

Wdyt?

2022-10-25 15:09 UTC, malinajirka requested changes
Thanks for working on this @kidinov!

I've found two potential issues

1.  🚫 💥  The app crashes when I attempt to create a ticket during the login flow - right after I click on "Contact Support" row.
2. 🚫  The tags are being truncated in Zendesk UI so it's not possible to differentiate between installed and activated and installed and not activated.
<img width="240" alt="Screenshot 2022-10-25 at 17 08 23" src="https://user-images.githubusercontent.com/2261188/197811727-c2a43d79-7857-46d4-9396-74f4b38f08c6.png">

2022-10-25 15:09 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/support/help/HelpViewModel.kt
> +            if (fetchSitePluginsResult.isError) {
Agree, often better to avoid `else`, but here is not the case =)

f39e7fc7b3d5ca2d8d3fb2b0770dff624b6afd07

2022-10-25 15:47 UTC, kidinov commented
@malinajirka thank you for the review

> 🚫 💥 The app crashes when I attempt to create a ticket during the login flow - right after I click on "Contact Support" row.

Good catch 🙏. 

Fixed here - 1377d4361c52a0274cf3c62c9beb038047cc3930

> 🚫 The tags are being truncated in Zendesk UI so it's not possible to differentiate between installed and activated and installed and not activated.

Do you think this is an issue with this PR, or maybe more with the screen density/size/zendesk setup? Short tags can be truncated as well, it depends on the factors above

https://user-images.githubusercontent.com/4923871/197820513-9df96318-14d4-443d-991f-67a45de6c1e6.mov


https://user-images.githubusercontent.com/4923871/197820497-5826c2f8-8dce-43eb-851d-5d2c155dfce7.mov

2022-10-27 06:10 UTC, malinajirka approved these changes
Thanks for the fix! 

> Do you think this is an issue with this PR, or maybe more with the screen density/size/zendesk setup? Short tags can be truncated as well, it depends on the factors above

Sorry, I tried expanding the sidebar before I mentioned this issue and it didn't work 🤷 . Now, that I see it works, I believe it's fine to keep it as is.

> Fixed here - https://github.com/woocommerce/woocommerce-android/commit/1377d4361c52a0274cf3c62c9beb038047cc3930

LGTM!


I retested the app and it seems to work as expected 🚢 .

2022-10-27 06:10 UTC, merged