[Simplified login] Not WordPress.com account screen changes
woocommerce/woocommerce-android pull request #7639
Opened 2022-10-26 14:01 UTC by hichamboushaba

Closes: #7612

### Description

### Testing instructions

### Images/gif
https://user-images.githubusercontent.com/1657201/198046898-4180b024-254d-4637-aab0-c8ca1e00c6b1.mov

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-10-26 15:18 UTC, hichamboushaba commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="what_is_wordpress_link">What is WordPress.com?</string>
I removed the underline from this key and `login_need_help_finding_email`, we don't have the underline in Figma, and I confirmed that the last decision was to remove even before this project (ref p1658816607458229/1658117084.869099-slack-C0354HSNUJH), I think it was just missed.

2022-10-27 10:55 UTC, hafizrahman commented
I got a crash when testing this from using the "Continue with WordPress.com" button on the Prologue screen. `remoteConfig.getString(SIMPLIFIED_LOGIN_VARIANT_KEY).uppercase()` in `FirebaseRemoteConfigRepository#getSimplifiedLoginVariant()` was returning an empty string. 

So I merged latest trunk to this branch to include the fix from #7642

2022-10-28 02:26 UTC, hafizrahman requested changes
Minor:

Can you check the "no WP.com account" screen on your side? Mine shows a gray instead of white background, for some reason 🤔 

<img src="https://user-images.githubusercontent.com/266376/198467678-22fe38ef-bd01-446a-987d-c5a6e78ad0a2.png" width="42%" />

2022-10-28 07:45 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModel.kt
> +                fetchUserAccount()
❓  I haven't followed the entire Site Picker logic so probably a basic question: Why is it needed to fetch user account here, while `updateSiteViewDetails()` is called before it and that function already does `getUserInfo()`? 

Would it be better if `updateSiteViewDetails()` does the fetch instead if it gets no result for `getUserInfo()`?

2022-10-28 07:45 UTC, hafizrahman commented
In general everything works as expected to me, just left two small questions above.

2022-10-28 09:49 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModel.kt
> +                fetchUserAccount()
I didn't have any specific reason for putting it there, I just wanted to put it next to where we fetch sites.
I made a small change in 4e956e560f342713a8f98ed2fc2d380bc659b385, I hope it makes things clearer.

2022-10-28 09:50 UTC, hichamboushaba commented
>  Can you check the "no WP.com account" screen on your side? Mine shows a gray instead of white background, for some reason 🤔

@hafizrahman I believe this happens only on the emulator, maybe because of using the mouse which triggers some sort of selection.
Can you double-check if happens in real devices?

2022-10-28 13:56 UTC, hafizrahman commented
> I believe this happens only on the emulator, maybe because of using the mouse which triggers some sort of selection.

Huh, you're right. I've never run into this before for some reason 🤔

2022-10-28 13:56 UTC, hafizrahman approved these changes

2022-10-28 13:58 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModel.kt
> +                fetchUserAccount()
That's awesome, thanks for adding that change!

2022-10-28 14:23 UTC, merged