Add simulated card reader toggle logic
woocommerce/woocommerce-android pull request #7661
Opened 2022-10-27 12:31 UTC by rossanafmenezes

Closes: #7536 

### Description

This PR adds the logic to enable/disable the Simulated reader using the toggle button in the Developer Options screen 

### Testing instructions

1 - in Debug build -> Go to the App Menu - Settings - Developer Options
2 - Toggle the Simulated Reader ON
3 - create a simple payment or an order
4 - take the payment via credit card
5 - make sure the simulated reader is activated (It might ask you to select which reader, select the one according to where your store is based - US or Canada)
6 - Go back to the settings screen - Developer Options
7 - Toggle the simulated reader OFF
8 - repeat the steps to collect a payment
9 - Make sure the simulated reader won't activate

### Images/gif

https://user-images.githubusercontent.com/30724184/198228337-3d90eb06-31f6-40e8-a0d1-d733e2661687.mp4

Please note: Currently, untoggling the button is not clearing the selected card reader  (LAST_CONNECTED_CARD_READER_ID) so the button is not disabling the simulated reader. 

This will be addressed in the next PR

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-10-27 12:47 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +        val newState = (viewState.value?.rows?.first() as ToggleableListItem).copy(isChecked = isChecked)
I will start also working on the improvement here to replace the .first() with .find {} as we discussed.

2022-10-28 09:27 UTC, malinajirka requested changes
Great job @rossanafmenezes, it looks great overall!

I've noticed one potential issue with the code we wrote together on Wednesday. Let me know if the comment makes sense.

2022-10-28 09:27 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +    val viewStateData: LiveData<DeveloperOptionsViewState> = viewState
🔍 Nitpick: We usually follow these two practices:
1. Class fields are defined at the top of the class, before any methods. Moreover, related fields should be defined close to each other. We might want to consider moving this below the `viewState` initialization, wdyt?
2. We usually follow a pattern where the mutable livedata are prefixed with `_` and the immutable livedata don't have a prefix. For example, we'd have `_viewState` and `viewState` instead of `viewState` and `viewStateData`. Example can be found eg [here](https://github.com/woocommerce/woocommerce-android/blob/64dec7ddbe4e83e6ac88a3cb874bb89858f954a0/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/signup/SignUpViewModel.kt#L29).

2022-10-28 09:27 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +        val newState = (viewState.value?.rows?.first() as ToggleableListItem).copy(isChecked = isChecked)
⚠️ I noticed a bug in this code -> if viewState.value or viewstate.value.rows is null, the cast to `ToggleableListItem ` will fail. Also the usage of `!!` is discouraged in production code, unless we are 100% sure it won't crash on NullPointerException(NPE).

Perhaps, we could do something like this:
```
private fun onSimulatedReaderToggled(isChecked: Boolean) {
        developerOptionsRepository.changeSimulatedReaderState(isChecked)
        
        val currentViewState = viewState.value
        (currentViewState?.rows?.first() as? ToggleableListItem)?.let { originalListItem ->
            val newState = originalListItem.copy(isChecked = isChecked)
            viewState.value = currentViewState.copy(
                rows = currentViewState.rows.map {
                    if (it.label == newState.label)
                        newState
                    else it
                }
            )
        }
    }
```

2022-10-28 09:48 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +    val viewStateData: LiveData<DeveloperOptionsViewState> = viewState
Thanks! Changed 👍

2022-10-28 10:19 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +        val newState = (viewState.value?.rows?.first() as ToggleableListItem).copy(isChecked = isChecked)
It makes sense. Thank you for pointing that out. I have made the changes.

2022-10-28 10:27 UTC, malinajirka approved these changes
Thanks @rossanafmenezes! LGTM :)

P.S. It doesn't disconnect from a reader when the toggle is switched, but that's being worked on as part of another PR.

2022-10-28 11:11 UTC, merged