[Simplified login] site picker changes
woocommerce/woocommerce-android pull request #7677
Opened 2022-10-28 13:53 UTC by hichamboushaba

Closes: #7613 

### Description

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-11-02 10:23 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NavController.kt
> +    fun navigateSafelyInternal(
❓  I understand what this is doing, but curious why this uses the word `Internal`?

2022-11-02 10:30 UTC, hafizrahman commented on WooCommerce/src/main/res/layout/fragment_site_picker.xml
> +                <com.google.android.material.button.MaterialButton
Just wanted to add that because I have a long list of sites under my account, it requires a bit of scrolling before I can see the "+ Add A Store" button.

In case we want to make it more discoverable, I wonder if it's worth moving it above the "Continue button" and have it always show up. Or at the top before "Select Store To Connect". But I understand this is probably an edge case issue.

2022-11-02 10:37 UTC, hafizrahman requested changes
Tested:

✅ Empty State (account not connected to any site).
✅ Account has Connected WooCommerce Stores.
✅ Account has Connected Non-Woo sites.
✅ Account has both WooCommerce Stores and Non-Woo sites.
✅ Store Switching flow.

In landscape I found this minor issue with the bottom sheet:

https://user-images.githubusercontent.com/266376/199468332-ad199025-3f25-4ed9-bc50-bc3bc36fa50a.mov

2022-11-02 10:49 UTC, hichamboushaba commented on WooCommerce/src/main/res/layout/fragment_site_picker.xml
> +                <com.google.android.material.button.MaterialButton
Yes, this was discussed internally multiple times, we agreed to keep as is, because of two reasons:
1. The vast majority of the users have only 1 or 2 sites.
2. The design is going to change in a new iteration soon.

For more information: p1667356043934939-slack-C03L1NF1EA3

2022-11-02 10:49 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NavController.kt
> +    fun navigateSafelyInternal(
It's just because it's just used internally (as a local function), I'm open to remove it if you think it doesn't make sense 🙂.

2022-11-02 11:09 UTC, hichamboushaba commented
> In landscape I found this minor issue with the bottom sheet:

Thanks for catching this issue @hafizrahman, I found that we had a logic to expand bottom sheets on tablets in landscape, but not on phones, I assume because we don't want the bottom sheet to block the UI entirely.
I updated the logic to fully display the sheet if it's less than half of the device's height, otherwise, we'll show enough space to not hide more than the half, this gives the following result:

| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1657201/199474546-3a34974e-0d38-4498-9960-1ee157b9192f.png) | ![image](https://user-images.githubusercontent.com/1657201/199473807-73c77124-ba82-4683-9b35-c71358038441.png) |
| ![image](https://user-images.githubusercontent.com/1657201/199474614-12f1b8f6-4ec9-4e63-a95d-bf06ee6a2db6.png) | ![image](https://user-images.githubusercontent.com/1657201/199474897-fc3d1d1d-6458-40b7-9c83-ccb3ffb2b20e.png) |
| ![image](https://user-images.githubusercontent.com/1657201/199474678-adfc7a72-ea6e-43fe-a47b-cd2de4309ede.png) | ![image](https://user-images.githubusercontent.com/1657201/199473908-87855ea2-02de-497a-b69a-0d904d72ad6e.png) |

Do you think this is a good fix?

2022-11-03 08:55 UTC, hafizrahman approved these changes
Tested the landscape fix and works well in various different sizes. 👍

2022-11-03 09:41 UTC, merged