Improve simulated reader toggle on dev options screen
woocommerce/woocommerce-android pull request #7684
Opened 2022-10-29 14:20 UTC by rossanafmenezes

Closes: #7670 

### Description

Adds the logic to disconnect the selected card reader once you toggle the simulated reader off. 
Also adds a toast message to indicate the reader was disconnected

### Testing instructions

1 - in Debug build -> Go to the App Menu - Settings - Developer Options
2 - Toggle the Simulated Reader ON
3 - create a simple payment or an order
4 - take the payment via credit card
5 - make sure the simulated reader is activated (It might ask you to select which reader, select the one according to where your store is based - US or Canada)
6 - Go back to the settings screen - Developer Options
7 - Toggle the simulated reader OFF
8 - repeat the steps to collect a payment
9 - Make sure the simulated reader won't activate

### Images/gif

https://user-images.githubusercontent.com/30724184/198836485-a0db5762-1a1d-4634-b89b-1114dc4a0fd6.mp4

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-10-30 08:12 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsRepository.kt
> +        clearCardReaderDataAction.invoke()
Here I'm not 100% sure if clearCardReaderDataAction.invoke() is the right way to go or if calling DisconnectReader() from the CardReaderManager would be enough.

2022-11-02 10:43 UTC, malinajirka requested changes
Thanks for working on this @rossanafmenezes! I've left one important comment and a couple of nitpicky suggestions (feel free to ignore those). I'll re-test the app after the toast is moved to the appropriate layer.

2022-11-02 10:43 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsRepository.kt
> +    fun showToast() {
🚫 Showing a toast is a responsibility of the view layer. We usually propagate an event from the VM to the view layer -> and display a toast there.

The responsibility of repository is a bit vague in our codebase. Usually, repository is used to access data from the VM layer and hides how the data are accessed - network vs database vs shared prefs vs .. . In our repository, we usually use it as a layer between FluxC and the Woo app. Having said that, I think using `clearCardReaderDataAction` here is +- ok, however, accessing UI is definitely out of the scope of the repository.

2022-11-02 10:43 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsRepository.kt
> +        clearCardReaderDataAction.invoke()
Good question! I think it is the right way to go - if we only disconnected, the app might pre-select the simulated reader upon the next connection.

2022-11-02 10:43 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +        if (!isChecked) {
🔍 Nitpick: The code works completely fine. However, the onSimulatedReaderToggled method is starting to become quite difficult to read - it does multiple things and all of them are within this method. Perhaps, we could simplify it a bit by extracting some of the parts into different methods.
eg.
```
launch {
                developerOptionsRepository.clearSelectedCardReader()
                developerOptionsRepository.showToast()
            }
``` 
could be replaced with 
```
disconnectAndClearSelectedCardReader()
```
etc. 

Wdyt?

2022-11-02 10:43 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +            abstract var devOptionsKey: UiString
🔍 Nitpick: This field is in DeveloperOptionsViewModel as part of DeveloperOptionsViewState => I think the `devOptions` prefix might not be necessary, wdyt?

2022-11-02 12:30 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +            abstract var devOptionsKey: UiString
True 😄  Thanks for pointing that out.

2022-11-02 12:55 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +        if (!isChecked) {
Sounds good 😄 Will work on that. Thanks

2022-11-02 14:01 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsRepository.kt
> +    fun showToast() {
Thank you for pointing that out 😄 
I have moved it to the view layer. Please let me know if the way I implemented is the right way to go. 

Thanks

2022-11-02 14:25 UTC, malinajirka approved these changes
LGTM, great job! Thanks :)

2022-11-02 14:26 UTC, merged