Issue/7690 add option update simulator
woocommerce/woocommerce-android pull request #7735
Opened 2022-11-03 12:25 UTC by rossanafmenezes

Closes: #

### Description

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-11-15 18:32 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +            .setSingleChoiceItems(textValues, selectedItemIndex.ordinal) { dialog, which ->
Note: Here I have removed the option to dismiss the dialog when you select the option due to the lack of a visual cue. Even tho it works fine, it looks like a bug. In the future, we can add a header to replace the Row title and let the option selected show in the actual row to visually indicate it was actually selected. Wdyt?

2022-11-16 14:37 UTC, malinajirka requested changes
Thanks Rosie, great job! It works as described. 

Since the main goal of this task is to learn, I decided to comment even on things which I might usually skip during review. Feel free to completely ignore any comments which don't have ⚠️ icon. The ones which do, I'd like us to at least discuss even if we decide not to make any changes. Thanks!

2022-11-16 14:37 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
> +        get() = getString(UPDATE_SIMULATED_READER_OPTION, "Never")
⚠️ I'm wondering if hardcoding "Never" here is safe. What if the options change or someone decides to rename the enum from NEVER to NEVER_UPDATE or something in that sense. Perhaps we could use `UpdateOptions.NEVER.toString()` to be on the safe side => make what we save and load from the shared preferences consistent. Wdyt?

2022-11-16 14:37 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsAdapter.kt
> +            VIEW_TYPE_SPINNER -> {
❓ I'm wondering if `spinner` is the proper term here - I always considered a spinner something like this:
<img width="104" alt="Screenshot 2022-11-16 at 14 39 06" src="https://user-images.githubusercontent.com/2261188/202195555-97658325-2df1-47fa-a0ba-dd6700f47657.png">

Wdyt? (P.S. We could name it VIEW_DIALOG_WITH_RADIO_BUTTONS perhaps?)

2022-11-16 14:37 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +                        values = UpdateOptions.values(),
🔍 The values would ideally come from the VM and would not be "hardcoded" here to keep the logic in the VM => also to make it testable. It seems the `ShowDialog` class already has `options` field - any reason why we don't use it (other than it's just a single string instead of List<String> or similar)?

2022-11-16 14:37 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +                is DeveloperOptionsViewModel.DeveloperOptionsEvents.ShowDialog -> {
🔍 "ShowDialog" feels a bit too generic, wdyt? Perhaps, we could name it something like "ShowUpdateOptionsDialog"?

2022-11-16 14:37 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +        mapper: (UpdateOptions) -> String = { it.toString() }
❓ Any reason we are setting a default mapper here - seems like we are never using the default value anyway?

Moreover, unless, I'm missing something the default implementation won't be localized => it'll simply convert the enum value into a string, eg. NEVER -> never, ... . Wdyt?

2022-11-16 14:37 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +        var selectedValue: UpdateOptions = UpdateOptions.NEVER
⚠️ Default value selection and loading the stored value from the shared preferences are both business logic => would ideally live in the VM layer. Wdyt?

2022-11-16 14:37 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +            .setTitle("Update Simulated Reader")
⚠️ Setting the title would ideally come from the VM as well, so it can be unit tested.

2022-11-16 14:37 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +                selectedValue = values[which]
❓ It seems we are doing an extra step here, which feels unnecessary, unless I'm missing something.
We currently:
1. User clicks on an option
2. We store the selection into `selectedValue`
3. When the user dismisses the dialog, we load `selectedValue` and store it into shared preferences.

Is there any reason why we don't omit the second step?

1. User clicks on an option
2. We store the selection into shared preferences
3. When the user dismisses the dialog, we don't do anything at all => we wouldn't even need to implement `setOnDismissListener` at all.
Wdyt?

2022-11-16 14:37 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsRepository.kt
> +    fun updateSimulatedReaderOption(selectedOption: UpdateOptions) {
⚠️ It seems we are using the repository to store the value into shared preferences. Is there any reason why we don't use it also to load the value from shared preferences?

Tbh I wouldn't mind if we didn't use the repository at all for this case, but since we decided to use it for storing the value I believe we should also use it for loading the value to keep the code consistent. Wdyt?

2022-11-16 14:37 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +            isEnabled = true,
❓ We originally discussed disabling the "Simulated Reader Updates" row when the user disables simulated reader => however, it seems it is enabled all the time. Is that planned to be implemented in a different PR?

2022-11-16 14:37 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +            DeveloperOptionsEvents.ShowDialog("blabla")
Is this a secret add for BlablaCar.com? :P

2022-11-16 14:37 UTC, malinajirka commented on WooCommerce/src/main/res/layout/developer_options_spinner_item.xml
> +        android:layout_marginTop="0.5dp"
🔍  I've never seen a half-pixel -> TIL it's even possible :D. I guess it's possible because it's DP not a real pixel, but it's still confusing. 

Anyway, half pixel is close to `0`, so I'd suggest not setting the margin at all.

2022-11-16 14:37 UTC, malinajirka commented on WooCommerce/src/main/res/layout/developer_options_spinner_item.xml
> +        android:layout_width="100dp"
🔍  If we really want to hardcode the dimensions of the icon (read as `wrap_content` doesn't work) -> we might consider using one of the value in dimens.xml or introducing a new one. Wdyt?

2022-11-16 14:37 UTC, malinajirka commented on WooCommerce/src/main/res/layout/developer_options_spinner_item.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
⚠️  It seems we are missing some constraints on the views in this file. I personally prefer to set constraints on all items (start/end/top/bottom). But you can achieve that even if you set just some, but with the current code we might end up with a broken layout like this:
<img width="242" alt="Screenshot 2022-11-16 at 15 20 42" src="https://user-images.githubusercontent.com/2261188/202205490-8ebbb4ba-9300-4399-a6c3-b7555b7cbd19.png">

2022-11-16 14:37 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +            updateOptions.name == AppPrefs.updateReaderOptionSelected
🔍 When we are storing the value into shared preferences, we are using `.toString()`. However, here, after we load it, we compare it using `.name`. It works just fine, because the internal implementation of `toString` uses `name`. However, it feels a bit cumbersome, perhaps we could change this to `updateOptions.toString() == AppPrefs.updateReaderOptionSelected` or change [the storing code](https://github.com/woocommerce/woocommerce-android/blob/3cb4d96015af022008e88c3b04de645099607d21/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsRepository.kt#L25) to `.name`. Wdyt?

2022-11-17 12:09 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
> +        get() = getString(UPDATE_SIMULATED_READER_OPTION, "Never")
It is definitely a better option. Thank you for pointing that out.

2022-11-17 12:12 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsAdapter.kt
> +            VIEW_TYPE_SPINNER -> {
Makes sense. I used spinner because I based it on the WCMaterialOutlinedSpinnerView, but makes sense to change. In this case, should I change also the XML file for the list item developer_options_spinner_item?

2022-11-17 12:20 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +                is DeveloperOptionsViewModel.DeveloperOptionsEvents.ShowDialog -> {
Done!

2022-11-17 12:32 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +            updateOptions.name == AppPrefs.updateReaderOptionSelected
Makes sense. I will fix it. Thanks

2022-11-17 13:22 UTC, rossanafmenezes commented on WooCommerce/src/main/res/layout/developer_options_spinner_item.xml
> +        android:layout_marginTop="0.5dp"
🤔  I'm under the impression this was a mistake. I don't remember setting this. I have removed it. thanks

2022-11-17 13:28 UTC, rossanafmenezes commented on WooCommerce/src/main/res/layout/developer_options_spinner_item.xml
> +        android:layout_width="100dp"
I think wrap_content is fine. I have changed it.

2022-11-17 13:30 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +            DeveloperOptionsEvents.ShowDialog("blabla")
😨 I completely forgot this was there.

2022-11-17 16:48 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +        mapper: (UpdateOptions) -> String = { it.toString() }
Removed. Thank you.

2022-11-17 16:48 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +                is DeveloperOptionsViewModel.DeveloperOptionsEvents.ShowDialog -> {
renaming it as per our call

2022-11-17 17:58 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsAdapter.kt
> +            VIEW_TYPE_SPINNER -> {
will update the file name as per our call

2022-11-17 17:58 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +                        values = UpdateOptions.values(),
Thank you. Done

2022-11-17 17:58 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +        var selectedValue: UpdateOptions = UpdateOptions.NEVER
👍

2022-11-17 17:58 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +            .setTitle("Update Simulated Reader")
Done

2022-11-17 18:21 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +                selectedValue = values[which]
Fixed as per our call

2022-11-17 18:21 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsRepository.kt
> +    fun updateSimulatedReaderOption(selectedOption: UpdateOptions) {
Thank you, fixed it

2022-11-17 18:24 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +            isEnabled = true,
I will address it in a different PR. There's another glitch about enabling/disabling the simulated reader I would need to check.

2022-11-18 07:47 UTC, rossanafmenezes commented on WooCommerce/src/main/res/layout/developer_options_spinner_item.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
regarding our convo, changing the chainStyle to `spread inside ` fixed the issue with the icons, but the label is still centered and  for some reason adding a horizontal bias does nothing to it.

2022-11-18 08:23 UTC, malinajirka commented on WooCommerce/src/main/res/layout/developer_options_spinner_item.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Noice, using `spread inside` is an optimal solution, great job - the "horizontal bias" was an alternative for the "spread inside" not a solution for the middle view pushing the other views out of screen. 

The solution for that is setting `android:layout_width="0dp"` on `developerOptionsSpinnerListItemLabel` to ensure, it uses only the space given to it by the constraints. Good job setting everything else correctly!

<img width="222" alt="Screenshot 2022-11-18 at 9 21 51" src="https://user-images.githubusercontent.com/2261188/202655021-b48faf93-9774-47aa-bcbe-b587062a4e8b.png">

2022-11-18 08:25 UTC, malinajirka commented on WooCommerce/src/main/res/layout/developer_options_spinner_item.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Here is more info about the 0dp dimention - https://developer.android.com/reference/androidx/constraintlayout/widget/ConstraintLayout#DimensionConstraints

2022-11-18 08:28 UTC, rossanafmenezes commented on WooCommerce/src/main/res/layout/developer_options_spinner_item.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
🤦‍♀️ Of course!! Thank you! Changed and pushed

2022-11-18 09:41 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +            .setTitle("Update Simulated Reader")
It's minor, but this doesn't seem to be done. 

P.S. I usually prefer to share a commit in which it was done so the reviewer can easily open the commit from the inline comment to check how it was solved. If you share the commit hash, GitHub automatically adds a hyperlink to it. Example https://github.com/woocommerce/woocommerce-android/pull/6292#discussion_r854744809

2022-11-18 09:45 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +                selectedValue = values[which]
Just for the history purposes: We decided to keep the original approach - it's an optimization to store the value into a persistance storage only after the user dismisses the dialog so we don't store it every time they change their selection. It's a very minor optimization since we are using shared prefs (almost zero overhead), having said that, the view layer shouldn't know about the solution/storage and if we were sending a request to the server, the optimization would make some sense.

2022-11-18 10:02 UTC, malinajirka approved these changes
All the changes LGTM, thank you!

2022-11-18 10:43 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsFragment.kt
> +            .setTitle("Update Simulated Reader")
As per slack convo, the title has been removed ([68935f1](https://github.com/woocommerce/woocommerce-android/pull/7735/commits/68935f1426805c3f6ba66cd9624dbdf3d1829ef7) )

"P.S. I usually prefer to share a commit in which it was done so the reviewer can easily open the commit from the inline comment to check how it was solved. If you share the commit hash, GitHub automatically adds a hyperlink to it.""

Thank you, I will do that from now on.

2022-11-18 10:49 UTC, merged