[Simplified Login] experiment for Jetpack Installation
woocommerce/woocommerce-android pull request #7774
Opened 2022-11-09 17:41 UTC by hichamboushaba

Closes: #

### Description

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-11-10 12:53 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/ExperimentTracker.kt
> +        const val JETPACK_INSTALLATION_ELIGIBLE_EVENT = "wcandroid_jetpack_installation_eligible"
Since we share the same Firebase project between multiple apps, I decided to prefix the events that are specific to us with `wcandroid_`, this should help with the cleaning up after we finish with the experiments.

2022-11-12 09:58 UTC, hafizrahman requested changes

2022-11-12 09:58 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/config/FirebaseRemoteConfigRepository.kt
> +            JetpackInstallationVariant.valueOf(defaultValues[JETPACK_INSTALLATION_VARIANT_KEY]!!)
I think the value needs to be added in `defaultValues` here?

2022-11-14 08:28 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/config/FirebaseRemoteConfigRepository.kt
> +            JetpackInstallationVariant.valueOf(defaultValues[JETPACK_INSTALLATION_VARIANT_KEY]!!)
Nice catch, I added it in 21d7e9f.

2022-11-14 11:29 UTC, hafizrahman approved these changes
Thanks for updating the value, this looks good to go now.

2022-11-14 11:29 UTC, merged