Generate all variations complete flow
woocommerce/woocommerce-android pull request #7893
Opened 2022-11-18 08:44 UTC by wzieba

Closes: #7877

### Description

This PR is an early draft for #7877 - the complete flow of Generate all variations feature. To run it, one needs to substitute FluxC dependency with local build pointing to https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2569

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-11-22 16:06 UTC, wzieba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListViewModel.kt
> +    private val remoteProductId = navArgs.remoteProductId
Little refactor so we won't have to worry about mutability of `remoteProductId`

2022-11-22 16:06 UTC, wzieba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListViewModel.kt
> +                if (variationsInDb.isEmpty()) {
As `VariationRepository` returns `List<ProductVariation>` here, there was no point to check if the list is `null`. We only used that in tests (tests were mocking impossible scenarios).

2022-11-22 16:06 UTC, wzieba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListViewModel.kt
> +    sealed class ShowGenerateVariationsError : Event() {
I only added `s` here :)

2022-11-22 16:06 UTC, wzieba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/domain/GenerateVariationCandidates.kt
> +            get() = listOf(emptyList<VariationCandidate>())
I want to keep `GenerateVariationCandidates` stateless and emphasize that. I've extracted this value to a backing field getter to increase readability.

2022-11-22 19:04 UTC, atorresveiga commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationRepository.kt
> +                        )
Here we can use the `asSourceModel()` from `VariantOption`
```suggestion
                        variantOption.asSourceModel()
```

2022-11-22 19:08 UTC, atorresveiga commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/domain/GenerateVariationCandidates.kt
> +        return if (variationCandidates == initialAccumulator) {
Nice!

2022-11-22 19:21 UTC, atorresveiga commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/VariationListViewModelTest.kt
> +            (0..GenerateVariationCandidates.VARIATION_CREATION_LIMIT).map {
np: Nothing that needs to be changed, but here we can use the `List` class constructor to achieve the same result:
```
List(GenerateVariationCandidates.VARIATION_CREATION_LIMIT) { 
         listOf(VariantOption(1, "Size", "S"))
}
```

2022-11-22 20:01 UTC, atorresveiga approved these changes
Great work @wzieba! The code looks good and everything is working as expected. I just left one little comment about using the `asSourceModel()` function, and a np that you can feel free to ignore. Both are minor changes, so I'm approving this PR.
LGTM! :shipit:

2022-11-23 01:45 UTC, atorresveiga requested changes
Making a second round of tests, after my initial review, I found one issue.

When a product has all variations generated. If I press generate all variations again, the app will fail with a network error (I believe we can improve this notice), but the most important is that we are sending an empty request and we should not.

https://user-images.githubusercontent.com/18119390/203453911-78fb3a36-f3e9-4d93-8999-8f3f861ec9a3.mp4

<img width="532" alt="Screen Shot 2022-11-22 at 22 29 16" src="https://user-images.githubusercontent.com/18119390/203453989-90ede4e2-d7c3-497c-acf8-fbd237cbbcc3.png">

Do you think we should tackle this as part of this PR. I mean improving the notice. We can work on a different PR on FluxC throwing and exception when the list is empty.

2022-11-23 09:55 UTC, wzieba commented
I think we can work on this in a different PR, I've already created an issue for that: https://github.com/woocommerce/woocommerce-android/issues/7919

Adding a fix FluxC would also be a good idea!

2022-11-23 10:06 UTC, wzieba commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/VariationListViewModelTest.kt
> +            (0..GenerateVariationCandidates.VARIATION_CREATION_LIMIT).map {
Thanks, TIL!

2022-11-23 10:49 UTC, atorresveiga approved these changes
Great work @wzieba! I think that we are in a good place to merge these changes.
LGTM! :shipit:

2022-11-23 10:49 UTC, merged