Feature/check iap eligibility
woocommerce/woocommerce-android pull request #7924
Opened 2022-11-23 11:11 UTC by JorgeMucientes

Closes: #

### Description

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-12-21 12:46 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/di/InAppPurchasesModule.kt
> +import com.woocommerce.android.iapshowcase.IAPDebugLogWrapper
`iapshowcase` package is available only in debug, so you can not use it in production code. Probably you need to have your own log wrapper and IAPShowcaseMobilePayAPIProvider

2022-12-21 12:48 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/iapeligibility/CheckIapEligibilityFragment.kt
> +                is MultiLiveEvent.Event.ShowDialog -> event.showDialog()
np: would be good to hide `CircularProgressIndicator` when the dialog is shown. Now it is visible behind the dialog and might be a little bit confusing for a user

2022-12-21 12:50 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/iapeligibility/IapEligibilityViewModel.kt
> +class IapEligibilityViewModel @Inject constructor(
Maybe a unit test on this class?

2022-12-21 13:00 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/iapeligibility/IapEligibilityViewModel.kt
> +            triggerEvent(NavigateToNextStep)
Shell we go to the web here?

2022-12-21 13:01 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/iapeligibility/IapEligibilityViewModel.kt
> +        object NavigateToNextStep : IapEligibilityEvent()
np: maybe call it `NavigateToNativeStep` to be more explicit?

2022-12-21 15:45 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
> +        const val KEY_IAP_ELIGIBLE = "isEligible"
Just noticed in the logs:

```
2022-12-21 18:02:40.625 20529-20529 NosaraEvent             com.woocommerce.android              W  Properties should have lowercase name: isEligible
2022-12-21 18:02:40.626 20529-20529 NosaraEvent             com.woocommerce.android              E  Cannot add the property: isEligible to the event. Property name must match: ^[a-z_][a-z0-9_]*$
```

2022-12-22 08:55 UTC, kidinov requested changes
Overal looks good to me. I left some comments + CI should be fixed

2022-12-22 09:34 UTC, JorgeMucientes commented
Hey @kidinov thanks for the great feedback! I've addressed all the suggestions. If now I'll leave a comment explaining why not. 

Ready for another round :)

2022-12-22 09:34 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/iapeligibility/IapEligibilityViewModel.kt
> +) : ScopedViewModel(savedStateHandle) {
`planSupportChecker` will be passed as parameter of the ViewModel constructor in subsequent PR [here](https://github.com/woocommerce/woocommerce-android/pull/8053/files#diff-dfa5f27a6b0081652f06322fb8f3a2a56de2e3e3cc21cb6a83d24c56858f134e).

2022-12-22 09:34 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/di/InAppPurchasesModule.kt
> +@Module
Changes to this hilt module have been applied [here](https://github.com/woocommerce/woocommerce-android/pull/8053/files#diff-7c0f991eb187df783e5bb1441a22502f8b59a842d712c92e989bf961ddddcc56) to scope the IAP classes to the view model life cycle

2022-12-22 09:34 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/iapeligibility/IapEligibilityViewModel.kt
> +class IapEligibilityViewModel @Inject constructor(
Yes! I will add it in [this PR ](https://github.com/woocommerce/woocommerce-android/pull/8053) so I can have the latest changes from branch `feature/iap-payment-flow`

2022-12-22 09:41 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/iapeligibility/IapEligibilityViewModel.kt
> +            triggerEvent(NavigateToNextStep)
Not really. If IAP feature flag is disabled we keep using the native flow only that at the moment of purchasing/checking out the eCommerce plan, the user will be redirected to a "web view checkout flow", but 90% of the flow will still be native. 
That is also the reason why I called the event `NavigateToNextStep`. Because that is consistent with the naming of all the navigating event along the store creation native flow.

2022-12-22 09:42 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/iapeligibility/IapEligibilityViewModel.kt
> +        object NavigateToNextStep : IapEligibilityEvent()
As explained in the previous comment, the store creation web flow doesn't exist anymore, so the "next step" will always be native. I don't see any reason to be explicit about it. But good point 👍🏼

2022-12-23 11:33 UTC, kidinov approved these changes
LGTM to me!

2022-12-23 11:33 UTC, merged