Issue/7900 add update reader selected option logic
woocommerce/woocommerce-android pull request #7948
Opened 2022-11-25 07:06 UTC by rossanafmenezes

Closes: #

### Description

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-11-30 14:38 UTC, malinajirka requested changes
Thanks for working on this @rossanafmenezes! It looks good overall and works as expected - I've left some nitpicks, the only issue which I believe we must fix before we merge this PR is the one marked with 🚫 .

2022-11-30 14:38 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
> +    fun getReaderOptionsSelected() = AppPrefs.updateReaderOptionSelected
🔍 The order of the words feels a bit off and evokes to me that it's a boolean - we might want to consider renaming it to `selectedUpdateReaderOption`, wdyt?

2022-11-30 14:38 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt
> +    private fun mapper(updateFrequency: String): CardReaderManager.SimulatorUpdateFrequency {
⚠️ Is this method name intentional? If it is, it feels off as there isn't any verb and it is not a callback method starting with `on` or similar. Wdyt?

2022-11-30 14:38 UTC, malinajirka commented on libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
> +    fun initialize(updateFrequency: SimulatorUpdateFrequency = SimulatorUpdateFrequency.RANDOM)
💡 
When a future developer invokes `initialize` from a new place, they might not realize they need to load the current value from shared preferences and they might not pass any argument into this method and we'd wrongly default to `random` even when a value already exists in shared prefs.

I think it might be better not to provide any default value in order to force the client to pass what they want. 

Wdyt?

2022-11-30 14:38 UTC, malinajirka commented on libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/wrappers/TerminalWrapper.kt
> +        return SimulateReaderUpdate.valueOf(updateFrequency.name)
⚠️  Is this method name intentional? If it is, it feels off as there isn't any verb and it is not a callback method starting with on or similar. Wdyt?

🚫 The current implementation relies on the names provided by a 3rd party (Stripe). As soon as Stripe changes the names of these fields the app will stop working and we might not even realize it. I think we need to create a custom mapper in order to ensure it doesn't break.

This could work
```
return when(updateFrequency) {
            CardReaderManager.SimulatorUpdateFrequency.NONE -> SimulateReaderUpdate.NONE
            CardReaderManager.SimulatorUpdateFrequency.REQUIRED -> SimulateReaderUpdate.REQUIRED
            CardReaderManager.SimulatorUpdateFrequency.RANDOM -> SimulateReaderUpdate.RANDOM
        }
```
Btw if we renamed the options in `SimulatorUpdateFrequency` from `NEVER, ALWAYS, RANDOM` to `NONE, REQUIRED, RANDOM` just to make this mapping work, we might want to consider renaming them back.

2022-11-30 21:33 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt
> +    fun getReaderOptionsSelected() = AppPrefs.updateReaderOptionSelected
Thanks for pointing that out. Fixed here [5e7a8f4](https://github.com/woocommerce/woocommerce-android/pull/7948/commits/5e7a8f45c043129cb5909cf95869a28b676235ad)

2022-11-30 21:33 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt
> +    private fun mapper(updateFrequency: String): CardReaderManager.SimulatorUpdateFrequency {
Agreed. Modified it here [30c56bd](https://github.com/woocommerce/woocommerce-android/pull/7948/commits/30c56bd8d6c8704682589a5404d3cdd0d4c8adbd)

2022-11-30 21:36 UTC, rossanafmenezes commented on libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
> +    fun initialize(updateFrequency: SimulatorUpdateFrequency = SimulatorUpdateFrequency.RANDOM)
I think the initial idea was to have a default value when the app has a fresh install and there's nothing stored in the prefs. But in this case, the simulator will be disabled anyways, and once you initialize it it will get the default value from sharedPrefs, correct?

Removed it here [7126d3e](https://github.com/woocommerce/woocommerce-android/pull/7948/commits/7126d3ed229339d737c188d40e95b58abd13a60a)

2022-11-30 21:37 UTC, rossanafmenezes commented on libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/wrappers/TerminalWrapper.kt
> +        return SimulateReaderUpdate.valueOf(updateFrequency.name)
Renamed it and added custom mapper here [1398b96](https://github.com/woocommerce/woocommerce-android/pull/7948/commits/1398b9645141407d101126fb7bb9b2c52323f9dc)

Renamed the SimulatorUpdateFrequency options here [b40303f](https://github.com/woocommerce/woocommerce-android/pull/7948/commits/b40303f5bc6d231d415158bf39bbdf5836c73b59)

CIs are still running, hopefully, they will pass. If not, I will take a look again tomorrow. Thank you for the review @malinajirka

2022-12-01 09:36 UTC, rossanafmenezes commented on libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/wrappers/TerminalWrapper.kt
> +        return SimulateReaderUpdate.valueOf(updateFrequency.name)
Last change, rename the enum UpdateOptions back to Never, Always, Random [8674b5c](https://github.com/woocommerce/woocommerce-android/pull/7948/commits/8674b5c8c5487b950563fc845ef83856783bbae3) 

Thanks 🙏

2022-12-01 10:08 UTC, malinajirka commented on libs/cardreader/src/main/java/com/woocommerce/android/cardreader/CardReaderManager.kt
> +    fun initialize(updateFrequency: SimulatorUpdateFrequency = SimulatorUpdateFrequency.RANDOM)
Even when shared prefs are empty, [we return NEVER here](https://github.com/woocommerce/woocommerce-android/blob/79293227d234c39c4065dfdb4a1769aa5f1cd3d0/WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt#L218) so it never happens that shared prefs would return an empty value.

2022-12-01 11:02 UTC, malinajirka approved these changes
Thanks @rossanafmenezes! I think this is good to be merged even though I found one scenario in which the code doesn't work 👇. Feel free to merge it and fix it in a follow up PR or fix it here, up to you.

2022-12-01 11:02 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt
> +            cardReaderManager.initialize(mapUpdateOptions(appPrefs.selectedUpdateReaderOption()))
⚠️ I realized the current solution doesn't cover the following scenario:
1. Set frequency to "Always"
3. Go to Payments -> Manage card reader.
4. Start connecting to the reader.
5. Notice an update starts.
6. Cancel it or wait until it completes and disconnect from the reader.
1. Set frequency to "Never"
3. Go to Payments -> Manage card reader.
4. Start connecting to the reader.
5. Notice an update starts again (even though it's set to "never")

This is because, this line of code is run only once per lifetime of the app. We need to re-initialize the simulated card reader when the user changes the update frequency. We'll probably need to add a new method into `CardReaderManager` and invoke `terminal.setupSimulator(updateFrequency)` from it => we'll need to call this new method whenever the user changes the update frequency setting.

I'd suggest handling this in a follow up PR not here, as the current solution works for the basic usage and is an improvement for developers.

2022-12-01 11:14 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt
> +            cardReaderManager.initialize(mapUpdateOptions(appPrefs.selectedUpdateReaderOption()))
Thank you for pointing that out. I have created a new issue and will work on that next 
#7973

2022-12-01 11:15 UTC, merged