Upgrade Kotlin version to 1.7.20
woocommerce/woocommerce-android pull request #8091
Opened 2022-12-28 17:22 UTC by JorgeMucientes

Closes: #

### Description
This PR contains the following changes:
- Updates Kotlin [version to `1.7.20`](https://kotlinlang.org/docs/whatsnew1720.html). The reason why I didn't update it to the latest version `1.7.21` is because when using Compose BOM that [would force us](https://developer.android.com/jetpack/androidx/releases/compose-kotlin#pre-release_kotlin_compatibility) to use `1.4.0-alpha02 ` version of the Compose Compiler. I'd rather not use alphas in production code.
- Updates Compose dependencies to use [BOM](https://developer.android.com/jetpack/compose/setup#using-the-bom) 
- Fixes compile issues after dependency upgrades
- Migrates deprecated usage of `onBackPressed` that were preventing the project from compile. 

These changes should unblock several blocked PRs: 
- [PR](https://github.com/woocommerce/woocommerce-android/pull/7870)
- [PR](https://github.com/woocommerce/woocommerce-android/pull/6675)
- [PR](https://github.com/woocommerce/woocommerce-android/pull/7287) 
- Maybe more I'm missing?

- Provide the benefits of Compose BOM and enable the usages of Kotlin latest features.

### Testing instructions
Smoke test the app in general. 
Test on back pressed from all of the 3 dialogues where on back pressed implementation was updated. 

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-12-30 14:59 UTC, hichamboushaba requested changes
Great work @JorgeMucientes 👏, thanks for working on it.

There is only one change that broke the WCShip installation screen, check the comments, once its fixed, this will be good to go.

2022-12-30 14:59 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/shipping/InstallWCShippingFlow.kt
> +            val isShowingLoadingIndicator by remember { mutableStateOf(alpha == 0f) }
What was the reason for this change? This doesn't have the same behavior as `derivedStateOf`, as the state won't depend now on the value of `alpha`, which means `isShowingLoadingIndicator` will stay `false` for this case.
I tested the animation, and I confirmed it did break it 🙂.

2022-12-30 14:59 UTC, hichamboushaba commented on WooCommerce/build.gradle
> +    implementation platform('androidx.compose:compose-bom:2022.12.00')
np, wouldn't it be better to declare the BOM version in the root `build.gradle` next to `composeCompilerVersion`?

2022-12-30 15:02 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/shipping/InstallWCShippingFlow.kt
> +            val isShowingLoadingIndicator by remember { mutableStateOf(alpha == 0f) }
Notice the loading indicator in the below animations:

| Expected behavior | Behavior with the change |
| --- | --- |
| <video src="https://user-images.githubusercontent.com/1657201/210084105-b01d25c0-a5b6-448c-a1c3-49023ecc8835.mp4"/> | <video src="https://user-images.githubusercontent.com/1657201/210084076-d3f8bd73-9897-4104-9738-297149976f92.mp4"/> |

2022-12-30 19:07 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/shipping/InstallWCShippingFlow.kt
> +            val isShowingLoadingIndicator by remember { mutableStateOf(alpha == 0f) }
Hey @hichamboushaba good catch! The reason for the change was this lint warning: 

![Screenshot 2022-12-30 at 19 39 08](https://user-images.githubusercontent.com/2663464/210103901-a0893244-b96a-4343-b2df-ec021935ad74.png)

The problem is: I accidentally replaced `derivedStateOf` with `mutableStateOf`. Shame on me. Sorry about that. I've reverted to use `derivedStateOf` but using `remember`. That will prevent unnecessary recompositions (if I understood correctly) of `InstallationLoadingIndicator` function, until `alpha` value is 0. 
I tested the animation and it now works as expected.

2022-12-30 19:09 UTC, JorgeMucientes commented
I'll be AFK the next week, so if nothing else blocking arises from my latest changes please feel free to merge, once at least 2 reviewers have smoke tested the app 🙏🏼

2023-01-02 10:28 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/shipping/InstallWCShippingFlow.kt
> +            val isShowingLoadingIndicator by remember { mutableStateOf(alpha == 0f) }
Thanks for the clarification @JorgeMucientes, TIL, I'm wondering why the error wasn't shown for me in AS 😕?

2023-01-02 10:29 UTC, hichamboushaba approved these changes
Nice job @JorgeMucientes 🥇 

I'll leave the PR unmerged until we get a second review.

2023-01-03 06:30 UTC, kidinov approved these changes
Looks and tests well. Thank you!

2023-01-03 06:30 UTC, merged