[REST API] Hide "Switch Store" Option
woocommerce/woocommerce-android pull request #8203
Opened 2023-01-17 12:10 UTC by hafizrahman

Part of: #8107

### Description

Switch Store functionality is not supported on application passwords login, so we're removing it in this case.

### Testing instructions

1. login using a self-hosted site credentials,
2. go to More menu,
3. make sure "Switch Store" option at the top, under site address, is not shown.

2023-01-17 14:49 UTC, hichamboushaba requested changes
Nice work on the hiding part Hafiz, but we need to disable the click event too, currently the whole header is clickable and opens the store switching which doesn't work.

A quick fix would be to set `enabled` of the `clickable` modifier to match the value of `showStoreSwitcher`.

2023-01-17 23:05 UTC, hafizrahman commented
> Nice work on the hiding part Hafiz, but we need to disable the click event too, currently the whole header is clickable and opens the store switching which doesn't work.
> 
> A quick fix would be to set `enabled` of the `clickable` modifier to match the value of `showStoreSwitcher`.

Oh right, I missed this. Thanks!

2023-01-18 09:25 UTC, hichamboushaba approved these changes
Nice job, works well.

Suggestion: WDYT about adding a test case for this scenario in `MoreMenuViewModelTests`?

2023-01-19 13:03 UTC, hafizrahman commented
@hichamboushaba  not urgent but I wonder if you know why the "unnecessary Mockito stubbing" error shows up, although the test that I added passes.

My feeling is that this is because in this code in `SiteConnectionType`:

```
val SiteModel.connectionType
    get() = when {
        origin != SiteModel.ORIGIN_WPCOM_REST -> SiteConnectionType.ApplicationPasswords
        isJetpackConnected -> SiteConnectionType.Jetpack
        isJetpackCPConnected -> SiteConnectionType.JetpackConnectionPackage
```

`origin != SiteModel.ORIGIN_WPCOM_REST` always return true in the mocked SiteModel, thus the stubbing is deemed unnecesary. But I thought adding the stubbing is needed to make the "given" case more explicit.

2023-01-19 13:45 UTC, hichamboushaba commented
> @hichamboushaba not urgent but I wonder if you know why the "unnecessary Mockito stubbing" error shows up, although the test that I added passes.

This is because because there are two properties `connectionType`:
1. The `SiteModel` extension one.
2. The `SelectedSite` instance property.

The one you mocked is the `SelectedSite` property, while in `MoreMenuViewModel` we use the `SiteModel` extension, so the mock is not used.
You can confirm this by updating the code in the mock to return `Jetpack` instead of `ApplicationPasswords`, and you'll see that it's still green.

A proper fix would be to make sure we are updating the site's `origin` directly, we can do so with something like the following patch:
```patch
Index: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt b/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt
--- a/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt	(revision da4113e9790a2cc5b471cc8909d3ecdaccfd8a1a)
+++ b/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt	(date 1674135607565)
@@ -11,7 +11,9 @@
 import com.woocommerce.android.viewmodel.BaseUnitTest
 import kotlinx.coroutines.ExperimentalCoroutinesApi
 import kotlinx.coroutines.flow.MutableSharedFlow
+import kotlinx.coroutines.flow.MutableStateFlow
 import kotlinx.coroutines.flow.flowOf
+import kotlinx.coroutines.flow.update
 import org.assertj.core.api.Assertions.assertThat
 import org.junit.Test
 import org.mockito.kotlin.doReturn
@@ -26,13 +28,14 @@
     private val unseenReviewsCountHandler: UnseenReviewsCountHandler = mock {
         on { observeUnseenCount() } doReturn flowOf(0)
     }
-    private val selectedSite: SelectedSite = mock {
-        on { observe() } doReturn flowOf(
-            SiteModel().apply {
-                displayName = "Site"
-                url = "url"
-            }
-        )
+    private val selectedSiteFlow = MutableStateFlow(
+        SiteModel().apply {
+            displayName = "Site"
+            url = "url"
+        }
+    )
+    private val selectedSite: SelectedSite = mock {
+        on { observe() } doReturn selectedSiteFlow
     }
     private val moreMenuRepository: MoreMenuRepository = mock {
         onBlocking { isInboxEnabled() } doReturn true
@@ -48,7 +51,7 @@
 
     private lateinit var viewModel: MoreMenuViewModel
 
-    suspend fun setup(setupMocks: suspend () -> Unit) {
+    suspend fun setup(setupMocks: suspend () -> Unit = {}) {
         setupMocks()
         viewModel = MoreMenuViewModel(
             savedState = SavedStateHandle(),
@@ -122,11 +125,8 @@
     fun `given application passwords login, when building state, then store switcher state is disabled `() =
         testBlocking {
             // GIVEN
-            setup {
-                whenever(selectedSite.connectionType).thenReturn(
-                    SiteConnectionType.ApplicationPasswords
-                )
-            }
+            selectedSiteFlow.update { it.apply { origin = SiteModel.ORIGIN_XMLRPC } }
+            setup()
 
             // WHEN
             val states = viewModel.moreMenuViewState.captureValues()
```

And to make sure we cover all cases, I would suggest testing the other scenario: I mean showing the button for Jetpack sites, this would allow confirming we are actually testing the code, and it's not succeeding because of another side effect.

2023-01-20 07:50 UTC, hafizrahman commented
@hichamboushaba  Thanks for your suggestion!

I added a couple of unit tests for Jetpack and Jetpack CP cases, let me know what you think.

2023-01-20 08:32 UTC, hichamboushaba commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt
> +            selectedSiteFlow.value.setIsJetpackConnected(true)
Can you move this statement inside the `apply` block above to make it clear it's done in order to update the site returned from the `Flow`?

```kotlin
                it.apply {
                    origin = SiteModel.ORIGIN_WPCOM_REST
                    setIsJetpackConnected(true)
                }
```

The way you did it works because `SiteModel` is a mutable class, but if we were to update it to an immutable `data class`, we would need to replace the `update` with `copy`, and then the `flow.value.mutate` logic wouldn't be very clear.

2023-01-20 08:32 UTC, hichamboushaba commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt
> +            selectedSiteFlow.value.setIsJetpackCPConnected(true)
Same as above 🙂

2023-01-21 07:30 UTC, hafizrahman commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModelTests.kt
> +            selectedSiteFlow.value.setIsJetpackConnected(true)
Aha, got it, thanks!

2023-01-22 01:37 UTC, merged