Add option to simulate interac payment to the Simulated Card Reader
woocommerce/woocommerce-android pull request #8241
Opened 2023-01-23 17:47 UTC by rossanafmenezes

Closes: No issue was  created for this PR

### Description

It adds a new row based on the cardReaderConfig to enable testing using the Card Reader Simulator and Interac Payments. If the Store country is Canada, the new row will be displayed once you enable the simulated card reader from the developer options screen. If the store is not based in Canada, the option is not displayed. 

### Testing instructions

1. Access a Canadian Stor
2. go to the Menu
3. Click on Developer Options
4. Enable the Simulated Card Reader
5. Make sure the Interac row is displayed
6. Enabled Interac Payments
7. create an order or a simple payment
8. complete the payment using Wisepad3 reader
9. Make sure the payment was done using Interac either by checking the logs or by checking Stripe Dashboard if you have access to that
10. Go back to the Dev Options screen and disable Interac payments
11. Create a new payment
12. Make sure the payment used Card and not interac in the logs or Stripe Dashboard
13. Finally, switch to an US store 
14. go to the dev option screen
15. Make sure the Interac row is not displayed

### Images/gif

US vs CA (splitting the videos so it does not get gigantic)

 <img src="https://user-images.githubusercontent.com/30724184/214105665-79a8d84f-8067-41f5-abe0-b5ed4ae2c9f6.gif" width="350"/> 

Interac Payment

 <img src="https://user-images.githubusercontent.com/30724184/214111891-64fe530c-2fee-408b-9f66-df48a06ab748.mp4" width="350"/> 

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-01-24 07:18 UTC, malinajirka requested changes
Thank you for proactively adding this improvement into the app! 🥇 

I'm still looking into the issue with the tests, but the failures don't seem related to your changes. I've left one comment which I believe we'll need to address to ensure expected and predictable behavior. Let me know what you think :).

2023-01-24 07:18 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +                if (countryConfig is CardReaderConfigForCanada) {
🔍 This potential issue was here even before this PR, however, it's more visible now. It seems rows 42-46 and 95-99 are identical. If someone modifies the logic they might not realize they need to modify it in two places -> they might introduce a bug. It might be safer to move these rows into a method and call that method from both places. Wdyt?

2023-01-24 07:18 UTC, malinajirka commented on libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
> +    override fun enableSimulatorInterac() {
⚠️ I'm wondering if this will play nicely with the `initializeOnUpdateFrequencyChange`. It seems both methods re-initialize the simulator from scratch. I haven't tested it, but I'm wondering if they'll clear the setting of each other - example:

1. User invokes initializeOnUpdateFrequencyChange with ALWAYS => simulator is created with frequency ALWAYS.
2. User invoked enableSimulatorInterac -> it creates a brand new instance of the simulator without providing the updateFrequency attribute => I think the default frequency will be used in such case. Wdyt?
3. User invokes initializeOnUpdateFrequencyChange with ALWAYS => simulator is created with frequency ALWAYS but the card type is not provided => I think the default card type will be used in such case. Wdyt?

I think we'll need to set both attributes within one method and provide both attributes in `initialize(..)` method. Wdyt?

2023-01-24 09:11 UTC, malinajirka commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="enable_interac_key">Enbale Interac Key</string>
Typo `Enbale` instead of `Enable`

2023-01-24 12:28 UTC, rossanafmenezes commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="enable_interac_key">Enbale Interac Key</string>
Thank you. Fixed here [15e6eff](https://github.com/woocommerce/woocommerce-android/pull/8241/commits/15e6eff33b3f5f806e548d802944cbd13376d1f5)

2023-01-24 12:53 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +                if (countryConfig is CardReaderConfigForCanada) {
Absolutely. Fixed here: [da43b12](https://github.com/woocommerce/woocommerce-android/pull/8241/commits/da43b12e691f569ff388ae53e0e54c6ec38c58a8)

2023-01-24 13:59 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +    private fun showInteracRowForCanadianStore(): List<ListItem> {
💡 This seems to do more than just `showInteracRow` -> it adds even the other options. Moreover, it technically doesn't show anything since it only returns a list.

Perhaps, we could call it something like `getListItemsWhenSimulatedReaderEnabled` and we could rename `createDeveloperOptionsList` to `getListItemsWhenHardwareReaderEnabled`.  Doesn't need to be exactly this name, but something in that sense, wdyt?

2023-01-24 16:14 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +    private fun showInteracRowForCanadianStore(): List<ListItem> {
Rename here [0e27e24](https://github.com/woocommerce/woocommerce-android/pull/8241/commits/0e27e24ab2c51da87316008255a5982c12c29b93)

2023-01-27 14:39 UTC, rossanafmenezes commented on libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/CardReaderManagerImpl.kt
> +    override fun enableSimulatorInterac() {
Fixed here [66436da](https://github.com/woocommerce/woocommerce-android/pull/8241/commits/66436daa30af9ebbebda7c6551f3c2383e5fb2fd)

2023-01-30 09:08 UTC, malinajirka approved these changes
Thanks @rossanafmenezes! The changes look good to me overall - I've left one comment which we should discuss before merging, but other than that this is ready for merge.

2023-01-30 09:08 UTC, malinajirka commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="enable_interac_key">Enable Interac Key</string>
🔍 Nitpick: We might want to add "translatable=false" attribute to this key so it isn't uploaded to glotpress. Wdyt?

2023-01-30 09:08 UTC, malinajirka commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsTest.kt
>  class DeveloperOptionsTest : BaseUnitTest() {
🔍 Not related to this PR, but seems like this test has a bit misleading name -> we might want to rename this file and class to `DeveloperOptionsViewModelTest` wdyt?

2023-01-30 09:08 UTC, malinajirka commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +    private fun getListItemsForSimulatedReader(): List<ListItem> {
Sorry, I didn't realize what the current state was when we discussed this last week. I think we have two options:

1. Display the interac row for all stores - as we discussed, there is technically nothing wrong on testing interac payments in the US -> they'll fail, but it's a real world scenario.
2. Do not display interac row for US stores -> but in such case, we'd need to ensure that interac is set to false when the user switches to a US store and that the simulated reader gets reinitialized. This might be quite tricky, so I'd personally opt for option 1.

Wdyt?

2023-01-30 11:09 UTC, rossanafmenezes commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="enable_interac_key">Enable Interac Key</string>
Thank you. Add here [616ae99](https://github.com/woocommerce/woocommerce-android/pull/8241/commits/616ae9993c55ff152f33b4b318a5970c02d0c81e)

2023-01-30 11:17 UTC, rossanafmenezes commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsTest.kt
>  class DeveloperOptionsTest : BaseUnitTest() {
Renamed it here [1634d5c](https://github.com/woocommerce/woocommerce-android/pull/8241/commits/1634d5c455bb4f428a96949885fd82017571a870)

2023-01-30 11:23 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +    private fun getListItemsForSimulatedReader(): List<ListItem> {
Sure. I will remove the country config condition

2023-01-30 12:27 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/DeveloperOptionsViewModel.kt
> +    private fun getListItemsForSimulatedReader(): List<ListItem> {
Removed here [42ddbf7](https://github.com/woocommerce/woocommerce-android/pull/8241/commits/42ddbf7a6a2f752f82fd4c631aacbf376b6b05fa)

2023-01-30 12:32 UTC, malinajirka commented
LGTM, thanks! 🙇

2023-01-30 12:32 UTC, merged