Hackweek: Fix toolbar color
woocommerce/woocommerce-android pull request #8483
Opened 2023-03-06 10:19 UTC by kidinov

### Description

As discussed here p1677743676493199-slack-C6H8C3G23 we want to bring consistency across toolbar colors on different screens in the dark mode. Currently, on compose screens toolbar color is `woo_black_90`, while on XML screen it's `woo_black_900`. On Figma we have `woo_black_90` with an overlay which is added if the toolbar has a shadow. This PR attempts to align with Figma approach

### Testing instructions

Start in both dark and light modes:
* Main
* Settings
* Support

screens and notice that there no visual changes

---

Start Chrome Tab, for instance, from the inbox screen - notice that toolbar is grayer now and matches other places

### Images/gif

<img width="483" alt="image" src="https://user-images.githubusercontent.com/4923871/223092738-08650270-495e-41e2-aa5d-a9bcde65ba98.png">

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-03-06 11:01 UTC, kidinov commented
@hichamboushaba I noticed that TabLayout has a different color depending on whether it's opened for the first time. That is not really part of this issue, but if you have an idea how to fix that, we could do it here as well



<img width="488" alt="image" src="https://user-images.githubusercontent.com/4923871/223092367-3b8cccd9-bfd9-4482-a675-c2a638981fd1.png">

<img width="490" alt="image" src="https://user-images.githubusercontent.com/4923871/223092477-001a95ad-d4af-4d3a-be2b-00d45d9b08ac.png">

2023-03-06 16:37 UTC, hichamboushaba commented on WooCommerce/src/main/res/values-night/colors_base.xml
> +    <color name="color_toolbar_without_overlay">@color/woo_black_900</color>
Thanks @kidinov for working on this.
This is not a review yet, but just a question, from the discussion we had in Slack and the PR's description, I thought we are going to update this to `woo_black_90` to match Figma, am I missing something?

2023-03-07 11:26 UTC, kidinov commented on WooCommerce/src/main/res/values-night/colors_base.xml
> +    <color name="color_toolbar_without_overlay">@color/woo_black_900</color>
@hichamboushaba the toolbar color is updated to `woo_black_90` that's right, but things like CollapsingToolbarLayout and toolbar in chrome tabs don't support automatic overlay in the dark mode when they have elevation >0, unless I am missing something

2023-03-07 11:32 UTC, hichamboushaba commented on WooCommerce/src/main/res/values-night/colors_base.xml
> +    <color name="color_toolbar_without_overlay">@color/woo_black_900</color>
Oh, I see, as I didn't review the whole PR, I missed the fact that you removed the overridden background for the Toolbar style, which means it will now be using `color_surface` which is `woo_black_90`, nice 💯 .

I'll try to review the rest of the PR this afternoon, but in the meantime, what do you think about adding a comment for this color value? The name `color_toolbar_without_overlay` is not very clear by itself, at least for me.

2023-03-08 05:51 UTC, kidinov commented on WooCommerce/src/main/res/values-night/colors_base.xml
> +    <color name="color_toolbar_without_overlay">@color/woo_black_900</color>
> The name color_toolbar_without_overlay is not very clear by itself, at least for me.

That's a good point. I had no clue that MaterialToolbar works this way till next week and it's indeed maybe very confusing 

a71e6dcb65678d50d32db96a28e041b9cb7413cd

2023-03-08 08:42 UTC, hichamboushaba requested changes
Really nice work @kidinov, but sadly I found one weird glitch, it doesn't happen generally when app is launched directly to the correct theme, but if you change the theme while a top-level fragment is shown, sometimes the colors gets mixed up:

https://user-images.githubusercontent.com/1657201/223661479-8dd5705f-eec8-4ae6-8947-ee478ab20347.mp4

I tried to timebox a half an hour to investigate this a little (I wanted to move back to my Hack Week project 🙂), but I couldn't understand why it happens. From my short investigation I gathered the following:
1. AppBarLayout is the one which should be [responsible](https://github.com/material-components/material-components-android/blob/948d5dac03a55971338d36bb52f1f49bd448ebd7/lib/java/com/google/android/material/appbar/MaterialToolbar.java#L53-L58) for applying the correct overlay, so we normally we shouldn't need to set the color `color_toolbar_without_overlay` to the CollapsingToolbarLayout.
But there is another issue with this, the AppBarLayout will be ["lifted"](https://github.com/material-components/material-components-android/blob/948d5dac03a55971338d36bb52f1f49bd448ebd7/lib/java/com/google/android/material/appbar/AppBarLayout.java#L924) when scrolled, and this sets different elevations depending on whether it's expanding, I tried playing with the different variables, but I couldn't find a solution that allows keeping the overlay set for all states.
2. Our TopLevel Fragments (except the MyStoreFragment) don't have a shadow, and yet they need the background overlay.

Sorry I couldn't be of more help, if you have time to investigate this further, it would be awesome.
Otherwise, we can still re-think the strategy, if we can't get the official dark overlay color to work as expected, maybe we can go back to using `woo_black_900` even if it's still different than Figma, and update the color in the Login fragments 🤔.

2023-03-09 06:09 UTC, kidinov commented
@hichamboushaba 

Looks like this happens only when you change the theme without "stopping" the activity (via notification bar). Probably just a bug in the implementation

I tried to update the library - that's not fixed

Spending time on this probably not the most effective way so I just reverted all the changes except the one that changes color of toolbar on chrome tabs

2023-03-09 07:44 UTC, hichamboushaba approved these changes
Thanks @kidinov for working on this, hopefully we can figure out what's the cause in the future.

> Looks like this happens only when you change the theme without "stopping" the activity (via notification bar). Probably just a bug in the implementation

I had it happen on the first launch also, but it didn't happen all the time, changing the theme was the way to reproduce it consistently.

2023-03-09 07:45 UTC, merged