Store creation: Fix site preview
woocommerce/woocommerce-android pull request #8536
Opened 2023-03-10 19:51 UTC by 0nko

This PR fixes the new store preview, which got "broken" by making the sites private by default after creation. Now the WebView must be authenticated before a preview can be shown.

**To test:**
1. Log in and navigate to the store picker
2. Tap on Add new site button and go through the flow (make sure you have free credits to complete this)
3. After a store is created and the preview screen is displayed, notice that the preview is rendered (takes pretty long)

2023-03-14 13:53 UTC, hichamboushaba requested changes
Nice work @0nko, but I faced an issue, check the comments.

2023-03-14 13:53 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/InstallationScreen.kt
> +private fun PreviewWebView(
Suggestion: can't we reuse the Composable `WebView` that we already have for this?

I understand we want a custom loading indicator, but maybe we can think of having two versions of the `WebView` to support the different needs:
1. One basic one that doesn't add any loading indicator by itself, and instead it accepts an `onProgressChanged` callback.
2. A second one that uses the first one, and that it adds the loading indicator by itself, while using the `onProgressChanged` callback.

This is outside of the scope of the current PR, and it's OK to skip it for now 🙂.

2023-03-14 13:53 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/InstallationViewModel.kt
> +        if (url.contains(newStoreWpAdminUrl)) {
In my test, this check didn't succeed, and it's because `newStore.data.domain` was pointing to the site using a subdomain of `wordpress.com`, while the created site and after being upgraded to atomic redirects to a subdomain of `wpcomstaging.com`, I think you can improve the condition to account for this case.

2023-03-15 12:26 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/InstallationScreen.kt
> +private fun PreviewWebView(
Previously, there `WebView` did not have authentication and it was much simpler so it made sense to just create a new one. Now it makes more sense, thanks for suggesting it 👍.

2023-03-15 12:27 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/InstallationViewModel.kt
> +        if (url.contains(newStoreWpAdminUrl)) {
Nice catch, I'll fix it. Thanks!

2023-03-16 12:55 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/InstallationViewModel.kt
> +        if (url.contains(newStoreWpAdminUrl)) {
Fixed in https://github.com/woocommerce/woocommerce-android/pull/8536/commits/36d93399651e724985621e9c753aff8d20479741.

2023-03-16 12:56 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/installation/InstallationScreen.kt
> +private fun PreviewWebView(
I've refactored the WebView component in https://github.com/woocommerce/woocommerce-android/pull/8536/commits/c109fdb0f958dd0f6fd3782340331409aa50600c. Let me know what you think.

2023-03-20 11:15 UTC, hichamboushaba commented
@0nko should we merge https://github.com/woocommerce/woocommerce-android/pull/8582 before re-testing this PR? since we removed the authentication from the WebView now.

2023-03-20 12:29 UTC, hichamboushaba requested changes
Sorry @0nko, the last commit broke the preview, we show the preview of the previously selected site instead of the created one.
I think we read the value from the `selectedSite` before updating it, and this triggers saving the `lazy` values `newStoreUrl` and `newStoreWpAdminUrl`.

2023-03-20 14:26 UTC, 0nko commented
Oops, sorry about that @hichamboushaba! I forgot to set the initial view state to `InitialState` from `SuccessState` (which I used for testing to avoid creating new sites).

2023-03-20 14:27 UTC, 0nko commented
> @0nko should we merge https://github.com/woocommerce/woocommerce-android/pull/8582 before re-testing this PR? since we removed the authentication from the WebView now.

Sure, you can merge that one first.

2023-03-20 17:17 UTC, hichamboushaba approved these changes
Works as expected, thanks @0nko, nice work :shipit:

2023-03-20 17:18 UTC, merged