Feature/8635 onboarding tracking
woocommerce/woocommerce-android pull request #8639
Opened 2023-03-23 17:56 UTC by JorgeMucientes

Part of #8635

### Description

Tracking for Onboarding list interactions. 

![Screenshot 2023-03-23 at 14 41 59](https://user-images.githubusercontent.com/2663464/227222229-5aa80db8-9cd6-40b9-887b-8fd5578c7153.png)

This PR doesn't include the tracking for this as it is not simple to handle this, I'm still trying to figure out how to properly deal with it. So I don't want to block the rest of the tracking because of it: 

![Screenshot 2023-03-23 at 18 56 12](https://user-images.githubusercontent.com/2663464/227301999-46f17d26-b0a7-4365-ba65-7c43be49dfe8.png)

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-03-23 21:16 UTC, 0nko requested changes
I left one comment that needs to be addressed.

2023-03-23 21:16 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingViewModel.kt
> +            analyticsTrackerWrapper.track(stat = STORE_ONBOARDING_COMPLETED)
This may get triggered multiple times (whenever My store screen is refreshed using PTR, for example), which is probably not something we want.

2023-03-24 00:14 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/StoreOnboardingViewModel.kt
> +            analyticsTrackerWrapper.track(stat = STORE_ONBOARDING_COMPLETED)
Good point! 👍🏼 

I ended up moving that tracking to the repository to ensure it's only tracked once, right when we save that all tasks are completed.

2023-03-24 08:23 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
> +                        AnalyticsTracker.track(stat = AnalyticsEvent.STORE_ONBOARDING_SHOWN)
I just noticed that this event is missing the `is_wpcom_store` property.

2023-03-24 08:59 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
> +                        AnalyticsTracker.track(stat = AnalyticsEvent.STORE_ONBOARDING_SHOWN)
Hey @0nko  good point. Afaik `is_wpcom_store`  is tracked automatically for all events. It is added to the tracking client inside `private track()` function itself: 
`        tracksClient?.track(EVENTS_PREFIX + eventName, propertiesJson, user, userType)
`

2023-03-24 09:22 UTC, 0nko commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
> +                        AnalyticsTracker.track(stat = AnalyticsEvent.STORE_ONBOARDING_SHOWN)
Oh ok, I didn't realize that since it's explicitly mentioned in the description. 👍

2023-03-24 09:23 UTC, 0nko approved these changes
LGTM 👍

2023-03-24 09:23 UTC, merged