Use Annotate Tests Results to report test failures in Buildkite and Slack
woocommerce/woocommerce-android pull request #9189
Opened 2023-06-05 08:23 UTC by jostnes

### Description
This PR adds the `annotate_test_failures` utility to report test failures on Buildkite and Slack. On this project, it will introduce two new changes to the build which is the Buildkite Annotation on the Buildkite build itself and as a Slack notification. The Buildkite Annotation will be available for all builds, the Slack notification is only for failures on `trunk` and `release/*` branches.

This change is only for Instrumented tests and **not** Unit tests, as the unit tests in the project do not return a JUnit/XML report file for the utility to read from. 

Similar change on WCiOS in https://github.com/woocommerce/woocommerce-ios/pull/9853

### Testing instructions
Tested using this [draft PR](https://github.com/woocommerce/woocommerce-android/pull/9174)

### Images/gif

With this change, test failures and flaky tests will now be reported on the Buildkite build ([example build](https://buildkite.com/automattic/woocommerce-android/builds/12632)) and as a Slack message.

**Buildkite:**
<img width="1161" alt="image" src="https://github.com/woocommerce/woocommerce-android/assets/17252150/61a4b22d-d58d-4737-b18b-4dae97aebdff">

**Slack:**
<img width="682" alt="image" src="https://github.com/woocommerce/woocommerce-android/assets/17252150/3f62d779-aafd-4564-979b-7356c6619fab">

2023-06-05 16:00 UTC, jkmassel requested changes
This looks like a good start!

I see this in the build log:

> [2023-06-05T08:42:02Z] ⏩ No `--slack` channel name and/or `--slack-webhook` URL provided; skipping Slack notification.

You'll want to resolve this prior to landing the PR 🙂

I would expect to see a link to the Test Analyics run from the testing step – curious where that's at?

Lastly, you noted:

> This change is only for Instrumented tests and not Unit tests, as the unit tests in the project do not return a JUnit/XML report file for the utility to read from.

IMHO we should address that, because it'd be great to put the unit tests under analytics as well. Want to do that as part of this PR, or as a separate one?

2023-06-06 02:16 UTC, jostnes commented
> [2023-06-05T08:42:02Z] ⏩ No --slack channel name and/or --slack-webhook URL provided; skipping Slack notification.
> 
> You'll want to resolve this prior to landing the PR 🙂

Oops, I should have been clearer; that's intended on this PR because the branch name (`add-updated-annotate-test-failures` does not fulfill the `trunk` or `release/*` condition), a working test can be seen in [the testing PR build](https://buildkite.com/automattic/woocommerce-android/builds/12632#01888a3d-e97a-425f-afb6-600c3cefdb5e/332-765) where I updated the condition to this branch and this message is printed:
<img width="528" alt="image" src="https://github.com/woocommerce/woocommerce-android/assets/17252150/fb658435-cfef-4a8f-859b-49413d262fd9"> 

> I would expect to see a link to the Test Analytics run from the testing step – curious where that's at? 

Test Analytics hasn't been set up on the Android projects, _yet_. @mokagio helped with that for the iOS projects. Not sure how different the setup is for Android projects but we should have that available for Android projects too. I'll add that as a task to look into soon.

> IMHO we should address that, because it'd be great to put the unit tests under analytics as well. Want to do that as part of this PR, or as a separate one?

Yup I agree, the only reason it's not added is that the existing unit test step doesn't generate a report (the build artifacts are empty) whereas instrumented tests step already generates an XML that we can use. Will need to check with someone more familiar with the Android side of things to see if it's possible to generate a JUnit/XML report from the unit tests run, before we can update this to include unit tests. It'll be in a separate PR.

2023-06-06 15:57 UTC, oguzkocer commented
> Yup I agree, the only reason it's not added is that the existing unit test step doesn't generate a report (the build artifacts are empty) whereas instrumented tests step already generates an XML that we can use. Will need to check with someone more familiar with the Android side of things to see if it's possible to generate a JUnit/XML report from the unit tests run, before we can update this to include unit tests. It'll be in a separate PR.

I'll take a look at it this week - as soon as I wrap up the PR I am working on.

2023-06-07 03:45 UTC, jostnes commented
> I'll take a look at it this week - as soon as I wrap up the PR I am working on.

thanks @oguzkocer! FWIW i found that [reportDir](https://developer.android.com/reference/tools/gradle-api/7.0/com/android/build/api/dsl/TestOptions#reportdir) and [resultsDir](https://developer.android.com/reference/tools/gradle-api/7.0/com/android/build/api/dsl/TestOptions#resultsdir) values can be added to the test configuration. i wasn't successful in getting it to work though, so you taking a look would be great.

@jkmassel can you help take another look at this? or should we get unit tests to generate the report first and include unit test reporting as part of this PR too? this isn't urgent, so if that's preferred, i can leave this open for a while

2023-06-08 18:24 UTC, oguzkocer commented
@jostnes Please excuse my ignorance as I might be looking at something completely different, but I see the unit test xml reports in the `**/build/test-results/test{variant}DebugUnitTest/*.xml` files. For example;

* Run `./gradlew :libs:cardreader:test`
* Verify that the xml test reports are in `libs/cardreader/build/test-results/testDebugUnitTest/`
* Update the `libs/cardreader/src/test/java/com/woocommerce/android/cardreader/internal/payments/RefundErrorMapperTest.kt` (or any other test) so it results in a failure
* Run `./gradlew :libs:cardreader:test`
* Verify that the xml report contains the error in `libs/cardreader/build/test-results/testDebugUnitTest/TEST-com.woocommerce.android.cardreader.internal.payments.RefundErrorMapperTest.xml`

I've also tested this with:

* Run ` ./gradlew :WooCommerce:testVanillaDebug`
* Verify that the xml test reports are in `WooCommerce/build/test-results/testVanillaDebugUnitTest/`

Please let me know if this is what you're looking for, or if it's something different 😅

2023-06-09 02:05 UTC, jostnes commented
@oguzkocer thank you for looking! are those for local runs? i guess the question is when running in CI, where are those results files stored? looking at the build artifacts ([example](https://buildkite.com/automattic/woocommerce-android/builds/12634#01888aa8-071f-441a-a0a1-2246f23506b3)), if it's empty, the `annotate_test_failures` utility isn't able to read the file as there isn't one (i think Buildkite's Test Analytics also depends on these XML files):
![image](https://github.com/woocommerce/woocommerce-android/assets/17252150/858667eb-12b7-4a5c-bf3a-fd0feaf5a1e5)

as an example, on iOS projects, the results are available in the build artifacts:
<img width="561" alt="image" src="https://github.com/woocommerce/woocommerce-android/assets/17252150/0919bac8-df44-45e4-82e3-3d4bcf0b78a8">

how can we get the results for the android test runs to appear on the buildkite's build artifacts?

2023-06-09 18:20 UTC, oguzkocer commented
@jostnes I think that's just a matter of uploading the artifacts. Can you take a look at #9205?

2023-06-13 07:51 UTC, jostnes reviewed
Thanks again for adding the XML files for unit tests @oguzkocer ! 

From that change, I could include `annotate_test_failures` to also send a notification when there's a failure in Unit Tests step. Testing was done in this [testing PR](https://github.com/woocommerce/woocommerce-android/pull/9174/files):

Example notification for Unit Tests:
<img width="668" alt="image" src="https://github.com/woocommerce/woocommerce-android/assets/17252150/dcf77789-b07f-4f2c-94a4-3f7a6a23f1f2">

Example notification for Instrumented Tests:
<img width="668" alt="image" src="https://github.com/woocommerce/woocommerce-android/assets/17252150/e136f0a2-1b82-4d78-a33e-260a551f3637">

@jkmassel can you take another look at this please?

2023-06-13 07:51 UTC, jostnes commented on .buildkite/commands/run-unit-tests.sh
> +done
For Unit Tests, a test result file is created for each test class run so there are multiple .XML files created instead of just 1 (Instrumented tests create only 1 .XML file)

What's done here is to add all the files into an array and check each file for test failures. Because of this, there will be multiple notifications for unit tests failures if tests in different test classes fail, e.g. both notifications below are from [the same failing build](https://buildkite.com/automattic/woocommerce-android/builds/12761#_):

<img width="680" alt="image" src="https://github.com/woocommerce/woocommerce-android/assets/17252150/aa757062-dc52-4ab0-abd8-37d01f3cfcf0">

I think this should be okay since I don't think I've seen a case where a bunch of unit tests failed on the same build but if there is a better alternative to this, I'm open to feedback

2023-06-26 16:47 UTC, jkmassel approved these changes

2023-06-27 07:02 UTC, merged