[Customer Search] FAB that leads to customer creation
woocommerce/woocommerce-android pull request #9431
Opened 2023-07-18 09:57 UTC by kidinov

Closes: #9390

### Description

The PR adds FAB to the customer list, that opens empty customer details screen

### Testing instructions

* Start order creation flow
* Add customer
* Try different combinations of using existing customer or creating a new one

### Images/gif

https://github.com/woocommerce/woocommerce-android/assets/4923871/5aec8731-33b9-4e7f-8e86-6a5f589d5aa5

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-07-18 16:09 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/customerlistnew/CustomerListScreen.kt
> +        Icon(imageVector = Icons.Filled.Add, contentDescription = "Add coupon")
I understand this is minor, but since this is used for accessibility purposes, shouldn't this say "Add Customer" instead of Coupon? 🤔

2023-07-18 16:24 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/customerlistnew/CustomerListScreen.kt
> +        Icon(imageVector = Icons.Filled.Add, contentDescription = "Add coupon")
NP: It would be good to extract this as a resource. Wdyt?

2023-07-18 16:29 UTC, rossanafmenezes requested changes
LGTM. I left two minor comments but since it involves accessibility I think it would be good to change it.

2023-07-19 14:36 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/customerlistnew/CustomerListScreen.kt
> +        Icon(imageVector = Icons.Filled.Add, contentDescription = "Add coupon")
Good catch! Fixed here - 3aeef1ff13c6c713cf7514d84eaedf41b23bec30

2023-07-19 15:47 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/customerlistnew/CustomerListScreen.kt
> +        Icon(imageVector = Icons.Filled.Add, contentDescription = "Add coupon")
Thanks!

2023-07-19 15:48 UTC, rossanafmenezes approved these changes

2023-07-19 15:48 UTC, merged