display SKU on scan failure snack bar
woocommerce/woocommerce-android pull request #9433
Opened 2023-07-18 19:00 UTC by rossanafmenezes

Closes: #9295 

### Description

This PR changes the required returning type of the message on `OnAddingProductViaScanningFailed` class (and related methods) to String so we can have a dynamic error message in the snack bar. 

### Testing instructions

1. Go to the orders screen
2. click on the option to scan a barcode
3. scan an invalid barcode like the one here https://barcode.tec-it.com/en/?data=123_invalid_sku
4. Note the message saying the SKU `123_invalid_sku` is invalid
5. Feel free to change the code in the link to make sure it's updated in the snack bar when you scan again. 

### Images/gif

| Before | After |
| ---- | ---- |
| <img src="https://github.com/woocommerce/woocommerce-android/assets/30724184/7447cf2b-0773-41c1-af5e-5a82c3d364bf" width="350"/> | <img src="https://github.com/woocommerce/woocommerce-android/assets/30724184/d4e84271-c5bb-47f5-9335-ada22fb68db0" width="350"/> |

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-07-18 19:10 UTC, rossanafmenezes commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="order_creation_barcode_scanning_unable_to_add_product">Product with SKU %s not found. Unable to add to new order</string>
The original string read `Product not found. Unable to add to new order` and the suggestion on the issue was to change it to:

`Product with SKU {SKU_value} not found. Please try again`

I am under the impression that the "Please try again part" gives the idea that the scanning failed for a different reason (like a network error) and that if you try again it might help. Which is not the case. So I left the second part of the string unchanged because it sounds more accurate to me. But please let me know if you think we should use the "Please try again" and I will fix it. Thank you

2023-07-19 08:43 UTC, samiuelson requested changes

2023-07-19 08:43 UTC, samiuelson commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/UIMessageResolver.kt
> -        @StringRes stringResId: Int,
There is another `::getRetrySnack`, originally at line 178, that takes String instead of Int. It should fit your needs - no need to modify this function.

2023-07-19 08:43 UTC, samiuelson commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
> +            R.string.update_failed.toString(),
No need for this if you don't change the `::getRetrySnack`. BTW, toString() will not return the text from resources, rather its Int id converted to string

2023-07-19 08:43 UTC, samiuelson commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="order_creation_barcode_scanning_unable_to_add_product">Product with SKU %s not found. Unable to add to new order</string>
Makes sense 👍🏼

2023-07-19 19:49 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt
> +                Product(item.productId)
Remove redundant qualifier (not related to this PR)

2023-07-19 19:51 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/UIMessageResolver.kt
> -        @StringRes stringResId: Int,
Thanks. Switched to the correct one here [875fad7](https://github.com/woocommerce/woocommerce-android/pull/9433/commits/875fad7b850e45afb7cb9433d7d6b661140f5c94)

2023-07-19 19:52 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
> +            R.string.update_failed.toString(),
Thanks. all removed after changing to the correct `::getRetrySnack`

2023-07-20 08:01 UTC, samiuelson commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="order_creation_barcode_scanning_unable_to_add_product">Product with SKU %s not found. Unable to add to new order</string>
```suggestion
    <string name="order_creation_barcode_scanning_unable_to_add_product">Product with SKU %s not found. Unable to add to the order</string>
```
If I understand, this is also used in order edition. We could simplify it then

2023-07-20 12:56 UTC, rossanafmenezes commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="order_creation_barcode_scanning_unable_to_add_product">Product with SKU %s not found. Unable to add to new order</string>
Good point. Changed here: [730d340](https://github.com/woocommerce/woocommerce-android/pull/9433/commits/730d340b26eff788a7f01f569c4f24f4007b73ac)

2023-07-24 16:19 UTC, samiuelson approved these changes
LGTM :shipit:

2023-07-24 16:19 UTC, merged

2023-07-31 12:08 UTC, malinajirka commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="order_creation_barcode_scanning_unable_to_add_product">Product with SKU %s not found. Unable to add to the order</string>
@rossanafmenezes @samiuelson AFAIK we shouldn't modify any other strings except of the english version. If we need to add/remove a placeholder, we should create a new key. Hopefully, this won't result in any issues, but any changes to the non-english strings might get ignored as those strings are generated automatically from glotpress. 

Might be worth to still create a fix for this and create a new key just to be on the safe side. Otherwise we might end up with an exception if the app expects a string with a placeholder but the translation doesn't have one since it's still using the previous version of the string. Wdyt?

2023-07-31 12:53 UTC, samiuelson commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="order_creation_barcode_scanning_unable_to_add_product">Product with SKU %s not found. Unable to add to the order</string>
@malinajirka Interesting. The problem here was that we had a lint error due to the fact the English string contains a template and translated strings do not. That's why I proposed to remove the translations. Do you have an idea how to proceed with such lint error scenario?

2023-07-31 13:00 UTC, malinajirka commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="order_creation_barcode_scanning_unable_to_add_product">Product with SKU %s not found. Unable to add to the order</string>
If we need to add/remove a placeholder, we should create a new key => with this approach, we would never encounter this lint error, wdyt?

2023-07-31 13:16 UTC, samiuelson commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="order_creation_barcode_scanning_unable_to_add_product">Product with SKU %s not found. Unable to add to the order</string>
Makes sense. Then, when the string becomes obsolete, we should remove the base one and all the translations as well?

2023-07-31 13:17 UTC, malinajirka commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="order_creation_barcode_scanning_unable_to_add_product">Product with SKU %s not found. Unable to add to the order</string>
Just the base-one, the translations get removed automatically during the release process. I don't think we ever need to touch the files with translations, those are essentially just for the release process.

2023-07-31 13:39 UTC, rossanafmenezes commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="order_creation_barcode_scanning_unable_to_add_product">Product with SKU %s not found. Unable to add to the order</string>
> Might be worth to still create a fix for this and create a new key just to be on the safe side

Thanks for the input @malinajirka 
So, should I create the fix?

2023-07-31 13:48 UTC, samiuelson commented on WooCommerce/src/main/res/values/strings.xml
> +    <string name="order_creation_barcode_scanning_unable_to_add_product">Product with SKU %s not found. Unable to add to the order</string>
I believe this should be handled properly during the release. Anyway, we should probably ask apprelease team on Slack for recommendation.