My store using timestamp last synced
woocommerce/woocommerce-android pull request #9454
Opened 2023-07-21 20:43 UTC by atorresveiga

⚠️  Warning: This PR is a part of a more extensive work, please do not merge

Closes: #9443

### Why
As part of the Reliability project, we are working on improving the app's performance and reducing the perceived time it takes to load. One of the ideas we are working on is introducing a timestamp as the web does and preventing redundant requests to the API. This PR is part of the timestamp introduction in the My Store screen.

This how the web looks like:
<img width="594" alt="Screenshot 2023-06-21 at 11 25 43" src="https://github.com/woocommerce/woocommerce-android/assets/18119390/133b162b-f9f9-4344-bdb1-577f07cbbb43">

### Description
This PR changes the logic followed by the My Stats screen on where a request was forced to the API and follows the same strategy as the Analytics Hub screen. With these changes, the two screens (Hub and My Store) will share the timestamp for the last update and rely more on the cached data. 

### Testing instructions
TC1
1. Open the App and open a granularity (ex. Today)
2. Wait until the screen finish loading
3. Press on a different granularity (ex. This week)
4.  Wait until the screen finish loading
5. Change back to the first selection (Today)
6. Check that no request is made to the API and that data is presented from the cache
7. Change to the second selection (This week)
8. Check that no request is made to the API and that data is presented from the cache

TC2
1. Open the App and open a granularity (ex. Today)
2. Wait until the screen finish loading
3. Press on a different granularity (ex. This week)
4. Wait until the screen finish loading
5. Change back to the first selection (Today)
6. Check that no request is made to the API and that data is presented from the cache
7. Pull-To-Refresh and check that a call is made to the API and the data is refreshed

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-07-21 22:32 UTC, atorresveiga commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStore.kt
> +        selectionType: StatsTimeRangeSelection.SelectionType,
The My Store stats are based on stats granularities. I converted the granularity to a selection type to ensure we have the same key and sharing the key is possible between Hub and My Stats.

2023-07-21 22:37 UTC, atorresveiga commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModel.kt
> +    data class RefreshEvent(private val isForced: Boolean = false) {
Refresh is an event. To prevent resending isForcedRefresh true when the granularity change, once the property is consumed/handled, the isForcedRefresh value is turned to false (the default value)

2023-07-21 22:38 UTC, atorresveiga commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModelTest.kt
> -        testBlocking {
Refresh is now handled by the timestamp

2023-07-21 22:40 UTC, atorresveiga commented on WooCommerce/src/test/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModelTest.kt
> +            whenViewModelIsCreated()
Small refactor to avoid coroutine crashes on the test results. Also moving **_given_** before **_when_**

2023-07-26 01:10 UTC, ThomazFB requested changes
Awesome work integrating our existing work around the cache with the My Store, Alejo! I tested alongside the iOS app to verify any modification in the app data and I can verify that no regression was introduced!

The test scenarios described in the PR work just fine, but I decided to test if the usage of the Analytics data store would also prevent us from requesting recent data again when we restart the app. I noticed that all requests are triggered once more. Is this something that you already have on your radar? Asking just in case this is something you're already addressing in the upcoming PRs that I didn't start yet 😅 

I've also left some minor comments over code improvements, but nothing critical.

2023-07-26 01:10 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStore.kt
> +        selectionType: StatsTimeRangeSelection.SelectionType,
This granularity structure was something I had some issues with during the Analytics Hub project because I unified the time range generation between both areas of the app. But there's a benefit to that. Because of that project, the `GetStats` use case already has an internal conversion of Granularity to `StatsTimeRangeSelection`, which you can verify under the request calls for Revenue and Visitors data.

So if you want to reuse that option, it would allow removing those function overloads inside the `AnalyticsUpdateDataStore`. It is not critical, so I'm leaving it up to you to adopt it or not! 

Here's a patch with an example of what I'm talking about:

```
Subject: [PATCH] Optional solution for MyStore granularity conversion
---
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/domain/GetStats.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/domain/GetStats.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/domain/GetStats.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/domain/GetStats.kt	(revision c5c6b3e5794eb48ed28ad1b85e7d6eb95128aa27)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/domain/GetStats.kt	(date 1690332261612)
@@ -34,15 +34,15 @@
     private val analyticsUpdateDataStore: AnalyticsUpdateDataStore
 ) {
     suspend operator fun invoke(refresh: Boolean, granularity: StatsGranularity): Flow<LoadStatsResult> {
-        val selectionType = StatsTimeRangeSelection.SelectionType.from(granularity)
-        val isForcedRefresh = shouldUpdateStats(selectionType, refresh)
+        val selectionRange = granularity.asRangeSelection
+        val isForcedRefresh = shouldUpdateStats(selectionRange, refresh)
         return merge(
             hasOrders(),
             revenueStats(isForcedRefresh, granularity),
             visitorStats(isForcedRefresh, granularity)
         ).map { result ->
             if (result is LoadStatsResult.RevenueStatsSuccess && isForcedRefresh) {
-                analyticsUpdateDataStore.storeLastAnalyticsUpdate(selectionType)
+                analyticsUpdateDataStore.storeLastAnalyticsUpdate(selectionRange)
             }
             result
         }
@@ -107,12 +107,15 @@
     private fun isPluginNotActiveError(error: Throwable): Boolean =
         (error as? StatsException)?.error?.type == OrderStatsErrorType.PLUGIN_NOT_ACTIVE
 
-    private val StatsGranularity.statsDateRange
+    private val StatsGranularity.asRangeSelection
         get() = StatsTimeRangeSelection.SelectionType.from(this)
             .generateSelectionData(
                 calendar = Calendar.getInstance(),
                 locale = localeProvider.provideLocale() ?: Locale.getDefault()
-            ).let {
+            )
+
+    private val StatsGranularity.statsDateRange
+        get() = asRangeSelection.let {
                 Pair(
                     it.currentRange.start.formatToYYYYmmDDhhmmss(),
                     it.currentRange.end.formatToYYYYmmDDhhmmss()
@@ -120,12 +123,12 @@
             }
 
     private suspend fun shouldUpdateStats(
-        selectionType: StatsTimeRangeSelection.SelectionType,
+        selectionRange: StatsTimeRangeSelection,
         refresh: Boolean
     ): Boolean {
         if (refresh) return true
         return analyticsUpdateDataStore
-            .shouldUpdateAnalytics(selectionType)
+            .shouldUpdateAnalytics(selectionRange)
             .firstOrNull() ?: true
     }
 
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStore.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStore.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStore.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStore.kt	(revision c5c6b3e5794eb48ed28ad1b85e7d6eb95128aa27)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStore.kt	(date 1690332320391)
@@ -25,15 +25,6 @@
         rangeSelection: StatsTimeRangeSelection
     ) = storeLastAnalyticsUpdate(rangeSelection.identifier)
 
-    fun shouldUpdateAnalytics(
-        selectionType: StatsTimeRangeSelection.SelectionType,
-        maxOutdatedTime: Long = defaultMaxOutdatedTime
-    ) = shouldUpdateAnalytics(selectionType.identifier, maxOutdatedTime)
-
-    suspend fun storeLastAnalyticsUpdate(
-        selectionType: StatsTimeRangeSelection.SelectionType
-    ) = storeLastAnalyticsUpdate(selectionType.identifier)
-
     private fun shouldUpdateAnalytics(
         timestampKey: String,
         maxOutdatedTime: Long = defaultMaxOutdatedTime
```

2023-07-26 01:10 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModel.kt
> +    data class RefreshEvent(private val isForced: Boolean = false) {
NP: given the fact that this is being used as `mutable state flow`, I would say this is representing a state instead of a event, something like `RefreshState` with the internal value inside called `shouldRefresh`, just like we do with our LiveData objects.

2023-07-26 01:10 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/domain/GetStats.kt
> +            .flowOn(coroutineDispatchers.computation)
NP: I think the `onEach` operation would be a better fit here since there's no transformation of the data itself, this way you will not need to return the `result` at the end of the lambda.

```suggestion
        ).onEach { result ->
            if (result is LoadStatsResult.RevenueStatsSuccess && isForcedRefresh) {
                analyticsUpdateDataStore.storeLastAnalyticsUpdate(selectionRange)
            }
        }.flowOn(coroutineDispatchers.computation)
```

2023-07-26 16:14 UTC, atorresveiga commented
Thanks for your review @ThomazFB! I just updated all your recommendations. I missed the `asRangeSelection`; that is why it is great to have you as the reviewer of these PRs.

> Is this something that you already have on your radar?

Yes, I also notice that behavior.  The issue is not related to this code but to the request cache. Based on that, I was waiting to see your changes to improve the stats cache and planned to work on fixing this in a different PR. Does that make sense?

2023-07-26 16:29 UTC, ThomazFB approved these changes
Looks good! Thanks for the changes, @atorresveiga! Let's see how those changes will integrate with the `AnalyticsRepository` and `StatsRepository` changes. I think we will need some adaptations, but nothing complicated. 

I left just another small suggestion after your changes to avoid some repetitions, but I think we're ready to go!

2023-07-26 16:29 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStore.kt
>      }
Just one last thing 😬, I think those two alias functions are no longer necessary since they are just calling the same function with the same key value. WDYT? 

```

    fun shouldUpdateAnalytics(
        rangeSelection: StatsTimeRangeSelection,
        maxOutdatedTime: Long = defaultMaxOutdatedTime
    ) = dataStore.data
        .map { prefs -> prefs[longPreferencesKey(rangeSelection.identifier)] }
        .map { lastUpdateTime -> isElapsedTimeExpired(lastUpdateTime, maxOutdatedTime) }

    suspend fun storeLastAnalyticsUpdate(rangeSelection: StatsTimeRangeSelection) {
        dataStore.edit { preferences ->
            preferences[longPreferencesKey(rangeSelection.identifier)] = currentTime
        }
    }
```

2023-07-27 22:06 UTC, atorresveiga commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStore.kt
>      }
Makes sense, Thomaz. 
WDYT if I commit this suggestion as part of the final merge to `trunk`? 
Avoiding this way to bring the change to all of the PR that depends on this one.

2023-07-28 00:05 UTC, ThomazFB commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStore.kt
>      }
True! I think it's a good idea to leave that as a last change, I don't want to give you the trouble of updating multiple PRs  with this central interface change 😅 .

2023-07-28 17:32 UTC, atorresveiga commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/AnalyticsUpdateDataStore.kt
>      }
Fixed here [6b8e8a3](https://github.com/woocommerce/woocommerce-android/pull/9454/commits/6b8e8a361a42cd254249691137320257a22fd7c9). The storeLastAnalyticsUpdate behaves differently depending on the analytic data param, so I think it is fine to leave the overload function. WDYT?

2023-07-28 20:35 UTC, merged