Issue/9612 discoun edit add new layout
woocommerce/woocommerce-android pull request #9639
Opened 2023-08-23 14:18 UTC by rossanafmenezes

Closes: #

### Description

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-08-23 21:31 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountViewModel.kt
> +            val productUiModel = mapItemToProductUiModel(orderItem.value)
This line here is causing a weird cursor behaviour in the discount input text field. It's random, doesn't happen all the time, but happens a lot. I'll take a look at this tomorrow: ![5VB0MT.gif](https://github.com/woocommerce/woocommerce-android/assets/30724184/b05a09c5-ebd0-4b08-a07a-f6d78540af9a)

2023-08-24 15:01 UTC, samiuelson reviewed
Good work, @rossanafmenezes! I've left some improvements ideas. Let me know what you think.

2023-08-24 15:01 UTC, samiuelson commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountViewModel.kt
> +            val productUiModel = mapItemToProductUiModel(orderItem.value)
We don't need to call `mapItemToProductUiModel(orderItem.value)` to fetch the image url every time the `discount` or `discountType` value changes. 

Let's do it only once when the view model is created and then reuse the image url here. Under the hood `::mapItemToProductUiModel` fetches the product from a repository, which can cause performance issues because it's done on every change of the discount value.

2023-08-24 15:01 UTC, samiuelson commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountScreen.kt
> +            shape = RoundedCornerShape(2)
💡 I think it should be fairly easy to reach the shape from the designs:
<img width="173" alt="Screenshot 2023-08-24 at 16 33 14" src="https://github.com/woocommerce/woocommerce-android/assets/4527432/881588cb-c863-4010-b0f2-23ccfffb7084">
with only the outside corners rounded. WDUT?

2023-08-24 15:01 UTC, samiuelson commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountScreen.kt
> +            text = "$",
⚠️ What if the currency is different than USD or CA?

2023-08-24 15:01 UTC, samiuelson commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountScreen.kt
> +            text = if (state.discountAmount == null) "0.00" else discountAmount,
⚠️ IMO, the view is doing too much business logic here. Ideally, we should just render `state.discountAmount` text here and make the view model responsible for it always have the correct value. I'd personally change it's type to non-null.

2023-08-24 15:01 UTC, samiuelson commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountScreen.kt
> +    Row(
💡NIT: We'd have fewer nested components if we used ConstraintLayout instead of Row.

2023-08-24 15:01 UTC, samiuelson commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountViewModel.kt
> +    private fun getCalculatedPercentage(): BigDecimal {
💡 This code is duplicated, e.g. at line 162

2023-08-24 15:01 UTC, samiuelson commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountViewModel.kt
> +        val discountPercentage = discount.value ?: BigDecimal.ZERO
💡This code is very similar (duplicate?) to lines starting at 190

2023-08-24 20:24 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountScreen.kt
> +            text = "$",
I thought about that, but in this case, it's just a symbol to indicate "money" in general. Not necessarily have to be a specific currency symbol. Especially because it's a very small space, so if you have a currency that takes more space it won't show. I can absolutely make this change. But I'm not 100% sure it's needed. Wdyt?

2023-08-24 20:35 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountScreen.kt
> +            text = "$",
<img width="87" alt="Screenshot 2023-08-24 at 4 31 42 PM" src="https://github.com/woocommerce/woocommerce-android/assets/30724184/eb1a833a-535d-4337-9cfe-2dfe17534684">
Well, I tested with Cad (CA$) and Brazilian real (R$). Checking the Currencies we support, seems that nothing is wider than 3 chars. So it should be ok. But I still think it looks better and more balanced if we use only the $. Let me know

2023-08-24 20:38 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountScreen.kt
> +            shape = RoundedCornerShape(2)
I tried a few things, but nothing got me to this specific result. But today I found out that there's more than one RoundCornerShape function and found the one where you can set up specific corners. **TIL**

I'll add the commit # as soon as I push it

2023-08-28 15:09 UTC, samiuelson commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountScreen.kt
> +            text = "$",
I mean the text is now hardcoded to "$" char. Previously it was set to `state.currency`.

2023-08-28 18:22 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountScreen.kt
> +    Row(
I haven't used ConstraintLayout in Compose before. Tried it here https://github.com/woocommerce/woocommerce-android/pull/9639/commits/d30cf4b784e2151441510724c3276257f54c925b

Please let me know if anything needs to be improved.

2023-08-28 18:25 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountScreen.kt
> +            text = "$",
Changed here https://github.com/woocommerce/woocommerce-android/pull/9639/commits/c98ef06048fc2b869c3031da6e73d0ad691b9510

2023-08-28 18:26 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountScreen.kt
> +            shape = RoundedCornerShape(2)
Changed it here https://github.com/woocommerce/woocommerce-android/pull/9639/commits/fa29b6ca73dfe4eef204d7bce1da2de13b7bf3a7

2023-08-28 18:49 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountViewModel.kt
> +            val productUiModel = mapItemToProductUiModel(orderItem.value)
Fixed here https://github.com/woocommerce/woocommerce-android/pull/9639/commits/258111bf79a634318a9c381fb3d4fa1f681a7057

Is that what you had in mind?

2023-08-28 20:24 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountViewModel.kt
> +        val discountPercentage = discount.value ?: BigDecimal.ZERO
Fixed here https://github.com/woocommerce/woocommerce-android/pull/9639/commits/428a498927bbd728fa3eea502d285fa060866a12

2023-08-28 20:24 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountViewModel.kt
> +    private fun getCalculatedPercentage(): BigDecimal {
Fixed here https://github.com/woocommerce/woocommerce-android/pull/9639/commits/428a498927bbd728fa3eea502d285fa060866a12

2023-08-28 22:19 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountScreen.kt
> +            text = if (state.discountAmount == null) "0.00" else discountAmount,
Refactored here https://github.com/woocommerce/woocommerce-android/pull/9639/commits/f3b4f3bad8dcff4fdd0c964cd655d8b62c8c7d5a

2023-08-28 23:26 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/CalculateItemDiscountAmount.kt
> +        return (item.subtotal - item.total)
Adding a note here because I don't think we remembered that when we were pairing and decided to remove the `/ item.quantity.toBigDecimal()`

This was changing the discount amount in the product card here:
<img width="335" alt="Screen Shot 2023-08-28 at 19 17 36" src="https://github.com/woocommerce/woocommerce-android/assets/30724184/e56821cf-0b8f-4f69-9b72-b222acb5cb4b">

To be honest I am not sure if we should remove or leave it. The information looks duplicated since we have the total discounts below. Let me know what you think and I can revert the change if needed.

2023-08-29 16:53 UTC, samiuelson commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountViewModel.kt
> +            val productUiModel = mapItemToProductUiModel(orderItem.value)
I think we don't need to wrap the `ProductUIModel` with `Flow` because its value does not change over time. We can declare it as a simple class property `private productUIModel: ProductUIModel = orderItem.map { mapItemToProductUiModel(it) }` and then set its value to the ViewState.

2023-08-29 17:54 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountViewModel.kt
> +            val productUiModel = mapItemToProductUiModel(orderItem.value)
Ok, sorry if this is a dumb question, but orderItem is of type  MutableStateFlow<Order.Item> so I can't really store it in a variable of type productUIModel, right? It will return a type mismatch error. I'm probably missing something.

2023-08-29 18:36 UTC, samiuelson commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountViewModel.kt
> +            val productUiModel = mapItemToProductUiModel(orderItem.value)
Good point, IMO, the `orderItem` doesn't need to be of the Flow type either. It's just a single value that remains unchanged all the time. No need to wrap it in the `Flow`. Basically, we get the `Order.Item` value from `args.item`. This is the point where we obtain the item value passed from the order creation screen. 

Anyway, to get the current value from the Flow you can use `Flow.value` property. You can also refactor the code and store the `orderItem` as the `Order.Item` type. 

Let me know if this helps!

2023-08-29 21:55 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountViewModel.kt
> +            val productUiModel = mapItemToProductUiModel(orderItem.value)
Ok, changed here: https://github.com/woocommerce/woocommerce-android/pull/9639/commits/b020b877a6ddf3949d695b30d1b0052be9d3f881 - opted by using the flow value because refactoring orderItem would take a while. I can do that in a future PR if you think it's necessary so we don't delay this PR another sprint. 

I'm not sure if this is correct, but since the invoke function in the MapItemToProductUiModel class is suspended I could not simply assign it outside a coroutine. So this is the way I was able to get it to work.

2023-08-30 14:08 UTC, samiuelson commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountScreen.kt
> +    Row(
The advantage of Constraint layout is that we can unwrap the components of the Column (delete Column basically) and have fewer nested components as a result (better performance). Anyway, this is not crucial, rather a nice to have 👍🏼

2023-08-30 15:57 UTC, samiuelson commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountViewModel.kt
> +            val productUiModel = mapItemToProductUiModel(orderItem.value)
The b020b877a6ddf3949d695b30d1b0052be9d3f881 commit is not correct and doesn't fix the performance issue.

1. The root problem is that the result of the `mapItemToProductUiModel::init` call in the init block is not used anywhere:
```kotlin
init {
    viewModelScope.launch {
        mapItemToProductUiModel(orderItem.value)
    }
}
```
In other words, the above code creates the `ProductUIModel` object when the view model is created but it's not assigned to handle and we can't reuse it.

2. Inside the view state `::combine` block we're calling the `mapItemToProductUiModel()` function again (on each change of `discount` or `discountType`), so the performance is not improved by this change.

3. NP: No need to refer to viewModelScope, because the view model's base class (ScopedViewModel) implements the `CoroutineScope`. In other words, the view model is an instance of CoroutineScope itself.

Solution proposal:
1. Use the [async](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/async.html) function which creates a coroutine that returns a result. You can think about it as a "future result" (or "suspended result" in more Kotlin style). We may declare the future result of `mapItemToProductUiModel(): ProductUIModel` call the following way:
```kotlin
private val itemUiModelFuture: Deferred<ProductUIModel> = async {
    mapItemToProductUiModel(orderItem.value)
}
```
Side note: Normally we'd need to call it using the coroutine scope: `scope.async {}`. 

2. In order to wait for the result and access the value of the `itemUiModelFuture` in the blocking code, we use the `Deferred<T>.await(): T` function.

In the case of the view state computation, it would look like this:
```kotlin
val viewState: StateFlow<ViewState> =
        combine(discount, discountType) { discount, type ->
            ViewState(
                ...
                productDetailsState = ProductDetailsState(
                    imageUrl = itemUiModelFuture.await().imageUrl
                )
            )
        }.toStateFlow()
```
Let me know if that helps!

2023-08-30 16:08 UTC, samiuelson commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/CalculateItemDiscountAmount.kt
> +        return (item.subtotal - item.total)
I'm not sure how this can happen. The discount is independent of the quantity of the item, isn't it? Anyway, I can't reproduce this.

2023-08-30 17:13 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountScreen.kt
> +    Row(
I was having issues aligning the text without the column, but I think I got it https://github.com/woocommerce/woocommerce-android/pull/9639/commits/f2f3543d1b23fb41f3917dd483ad47ce9b893205

2023-08-30 17:14 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/OrderCreateEditProductDiscountViewModel.kt
> +            val productUiModel = mapItemToProductUiModel(orderItem.value)
Sorry about that. Fixed here https://github.com/woocommerce/woocommerce-android/pull/9639/commits/4403041f903acf154f004e942cf9d9528ed84192

2023-08-31 10:30 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/product/discount/CalculateItemDiscountAmount.kt
> +        return (item.subtotal - item.total)
> The discount is independent of the quantity of the item, isn't it?

It is now. My point is that the info is redundant now that we are not showing the discount by quantity anymore.

2023-08-31 12:08 UTC, malinajirka commented
@rossanafmenezes I'm still in the process of reviewing this, but I noticed this issue => I'm not 100% sure it's related to this PR though.

https://github.com/woocommerce/woocommerce-android/assets/2261188/4b1203f7-4cd1-47f2-8c49-b526df4e73d6

2023-08-31 14:25 UTC, rossanafmenezes commented
> @rossanafmenezes I'm still in the process of reviewing this, but I noticed this issue => I'm not 100% sure it's related to this PR though.

fixed here https://github.com/woocommerce/woocommerce-android/pull/9639/commits/059285b3fb1a7725e88299606a9734fe5af3d1d4

2023-09-01 07:14 UTC, malinajirka requested changes
I've finished reviewing this PR and I noticed one more broken behavior.

> increase and decrease the product count and make sure the discount amount does NOT changes

This behavior seems very weird to me. However, I assume it was discussed somewhere and a decision has been made with Joe's collaboration. (I'd personally at least consider showing a snakcbar on quantity change saying "The discount amount has NOT changed" or something in that sense).

Either case, there is a bug and inconsistency with iOS even if I treat this behavior as the desired.

1. Add product with price $100.
2. Increase quantity to 2.
3. Add 30% discount.
4. Notice the total cost is $170 💥  (iOS applies the 30% discount to `product price x quantity` and the total is $140) .
------------------------------
1. Add product with price $100.
2. Increase quantity to 2.
3. Add $140 discount.
4. Notice the app won't let you, since the amount is bigger than a price of a single product => however, there is no way how to apply let's say $70 on each piece of this product. 💥 (iOS let's you always enter `product price x quantity` as the maximum amount).

2023-09-01 14:20 UTC, rossanafmenezes commented
> * Add product with price $100.
> * Increase quantity to 2.
> * Add $140 discount.
> * Notice the app won't let you, since the amount is bigger than a price of a single product => however, there is no way how to apply let's say $70 on each piece of this product. 💥 (iOS let's you always enter `product price x quantity` as the maximum amount).

I have changed the validation method to allow discounts based on the subtotal per item as opposed to the unit price here https://github.com/woocommerce/woocommerce-android/pull/9639/commits/a67ce43884ee7d408f17256f88f347c28616dd94

2023-09-01 18:21 UTC, malinajirka approved these changes
Thanks @rossanafmenezes for the fixes! Everything looks good to me and the behavior feels consistent. 👏

2023-09-01 18:21 UTC, merged