[Data Sprint] Track selected site url in the all events
woocommerce/woocommerce-android pull request #9703
Opened 2023-08-30 10:19 UTC by kidinov

Closes: #9699

### Description

### Testing instructions

Use logcat with "track" filtering
* Notice that all the events have correct, currently selected "site_url" property
* Notice that if a user in logged out state that we don't track "site_url"

### Images/gif

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-08-30 10:21 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
> +            selectedSite.getIfExists()?.let {
This brings a side effect which I consider as a fix but not sure. Before, `site` was stored in here even after login, so this data could be tracked even when no site selected

2023-08-30 13:17 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
> +            selectedSite.getIfExists()?.let {
I didn't review the PR yet as I'm busy with some tasks, but this just caught my eye, `getIfExists` has a DB call (I really wish we could make it a suspendable function, but it would require a lot of effort for the whole codebase), so having it called for every `track` call will surely have a noticeable impact.

A suggestion to solve this: since you are injecting selectedSite here, I suggest you keep the `site` property, then use the function `SelectedSite#observe` to update it, you can pass the app's CoroutineScope to the constructor as well to start the Flow collection.

2023-08-30 16:10 UTC, hichamboushaba requested changes
Just to make sure my comment above is not missed 🙂

2023-08-31 06:57 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
> +            selectedSite.getIfExists()?.let {
Wow, that's really a surprise for me, as I was always sure that this was just shared in memory site model storage. That's actually two (same) DB calls that can be done in some cases.

> A suggestion to solve this: since you are injecting selectedSite here, I suggest you keep the site property, then use the function SelectedSite#observe to update it, you can pass the app's CoroutineScope to the constructor as well to start the Flow collection.

Tbh, I'd go with something simple here, e.g., exposing something like that.

```
fun getOrNull(): SiteModel? =
        try {
            get()
        } catch (e: IllegalStateException) {
            null
        }
```

I don't want to introduce another state that we have to keep in sync with the state in `SelectedSite`, and I don't need to get updates - I just need to get the current state at the moment of tracking.

**But**, it looks like we already do not do a good job keeping in sync `SelectedSite::state` and what's stored in the storage. It looks like we do not call `SelectedSite::reset` on logout; that's why the in-memory state still keeps the old model, but the persistent one cleared somewhere. Do you know if this is expected behavior, or I just need to call `reset` on logout to fix that?

2023-08-31 11:15 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
> +            selectedSite.getIfExists()?.let {
Good catch about the logout scenario, the logout logic was implemented before my time here, and I don't it had any significant changes except the logic for Application Passwords (which btw does call `reset`), IMO it's just something that the team didn't think off at that time, and we can introduce the `reset` to fix it.

2023-09-01 07:01 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt
> +            selectedSite.getIfExists()?.let {
@hichamboushaba please take a look again today if possible, as this is a cut off day

2023-09-01 07:21 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/AccountRepository.kt
>                  AnalyticsTracker.track(AnalyticsEvent.ACCOUNT_LOGOUT)
@JorgeMucientes @hafizrahman I just noticed that there is no tracking in the case of `Application passwords logout`, not sure if this intentionally done though

2023-09-01 07:22 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/AccountRepository.kt
>                  AnalyticsTracker.track(AnalyticsEvent.ACCOUNT_LOGOUT)
@JorgeMucientes @hafizrahman I just noticed that there is no tracking in the case of `Application passwords logout`, not sure if this was intentionally done though

2023-09-01 11:12 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/AccountRepository.kt
>                  AnalyticsTracker.track(AnalyticsEvent.ACCOUNT_LOGOUT)
I think this was just an accidental side-effect of this [commit](https://github.com/woocommerce/woocommerce-android/commit/6a6a088b3c76a80878473bdf9419ca68d6deb00a), we moved the tracking from the `cleanup` function, but accidentally it was put inside the block of WPCom logout, so I'd say it needs fixing, we need to track it for the other case too.

2023-09-01 11:12 UTC, hichamboushaba commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/AccountRepository.kt
> +                selectedSite.reset()
WDYT about moving this line to the `cleanup` function?

2023-09-01 12:08 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/AccountRepository.kt
> +                selectedSite.reset()
done here 268644a8c1c7c55b438fd8ea98be31849d45b293

2023-09-01 15:13 UTC, hichamboushaba approved these changes
Nice work @kidinov, code looks good and works well.

I'll leave it to you to decide when to merge it, and also to decide if you want to fix [this](https://github.com/woocommerce/woocommerce-android/pull/9703#discussion_r1312897619) or not.

2023-09-04 06:33 UTC, kidinov commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/AccountRepository.kt
>                  AnalyticsTracker.track(AnalyticsEvent.ACCOUNT_LOGOUT)
@JorgeMucientes @hafizrahman I am leaving this up for you folks as I have no context at all

2023-09-04 06:33 UTC, merged

2023-09-04 07:41 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/AccountRepository.kt
>                  AnalyticsTracker.track(AnalyticsEvent.ACCOUNT_LOGOUT)
Hey @kidinov thanks for the ping. I'll take a look at it and fix it asap. Also thanks @hichamboushaba for pointing out where the problem lies.