HACK week: AI Thank you note
woocommerce/woocommerce-android pull request #9749
Opened 2023-09-08 02:49 UTC by hafizrahman

Closes: #

### Description

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-09-16 00:30 UTC, rossanafmenezes requested changes
👋  Hi @hafizrahman 

Awesome feature! Looks great. It works as expected. However, I found an issue. The app crashes if the order has no products. Kindly take a look.

2023-09-16 00:30 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
> +            val firstProductId = when (val first = orderProducts.list.first()) {
Here, if the user opens an order generated via Simple Payments ( and soon via order creation), meaning no products and no product ID, the app crashes. 

```
 FATAL EXCEPTION: main
                 Process: com.woocommerce.android.dev, PID: 7642
                 java.util.NoSuchElementException: List is empty.
                 	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:214)
                 	at com.woocommerce.android.ui.orders.details.OrderDetailViewModel$onAIThankYouNoteButtonClicked$1.invokeSuspend(OrderDetailViewModel.kt:825)
```

![thank  you note](https://github.com/woocommerce/woocommerce-android/assets/30724184/e3577960-5198-4eab-8b65-f4fa6d8b633b)

2023-09-16 00:30 UTC, rossanafmenezes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
> +                order.status == Order.Status.Completed
So, maybe we could hide the button for orders with no products?

Something like:

```
 && productList.value?.isNotEmpty() == true
```
Or maybe if the product list is empty show a snackbar clarifying the flow.

2023-09-22 13:38 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
> +            val firstProductId = when (val first = orderProducts.list.first()) {
Thanks for mentioning that! Did not know this is a thing, will fix it.

2023-09-22 13:41 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
> +                order.status == Order.Status.Completed
The thank you AI generation now currently requires an existing product to populate the content, so I suppose it's better to hide it :)

2023-09-22 14:09 UTC, hafizrahman commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt
> +                order.status == Order.Status.Completed
Resolved in https://github.com/woocommerce/woocommerce-android/pull/9749/commits/7ff1852188bd16f9ab3d1b84d275ee7bcd558eb8

2023-09-25 12:07 UTC, rossanafmenezes approved these changes
Thanks for fixing it @hafizrahman 

LGTM

2023-10-10 06:34 UTC, JorgeMucientes commented
Hey @hafizrahman, friendly ping 🙂 . Is there anything preventing this from being merged other than resolving the conflicts?

2023-11-24 07:02 UTC, merged

2023-11-24 07:11 UTC, hafizrahman commented
Not sure about the new danger errors "Please add tests for class...". I'm seeing other classes like `AIProductDescriptionViewModel` also don't have tests 🤔 

Since we're close to code freeze, I'm merging this first and will add in the unit tests later.