[Hazmat Shipping] Add hazmat tracks
woocommerce/woocommerce-android pull request #9775
Opened 2023-09-12 22:09 UTC by ThomazFB

Closes: #

### Description

### Testing instructions

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-09-18 17:20 UTC, ThomazFB commented
@hafizrahman @JorgeMucientes, since since Alejandro will be unavailable until the end of the month, I'm requesting a review from you folks too, I hope that's OK! Thanks in advance 🙇

2023-09-19 10:05 UTC, JorgeMucientes requested changes

2023-09-19 10:05 UTC, JorgeMucientes commented on WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModel.kt
> +    }
I noticed this function is never called when enabling/disabling the toggle. So the event `CONTAINS_HAZMAT_CHECKED` is never tracked.

2023-09-19 10:07 UTC, JorgeMucientes commented
Good work @ThomazFB! I noticed that one of the events is never tracked and we should address that before merging. The rest of the events are working as expected 👍🏼

2023-09-19 21:47 UTC, ThomazFB commented
Sorry @JorgeMucientes, I forgot to push yesterday's commits before going to the airport, which addresses the point you mentioned. It's OK now. Thank you for your review 🙇

2023-09-20 07:56 UTC, JorgeMucientes approved these changes

2023-09-20 07:56 UTC, JorgeMucientes commented
No problem @ThomazFB. The PR is good to go now! :shipit:

2023-09-20 07:57 UTC, merged