WCAndroid: Update Fastfile with version model
woocommerce/woocommerce-android pull request #9865
Opened 2023-09-29 12:22 UTC by spencertransier

## Summary
- This PR integrates the new version and build code models from https://github.com/wordpress-mobile/release-toolkit/pull/512
- It currently points to a development version of the Release Toolkit so that I could test out the call site implementation before releasing a new version of the Release Toolkit. 
- Nearly all of the `precheck` actions from the Release Toolkit were tightly coupled with the existing version methods. To simplify things with the new version model, I took the relevant snippets from the precheck actions and added them directly here. This is something that I've discussed with Olivier and Jeremy before in the context of "no one knows what the precheck actions do unless you dive deep down into the RT". These changes are somewhat opposite of DRY, but I think it's worth it for transparency. We may also decide in the future to create smaller actions that do more specific things versus the existing precheck and version bump actions that combine many disparate methods. 

## Before Merging
- [ ] Point the Release Toolkit to a stable version
- [ ] WCAndroid versions must be switched from `build.gradle` to `version.properties`

2023-09-29 21:48 UTC, jkmassel commented on fastlane/Fastfile
> +    ensure_git_status_clean
We should do this at the top of the lane – it's not a great experience if we give input then find out that the starting parameters were invalid

2023-09-29 21:56 UTC, jkmassel requested changes
I'm getting this error:

> [14:51:13]: Exit status of command 'git add ./WooCommerce/build.gradle' was 128 instead of 0.
warning: could not open directory 'fastlane/WooCommerce/': No such file or directory
fatal: pathspec './WooCommerce/build.gradle' did not match any files

When trying to run the code freeze lane

2023-09-29 21:56 UTC, jkmassel commented on Gemfile
> + gem 'fastlane-plugin-wpmreleasetoolkit', git: 'https://github.com/wordpress-mobile/release-toolkit', branch: 'add/version-model'
We'll need to use a specific version before landing this

2023-09-29 23:10 UTC, spencertransier commented
> I'm getting this error:
> 
> [14:51:13]: Exit status of command 'git add ./WooCommerce/build.gradle' was 128 instead of 0.
> warning: could not open directory 'fastlane/WooCommerce/': No such file or directory
> fatal: pathspec './WooCommerce/build.gradle' did not match any files
> 
> When trying to run the code freeze lane

@jkmassel Is it trying to switch to `trunk` and running into issues? I had to disable the branch switches to be able to test the lanes: 
<img width="695" alt="Screenshot 2023-09-29 at 4 10 39 PM" src="https://github.com/woocommerce/woocommerce-android/assets/17955542/1a9ea687-a091-408a-8e64-4ef7b8af2e71">

2023-09-29 23:12 UTC, spencertransier commented on fastlane/Fastfile
> +    ensure_git_status_clean
Addressed in https://github.com/woocommerce/woocommerce-android/commit/25d15be1c32d65df177f08905062219fba7a0915

2023-09-30 03:00 UTC, jkmassel approved these changes

2023-09-30 06:29 UTC, merged