App login credentials deep link for Wordpress.com users
woocommerce/woocommerce-android pull request #9893
Opened 2023-10-04 03:42 UTC by atorresveiga

Closes: #9890
### Why
We are working on improving the app onboarding experience by adding a QR that shares the site URL and the email from the wp-admin. This way, merchants don't need to enter this information when logging into the apps.

### Description
This PR adds the `app-login` authority to the LoginActivity and reads the information shared through the deep link to open the Login screen with the site URL and wordpress.com email filled.

### Testing instructions
1. Log out from the app
2. Open the terminal and run this script using your site URL and wp.com email:

```
adb -s 22091FDF600240 shell am start -W -a android.intent.action.VIEW -d "woocommerce://app-login?siteUrl=[YourSiteUrl]\&wpcomEmail=[YourWPComEmail]"
```
Alternatively, you can change the text in [this](https://jsfiddle.net/atveiga/qbmd0xrn/14/) `jsfiddle`, press run to generate a new QR, and read the QR with your device camera.

3. Check that the app opens on the login screen with your email
4. Enter your credentials
5. Check that you are logged in with the store you used on the site url.

### Images/gif

https://github.com/woocommerce/woocommerce-android/assets/18119390/aeef9d81-cf1b-400a-9c97-ab9bbe67c139

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-10-04 22:41 UTC, ThomazFB requested changes
@atorresveiga I've noticed during my tests that the deep link is not working as expected. I tried to open the app both through the generated QR code and the `adb` input and only got a blank screen for both my physical device and emulator. I also tried the same test with the code available in https://github.com/woocommerce/woocommerce-android/pull/9894 and got the same results.

Here's the recording and the output I get:


https://github.com/woocommerce/woocommerce-android/assets/5920403/88d4a027-e770-44ed-8185-e1cba98587be

https://github.com/woocommerce/woocommerce-android/assets/5920403/3e81530a-3023-46ac-a6c9-51f89c4910e9

<img width="1338" alt="Screenshot 2023-10-04 at 19 32 00" src="https://github.com/woocommerce/woocommerce-android/assets/5920403/bd567f97-6309-403a-a3db-2a4f4a99c1a2">

2023-10-04 22:44 UTC, ThomazFB commented
Same problem with the `wpComEmail` parameter, as suggested by this PR:

<img width="1354" alt="image" src="https://github.com/woocommerce/woocommerce-android/assets/5920403/e2fe4512-ba4d-44e8-81af-28c64e7c8a5a">

2023-10-05 15:22 UTC, atorresveiga commented
Hi Thomaz! This PR is only for wpcom user, the user password email in on the other PR.

> Same problem with the wpComEmail parameter, as suggested by this PR

Looking at your url it seems that you missed a `\` between the url and the `&`  for the email. This causes that the email parameter is not sent and it breaks the feature. I'm handling edge cases and errors in a different PR this is only for the happy path

2023-10-05 21:18 UTC, ThomazFB approved these changes
Sorry for the inconvenience, @atorresveiga. It was a malformed URL on my part. I can confirm the feature is working and just requires the error handling indeed, and thank you for pointing me in the right direction. Looks good!

2023-10-05 21:18 UTC, merged